--T_TEMPERATURE_ANES

{{ config(materialized='ephemeral') }}

SELECT DISTINCT PERSON_ID
		,PAT_ENC_CSN_ID
		,RECORDED_TIME
		,MEAS_VALUE
		,MINVALUE
		,MAX_VAL
		,FLO_MEAS_NAME
		,FLO_MEAS_ID
		,FSD_ID
		,VISIT_PROV_ID
	
	FROM {{ref('MEASUREMENT_CLARITYANES_FLOWSHEET')}} AS MEASUREMENT_CLARITYANES_FLOWSHEET
	
	INNER JOIN {{ source('CDM','SOURCE_TO_CONCEPT_MAP')}} AS SOURCE_TO_CONCEPT_MAP_FLOWSHEET_MEAS
		ON FLO_MEAS_ID::VARCHAR = SOURCE_TO_CONCEPT_MAP_FLOWSHEET_MEAS.SOURCE_CODE
			AND UPPER(SOURCE_TO_CONCEPT_MAP_FLOWSHEET_MEAS.SOURCE_VOCABULARY_ID) = 'SH_FLWSHT_MEAS_TEMP'
	