-- T_TEMP_SOURCE_ANES

{{ config(materialized='ephemeral') }}

SELECT DISTINCT PERSON_ID
	,PAT_ENC_CSN_ID
	,RECORDED_TIME
	,MEAS_VALUE AS MEAS_VALUE

FROM {{ref('MEASUREMENT_CLARITYANES_FLOWSHEET')}} AS MEASUREMENT_CLARITYANES_FLOWSHEET

WHERE FLO_MEAS_ID IN ('7')