  {{ config(materialized='ephemeral') }}

SELECT BLOOD_ADMIN_INFO.ORDER_ID
		,BLOOD_ADMIN_INFO.BLOOD_ADMIN_UNIT
		,BLOOD_ADMIN_INFO.BLOOD_ADMIN_PROD
		,BLOOD_ADMIN_INFO.BLOOD_ADMIN_TYPE
		,ORDER_PROC.PROC_ID
		,ORDER_PROC.PROC_CODE
		,ORDER_PROC.ORDERING_DATE
		,CLARITY_EAP.PROC_NAME
	
FROM {{ source('CLARITY','BLOOD_ADMIN_INFO')}} AS BLOOD_ADMIN_INFO
	
    INNER JOIN {{ source('CLARITY','ORDER_PROC')}} AS ORDER_PROC
		ON BLOOD_ADMIN_INFO.ORDER_ID = ORDER_PROC.ORDER_PROC_ID
	
    INNER JOIN {{ source('CLARITY','CLARITY_EAP')}} AS CLARITY_EAP
		ON ORDER_PROC.PROC_ID = CLARITY_EAP.PROC_ID
	
WHERE (BLOOD_ADMIN_INFO.LINE = 1)