--T_PROCEDURE_SOURCE

{{ config(materialized='ephemeral') }}

SELECT CONCEPT_ID
	,CONCEPT_CODE
	,DOMAIN_ID
	,VOCABULARY_ID

FROM {{ source('CDM','CONCEPT')}} AS  C

WHERE UPPER(C.VOCABULARY_ID) IN ('CPT4')

	AND UPPER(C.DOMAIN_ID) = 'PROCEDURE'
