{{ config(materialized = 'view') }}

SELECT DISTINCT T_POS.POS_ID 
	, T_POS.POS_NAME 
	, T_POS.ADDRESS_LINE_1
	, T_POS.ADDRESS_LINE_2
	, T_POS.CITY
	, T_POS.STATE_C
	, ZC_STATE.ABBR AS STATE_ABBR
	, T_POS.COUNTY_C as COUNTY_C
	, ZC_COUNTY.NAME as COUNTY_NAME
	, T_POS.ZIP
	, POS_TYPE 
FROM {{ref('T_POS')}} AS T_POS
	LEFT JOIN {{ source('CLARITY','ZC_STATE')}}	 as ZC_STATE 
		ON T_POS.STATE_C = ZC_STATE.STATE_C
	LEFT JOIN {{ source('CLARITY','ZC_COUNTY')}}	 as ZC_COUNTY 
		ON T_POS.COUNTY_C = ZC_COUNTY.COUNTY_C
WHERE T_POS.POS_ID IS NOT NULL