{{ config(materialized = 'view') }}

SELECT DISTINCT T_POS.POS_ID 
	, T_POS.POS_NAME 
	, T_POS.ADDRESS_LINE_1
	, T_POS.ADDRESS_LINE_2
	, T_POS.CITY
	, T_POS.STATE_C
	, T_POS.STATE_ABBR
	, T_POS.COUNTY_C AS COUNTY_C
	, T_POS.COUNTY AS COUNTY_NAME
	, T_POS.ZIP
	, POS_TYPE 
FROM {{ref('T_POS')}} AS T_POS
WHERE T_POS.POS_ID IS NOT NULL