SELECT *
FROM
(
	SELECT *	
	-- PCP PHYSICIAN POINTOFSERVICE	
	FROM {{ref('PCP_PHYSICIAN_POINTOFSERVIDE')}}
	UNION
	SELECT *
	--Encounter physician PointOfService	
	FROM   {{ref('ENC_PHYSICIAN_POINTOFSERVICE')}}
) AS T_POS