--AOU_PII_VALIDATION 

--This code identifies valid participants from the AOU_PII table

{{ config(materialized = 'view') }}

SELECT PID
	,CASE 
		WHEN FIRSTNAME = 1
			THEN 'MATCH'
		ELSE 'NOMATCH'
		END AS FIRSTNAME
	,CASE 
		WHEN LASTNAME = 1
			THEN 'MATCH'
		ELSE 'NOMATCH'
		END AS LASTNAME
	,CASE 
		WHEN DOB = 1
			THEN 'MATCH'
		ELSE 'NOMATCH'
		END AS DOB
	,CASE 
		WHEN SEX = 1
			THEN 'MATCH'
		ELSE 'NOMATCH'
		END AS SEX
	,CASE 
		WHEN ADDRESS = 1
			THEN 'MATCH'
		ELSE 'NOMATCH'
		END AS ADDRESS
	,CASE 
		WHEN "PHONE NUMBER" = 1
			THEN 'MATCH'
		ELSE 'NOMATCH'
		END AS "PHONE NUMBER"
	,CASE 
		WHEN EMAIL = 1
			THEN 'MATCH'
		ELSE 'NOMATCH'
		END AS EMAIL
	,CASE 
		WHEN "MANUAL VALIDATION" = 1
			THEN 'YES'
		ELSE 'NO'
		END AS "MANUAL VALIDATION"
	,CASE 
		WHEN (LASTNAME + FIRSTNAME + DOB) = 3
			THEN 'YES'
		WHEN (LASTNAME + FIRSTNAME + DOB) < 3
			AND (SEX + ADDRESS + "PHONE NUMBER" + EMAIL) >= 2
			THEN  'YES'
		ELSE  'NO'
		END AS ALGORITHM_VALIDATION

FROM {{ref('AOU_PII')}} AS AOU_PII

