-- SH_OMOP_DB_PROD.OMOP.QRY_PARTICIPANTS 

WITH PII AS (   
SELECT CPI AS MRN
    , EPIC_PAT_ID AS EHR_PAT_ID
    , AOU_ID AS ALT_ID
    , PID
    , FIRSTNAME
    , EPIC_FIRST_NAME AS EHR_FIRST_NAME
    , AOU_FIRST_NAME AS ALT_FIRST_NAME
    , LASTNAME
    , EPIC_LAST_NAME AS EHR_LAST_NAME
    , AOU_LAST_NAME AS ALT_LAST_NAME
    , DOB
    , EPIC_BIRTH_DATE AS EHR_BIRTH_DATE
    , AOU_BIRTH_DATE AS ALT_BIRTH_DATE
    , SEX
    , EPIC_SEX AS EHR_SEX
    , AOU_SEX AS ALT_SEX
    , ADDRESS
    , EPIC_ADDRESS AS EHR_ADDRESS
    , AOU_ADDRESS AS ALT_ADDRESS
    , "PHONE NUMBER"
    , EPIC_PHONE AS EHR_PHONE
    , AOU_PHONE AS ALT_PHONE
    , EMAIL
    , EPIC_EMAIL AS EHR_EMAIL
    , AOU_EMAIL AS ALT_EMAIL
    , "MANUAL VALIDATION"

FROM {{ref('AOU_PII')}} AS AOU_PII
)

SELECT PII.MRN
    , PII.EHR_PAT_ID
    , PII.ALT_ID
    , PERSON.PERSON_ID AS PID
    , PII.EHR_FIRST_NAME
    , PII.EHR_LAST_NAME
    , PII.ALT_FIRST_NAME
    , PII.ALT_LAST_NAME
    , PII.EHR_BIRTH_DATE
    , PII.ALT_BIRTH_DATE
    , PII.EHR_SEX
    , PII.ALT_SEX
    , PII.EHR_ADDRESS
    , PII.ALT_ADDRESS
    , PII.EHR_PHONE
    , PII.ALT_PHONE
    , PII.EHR_EMAIL
    , PII.ALT_EMAIL

FROM {{ref('PERSON')}} AS PERSON

LEFT JOIN PII
    ON PERSON.PERSON_ID = PII.PID