-- NOTE_CLARITYANES_ALL
{{ config(materialized='view') }}

SELECT  SUBSTRING(PAT_ENC_AMB.AoU_ID, 2, LEN(PAT_ENC_AMB.AoU_ID)) AS person_id
	,PAT_ENC_AMB.AoU_ID
	,PAT_ENC_AMB.PAT_ID
	-----hospital encounter---------
	,PAT_ENC_HSP.PAT_ENC_CSN_ID
	--------------------------------
	,PAT_ENC_AMB.HSP_ACCOUNT_ID
	,PAT_ENC_AMB.IP_DOC_CONTACT_CSN
	,PAT_ENC_AMB.ENC_TYPE_C
	,PAT_ENC_AMB.ZC_DISP_ENC_TYPE_NAME
	,PAT_ENC_AMB.pat_or_adm_link_csn as pat_or_adm_link_PAT_ENC_CSN_ID
	,Z_NOTE_LOOKUP.ENTRY_INSTANT_DTTM
	,Z_NOTE_LOOKUP.ZC_NOTE_TYPE_IP_NAME
	,Z_NOTE_LOOKUP.IP_NOTE_TYPE_C
	,Z_NOTE_LOOKUP.AMB_NOTE_YN
	,Z_NOTE_LOOKUP.NOTE_ID
	,Z_NOTE_LOOKUP.CONTACT_DATE_REAL
	,PAT_ENC_AMB.visit_PROV_ID
--	,HNO_INFO.IP_NOTE_TYPE_C
	,Z_NOTE_LOOKUP.LINE
	,Z_NOTE_LOOKUP.NOTE_CSN_ID
	,Z_NOTE_LOOKUP.CONTACT_DATE
	,Z_NOTE_LOOKUP.CM_CT_OWNER_ID
	,Z_NOTE_LOOKUP.CHRON_ITEM_NUM
	,Z_NOTE_LOOKUP.NOTE_TEXT
	,Z_NOTE_LOOKUP.IS_ARCHIVED_YN
	,'PULL_NOTE--CLARITYANES--ALL' AS ETL_Module


 FROM {{ref('VISIT_OCCURRENCE_CLARITYAMB_ALL')}}  PAT_ENC_AMB

--INNER JOIN {{ref('AOU_DRIVER')}} AS AOU_DRIVER
--	ON PAT_ENC_AMB.PAT_ID = AOU_DRIVER.EPIC_PAT_ID

-- associates anethesia EVENT to hospital encounter
  INNER JOIN {{ source('CLARITY','F_AN_RECORD_SUMMARY')}} AS F_AN_RECORD_SUMMARY on PAT_ENC_AMB.PAT_ENC_CSN_ID = F_AN_RECORD_SUMMARY.AN_53_ENC_CSN_ID
  inner join {{ source('CLARITY','AN_HSB_LINK_INFO')}} AS AN_HSB_LINK_INFO on F_AN_RECORD_SUMMARY.AN_EPISODE_ID=AN_HSB_LINK_INFO.SUMMARY_BLOCK_ID
  inner join {{ source('CLARITY','PAT_ENC_HSP')}} AS PAT_ENC_HSP on AN_HSB_LINK_INFO.AN_BILLING_CSN_ID=PAT_ENC_HSP.PAT_ENC_CSN_ID

INNER JOIN  {{ref('Z_NOTE_LOOKUP')}} AS Z_NOTE_LOOKUP
		ON  PAT_ENC_AMB.PAT_ENC_CSN_ID= Z_NOTE_LOOKUP.PAT_ENC_CSN_ID


{# replaced by Z_NOTE_LOOKUP
	INNER JOIN {{ source('CLARITY','HNO_INFO')}} AS HNO_INFO
	ON  PAT_ENC_AMB.PAT_ENC_CSN_ID= hno_info.PAT_ENC_CSN_ID

INNER JOIN {{ source('CLARITY','ZC_NOTE_TYPE_IP')}} AS ZC_NOTE_TYPE_IP
	ON HNO_INFO.IP_NOTE_TYPE_C = ZC_NOTE_TYPE_IP.TYPE_IP_C

INNER JOIN {{ source('CLARITY','NOTE_ENC_INFO')}} AS NOTE_ENC_INFO
	ON HNO_INFO.NOTE_ID = NOTE_ENC_INFO.NOTE_ID

INNER JOIN {{ source('CLARITY','HNO_NOTE_TEXT')}} AS HNO_NOTE_TEXT
	ON NOTE_ENC_INFO.NOTE_ID = HNO_NOTE_TEXT.NOTE_ID
		AND NOTE_ENC_INFO.CONTACT_DATE_REAL = HNO_NOTE_TEXT.CONTACT_DATE_REAL #}

WHERE
	PAT_ENC_AMB.ENC_TYPE_C = 53 -- Anesthesia EVENT

