-- NOTE_CLARITYAMB_ALL

SELECT  SUBSTRING(AOU_DRIVER.AOU_ID, 2, LEN(AOU_DRIVER.AOU_ID)) AS PERSON_ID
	,AOU_DRIVER.AOU_ID
	,PAT_ENC_AMB.PAT_ID
	,PAT_ENC_AMB.PAT_ENC_CSN_ID
	,PAT_ENC_AMB.HSP_ACCOUNT_ID
	,PAT_ENC_AMB.IP_DOC_CONTACT_CSN
	,PAT_ENC_AMB.ENC_TYPE_C
	,PAT_ENC_AMB.ZC_DISP_ENC_TYPE_NAME
	,PAT_ENC_AMB.PAT_OR_ADM_LINK_CSN AS PAT_OR_ADM_LINK_PAT_ENC_CSN_ID
	,NOTE_ENC_INFO.ENTRY_INSTANT_DTTM
	
	,ZC_NOTE_TYPE_IP.NAME AS ZC_NOTE_TYPE_IP_NAME
--	,NULL AS ZC_NOTE_TYPE_IP_NAME

	,HNO_INFO.IP_NOTE_TYPE_C
--	,NULL AS TYPE_IP_C
	
	,HNO_INFO.AMB_NOTE_YN
	,NOTE_ENC_INFO.NOTE_ID
	,NOTE_ENC_INFO.CONTACT_DATE_REAL
	--,PAT_ENC_AMB.VISIT_PROV_ID
		--ADDED 3/3/2021 
	,PAT_ENC_AMB.VISIT_PROV_ID
	,VISIT_PROVIDER_NAME
	,VISIT_PROVIDER_TYPE

	,PAT_ENC_AMB.PCP_PROV_ID
	,PCP_PROVIDER_NAME
	, PCP_PROVIDER_TYPE
--	,HNO_INFO.IP_NOTE_TYPE_C
	,HNO_NOTE_TEXT.LINE
	,HNO_NOTE_TEXT.NOTE_CSN_ID
	,HNO_NOTE_TEXT.CONTACT_DATE
	,HNO_NOTE_TEXT.CM_CT_OWNER_ID
	,HNO_NOTE_TEXT.CHRON_ITEM_NUM
	,HNO_NOTE_TEXT.NOTE_TEXT
	,HNO_NOTE_TEXT.IS_ARCHIVED_YN
	,'PULL_NOTE--CLARITYAMB--ALL' AS ETL_MODULE

--INTO SH_OMOP_DB_PROD.OMOP_CLARITY.NOTE_CLARITYAMB_ALL

FROM {{ref('VISIT_OCCURRENCE_CLARITYAMB_ALL')}} AS PAT_ENC_AMB

INNER JOIN {{ref('AOU_DRIVER')}} AS AOU_DRIVER
	ON PAT_ENC_AMB.PAT_ID = AOU_DRIVER.EPIC_PAT_ID

INNER JOIN {{ source('CLARITY','HNO_INFO')}} AS HNO_INFO
	ON  PAT_ENC_AMB.PAT_ENC_CSN_ID= HNO_INFO.PAT_ENC_CSN_ID

INNER JOIN {{ source('CLARITY','ZC_NOTE_TYPE_IP')}} AS ZC_NOTE_TYPE_IP
	ON HNO_INFO.IP_NOTE_TYPE_C = ZC_NOTE_TYPE_IP.TYPE_IP_C

INNER JOIN {{ source('CLARITY','NOTE_ENC_INFO')}} AS NOTE_ENC_INFO
	ON HNO_INFO.NOTE_ID = NOTE_ENC_INFO.NOTE_ID

INNER JOIN {{ source('CLARITY','HNO_NOTE_TEXT')}} AS HNO_NOTE_TEXT
	ON NOTE_ENC_INFO.NOTE_ID = HNO_NOTE_TEXT.NOTE_ID
		AND NOTE_ENC_INFO.CONTACT_DATE_REAL = HNO_NOTE_TEXT.CONTACT_DATE_REAL

WHERE ENTRY_INSTANT_DTTM IS NOT NULL 
	AND 
	PAT_ENC_AMB.ENC_TYPE_C <> 3 

