-- NOTE_CLARITYHOSP_ALL
{{ config(materialized='view') }}

SELECT DISTINCT --HNO_INFO.NOTE_ID

	SUBSTRING(AOU_DRIVER.AoU_ID, 2, LEN(AOU_DRIVER.AOU_ID)) AS PERSON_ID
	,AOU_ID
	,Z_NOTE_LOOKUP.ENTRY_INSTANT_DTTM

  ,Z_NOTE_LOOKUP. ZC_NOTE_TYPE_IP_NAME
--    ,NULL AS ZC_NOTE_TYPE_IP_NAME

    ,Z_NOTE_LOOKUP.IP_NOTE_TYPE_C
--  ,NULL AS TYPE_IP_C
    
	,Z_NOTE_LOOKUP.AMB_NOTE_YN
	,PAT_ENC_HSP.PAT_ENC_CSN_ID
	,Z_NOTE_LOOKUP.NOTE_ID
	,Z_NOTE_LOOKUP.CONTACT_DATE_REAL
	,PAT_ENC_HSP.BILL_ATTEND_PROV_ID
	,Z_NOTE_LOOKUP.LINE
	,Z_NOTE_LOOKUP.NOTE_CSN_ID
	,Z_NOTE_LOOKUP.CONTACT_DATE
	,Z_NOTE_LOOKUP.CM_CT_OWNER_ID
	,Z_NOTE_LOOKUP.CHRON_ITEM_NUM
	,Z_NOTE_LOOKUP.NOTE_TEXT
	,Z_NOTE_LOOKUP.IS_ARCHIVED_YN
	{# ,Z_NOTE_LOOKUP.CURRENT_AUTHOR_ID #}
	,HSP_ATND_PROV.PROV_ID
	,ATTENDING_PROV_ID
	,COALESCE(ATTENDING_PROV_ID,HSP_ATND_PROV.PROV_ID) as  CALC_ATTEND_PROV_ID
	,'PULL_NOTE--CLARITYHOSP--ALL' AS ETL_Module


--INTO OMOP_Clarity.NOTE_ClarityHosp_ALL

FROM {{ source('CLARITY','PAT_ENC_HSP')}} AS PAT_ENC_HSP

INNER JOIN {{ref('AOU_DRIVER')}} AS AOU_DRIVER
	ON PAT_ENC_HSP.PAT_ID = AOU_DRIVER.Epic_Pat_id

INNER JOIN  {{ref('Z_NOTE_LOOKUP')}} AS Z_NOTE_LOOKUP
		ON  PAT_ENC_HSP.PAT_ENC_CSN_ID= Z_NOTE_LOOKUP.PAT_ENC_CSN_ID

{# replaced by Z_NOTE_LOOKUP
	LEFT JOIN {{ source('CLARITY','HNO_INFO')}} AS HNO_INFO
	ON hno_info.PAT_ENC_CSN_ID = PAT_ENC_HSP.PAT_ENC_CSN_ID
INNER JOIN {{ source('CLARITY','ZC_NOTE_TYPE_IP')}} AS ZC_NOTE_TYPE_IP
	ON HNO_INFO.IP_NOTE_TYPE_C = ZC_NOTE_TYPE_IP.TYPE_IP_C
LEFT JOIN {{ source('CLARITY','NOTE_ENC_INFO')}} AS NOTE_ENC_INFO
	ON HNO_INFO.NOTE_ID = NOTE_ENC_INFO.NOTE_ID
LEFT JOIN {{ source('CLARITY','HNO_NOTE_TEXT')}} AS HNO_NOTE_TEXT
	ON NOTE_ENC_INFO.NOTE_ID = HNO_NOTE_TEXT.NOTE_ID
		AND NOTE_ENC_INFO.CONTACT_DATE_REAL = HNO_NOTE_TEXT.CONTACT_DATE_REAL #}

LEFT JOIN {{ source('CLARITY','HSP_ATND_PROV')}} AS HSP_ATND_PROV
		ON PAT_ENC_HSP.PAT_ENC_CSN_ID = HSP_ATND_PROV.PAT_ENC_CSN_ID
			AND HOSP_DISCH_TIME BETWEEN ATTEND_FROM_DATE
				AND COALESCE(ATTEND_TO_DATE, GETDATE())

LEFT JOIN {{ source('CLARITY','HSP_ACCOUNT')}} AS HSP_ACCOUNT
		ON PAT_ENC_HSP.HSP_ACCOUNT_ID = HSP_ACCOUNT.HSP_ACCOUNT_ID

WHERE ENTRY_INSTANT_DTTM IS NOT NULL

