-- NOTE_CLARITYAMB_ALL
{{ config(materialized='view') }}

SELECT  SUBSTRING(PAT_ENC_AMB.AOU_ID, 2, LEN(PAT_ENC_AMB.AOU_ID)) ::NUMBER(28,0) AS PERSON_ID
	,PAT_ENC_AMB.AOU_ID
	,PAT_ENC_AMB.PAT_ID
	,PAT_ENC_AMB.PAT_ENC_CSN_ID
	,PAT_ENC_AMB.HSP_ACCOUNT_ID
	,PAT_ENC_AMB.IP_DOC_CONTACT_CSN
	,PAT_ENC_AMB.ENC_TYPE_C
	,PAT_ENC_AMB.ZC_DISP_ENC_TYPE_NAME
	,PAT_ENC_AMB.PAT_OR_ADM_LINK_CSN AS PAT_OR_ADM_LINK_PAT_ENC_CSN_ID
	,Z_NOTE_LOOKUP.ENTRY_INSTANT_DTTM
	,Z_NOTE_LOOKUP.ZC_NOTE_TYPE_IP_NAME
	,Z_NOTE_LOOKUP.IP_NOTE_TYPE_C
	,Z_NOTE_LOOKUP.AMB_NOTE_YN
	,Z_NOTE_LOOKUP.NOTE_ID
	,Z_NOTE_LOOKUP.CONTACT_DATE_REAL
	,PAT_ENC_AMB.VISIT_PROV_ID
	,VISIT_PROVIDER_NAME
	,VISIT_PROVIDER_TYPE
	,PAT_ENC_AMB.PCP_PROV_ID
	,PCP_PROVIDER_NAME
	, PCP_PROVIDER_TYPE
	,Z_NOTE_LOOKUP.LINE
	,Z_NOTE_LOOKUP.NOTE_CSN_ID
	,Z_NOTE_LOOKUP.CONTACT_DATE
	,Z_NOTE_LOOKUP.CM_CT_OWNER_ID
	,Z_NOTE_LOOKUP.CHRON_ITEM_NUM
	,Z_NOTE_LOOKUP.NOTE_TEXT
	,Z_NOTE_LOOKUP.IS_ARCHIVED_YN
	,'PULL_NOTE--CLARITYAMB--ALL' AS ETL_MODULE

--INTO SH_OMOP_DB_PROD.OMOP_CLARITY.NOTE_CLARITYAMB_ALL

FROM {{ref('VISIT_OCCURRENCE_CLARITYAMB_ALL')}} AS PAT_ENC_AMB

{# INNER JOIN {{ref('AOU_DRIVER')}} AS AOU_DRIVER
	ON PAT_ENC_AMB.PAT_ID = AOU_DRIVER.EPIC_PAT_ID #}

INNER JOIN  {{ref('Z_NOTE_LOOKUP')}} AS Z_NOTE_LOOKUP
		ON  PAT_ENC_AMB.PAT_ENC_CSN_ID= Z_NOTE_LOOKUP.PAT_ENC_CSN_ID

{# replaced by Z_NOTE_LOOKUP
	 LEFT JOIN {{ source('CLARITY','HNO_INFO')}} AS HNO_INFO
	ON  PAT_ENC_AMB.PAT_ENC_CSN_ID= HNO_INFO.PAT_ENC_CSN_ID

INNER JOIN {{ source('CLARITY','ZC_NOTE_TYPE_IP')}} AS ZC_NOTE_TYPE_IP
	ON HNO_INFO.IP_NOTE_TYPE_C = ZC_NOTE_TYPE_IP.TYPE_IP_C

LEFT JOIN {{ source('CLARITY','NOTE_ENC_INFO')}} AS NOTE_ENC_INFO
	ON HNO_INFO.NOTE_ID = NOTE_ENC_INFO.NOTE_ID

LEFT JOIN {{ source('CLARITY','HNO_NOTE_TEXT')}} AS HNO_NOTE_TEXT
	ON NOTE_ENC_INFO.NOTE_ID = HNO_NOTE_TEXT.NOTE_ID
		AND NOTE_ENC_INFO.CONTACT_DATE_REAL = HNO_NOTE_TEXT.CONTACT_DATE_REAL #}

WHERE ENTRY_INSTANT_DTTM IS NOT NULL 
	AND 
	PAT_ENC_AMB.ENC_TYPE_C <> 3 

