--PROCEDURE_OCCURRENCE

{{ config(materialized = 'table') }} 

SELECT 
    SEQ_PROCEDURE_OCCURRENCE.NEXTVAL::NUMBER(28,0)  AS PROCEDURE_OCCURRENCE_ID,
      PERSON_ID::NUMBER(28,0)                       AS PERSON_ID 
    , PROCEDURE_CONCEPT_ID::NUMBER(28,0)            AS PROCEDURE_CONCEPT_ID 
    , PROCEDURE_DATE::DATE                          AS PROCEDURE_DATE
    , PROCEDURE_DATETIME::DATETIME                  AS PROCEDURE_DATETIME
    , PROCEDURE_TYPE_CONCEPT_ID::NUMBER(28,0)       AS PROCEDURE_TYPE_CONCEPT_ID 
    , MODIFIER_CONCEPT_ID::NUMBER(28,0)             AS MODIFIER_CONCEPT_ID 
    , QUANTITY::NUMBER(28,0)                        AS QUANTITY
    , PROVIDER_ID::NUMBER(28,0)                     AS PROVIDER_ID 
    , VISIT_OCCURRENCE_ID::NUMBER(28,0)             AS VISIT_OCCURRENCE_ID 
    , VISIT_DETAIL_ID::NUMBER(28,0)                 AS VISIT_DETAIL_ID 
    , PROCEDURE_SOURCE_VALUE::VARCHAR(50)           AS PROCEDURE_SOURCE_VALUE
    , PROCEDURE_SOURCE_CONCEPT_ID::NUMBER(28,0)     AS PROCEDURE_SOURCE_CONCEPT_ID 
    , MODIFIER_SOURCE_VALUE::VARCHAR(50)            AS MODIFIER_SOURCE_VALUE
    , ETL_MODULE::VARCHAR(100)                      AS ETL_MODULE
    , VISIT_SOURCE_VALUE ::VARCHAR(50)              AS VISIT_SOURCE_VALUE 
FROM
(   
    SELECT * FROM {{ref('V_PROCEDURE_OCCURRENCE_CPT_AMB')}} 
    UNION ALL
    SELECT * FROM {{ref('V_PROCEDURE_OCCURRENCE_CPT_HSP')}} 
    UNION ALL
    SELECT * FROM {{ref('V_PROCEDURE_OCCURRENCE_CPT_SURG')}}
) AS A    