--PERSON

{{ config(materialized='table') }}
SELECT
      PERSON_ID::NUMBER(28,0)                   AS PERSON_ID  
    , GENDER_CONCEPT_ID::NUMBER(28,0)           AS GENDER_CONCEPT_ID  
    , YEAR_OF_BIRTH::NUMBER(28,0)               AS YEAR_OF_BIRTH  
    , MONTH_OF_BIRTH::NUMBER(28,0)              AS MONTH_OF_BIRTH  
    , DAY_OF_BIRTH::NUMBER(28,0)                AS DAY_OF_BIRTH  
    , BIRTH_DATETIME::DATETIME                  AS BIRTH_DATETIME
    , RACE_CONCEPT_ID::NUMBER(28,0)             AS RACE_CONCEPT_ID  
    , ETHNICITY_CONCEPT_ID::NUMBER(28,0)        AS ETHNICITY_CONCEPT_ID  
    , LOCATION_ID::NUMBER(28,0)                 AS LOCATION_ID  
    , PROVIDER_ID::NUMBER(28,0)                 AS PROVIDER_ID  
    , CARE_SITE_ID::NUMBER(28,0)                AS CARE_SITE_ID  
    , PERSON_SOURCE_VALUE::VARCHAR(50)          AS PERSON_SOURCE_VALUE
    , GENDER_SOURCE_VALUE::VARCHAR(50)          AS GENDER_SOURCE_VALUE
    , GENDER_SOURCE_CONCEPT_ID::NUMBER(28,0)    AS GENDER_SOURCE_CONCEPT_ID  
    , RACE_SOURCE_VALUE::VARCHAR(50)            AS RACE_SOURCE_VALUE
    , RACE_SOURCE_CONCEPT_ID::NUMBER(28,0)      AS RACE_SOURCE_CONCEPT_ID  
    , ETHNICITY_SOURCE_VALUE::VARCHAR(50)       AS ETHNICITY_SOURCE_VALUE
    , ETHNICITY_SOURCE_CONCEPT_ID::NUMBER(28,0) AS ETHNICITY_SOURCE_CONCEPT_ID  

FROM 	
 {{ref('V_PERSON_ALL')}} 