--OBSERVATION_CLARITYHOSP_ICD

{{ config(materialized = 'view') }}

SELECT DISTINCT SUBSTRING(AOU_DRIVER.AOU_ID, 2, LEN(AOU_DRIVER.AOU_ID))::NUMBER(28,0) AS PERSON_ID
	,AOU_ID
	,PAT_ENC_DX.CONTACT_DATE
	,PAT_ENC_DX.PAT_ENC_CSN_ID
	,T_DIAGNOSIS.DX_ID
	,T_DIAGNOSIS.DX_NAME
	,T_DIAGNOSIS.ICD10_CODE
	,T_DIAGNOSIS.ICD9_CODE
	,PAT_ENC_HSP.BILL_ATTEND_PROV_ID
	,'OBSERVATION--CLARITYHOSP--ICD' AS ETL_MODULE

FROM {{ source('CLARITY','PAT_ENC_DX')}} AS PAT_ENC_DX

	INNER JOIN {{ source('CLARITY','PAT_ENC_HSP')}} AS PAT_ENC_HSP
		ON PAT_ENC_DX.PAT_ENC_CSN_ID = PAT_ENC_HSP.PAT_ENC_CSN_ID

		LEFT JOIN {{ source('CLARITY','HSP_ATND_PROV')}} AS HSP_ATND_PROV
		ON PAT_ENC_HSP.PAT_ENC_CSN_ID = HSP_ATND_PROV.PAT_ENC_CSN_ID
			AND HOSP_DISCH_TIME BETWEEN ATTEND_FROM_DATE
				AND COALESCE(ATTEND_TO_DATE, GETDATE())

	INNER JOIN {{ref('AOU_DRIVER')}} AS AOU_DRIVER 
		ON PAT_ENC_DX.PAT_ID = AOU_DRIVER.EPIC_PAT_ID

	--------CONCEPT MAPPING--------------------
	INNER JOIN {{ref('T_DIAGNOSIS_OBSERVATION')}} AS T_DIAGNOSIS
		ON PAT_ENC_DX.DX_ID = T_DIAGNOSIS.DX_ID
