--OBSERVATION_CLARITYALL_ALLERGY

{{ config(materialized = 'view') }}

SELECT SUBSTRING(AOU_DRIVER.AOU_ID, 2, LEN(AOU_DRIVER.AOU_ID)) AS PERSON_ID
	, AOU_DRIVER.AOU_ID
	, PAT_ENC.PAT_ID
	, PAT_ENC.PAT_ENC_CSN_ID
	, PAT_ENC.ENC_TYPE_C
	, T_ALLERGY_CODES.ALLERGEN_ID
	, T_ALLERGY_CODES.ALLERGEN_NAME
	, T_ALLERGY_CODES.CONCEPT_NAME
	, ALLERGY.ALRGY_ENTERED_DTTM
	, ALLERGY.DATE_NOTED
	, PAT_ENC.CONTACT_DATE
	, ALLERGY.DESCRIPTION AS VALUE_AS_STRING
	,COALESCE(PAT_ENC.VISIT_PROV_ID, PAT_ENC_hsp.BILL_ATTEND_PROV_ID) as PROV_ID

--INTO OMOP_CLARITY.OBSERVATION_CLARITYALL_ALLERGY

FROM {{ source('CLARITY','PAT_ALLERGIES')}}  AS PAT_ALLERGIES 

	INNER JOIN {{ source('CDM','AOU_DRIVER')}} AS AOU_DRIVER  
		ON (AOU_DRIVER.EPIC_PAT_ID = PAT_ALLERGIES.PAT_ID)

	INNER JOIN {{ source('CLARITY','ALLERGY')}}  AS ALLERGY  
		ON (PAT_ALLERGIES.ALLERGY_RECORD_ID = ALLERGY.ALLERGY_ID)

	LEFT JOIN {{ref('T_ALLERGY_CODES_OBSERVATION')}} AS T_ALLERGY_CODES
		ON (T_ALLERGY_CODES.ALLERGEN_ID = ALLERGY.ALLERGEN_ID)

	INNER JOIN {{ source('CLARITY','PAT_ENC')}} AS PAT_ENC  
		ON ALLERGY.ALLERGY_PAT_CSN = PAT_ENC.PAT_ENC_CSN_ID
	
	LEFT JOIN {{ source('CLARITY','PAT_ENC_HSP')}} AS PAT_ENC_HSP  
		ON ALLERGY.ALLERGY_PAT_CSN = PAT_ENC_HSP.PAT_ENC_CSN_ID		

WHERE UPPER(ALLERGY.DESCRIPTION) != 'NO KNOWN ALLERGIES' 

