--CONDITION_OCCURRENCE 

{{ config(materialized = 'table') }} 

SELECT
    DISTINCT SEQ_CONDITION_OCCURRENCE.NEXTVAL::NUMBER(28,0) AS CONDITION_OCCURRENCE_ID 
    , PERSON_ID::NUMBER(28,0)                     AS PERSON_ID
    , CONDITION_CONCEPT_ID::NUMBER(28,0)          AS CONDITION_CONCEPT_ID
    , CONDITION_START_DATE::DATE                  AS CONDITION_START_DATE
    , CONDITION_START_DATETIME::DATETIME          AS CONDITION_START_DATETIME
    , CONDITION_END_DATE::DATE                    AS CONDITION_END_DATE
    , CONDITION_END_DATETIME::DATETIME            AS CONDITION_END_DATETIME
    , CONDITION_TYPE_CONCEPT_ID::NUMBER(28,0)     AS CONDITION_TYPE_CONCEPT_ID
    , STOP_REASON::VARCHAR(20)                    AS STOP_REASON
    , PROVIDER_ID::NUMBER(28,0)                   AS PROVIDER_ID 
    , VISIT_OCCURRENCE_ID::NUMBER(28,0)           AS VISIT_OCCURRENCE_ID
    , VISIT_DETAIL_ID::NUMBER(28,0)               AS VISIT_DETAIL_ID 
    , CONDITION_SOURCE_VALUE::VARCHAR(50)         AS CONDITION_SOURCE_VALUE
    , CONDITION_SOURCE_CONCEPT_ID::NUMBER(28,0)   AS CONDITION_SOURCE_CONCEPT_ID
    , CONDITION_STATUS_SOURCE_VALUE::VARCHAR(50)  AS CONDITION_STATUS_SOURCE_VALUE
    , CONDITION_STATUS_CONCEPT_ID::NUMBER(28,0)   AS CONDITION_STATUS_CONCEPT_ID
    , ETL_MODULE::VARCHAR(100)                    AS ETL_MODULE
    , VISIT_SOURCE_VALUE::NUMBER(28,0)            AS VISIT_SOURCE_VALUE

FROM
(SELECT *
FROM
     {{ref('V_CONDITION_OCCURRENCE_AMB')}} AS V_CONDITION_OCCURRENCE_AMB    
UNION ALL
SELECT *
FROM 
     {{ref('V_CONDITION_OCCURRENCE_HSP')}} AS V_CONDITION_OCCURRENCE_HSP ) A