--MEASUREMENT 

{{ config(materialized = 'table') }} 

SELECT 
    SEQ_MEASUREMENT.NEXTVAL AS MEASUREMENT_ID,
    A.* 
FROM
(   --HSP
    SELECT * FROM {{ref('V_MEASUREMENT_FLOWSHEET_HSP_BMI')}} 
    UNION ALL
    SELECT * FROM {{ref('V_MEASUREMENT_FLOWSHEET_HSP_BPD')}} 
    UNION ALL
    SELECT * FROM {{ref('V_MEASUREMENT_FLOWSHEET_HSP_BPS')}} 
    UNION ALL
    SELECT * FROM {{ref('V_MEASUREMENT_FLOWSHEET_HSP_MISC')}} 
    UNION ALL
    SELECT * FROM {{ref('V_MEASUREMENT_FLOWSHEET_HSP_TEMPERATURE')}} 
    UNION ALL
    SELECT * FROM {{ref('V_MEASUREMENT_FLOWSHEET_HSP_VITALS')}} 
    UNION ALL
    SELECT * FROM {{ref('V_MEASUREMENT_LOINC_HSP')}}

    --AMB
    UNION ALL
    SELECT * FROM {{ref('V_MEASUREMENT_FLOWSHEET_AMB_BMI')}} 
    UNION ALL
    SELECT * FROM {{ref('V_MEASUREMENT_FLOWSHEET_AMB_BPD')}} 
    UNION ALL
    SELECT * FROM {{ref('V_MEASUREMENT_FLOWSHEET_AMB_BPS')}} 
    UNION ALL
    SELECT * FROM {{ref('V_MEASUREMENT_FLOWSHEET_AMB_MISC')}} 
    UNION ALL
    SELECT * FROM {{ref('V_MEASUREMENT_FLOWSHEET_AMB_TEMPERATURE')}}  
    UNION ALL
    SELECT * FROM {{ref('V_MEASUREMENT_FLOWSHEET_AMB_VITALS')}}
    UNION ALL
    SELECT * FROM {{ref('V_MEASUREMENT_LOINC_AMB')}}

    --ANES
    UNION ALL
    SELECT * FROM {{ref('V_MEASUREMENT_FLOWSHEET_ANES_BPD')}} 
    UNION ALL
    SELECT * FROM {{ref('V_MEASUREMENT_FLOWSHEET_ANES_BPM')}} 
    UNION ALL
    SELECT * FROM {{ref('V_MEASUREMENT_FLOWSHEET_ANES_BPS')}} 
    UNION ALL
    SELECT * FROM {{ref('V_MEASUREMENT_FLOWSHEET_ANES_MISC')}} 
    UNION ALL
    SELECT * FROM {{ref('V_MEASUREMENT_FLOWSHEET_ANES_TEMPERATURE')}}
    UNION ALL
    SELECT * FROM {{ref('V_MEASUREMENT_FLOWSHEET_ANES_VITALS')}}        
) AS A
