------ QA_VISIT_OCCURRENCE_NONSTANDARD_COUNT
---------------------------------------------------------------------
WITH NONSTANDARD_COUNT
AS (
	--VISIT_CONCEPT_ID-------------------------------------------
	SELECT 'VISIT_CONCEPT_ID' AS METRIC_FIELD, 'NON-STANDARD' AS QA_METRIC, 'INVALID DATA' AS ERROR_TYPE, COUNT(*) AS CNT
	FROM {{ref('VISIT_OCCURRENCE')}} AS VO
	LEFT JOIN {{ source('CDM','CONCEPT')}} AS C
		ON VO.VISIT_CONCEPT_ID = C.CONCEPT_ID AND upper(C.VOCABULARY_ID) =  'VISIT' AND upper(C.DOMAIN_ID) = 'VISIT'
	WHERE VISIT_CONCEPT_ID <> 0 AND STANDARD_CONCEPT <> 'S'
	
	UNION ALL
	
	--VISIT_TYPE_CONCEPT_ID-------------------------------------------
	SELECT 'VISIT_TYPE_CONCEPT_ID', 'NON-STANDARD' AS QA_METRIC, 'INVALID DATA' AS ERROR_TYPE, COUNT(*) AS CNT
	FROM {{ref('VISIT_OCCURRENCE')}} AS VO
	LEFT JOIN {{ source('CDM','CONCEPT')}} AS C
		ON VO.VISIT_TYPE_CONCEPT_ID = C.CONCEPT_ID AND upper(C.VOCABULARY_ID) =  'VISIT TYPE' AND upper(C.DOMAIN_ID) = 'TYPE CONCEPT'
	WHERE VISIT_TYPE_CONCEPT_ID <> 0 AND STANDARD_CONCEPT <> 'S'
	
	UNION ALL
	
	--VISIT_SOURCE_CONCEPT_ID-------------------------------------------
	SELECT 'VISIT_SOURCE_CONCEPT_ID', 'NON-STANDARD' AS QA_METRIC, 'INVALID DATA' AS ERROR_TYPE, COUNT(*) AS CNT
	FROM {{ref('VISIT_OCCURRENCE')}} AS VO
	LEFT JOIN {{ source('CDM','CONCEPT')}} AS C
		ON VO.VISIT_SOURCE_CONCEPT_ID = C.CONCEPT_ID AND upper(C.VOCABULARY_ID) =  'VISIT' AND upper(C.DOMAIN_ID) = 'VISIT'
	WHERE VISIT_SOURCE_CONCEPT_ID <> 0 AND STANDARD_CONCEPT <> 'S'
	
	UNION ALL
	
	--ADMITTING_SOURCE_CONCEPT_ID-------------------------------------------			
	SELECT 'ADMITTING_SOURCE_CONCEPT_ID', 'NON-STANDARD' AS QA_METRIC, 'INVALID DATA' AS ERROR_TYPE, COUNT(*) AS CNT
	FROM {{ref('VISIT_OCCURRENCE')}} AS VO
	LEFT JOIN {{ source('CDM','CONCEPT')}} AS C
		ON VO.ADMITTING_SOURCE_CONCEPT_ID = C.CONCEPT_ID AND upper(C.VOCABULARY_ID) =  'CMS PLACE OF SERVICE'
	WHERE ADMITTING_SOURCE_CONCEPT_ID <> 0 AND STANDARD_CONCEPT <> 'S'
	
	UNION ALL
	
	--DISCHARGE_TO_CONCEPT_ID-------------------------------------------
	SELECT 'DISCHARGE_TO_CONCEPT_ID', 'NON-STANDARD' AS QA_METRIC, 'INVALID DATA' AS ERROR_TYPE, COUNT(*) AS CNT
	FROM {{ref('VISIT_OCCURRENCE')}} AS VO
	LEFT JOIN {{ source('CDM','CONCEPT')}} AS C
		ON VO.DISCHARGE_TO_CONCEPT_ID = C.CONCEPT_ID AND upper(C.VOCABULARY_ID) =  'CMS PLACE OF SERVICE'
	WHERE DISCHARGE_TO_CONCEPT_ID <> 0 AND STANDARD_CONCEPT <> 'S'
	)


SELECT CAST( GETDATE() AS DATE) AS RUN_DATE
	,'VISIT_OCCURRENCE' AS STANDARD_DATA_TABLE
	, QA_METRIC AS QA_METRIC	
	, METRIC_FIELD  AS METRIC_FIELD
	, COALESCE(SUM(CNT),0) AS QA_ERRORS
	, CASE WHEN SUM(CNT) <> 0 THEN ERROR_TYPE ELSE NULL END   AS ERROR_TYPE
	, (SELECT COUNT(*) AS NUM_ROWS FROM {{ref('VISIT_OCCURRENCE')}}) AS TOTAL_RECORDS
FROM NONSTANDARD_COUNT	
GROUP BY  METRIC_FIELD, QA_METRIC, ERROR_TYPE

