--QA_VISIT_OCCURRENCE_DUPLICATES_DETAIL
---------------------------------------------------------------------
WITH TMP_DUPES_DETAIL AS (
SELECT PERSON_ID
	,VISIT_CONCEPT_ID
	,VISIT_START_DATE
	,VISIT_START_DATETIME
	,VISIT_END_DATE
	,VISIT_END_DATETIME
	,VISIT_TYPE_CONCEPT_ID
	,PROVIDER_ID
	,CARE_SITE_ID
	,VISIT_SOURCE_VALUE
	,VISIT_SOURCE_CONCEPT_ID
	,ADMITTING_SOURCE_CONCEPT_ID
	,ADMITTING_SOURCE_VALUE
	,DISCHARGE_TO_CONCEPT_ID
	,DISCHARGE_TO_SOURCE_VALUE
	,PRECEDING_VISIT_OCCURRENCE_ID
	,COUNT(*) AS CNT
--INTO #TMP_DUPES	
FROM {{ref('VISIT_OCCURRENCE')}} AS T1
GROUP BY PERSON_ID
	,VISIT_CONCEPT_ID
	,VISIT_START_DATE
	,VISIT_START_DATETIME
	,VISIT_END_DATE
	,VISIT_END_DATETIME
	,VISIT_TYPE_CONCEPT_ID
	,PROVIDER_ID
	,CARE_SITE_ID
	,VISIT_SOURCE_VALUE
	,VISIT_SOURCE_CONCEPT_ID
	,ADMITTING_SOURCE_CONCEPT_ID
	,ADMITTING_SOURCE_VALUE
	,DISCHARGE_TO_CONCEPT_ID
	,DISCHARGE_TO_SOURCE_VALUE
	,PRECEDING_VISIT_OCCURRENCE_ID
HAVING COUNT(*) > 1
)

SELECT CAST(GETDATE() AS DATE) AS RUN_DATE
	,'VISIT_OCCURRENCE' AS STANDARD_DATA_TABLE
	,'DUPLICATE' AS QA_METRIC
	,'RECORDS'  AS METRIC_FIELD
	,'FATAL' AS ERROR_TYPE
	,VI.VISIT_OCCURRENCE_ID

FROM TMP_DUPES_DETAIL AS D
INNER JOIN {{ref('VISIT_OCCURRENCE')}} AS VI ON D.PERSON_ID = VI.PERSON_ID
	AND D.VISIT_CONCEPT_ID =VI.VISIT_CONCEPT_ID
	AND D.VISIT_START_DATE = VI.VISIT_START_DATE
	AND D.VISIT_START_DATETIME = VI.VISIT_START_DATETIME
	AND D.VISIT_END_DATE = VI.VISIT_END_DATE
	AND COALESCE(D.VISIT_END_DATETIME,'1900-01-01') = COALESCE(VI.VISIT_END_DATETIME,'1900-01-01')
	AND COALESCE(D.VISIT_TYPE_CONCEPT_ID, 0) = COALESCE(VI.VISIT_TYPE_CONCEPT_ID, 0)
	AND COALESCE(D.PROVIDER_ID, 0) = COALESCE(VI.PROVIDER_ID, 0)
	AND COALESCE(D.CARE_SITE_ID, 0) = COALESCE(VI.CARE_SITE_ID, 0)
	AND COALESCE(D.VISIT_SOURCE_VALUE, '0') = COALESCE(VI.VISIT_SOURCE_VALUE, '0')
	AND COALESCE(D.VISIT_SOURCE_CONCEPT_ID, 0) = COALESCE(VI.VISIT_SOURCE_CONCEPT_ID, 0)
	AND COALESCE(D.ADMITTING_SOURCE_CONCEPT_ID, 0) = COALESCE(VI.ADMITTING_SOURCE_CONCEPT_ID, 0)
	AND COALESCE(D.ADMITTING_SOURCE_VALUE, '0') = COALESCE(VI.ADMITTING_SOURCE_VALUE, '0')
	AND COALESCE(D.DISCHARGE_TO_CONCEPT_ID, 0) = COALESCE(VI.DISCHARGE_TO_CONCEPT_ID, 0)
	AND COALESCE(D.DISCHARGE_TO_SOURCE_VALUE, '0') = COALESCE(VI.DISCHARGE_TO_SOURCE_VALUE, '0')
	AND COALESCE(D.PRECEDING_VISIT_OCCURRENCE_ID, 0) = COALESCE(VI.PRECEDING_VISIT_OCCURRENCE_ID, 0)

 