--Z_NOTE_LOOKUP
{{ config(materialized='table', 
        cluster_by = ['PAT_ENC_CSN_ID']) }}

SELECT HNO_INFO.PAT_ID
 	,HNO_INFO.PAT_ENC_CSN_ID
	,NOTE_ENC_INFO.ENTRY_INSTANT_DTTM
	,ZC_NOTE_TYPE_IP.NAME AS ZC_NOTE_TYPE_IP_NAME
	,HNO_INFO.IP_NOTE_TYPE_C
	,HNO_INFO.AMB_NOTE_YN
	,NOTE_ENC_INFO.NOTE_ID
	,NOTE_ENC_INFO.CONTACT_DATE_REAL
	,HNO_NOTE_TEXT.LINE
	,HNO_NOTE_TEXT.NOTE_CSN_ID
	,HNO_NOTE_TEXT.CONTACT_DATE
	,HNO_NOTE_TEXT.CM_CT_OWNER_ID
	,HNO_NOTE_TEXT.CHRON_ITEM_NUM
	,HNO_NOTE_TEXT.NOTE_TEXT
	,HNO_NOTE_TEXT.IS_ARCHIVED_YN
FROM
{{ source('CLARITY','HNO_INFO')}} AS HNO_INFO
{# 
INNER JOIN {{ref('AOU_DRIVER')}} AS AOU_DRIVER
	ON HNO_INFO.PAT_ID = AOU_DRIVER.EPIC_PAT_ID #}

INNER JOIN {{ source('CLARITY','ZC_NOTE_TYPE_IP')}} AS ZC_NOTE_TYPE_IP
	ON HNO_INFO.IP_NOTE_TYPE_C = ZC_NOTE_TYPE_IP.TYPE_IP_C

INNER JOIN {{ source('CLARITY','NOTE_ENC_INFO')}} AS NOTE_ENC_INFO
	ON HNO_INFO.NOTE_ID = NOTE_ENC_INFO.NOTE_ID

INNER JOIN {{ source('CLARITY','HNO_NOTE_TEXT')}} AS HNO_NOTE_TEXT
	ON NOTE_ENC_INFO.NOTE_ID = HNO_NOTE_TEXT.NOTE_ID
		AND NOTE_ENC_INFO.CONTACT_DATE_REAL = HNO_NOTE_TEXT.CONTACT_DATE_REAL

WHERE HNO_INFO.PAT_ID IN (SELECT EPIC_PAT_ID from {{ref('AOU_DRIVER')}})