--DEATH_CLARITY_ALL
{{ config(materialized = 'view') }}

SELECT DISTINCT SUBSTRING(AOU_DRIVER.AOU_ID, 2, LEN(AOU_DRIVER.AOU_ID)) AS PERSON_ID
      ,DEATH_DATE::DATE AS DEATH_DATE
      ,DEATH_DATE AS DEATH_DATETIME
      --,--NEED CAUSE OF DEATH

  FROM   {{ source('CDM','AOU_DRIVER')}} AS AOU_DRIVER  
 INNER JOIN   {{ source('CLARITY','PATIENT')}} AS PATIENT 
    ON AOU_DRIVER.EPIC_PAT_ID = PATIENT.PAT_ID 
        AND PAT_STATUS_C = 2