-- V_NOTE_ANES


SELECT  --DISTINCT 
--	CDM.SEQ_NOTE.NEXTVAL AS NOTE_ID
	NOTE_CLARITYANES_ALL.PERSON_ID
	,CAST( NOTE_CLARITYANES_ALL.ENTRY_INSTANT_DTTM AS DATE) AS NOTE_DATE
	,NOTE_CLARITYANES_ALL.ENTRY_INSTANT_DTTM AS NOTE_DATETIME
	,32817 AS NOTE_TYPE_CONCEPT_ID
	,COALESCE(SOURCE_TO_CONCEPT_MAP_NOTE_CLASS.TARGET_CONCEPT_ID, 0) AS NOTE_CLASS_CONCEPT_ID
	,NOTE_CLARITYANES_ALL.ZC_NOTE_TYPE_IP_NAME AS NOTE_TITLE

	-- ******************************************
	  ,'NO_TEXT' AS NOTE_TEXT	-- NO ACTUAL TEXT IS BEING WRITTEN AT THIS TIME OVER PHI CONCERNS
	--,NOTE_CLARITYHOSP_ALL.NOTE_TEXT AS NOTE_TEXT
	-- ******************************************

	,32678 AS ENCODING_CONCEPT_ID --UTF-8 
	,4180186 AS LANGUAGE_CONCEPT_ID
	,PROVIDER.PROVIDER_ID AS PROVIDER_ID
	,VISIT_OCCURRENCE.VISIT_OCCURRENCE_ID AS VISIT_OCCURRENCE_ID
	    
--    ,VISIT_DETAIL.VISIT_DETAIL_ID AS VISIT_DETAIL_ID
    ,0 AS VISIT_DETAIL_ID

	,NOTE_CLARITYANES_ALL.IP_NOTE_TYPE_C || ':' || NOTE_CLARITYANES_ALL.AMB_NOTE_YN || ':' || ZC_NOTE_TYPE_IP_NAME AS NOTE_SOURCE_VALUE
	,'NOTE--CLARITYANES--ALL' AS ETL_MODULE
	,VISIT_SOURCE_VALUE

FROM {{ref('NOTE_CLARITYANES_ALL')}} AS NOTE_CLARITYANES_ALL

INNER JOIN {{ref('T_MAX_NOTE_DATE_ANES')}} AS T_MAX_NOTE_DATE
	ON NOTE_CLARITYANES_ALL.NOTE_ID = T_MAX_NOTE_DATE.NOTE_ID
	AND NOTE_CLARITYANES_ALL.LINE= T_MAX_NOTE_DATE.LINE

LEFT JOIN {{ source('CDM','SOURCE_TO_CONCEPT_MAP')}} AS  SOURCE_TO_CONCEPT_MAP_NOTE_TYPE
	ON NOTE_CLARITYANES_ALL.AMB_NOTE_YN = SOURCE_TO_CONCEPT_MAP_NOTE_TYPE.SOURCE_CODE
		AND UPPER(SOURCE_TO_CONCEPT_MAP_NOTE_TYPE.SOURCE_VOCABULARY_ID) = 'SH_NOTE_TYPE'

LEFT JOIN {{ source('CDM','SOURCE_TO_CONCEPT_MAP')}} AS SOURCE_TO_CONCEPT_MAP_NOTE_CLASS
	ON NOTE_CLARITYANES_ALL.IP_NOTE_TYPE_C || NOTE_CLARITYANES_ALL.AMB_NOTE_YN = SOURCE_TO_CONCEPT_MAP_NOTE_CLASS.SOURCE_CODE
		AND UPPER(SOURCE_TO_CONCEPT_MAP_NOTE_CLASS.SOURCE_VOCABULARY_ID) = 'SH_NOTE_CLASS'

INNER JOIN {{ref('VISIT_OCCURRENCE')}} AS VISIT_OCCURRENCE
	ON NOTE_CLARITYANES_ALL.PAT_ENC_CSN_ID = VISIT_OCCURRENCE.VISIT_SOURCE_VALUE

LEFT JOIN {{ref('PROVIDER')}} AS PROVIDER
	ON NOTE_CLARITYANES_ALL.VISIT_PROV_ID = PROVIDER.PROVIDER_SOURCE_VALUE

WHERE ENTRY_INSTANT_DTTM IS NOT NULL
	AND NOTE_CLARITYANES_ALL.LINE = 1

