--V_OBSERVATION_ICD_AMB

{{ config(materialized = 'view') }}

SELECT DISTINCT 
--	CDM.SEQ_OBSERVATION.NEXTVAL AS OBSERVATION_ID
	OBSERVATION_CLARITYAMB_ICD.PERSON_ID
	,CASE 
		WHEN OBSERVATION_CLARITYAMB_ICD.CONTACT_DATE >= '2015-10-01'
			THEN T_ICD10_CONCEPT.CONCEPT_ID
		ELSE T_ICD9_CONCEPT.CONCEPT_ID
		END AS OBSERVATION_CONCEPT_ID

	,CAST( OBSERVATION_CLARITYAMB_ICD.CONTACT_DATE AS DATE) AS OBSERVATION_DATE
	,OBSERVATION_CLARITYAMB_ICD.CONTACT_DATE AS OBSERVATION_DATETIME
	,32817 AS OBSERVATION_TYPE_CONCEPT_ID --EHR
	,NULL AS VALUE_AS_NUMBER
	-- RETURNS ICD10 CODES AFTER SWITCH DATE-----
	,CASE 
		WHEN OBSERVATION_CLARITYAMB_ICD.CONTACT_DATE >= '2015-10-01'
			THEN T_ICD10_SOURCE.CONCEPT_CODE
		ELSE T_ICD9_SOURCE.CONCEPT_CODE
		END AS VALUE_AS_STRING
	,CASE 
		WHEN OBSERVATION_CLARITYAMB_ICD.CONTACT_DATE >= '2015-10-01'
			THEN T_ICD10_CONCEPT.CONCEPT_ID
		ELSE T_ICD9_CONCEPT.CONCEPT_ID
		END AS VALUE_AS_CONCEPT_ID
	--------------------------------------------
	,0 AS UNIT_CONCEPT_ID
	,0 AS QUALIFIER_CONCEPT_ID
	,COALESCE(VST.PROVIDER_ID, PCP.PROVIDER_ID) AS PROVIDER_ID

	,VISIT_OCCURRENCE.VISIT_OCCURRENCE_ID AS VISIT_OCCURRENCE_ID
	    
--    ,VISIT_DETAIL.VISIT_DETAIL_ID AS VISIT_DETAIL_ID
    ,0 AS VISIT_DETAIL_ID

	-- RETURNS ICD10 CODES AFTER SWITCH DATE-----
	,CASE 
		WHEN OBSERVATION_CLARITYAMB_ICD.CONTACT_DATE >= '2015-10-01'
			THEN LEFT(T_ICD10_SOURCE.CONCEPT_CODE || ':' || T_ICD10_SOURCE.CONCEPT_NAME, 50)
		ELSE LEFT(T_ICD9_SOURCE.CONCEPT_CODE || ':' || T_ICD9_SOURCE.CONCEPT_NAME, 50)
		END AS OBSERVATION_SOURCE_VALUE
	,CASE 
		WHEN OBSERVATION_CLARITYAMB_ICD.CONTACT_DATE >= '2015-10-01'
			THEN T_ICD10_SOURCE.CONCEPT_ID
		ELSE T_ICD9_SOURCE.CONCEPT_ID
		END AS OBSERVATION_SOURCE_CONCEPT_ID
	--------------------------------------------
	,NULL AS UNIT_SOURCE_VALUE
	,NULL AS QUALIFIER_SOURCE_VALUE
	,'OBSERVATION--CLARITYAMB--ICD' AS ETL_MODULE
	,VISIT_OCCURRENCE.VISIT_SOURCE_VALUE

FROM {{ref('OBSERVATION_CLARITYAMB_ICD')}} AS OBSERVATION_CLARITYAMB_ICD

INNER JOIN {{ref('VISIT_OCCURRENCE')}} AS VISIT_OCCURRENCE
	ON OBSERVATION_CLARITYAMB_ICD.PAT_ENC_CSN_ID = VISIT_OCCURRENCE.VISIT_SOURCE_VALUE
	--MODIFIED 3/3/2021 FOR NULL PROVIDERS

LEFT JOIN
            {{ref('PROVIDER')}} AS VST
            ON
                        OBSERVATION_CLARITYAMB_ICD.VISIT_PROV_ID = VST.PROVIDER_SOURCE_VALUE         
LEFT JOIN
            {{ref('PROVIDER')}} AS PCP
            ON
                        OBSERVATION_CLARITYAMB_ICD.PCP_PROV_ID = PCP.PROVIDER_SOURCE_VALUE 
--------CONCEPT MAPPING--------------------

LEFT JOIN {{ref('T_ICD_SOURCE_OBSERVATION')}} AS T_ICD9_SOURCE
	ON OBSERVATION_CLARITYAMB_ICD.ICD9_CODE = T_ICD9_SOURCE.CONCEPT_CODE

LEFT JOIN {{ref('T_ICD_SOURCE_OBSERVATION')}} AS T_ICD10_SOURCE
	ON OBSERVATION_CLARITYAMB_ICD.ICD10_CODE = T_ICD10_SOURCE.CONCEPT_CODE

LEFT JOIN {{ref('T_CONCEPT_OBSERVATION')}} AS T_ICD9_CONCEPT
	ON T_ICD9_CONCEPT.SOURCE_CONCEPT_ID = T_ICD9_SOURCE.CONCEPT_ID

LEFT JOIN {{ref('T_CONCEPT_OBSERVATION')}} AS T_ICD10_CONCEPT
	ON T_ICD10_CONCEPT.SOURCE_CONCEPT_ID = T_ICD10_SOURCE.CONCEPT_ID
		--------CONCEPT MAPPING END --------------------

WHERE 
	(OBSERVATION_CLARITYAMB_ICD.CONTACT_DATE >= '2015-10-01' AND T_ICD10_CONCEPT.CONCEPT_ID IS NOT NULL)   
	OR 
	(OBSERVATION_CLARITYAMB_ICD.CONTACT_DATE < '2015-10-01' AND T_ICD9_CONCEPT.CONCEPT_ID IS NOT NULL   )
