USE DATABASE SH_OMOP_DB_PROD;
USE SCHEMA OMOP;
USE ROLE SF_SH_OMOP_DEVELOPER;
USE WAREHOUSE SH_OMOP_DATA_SCIENCE_WH;

CREATE OR REPLACE table SH_OMOP_DB_PROD.OMOP.SOURCE_TO_CONCEPT_MAP_TEMP clone SH_OMOP_DB_PROD.OMOP.SOURCE_TO_CONCEPT_MAP at (timestamp => to_timestamp_tz('09/13/2021 01:02:03', 'mm/dd/yyyy hh24:mi:ss'));



--DELETE FROM XXX.SOURCE_TO_CONCEPT_MAP;
--
--INSERT INTO XXX.SOURCE_TO_CONCEPT_MAP
--(SOURCE_CODE, SOURCE_CONCEPT_ID, SOURCE_VOCABULARY_ID, SOURCE_CODE_DESCRIPTION, TARGET_CONCEPT_ID, TARGET_VOCABULARY_ID, VALID_START_DATE, VALID_END_DATE, INVALID_REASON)
--SELECT SOURCE_CODE, SOURCE_CONCEPT_ID, SOURCE_VOCABULARY_ID, SOURCE_CODE_DESCRIPTION, TARGET_CONCEPT_ID, TARGET_VOCABULARY_ID, VALID_START_DATE, VALID_END_DATE, INVALID_REASON
--FROM XXX.SOURCE_TO_CONCEPT_MAP_TEMP;