  {{ config(materialized='ephemeral') }}

SELECT DISTINCT CLARITY_EDG.DX_ID
    ,CLARITY_EDG.DX_NAME
    ,EDG_CURRENT_ICD10.CODE AS ICD10_CODE
    ,EDG_CURRENT_ICD9.CODE AS ICD9_CODE

FROM   {{ source('CLARITY','CLARITY_EDG')}} AS CLARITY_EDG

    LEFT JOIN   {{ source('CLARITY','EDG_CURRENT_ICD10')}} AS EDG_CURRENT_ICD10
        ON CLARITY_EDG.DX_ID = EDG_CURRENT_ICD10.DX_ID
    
    LEFT JOIN   {{ source('CLARITY','EDG_CURRENT_ICD9')}} AS EDG_CURRENT_ICD9
        ON CLARITY_EDG.DX_ID = EDG_CURRENT_ICD9.DX_ID
	