
--CONDITION_OCCURRENCE_CLARITYHOSP_ICD

SELECT DISTINCT 
    SUBSTRING(AOU_DRIVER.AOU_ID, 2, LEN(AOU_DRIVER.AOU_ID)) AS PERSON_ID
    ,AOU_DRIVER.AOU_ID
    ,PAT_ENC_HSP.PAT_ID
    ,PAT_ENC_DX.CONTACT_DATE
    ,PAT_ENC_HSP.PAT_ENC_CSN_ID
    ,PAT_ENC_HSP.HOSP_ADMSN_TIME
    ,PAT_ENC_HSP.HOSP_DISCH_TIME
    ,ATTEND_FROM_DATE
    ,ATTEND_TO_DATE
    ,PRIMARY_DX_YN
    ,DISCH_DISP_C
    ,HSP_ATND_PROV.PROV_ID
    ,ATTENDING_PROV_ID
    ,COALESCE(ATTENDING_PROV_ID,HSP_ATND_PROV.PROV_ID) AS  CALC_ATTEND_PROV_ID
    ,T_DIAGNOSIS.ICD10_CODE
    ,T_DIAGNOSIS.ICD9_CODE
    ,DX_NAME
    --------------------------------------------
    ,'PULL_CONDITION_OCCURRENCE--CLARITYHOSP--ICD' AS ETL_MODULE


FROM   {{ source('CDM','AOU_DRIVER')}} AS AOU_DRIVER 

    INNER JOIN   {{ source('CLARITY','PAT_ENC_DX')}} AS PAT_ENC_DX
        ON PAT_ENC_DX.PAT_ID = AOU_DRIVER.EPIC_PAT_ID

    INNER JOIN   {{ source('CLARITY','PAT_ENC_HSP')}} AS PAT_ENC_HSP
        ON PAT_ENC_DX.PAT_ENC_CSN_ID = PAT_ENC_HSP.PAT_ENC_CSN_ID

    LEFT JOIN   {{ source('CLARITY','HSP_ATND_PROV')}} AS HSP_ATND_PROV
        ON PAT_ENC_HSP.PAT_ENC_CSN_ID = HSP_ATND_PROV.PAT_ENC_CSN_ID
            AND HOSP_DISCH_TIME BETWEEN ATTEND_FROM_DATE
                AND COALESCE(ATTEND_TO_DATE, GETDATE())

    LEFT JOIN   {{ source('CLARITY','HSP_ACCOUNT')}} AS HSP_ACCOUNT
        ON PAT_ENC_HSP.HSP_ACCOUNT_ID = HSP_ACCOUNT.HSP_ACCOUNT_ID

    LEFT JOIN  {{ref('T_DIAGNOSIS')}} AS T_DIAGNOSIS
        ON PAT_ENC_DX.DX_ID = T_DIAGNOSIS.DX_ID