--V_PROCEDURE_OCCURRENCE_CPT_AMB

{{ config(materialized='view') }}

SELECT DISTINCT 
--	CDM.SEQ_PROCEDURE_OCCURRENCE.NEXTVAL AS PROCEDURE_OCCURRENCE_ID
	PROCEDURE_OCCURRENCE_CLARITYAMB_CPT.PERSON_ID
	,T_CONCEPT.CONCEPT_ID AS PROCEDURE_CONCEPT_ID
	,CAST( COALESCE(PROCEDURE_OCCURRENCE_CLARITYAMB_CPT.OP_CHILD_INSTANTIATED_TIME
				, PROCEDURE_OCCURRENCE_CLARITYAMB_CPT.OP_INSTANTIATED_TIME
				, PROCEDURE_OCCURRENCE_CLARITYAMB_CPT.OP_PROC_START_TIME
				, PROCEDURE_OCCURRENCE_CLARITYAMB_CPT.OP_ORDER_TIME) AS DATE) AS PROCEDURE_DATE
	,COALESCE(PROCEDURE_OCCURRENCE_CLARITYAMB_CPT.OP_CHILD_INSTANTIATED_TIME
				, PROCEDURE_OCCURRENCE_CLARITYAMB_CPT.OP_INSTANTIATED_TIME
				, PROCEDURE_OCCURRENCE_CLARITYAMB_CPT.OP_PROC_START_TIME
				, PROCEDURE_OCCURRENCE_CLARITYAMB_CPT.OP_ORDER_TIME) AS PROCEDURE_DATETIME

	,32817 AS PROCEDURE_TYPE_CONCEPT_ID
	,COALESCE(SOURCE_TO_CONCEPT_MAP_MODIFIER.TARGET_CONCEPT_ID, 0) AS MODIFIER_CONCEPT_ID
	,PROCEDURE_OCCURRENCE_CLARITYAMB_CPT.QUANTITY AS QUANTITY
	,PROVIDER.PROVIDER_ID AS PROVIDER_ID
	,VISIT_OCCURRENCE.VISIT_OCCURRENCE_ID AS VISIT_OCCURRENCE_ID
	    
--    ,VISIT_DETAIL.VISIT_DETAIL_ID AS VISIT_DETAIL_ID
    ,0 AS VISIT_DETAIL_ID

	,PROCEDURE_OCCURRENCE_CLARITYAMB_CPT.PROC_CODE || ':' 
		|| LEFT(PROCEDURE_OCCURRENCE_CLARITYAMB_CPT.PROC_NAME, 49 
		- LEN(PROCEDURE_OCCURRENCE_CLARITYAMB_CPT.PROC_CODE)) 
		AS PROCEDURE_SOURCE_VALUE
	,T_SOURCE.CONCEPT_ID AS PROCEDURE_SOURCE_CONCEPT_ID
	,PROCEDURE_OCCURRENCE_CLARITYAMB_CPT.MODIFIER1_ID || ':' || MODIFIER_NAME AS MODIFIER_SOURCE_VALUE
	,'PROCEDURE_OCCURRENCE--CLARITYAMB--CPT' AS ETL_MODULE
	,VISIT_SOURCE_VALUE

FROM {{ref('PROCEDURE_OCCURRENCE_CLARITYAMB_CPT')}} AS  PROCEDURE_OCCURRENCE_CLARITYAMB_CPT

	INNER JOIN {{ref('T_PROCEDURE_SOURCE')}} AS T_SOURCE
		ON PROCEDURE_OCCURRENCE_CLARITYAMB_CPT.PROC_CODE = T_SOURCE.CONCEPT_CODE

	INNER JOIN {{ref('T_PROCEDURE_CONCEPT')}} AS T_CONCEPT
		ON T_SOURCE.CONCEPT_ID = T_CONCEPT.CONCEPT_ID

	INNER JOIN {{ref('VISIT_OCCURRENCE')}} AS VISIT_OCCURRENCE
		ON PROCEDURE_OCCURRENCE_CLARITYAMB_CPT.PAT_ENC_CSN_ID = VISIT_OCCURRENCE.VISIT_SOURCE_VALUE

	LEFT JOIN {{ref('PROVIDER')}} AS PROVIDER
		ON PROCEDURE_OCCURRENCE_CLARITYAMB_CPT.AUTHRZING_PROV_ID = PROVIDER.PROVIDER_SOURCE_VALUE

	LEFT JOIN {{ source('CDM','SOURCE_TO_CONCEPT_MAP')}} AS SOURCE_TO_CONCEPT_MAP_MODIFIER
		ON PROCEDURE_OCCURRENCE_CLARITYAMB_CPT.MODIFIER1_ID::VARCHAR = SOURCE_TO_CONCEPT_MAP_MODIFIER.SOURCE_CODE::VARCHAR 
			AND UPPER(source_to_concept_map_modifier.source_vocabulary_id) = 'SH_MODIFIER'

