--V_PROCEDURE_OCCURRENCE_CPT_HSP

{{ config(materialized='view') }}

SELECT DISTINCT  
--	CDM.SEQ_PROCEDURE_OCCURRENCE.NEXTVAL AS PROCEDURE_OCCURRENCE_ID
	PAT_ENC_HSP.PERSON_ID
	,T_CONCEPT.CONCEPT_ID AS PROCEDURE_CONCEPT_ID
	,CAST( PAT_ENC_HSP.OP_PROC_START_TIME AS DATE) AS PROCEDURE_DATE
	,PAT_ENC_HSP.OP_PROC_START_TIME AS PROCEDURE_DATETIME

	,32817 AS PROCEDURE_TYPE_CONCEPT_ID

	,COALESCE(SOURCE_TO_CONCEPT_MAP_MODIFIER.TARGET_CONCEPT_ID, 0) AS MODIFIER_CONCEPT_ID
	,PAT_ENC_HSP.QUANTITY AS QUANTITY
	,PROVIDER.PROVIDER_ID AS PROVIDER_ID
	,VISIT_OCCURRENCE.VISIT_OCCURRENCE_ID AS VISIT_OCCURRENCE_ID
	    
--    ,VISIT_DETAIL.VISIT_DETAIL_ID AS VISIT_DETAIL_ID
    ,0 AS VISIT_DETAIL_ID

	,PAT_ENC_HSP.PROC_CODE || ':' || LEFT(PAT_ENC_HSP.PROC_NAME, 49 - LEN(PAT_ENC_HSP.PROC_CODE)) AS PROCEDURE_SOURCE_VALUE
	,T_SOURCE.CONCEPT_ID AS PROCEDURE_SOURCE_CONCEPT_ID
	,PAT_ENC_HSP.MODIFIER1_ID || ':' || MODIFIER_NAME AS MODIFIER_SOURCE_VALUE
	,'PROCEDURE_OCCURRENCE--CLARITYHOSP--CPT' AS ETL_MODULE
	,VISIT_SOURCE_VALUE

FROM {{ref('PROCEDURE_OCCURRENCE_CLARITYHSP_CPT')}}  AS PAT_ENC_HSP

INNER JOIN {{ref('T_PROCEDURE_SOURCE')}} AS T_SOURCE
	ON PAT_ENC_HSP.PROC_CODE = T_SOURCE.CONCEPT_CODE

INNER JOIN {{ref('T_PROCEDURE_CONCEPT')}} AS T_CONCEPT
	ON T_SOURCE.CONCEPT_ID = T_CONCEPT.CONCEPT_ID

-------------------------------------------
INNER JOIN {{ref('VISIT_OCCURRENCE')}} AS VISIT_OCCURRENCE
	ON PAT_ENC_HSP.PAT_ENC_CSN_ID = VISIT_OCCURRENCE.VISIT_SOURCE_VALUE

LEFT JOIN {{ref('PROVIDER')}} AS PROVIDER
	ON PAT_ENC_HSP.AUTHRZING_PROV_ID = PROVIDER.PROVIDER_SOURCE_VALUE

LEFT JOIN {{ source('CDM','SOURCE_TO_CONCEPT_MAP')}} AS  SOURCE_TO_CONCEPT_MAP_MODIFIER
	ON PAT_ENC_HSP.MODIFIER1_ID::VARCHAR = SOURCE_TO_CONCEPT_MAP_MODIFIER.SOURCE_CODE::VARCHAR
		AND UPPER(SOURCE_TO_CONCEPT_MAP_MODIFIER.SOURCE_VOCABULARY_ID) = 'SH_MODIFIER'

WHERE PAT_ENC_HSP.OP_PROC_START_TIME IS NOT NULL