  {{ config(materialized='ephemeral') }}

SELECT CONCEPT_ID
		,CONCEPT_CODE
		,CONCEPT_NAME
FROM {{ source('CDM','CONCEPT')}} AS C
WHERE UPPER(C.VOCABULARY_ID) IN ('SNOMED')
		AND (C.INVALID_REASON IS NULL
			OR C.INVALID_REASON = '')
		AND UPPER(C.DOMAIN_ID) = 'OBSERVATION'
		AND UPPER(CONCEPT_NAME) LIKE 'ALLERGY TO %'