{{ config(materialized='ephemeral') }}

SELECT NOTE_ID
		,LINE AS LINE
		,MAX(CONTACT_DATE_REAL) AS MAX_CONTACT_DATE_REAL
FROM  {{ref('NOTE_CLARITYHOSP_ALL')}} AS  NOTE_CLARITYHOSP_ALL
GROUP BY NOTE_ID, LINE