{{ config(materialized='ephemeral') }}

SELECT NOTE_ID
		,LINE AS LINE
		,MAX(CONTACT_DATE_REAL) AS MAX_CONTACT_DATE_REAL
FROM  {{ref('NOTE_CLARITYANES_ALL')}} AS  NOTE_CLARITYANES_ALL
GROUP BY NOTE_ID, LINE