-- V_AOU_PII_PHONE_NUMBER

{{ config(materialized = 'view') }}

SELECT DISTINCT PERSON.PERSON_ID AS "person_id"
	,PHONE AS "phone_number"
FROM {{ref('PERSON')}} AS PERSON
INNER JOIN {{ref('AOU_DRIVER')}} AS AOU_DRIVER
	ON PERSON.PERSON_ID = SUBSTRING(AOU_DRIVER.AOU_ID, 2, LEN(AOU_DRIVER.AOU_ID))::NUMERIC
WHERE PHONE <>'' AND PHONE IS NOT NULL
