--V_AOU_DEVICE_EXPOSURE

{{ config(materialized = 'view') }}

SELECT DEVICE_EXPOSURE.DEVICE_EXPOSURE_ID AS "device_exposure_id"
    , DEVICE_EXPOSURE.PERSON_ID AS "person_id"
    , DEVICE_EXPOSURE.DEVICE_CONCEPT_ID AS "device_concept_id"
    , TO_CHAR(DEVICE_EXPOSURE.DEVICE_EXPOSURE_START_DATE) AS "device_exposure_start_date"
    , TO_CHAR(DEVICE_EXPOSURE.DEVICE_EXPOSURE_START_DATETIME)  AS "device_exposure_start_datetime"
    , TO_CHAR(DEVICE_EXPOSURE.DEVICE_EXPOSURE_END_DATE) AS "device_exposure_end_date"
    , TO_CHAR(DEVICE_EXPOSURE.DEVICE_EXPOSURE_END_DATETIME)  AS "device_exposure_end_datetime"
    , DEVICE_EXPOSURE.DEVICE_TYPE_CONCEPT_ID AS "device_type_concept_id"
    , DEVICE_EXPOSURE.UNIQUE_DEVICE_ID AS "unique_device_id"
    , DEVICE_EXPOSURE.QUANTITY AS "quantity"
    , DEVICE_EXPOSURE.PROVIDER_ID AS "provider_id"
    , DEVICE_EXPOSURE.VISIT_OCCURRENCE_ID AS "visit_occurrence_id"
    , DEVICE_EXPOSURE.VISIT_DETAIL_ID AS "visit_detail_id"
    , DEVICE_EXPOSURE.DEVICE_SOURCE_VALUE AS "device_source_value"
    , DEVICE_EXPOSURE.DEVICE_SOURCE_CONCEPT_ID AS "device_source_concept_id"
FROM  {{ref('DEVICE_EXPOSURE')}} AS DEVICE_EXPOSURE
LEFT JOIN (
    SELECT CDT_ID
    FROM {{ref('QA_ERR')}}
    WHERE (STANDARD_DATA_TABLE = 'DEVICE_EXPOSURE')
        AND (ERROR_TYPE IN ('FATAL', 'INVALID DATA'))
    ) AS EXCLUSION_RECORDS
    ON DEVICE_EXPOSURE.DEVICE_EXPOSURE_ID = EXCLUSION_RECORDS.CDT_ID
WHERE (EXCLUSION_RECORDS.CDT_ID IS NULL)

