--V_AOU_PII_EMAIL

{{ config(materialized = 'view') }}

SELECT DISTINCT PERSON.PERSON_ID AS "person_id"
	,EMAIL AS "email"
FROM {{ref('PERSON')}} AS PERSON
INNER JOIN {{ref('AOU_DRIVER')}} AS AOU_DRIVER
	ON PERSON.PERSON_ID = SUBSTRING(AOU_DRIVER.AOU_ID, 2, LEN(AOU_DRIVER.AOU_ID))
WHERE (EMAIL <>'' AND EMAIL IS NOT NULL)

