--DRUG_EXPOSURE 

{{ config(materialized = 'table') }} 

SELECT 
    SEQ_DRUG_EXPOSURE.NEXTVAL::NUMBER(28,0)     AS DRUG_EXPOSURE_ID
    , PERSON_ID::NUMBER(28,0)                   AS PERSON_ID
    , DRUG_CONCEPT_ID::NUMBER(28,0)             AS DRUG_CONCEPT_ID
    , DRUG_EXPOSURE_START_DATE::DATE            AS DRUG_EXPOSURE_START_DATE
    , DRUG_EXPOSURE_START_DATETIME::DATETIME    AS DRUG_EXPOSURE_START_DATETIME
    , DRUG_EXPOSURE_END_DATE::DATE              AS DRUG_EXPOSURE_END_DATE
    , DRUG_EXPOSURE_END_DATETIME::DATETIME      AS DRUG_EXPOSURE_END_DATETIME
    , VERBATIM_END_DATE::DATE                   AS VERBATIM_END_DATE
    , DRUG_TYPE_CONCEPT_ID::NUMBER(28,0)        AS DRUG_TYPE_CONCEPT_ID
    , STOP_REASON::VARCHAR(20)                  AS STOP_REASON
    , REFILLS::NUMBER(28,0)                     AS REFILLS
    , QUANTITY::FLOAT                           AS QUANTITY
    , DAYS_SUPPLY::NUMBER(28,0)                 AS DAYS_SUPPLY  
    , SIG::VARCHAR                              AS SIG
    , ROUTE_CONCEPT_ID::NUMBER(28,0)            AS ROUTE_CONCEPT_ID
    , LOT_NUMBER::VARCHAR(50)                   AS LOT_NUMBER
    , PROVIDER_ID::NUMBER(28,0)                 AS PROVIDER_ID
    , VISIT_OCCURRENCE_ID::NUMBER(28,0)         AS VISIT_OCCURRENCE_ID
    , VISIT_DETAIL_ID::NUMBER(28,0)             AS VISIT_DETAIL_ID
    , DRUG_SOURCE_VALUE::VARCHAR(50)            AS DRUG_SOURCE_VALUE
    , DRUG_SOURCE_CONCEPT_ID::NUMBER(28,0)      AS DRUG_SOURCE_CONCEPT_ID
    , ROUTE_SOURCE_VALUE::VARCHAR(50)           AS ROUTE_SOURCE_VALUE
    , DOSE_UNIT_SOURCE_VALUE::VARCHAR(50)       AS DOSE_UNIT_SOURCE_VALUE
    , ETL_MODULE::VARCHAR(100)                  AS ETL_MODULE
    , VISIT_SOURCE_VALUE::VARCHAR(50)           AS VISIT_SOURCE_VALUE
FROM
(   
    SELECT * FROM {{ref('V_DRUG_EXPOSURE_RXNORM_AMB')}} 
    {# UNION ALL
    UNION ALL * FROM {{ref('V_DRUG_EXPOSURE_RXNORM_ANES')}}  #}
    UNION
    SELECT * FROM {{ref('V_DRUG_EXPOSURE_RXNORM_HSP')}}
) AS A    