--MEASUREMENT_CLARITYHOSP_FLOWSHEET

SELECT SUBSTRING(AOU_DRIVER.AOU_ID, 2, LEN(AOU_DRIVER.AOU_ID))::NUMBER(28,0) AS PERSON_ID
    ,AOU_DRIVER.AOU_ID
    ,IP_FLWSHT_MEAS.RECORDED_TIME
    ,IP_FLWSHT_MEAS.MEAS_VALUE
    ,IP_FLO_GP_DATA.MINVALUE
    ,IP_FLO_GP_DATA.MAX_VAL
    ,IP_FLO_GP_DATA.FLO_MEAS_ID
    ,IP_FLO_GP_DATA.FLO_MEAS_NAME
    ,IP_FLO_GP_DATA.VAL_TYPE_C
    ,ZC_VAL_TYPE.NAME AS ZC_VAL_TYPE_NAME
    ,IP_FLO_GP_DATA.UNITS
    ,IP_FLO_GP_DATA.DISP_NAME
    ,PAT_ENC_HSP.PAT_ID
    ,PAT_ENC_HSP.PAT_ENC_CSN_ID
    ,IP_DATA_STORE.EPT_CSN
    ,IP_DATA_STORE.INPATIENT_DATA_ID
    ,IP_FLWSHT_REC.FSD_ID
    ,PAT_ENC_HSP.BILL_ATTEND_PROV_ID
    , HSP_ACCOUNT.ATTENDING_PROV_ID
    , HSP_ACCOUNT.REFERRING_PROV_ID
    , HSP_ACCOUNT.ADM_DATE_TIME
    , HSP_ACCOUNT.DISCH_DATE_TIME
    ,ATTEND_FROM_DATE
    ,ATTEND_TO_DATE
    ,HSP_ATND_PROV.PROV_ID
    ,COALESCE(ATTENDING_PROV_ID,HSP_ATND_PROV.PROV_ID) AS  CALC_ATTEND_PROV_ID
    ,'PULL_MEASUREMENT--CLARITYHOSP--FLOWSHEET_ALL' AS ETL_MODULE

FROM {{ source('CLARITY','PAT_ENC_HSP')}} AS PAT_ENC_HSP

    INNER JOIN {{ref('AOU_DRIVER')}} AS AOU_DRIVER
        ON PAT_ENC_HSP.PAT_ID = AOU_DRIVER.EPIC_PAT_ID

    LEFT JOIN {{ source('CLARITY','IP_DATA_STORE')}} AS IP_DATA_STORE
        ON PAT_ENC_HSP.PAT_ENC_CSN_ID = IP_DATA_STORE.EPT_CSN

    LEFT JOIN {{ source('CLARITY','IP_FLWSHT_REC')}} AS IP_FLWSHT_REC
        ON IP_DATA_STORE.INPATIENT_DATA_ID = IP_FLWSHT_REC.INPATIENT_DATA_ID

    LEFT JOIN {{ source('CLARITY','IP_FLWSHT_MEAS')}} AS IP_FLWSHT_MEAS
        ON IP_FLWSHT_REC.FSD_ID = IP_FLWSHT_MEAS.FSD_ID

    INNER JOIN {{ source('CLARITY','IP_FLO_GP_DATA')}} AS IP_FLO_GP_DATA
        ON IP_FLWSHT_MEAS.FLO_MEAS_ID = IP_FLO_GP_DATA.FLO_MEAS_ID

    INNER JOIN {{ source('CLARITY','ZC_VAL_TYPE')}} AS ZC_VAL_TYPE
        ON IP_FLO_GP_DATA.VAL_TYPE_C = ZC_VAL_TYPE.VAL_TYPE_C
        
    LEFT JOIN {{ source('CLARITY','HSP_ACCOUNT')}} AS HSP_ACCOUNT
        ON PAT_ENC_HSP.HSP_ACCOUNT_ID = HSP_ACCOUNT.HSP_ACCOUNT_ID

    LEFT JOIN {{ source('CLARITY','HSP_ATND_PROV')}} AS HSP_ATND_PROV
        ON PAT_ENC_HSP.PAT_ENC_CSN_ID = HSP_ATND_PROV.PAT_ENC_CSN_ID
            AND IP_FLWSHT_MEAS.RECORDED_TIME BETWEEN ATTEND_FROM_DATE
                AND COALESCE(ATTEND_TO_DATE, GETDATE())


	
	


