--MEASUREMENT_CLARITYANES_FLOWSHEET

SELECT  DISTINCT SUBSTRING(AOU_DRIVER.AOU_ID, 2, LEN(AOU_DRIVER.AOU_ID)) AS PERSON_ID
	,AOU_DRIVER.AOU_ID
	,PAT_ENC_AMB.PAT_ID
	-----HOSPITAL ENCOUNTER---------
	,PAT_ENC_HSP.PAT_ENC_CSN_ID
	--------------------------------
	,PAT_ENC_AMB.HSP_ACCOUNT_ID
	,PAT_ENC_AMB.IP_DOC_CONTACT_CSN
	,PAT_ENC_AMB.ENC_TYPE_C
	,PAT_ENC_AMB.ZC_DISP_ENC_TYPE_NAME
	,PAT_ENC_AMB.PAT_OR_ADM_LINK_CSN AS PAT_OR_ADM_LINK_PAT_ENC_CSN_ID

	,IP_FLWSHT_MEAS.RECORDED_TIME
	,IP_FLWSHT_MEAS.MEAS_VALUE
	,IP_FLO_GP_DATA.MINVALUE
	,IP_FLO_GP_DATA.MAX_VAL
	,IP_FLO_GP_DATA.FLO_MEAS_ID
	,IP_FLO_GP_DATA.FLO_MEAS_NAME
	,IP_FLO_GP_DATA.VAL_TYPE_C
	,ZC_VAL_TYPE.NAME AS ZC_VAL_TYPE_NAME
	,IP_FLO_GP_DATA.UNITS
	,IP_FLO_GP_DATA.DISP_NAME

	,IP_DATA_STORE.EPT_CSN
	,IP_DATA_STORE.INPATIENT_DATA_ID
	,IP_FLWSHT_REC.FSD_ID
	,PAT_ENC_AMB.visit_PROV_ID
	,'PULL_MEASUREMENT--CLARITYANES--FLOWSHEET' AS ETL_Module


FROM {{ref('VISIT_OCCURRENCE_CLARITYAMB_ALL')}} AS PAT_ENC_AMB

-- ASSOCIATES ANETHESIA RECORD TO HOSPITAL ENCOUNTER
  INNER JOIN {{ source('CLARITY','F_AN_RECORD_SUMMARY')}} AS F_AN_RECORD_SUMMARY ON PAT_ENC_AMB.PAT_ENC_CSN_ID = F_AN_RECORD_SUMMARY.AN_52_ENC_CSN_ID
  INNER JOIN {{ source('CLARITY','ASAN_HSB_LINK_INFO')}} AS ASAN_HSB_LINK_INFO ON F_AN_RECORD_SUMMARY.AN_EPISODE_ID=AN_HSB_LINK_INFO.SUMMARY_BLOCK_ID
  INNER JOIN {{ source('CLARITY','ASPAT_ENC_HSP')}} AS ASPAT_ENC_HSP ON AN_HSB_LINK_INFO.AN_BILLING_CSN_ID=PAT_ENC_HSP.PAT_ENC_CSN_ID
---------------------------------------------------

LEFT JOIN {{ source('CLARITY','IP_DATA_STORE')}} AS IP_DATA_STORE
	ON PAT_ENC_AMB.PAT_ENC_CSN_ID = IP_DATA_STORE.EPT_CSN

LEFT JOIN {{ source('CLARITY','IP_FLWSHT_REC')}} AS IP_FLWSHT_REC
	ON IP_DATA_STORE.INPATIENT_DATA_ID = IP_FLWSHT_REC.INPATIENT_DATA_ID

LEFT JOIN {{ source('CLARITY','IP_FLWSHT_MEAS')}} AS IP_FLWSHT_MEAS
	ON IP_FLWSHT_REC.FSD_ID = IP_FLWSHT_MEAS.FSD_ID

INNER JOIN {{ source('CLARITY','IP_FLO_GP_DATA')}} AS IP_FLO_GP_DATA
	ON IP_FLWSHT_MEAS.FLO_MEAS_ID = IP_FLO_GP_DATA.FLO_MEAS_ID

INNER JOIN {{ source('CLARITY','ZC_VAL_TYPE')}} AS ZC_VAL_TYPE
	ON IP_FLO_GP_DATA.VAL_TYPE_C = ZC_VAL_TYPE.VAL_TYPE_C
 
WHERE PAT_ENC_AMB.ENC_TYPE_C = 52 -- ANESTHESIA
