USE ROLE SF_SH_OMOP_DEVELOPER;
USE SCHEMA SH_OMOP_DB_PROD.CDM;
USE WAREHOUSE SH_OMOP_DATA_SCIENCE_WH;

TRUNCATE TABLE CDM.DRUG_STRENGTH ;
COPY INTO CDM.DRUG_STRENGTH FROM '@SH_OMOP_DB_PROD.OMOP.OMOP_VOCABULARIES/DRUG_STRENGTH.csv.gz' FILE_FORMAT = 'SH_OMOP_DB_PROD.OMOP.OMOP_VOCAB_FORMAT' ON_ERROR = 'ABORT_STATEMENT' PURGE = FALSE;
--SELECT DRUG_CONCEPT_ID, INGREDIENT_CONCEPT_ID, AMOUNT_VALUE, AMOUNT_UNIT_CONCEPT_ID, NUMERATOR_VALUE, NUMERATOR_UNIT_CONCEPT_ID, DENOMINATOR_VALUE, DENOMINATOR_UNIT_CONCEPT_ID, BOX_SIZE, VALID_START_DATE, VALID_END_DATE, INVALID_REASON
--FROM CDM.DRUG_STRENGTH;

TRUNCATE TABLE CDM.CONCEPT_RELATIONSHIP ;
COPY INTO CDM.CONCEPT_RELATIONSHIP FROM '@SH_OMOP_DB_PROD.OMOP.OMOP_VOCABULARIES/CONCEPT_RELATIONSHIP.csv.gz' FILE_FORMAT = 'SH_OMOP_DB_PROD.OMOP.OMOP_VOCAB_FORMAT' ON_ERROR = 'ABORT_STATEMENT' PURGE = FALSE;
--SELECT CONCEPT_ID_1, CONCEPT_ID_2, RELATIONSHIP_ID, VALID_START_DATE, VALID_END_DATE, INVALID_REASON
--FROM CDM.CONCEPT_RELATIONSHIP;

TRUNCATE TABLE CDM.CONCEPT_ANCESTOR ;
COPY INTO CDM.CONCEPT_ANCESTOR FROM '@SH_OMOP_DB_PROD.OMOP.OMOP_VOCABULARIES/CONCEPT_ANCESTOR.csv.gz' FILE_FORMAT = 'SH_OMOP_DB_PROD.OMOP.OMOP_VOCAB_FORMAT' ON_ERROR = 'ABORT_STATEMENT' PURGE = FALSE;
--SELECT ANCESTOR_CONCEPT_ID, DESCENDANT_CONCEPT_ID, MIN_LEVELS_OF_SEPARATION, MAX_LEVELS_OF_SEPARATION
--FROM CDM.CONCEPT_ANCESTOR;

TRUNCATE TABLE CDM.CONCEPT_SYNONYM ;
COPY INTO CDM.CONCEPT_SYNONYM FROM '@SH_OMOP_DB_PROD.OMOP.OMOP_VOCABULARIES/CONCEPT_SYNONYM.csv.gz' FILE_FORMAT = 'SH_OMOP_DB_PROD.OMOP.OMOP_VOCAB_FORMAT' ON_ERROR = 'CONTINUE' PURGE = FALSE;
--SELECT CONCEPT_ID, CONCEPT_SYNONYM_NAME, LANGUAGE_CONCEPT_ID
--FROM CDM.CONCEPT_SYNONYM;

TRUNCATE TABLE CDM.VOCABULARY ;
COPY INTO CDM.VOCABULARY FROM '@SH_OMOP_DB_PROD.OMOP.OMOP_VOCABULARIES/VOCABULARY.csv.gz' FILE_FORMAT = 'SH_OMOP_DB_PROD.OMOP.OMOP_VOCAB_FORMAT' ON_ERROR = 'ABORT_STATEMENT' PURGE = FALSE;
--SELECT VOCABULARY_ID, VOCABULARY_NAME, VOCABULARY_REFERENCE, VOCABULARY_VERSION, VOCABULARY_CONCEPT_ID
--FROM CDM.VOCABULARY;

TRUNCATE TABLE CDM.RELATIONSHIP ;
COPY INTO CDM.RELATIONSHIP FROM '@SH_OMOP_DB_PROD.OMOP.OMOP_VOCABULARIES/RELATIONSHIP.csv.gz' FILE_FORMAT = 'SH_OMOP_DB_PROD.OMOP.OMOP_VOCAB_FORMAT' ON_ERROR = 'ABORT_STATEMENT' PURGE = FALSE;
--SELECT RELATIONSHIP_ID, RELATIONSHIP_NAME, IS_HIERARCHICAL, DEFINES_ANCESTRY, REVERSE_RELATIONSHIP_ID, RELATIONSHIP_CONCEPT_ID
--FROM CDM.RELATIONSHIP;

TRUNCATE TABLE CDM.CONCEPT ;
COPY INTO CDM.CONCEPT FROM '@SH_OMOP_DB_PROD.OMOP.OMOP_VOCABULARIES/CONCEPT.csv.gz' FILE_FORMAT = 'SH_OMOP_DB_PROD.OMOP.OMOP_VOCAB_FORMAT' ON_ERROR = 'ABORT_STATEMENT' PURGE = FALSE;
--SELECT CONCEPT_ID, CONCEPT_NAME, DOMAIN_ID, VOCABULARY_ID, CONCEPT_CLASS_ID, STANDARD_CONCEPT, CONCEPT_CODE, VALID_START_DATE, VALID_END_DATE, INVALID_REASON
--FROM CDM.CONCEPT;

TRUNCATE TABLE CDM.CONCEPT_CLASS ;
COPY INTO CDM.CONCEPT_CLASS FROM '@SH_OMOP_DB_PROD.OMOP.OMOP_VOCABULARIES/CONCEPT_CLASS.csv.gz' FILE_FORMAT = 'SH_OMOP_DB_PROD.OMOP.OMOP_VOCAB_FORMAT' ON_ERROR = 'ABORT_STATEMENT' PURGE = FALSE;
--SELECT CONCEPT_CLASS_ID, CONCEPT_CLASS_NAME, CONCEPT_CLASS_CONCEPT_ID
--FROM CDM.CONCEPT_CLASS;

TRUNCATE TABLE CDM.DOMAIN ;
COPY INTO CDM.DOMAIN FROM '@SH_OMOP_DB_PROD.OMOP.OMOP_VOCABULARIES/DOMAIN.csv.gz' FILE_FORMAT = 'SH_OMOP_DB_PROD.OMOP.OMOP_VOCAB_FORMAT' ON_ERROR = 'ABORT_STATEMENT' PURGE = FALSE;
--SELECT DOMAIN_ID, DOMAIN_NAME, DOMAIN_CONCEPT_ID
--FROM CDM.DOMAIN;


TRUNCATE TABLE CDM.SOURCE_TO_CONCEPT_MAP ;
COPY INTO CDM.SOURCE_TO_CONCEPT_MAP FROM '@SH_OMOP_DB_PROD.OMOP.OMOP_VOCABULARIES/SOURCE_TO_CONCEPT_MAP.csv.gz' FILE_FORMAT = 'SH_OMOP_DB_PROD.OMOP.OMOP_VOCAB_FORMAT' ON_ERROR = 'ABORT_STATEMENT' PURGE = FALSE;
--SELECT *
--FROM CDM.SOURCE_TO_CONCEPT_MAP;

