--VISIT_DETAIL 

{{ config(materialized = 'table') }} 

SELECT DISTINCT VISIT_DETAIL_ID
    , VISIT_DETAIL_CLARITYHOSP_ALL.PERSON_ID AS PERSON_ID
    , COALESCE(SOURCE_TO_CONCEPT_MAP_VISIT.TARGET_CONCEPT_ID, 0) AS VISIT_DETAIL_CONCEPT_ID
    , CAST(COALESCE(A_EFFECTIVE_TIME, CHECKIN_TIME, APPT_TIME, CONTACT_DATE) AS DATE) AS VISIT_DETAIL_START_DATE
    , COALESCE(A_EFFECTIVE_TIME, CHECKIN_TIME, APPT_TIME, CONTACT_DATE) AS VISIT_DETAIL_START_DATETIME

    , CASE 
        WHEN COALESCE(B_EFFECTIVE_TIME, HOSP_DISCH_TIME, CHECKOUT_TIME) IS NOT NULL
            AND COALESCE(B_EFFECTIVE_TIME, HOSP_DISCH_TIME, CHECKOUT_TIME) >= COALESCE(A_EFFECTIVE_TIME, CHECKIN_TIME, APPT_TIME, CONTACT_DATE)
            THEN CAST(COALESCE(B_EFFECTIVE_TIME, HOSP_DISCH_TIME, CHECKOUT_TIME) AS DATE)
        WHEN COALESCE(HOSP_DISCH_TIME, CHECKOUT_TIME) >= COALESCE(A_EFFECTIVE_TIME, CHECKIN_TIME, APPT_TIME, CONTACT_DATE)
            THEN CAST(COALESCE(HOSP_DISCH_TIME, CHECKOUT_TIME) AS DATE)
        ELSE NULL
        END AS VISIT_DETAIL_END_DATE
    , CASE 
        WHEN COALESCE(B_EFFECTIVE_TIME, HOSP_DISCH_TIME, CHECKOUT_TIME) IS NOT NULL
            AND COALESCE(B_EFFECTIVE_TIME, HOSP_DISCH_TIME, CHECKOUT_TIME) >= COALESCE(A_EFFECTIVE_TIME, CHECKIN_TIME, APPT_TIME, CONTACT_DATE)
            THEN CAST(COALESCE(B_EFFECTIVE_TIME, HOSP_DISCH_TIME, CHECKOUT_TIME) AS DATETIME)
        WHEN COALESCE(HOSP_DISCH_TIME, CHECKOUT_TIME) >= COALESCE(A_EFFECTIVE_TIME, CHECKIN_TIME, APPT_TIME, CONTACT_DATE)
            THEN CAST(COALESCE(HOSP_DISCH_TIME, CHECKOUT_TIME) AS DATETIME)
        ELSE NULL
        END AS VISIT_DETAIL_END_DATETIME
    , 44818518 AS VISIT_DETAIL_TYPE_CONCEPT_ID

    , PROVIDER.PROVIDER_ID AS ATTENDING_PROV

    , CARE_SITE.CARE_SITE_ID AS CARE_SITE_ID

    , LEFT(VISIT_DETAIL_CLARITYHOSP_ALL.VISIT_DETAIL_SOURCE_VALUE, 50) AS VISIT_DETAIL_SOURCE_VALUE
    , 0 AS VISIT_DETAIL_SOURCE_CONCEPT_ID
    , LEFT(VISIT_DETAIL_CLARITYHOSP_ALL.ADMIT_SOURCE_NAME, 50) AS ADMITTING_SOURCE_VALUE
    , COALESCE(SOURCE_TO_CONCEPT_MAP_ADMIT.TARGET_CONCEPT_ID, 0) AS ADMITTING_SOURCE_CONCEPT_ID
    , LEFT(VISIT_DETAIL_CLARITYHOSP_ALL.DISCH_DISP_NAME, 50) AS DISCHARGE_TO_SOURCE_VALUE
    , COALESCE(SOURCE_TO_CONCEPT_MAP_DISCHARGE.TARGET_CONCEPT_ID, 0) AS DISCHARGE_TO_CONCEPT_ID
    , CASE 
        WHEN RA = 1
            THEN NULL
        ELSE VISIT_DETAIL_ID - 1
        END AS PRECEDING_VISIT_DETAIL_ID -- A FOREIGN KEY TO THE VISIT_DETAIL TABLE OF THE VISIT IMMEDIATELY PRECEDING THIS VISIT
    , CASE 
        WHEN RA = 1
            THEN VISIT_DETAIL_ID
        ELSE VISIT_DETAIL_ID - RA + 1
        END AS VISIT_DETAIL_PARENT_ID
    , VISIT_OCCURRENCE.VISIT_OCCURRENCE_ID AS VISIT_OCCURRENCE_ID
    , 'VISIT_DETAIL--CLARITYHOSP--ALL' AS ETL_MODULE
    , VISIT_DETAIL_CLARITYHOSP_ALL.VISIT_SOURCE_VALUE AS VISIT_SOURCE_VALUE

FROM {{ref('VISIT_DETAIL_CLARITYHOSP_ALL')}} AS VISIT_DETAIL_CLARITYHOSP_ALL

    LEFT JOIN  {{ref('CARE_SITE')}} AS CARE_SITE
        ON VISIT_DETAIL_CLARITYHOSP_ALL.HOSPITAL_AREA_ID = CARE_SITE.CARE_SITE_ID
    
    INNER JOIN  {{ref('VISIT_OCCURRENCE')}} AS VISIT_OCCURRENCE
        ON VISIT_DETAIL_CLARITYHOSP_ALL.VISIT_SOURCE_VALUE = VISIT_OCCURRENCE.VISIT_SOURCE_VALUE
    
    LEFT JOIN  {{ref('PROVIDER')}} AS PROVIDER
        ON VISIT_DETAIL_CLARITYHOSP_ALL.ATTENDING_PROV_ID = PROVIDER.PROVIDER_SOURCE_VALUE
    
    LEFT JOIN   {{ source('CDM','SOURCE_TO_CONCEPT_MAP')}} AS SOURCE_TO_CONCEPT_MAP_VISIT
        ON SOURCE_TO_CONCEPT_MAP_VISIT.SOURCE_CODE = VISIT_DETAIL_CLARITYHOSP_ALL.VISIT_DETAIL_SOURCE_CONCEPT
            AND SOURCE_TO_CONCEPT_MAP_VISIT.SOURCE_VOCABULARY_ID = 'SH_visit'
    
    LEFT JOIN   {{ source('CDM','SOURCE_TO_CONCEPT_MAP')}} AS SOURCE_TO_CONCEPT_MAP_ADMIT
        ON SOURCE_TO_CONCEPT_MAP_ADMIT.SOURCE_CODE = VISIT_DETAIL_CLARITYHOSP_ALL.ADMIT_SOURCE_C
            AND SOURCE_TO_CONCEPT_MAP_ADMIT.SOURCE_VOCABULARY_ID = 'SH_admit'
    
    LEFT JOIN   {{ source('CDM','SOURCE_TO_CONCEPT_MAP')}} AS SOURCE_TO_CONCEPT_MAP_DISCHARGE
        ON SOURCE_TO_CONCEPT_MAP_DISCHARGE.SOURCE_CODE = VISIT_DETAIL_CLARITYHOSP_ALL.DISCH_DISP_C
            AND SOURCE_TO_CONCEPT_MAP_DISCHARGE.SOURCE_VOCABULARY_ID = 'SH_discharge'

ORDER BY VISIT_DETAIL_ID
