--VISIT_OCCURRENCE 

{{ config(materialized='table', 
        cluster_by = ['VISIT_OCCURRENCE_ID']) }}

SELECT DISTINCT
     SEQ_VISIT_OCCURRENCE.NEXTVAL::NUMBER(28,0)   AS VISIT_OCCURRENCE_ID
    , PERSON_ID::NUMBER(28,0)                     AS PERSON_ID 
    , VISIT_CONCEPT_ID::NUMBER(28,0)              AS VISIT_CONCEPT_ID 
    , VISIT_START_DATE::DATE                      AS VISIT_START_DATE
    , VISIT_START_DATETIME::DATETIME              AS VISIT_START_DATETIME
    , VISIT_END_DATE::DATE                        AS VISIT_END_DATE
    , VISIT_END_DATETIME::DATETIME                AS VISIT_END_DATETIME
    , VISIT_TYPE_CONCEPT_ID::NUMBER(28,0)         AS VISIT_TYPE_CONCEPT_ID 
    , PROVIDER_ID::NUMBER(28,0)                   AS PROVIDER_ID  
    , CARE_SITE_ID::NUMBER(28,0)                  AS CARE_SITE_ID  
    , VISIT_SOURCE_VALUE::VARCHAR(50)             AS VISIT_SOURCE_VALUE
    , VISIT_SOURCE_CONCEPT_ID::NUMBER(28,0)       AS VISIT_SOURCE_CONCEPT_ID 
    , ADMITTING_SOURCE_CONCEPT_ID::NUMBER(28,0)   AS ADMITTING_SOURCE_CONCEPT_ID 
    , ADMITTING_SOURCE_VALUE::VARCHAR(50)         AS ADMITTING_SOURCE_VALUE
    , DISCHARGE_TO_CONCEPT_ID::NUMBER(28,0)       AS DISCHARGE_TO_CONCEPT_ID 
    , DISCHARGE_TO_SOURCE_VALUE::VARCHAR(50)      AS DISCHARGE_TO_SOURCE_VALUE
    , PRECEDING_VISIT_OCCURRENCE_ID::NUMBER(28,0) AS PRECEDING_VISIT_OCCURRENCE_ID 
    , ETL_MODULE::VARCHAR(100)                    AS ETL_MODULE
FROM
(SELECT *
FROM
     {{ref('V_VISIT_OCCURRENCE_AMB_F2F')}} AS VISIT_OCCURRENCE_AMB_F2F    
UNION ALL
SELECT *
FROM 
     {{ref('V_VISIT_OCCURRENCE_HSP')}} AS VISIT_OCCURRENCE_HSP ) A