--VISIT_DETAIL 

{{ config(materialized='table') }}

SELECT
    DISTINCT 
      VISIT_DETAIL_ID::NUMBER(28,0)                 AS VISIT_DETAIL_ID 
    , PERSON_ID::NUMBER(28,0)                       AS PERSON_ID 
    , VISIT_DETAIL_CONCEPT_ID::NUMBER(28,0)         AS VISIT_DETAIL_CONCEPT_ID 
    , VISIT_DETAIL_START_DATE::DATE                 AS VISIT_DETAIL_START_DATE
    , VISIT_DETAIL_START_DATETIME::DATETIME         AS VISIT_DETAIL_START_DATETIME
    , VISIT_DETAIL_END_DATE::DATE                   AS VISIT_DETAIL_END_DATE
    , VISIT_DETAIL_END_DATETIME::DATETIME           AS VISIT_DETAIL_END_DATETIME
    , VISIT_DETAIL_TYPE_CONCEPT_ID::NUMBER(28,0)    AS VISIT_DETAIL_TYPE_CONCEPT_ID 
    , PROVIDER_ID::NUMBER(28,0)                     AS PROVIDER_ID 
    , CARE_SITE_ID::NUMBER(28,0)                    AS CARE_SITE_ID 
    , VISIT_DETAIL_SOURCE_VALUE::VARCHAR(50)        AS VISIT_DETAIL_SOURCE_VALUE
    , VISIT_DETAIL_SOURCE_CONCEPT_ID::NUMBER(28,0)  AS VISIT_DETAIL_SOURCE_CONCEPT_ID 
    , ADMITTING_SOURCE_VALUE::VARCHAR(50)           AS ADMITTING_SOURCE_VALUE
    , ADMITTING_SOURCE_CONCEPT_ID::NUMBER(28,0)     AS ADMITTING_SOURCE_CONCEPT_ID 
    , DISCHARGE_TO_SOURCE_VALUE::VARCHAR(50)        AS DISCHARGE_TO_SOURCE_VALUE
    , DISCHARGE_TO_CONCEPT_ID::NUMBER(28,0)         AS DISCHARGE_TO_CONCEPT_ID 
    , PRECEDING_VISIT_DETAIL_ID::NUMBER(28,0)       AS PRECEDING_VISIT_DETAIL_ID 
    , VISIT_DETAIL_PARENT_ID::NUMBER(28,0)          AS VISIT_DETAIL_PARENT_ID 
    , VISIT_OCCURRENCE_ID::NUMBER(28,0)             AS VISIT_OCCURRENCE_ID 
    , ETL_MODULE::VARCHAR(100)                      AS ETL_MODULE
    , VISIT_SOURCE_VALUE::VARCHAR(50)               AS VISIT_SOURCE_VALUE
FROM
     {{ref('V_VISIT_DETAIL_ALL')}} AS V_VISIT_DETAIL_ALL    
