  {{ config(materialized='ephemeral') }}
  
SELECT PATIENT_RACE.PAT_ID
    , PATIENT_RACE.LINE
    , PATIENT_RACE.PATIENT_RACE_C
FROM  {{ref('MAX_RACE')}} AS MAX_RACE
INNER JOIN {{ source('CLARITY','PATIENT_RACE')}} AS PATIENT_RACE
    ON (MAX_RACE.MAXOFLINE = PATIENT_RACE.LINE)
        AND (MAX_RACE.PAT_ID = PATIENT_RACE.PAT_ID)
