--SQRY_SNOWFLAKE_COUNTS

{{ config(materialized = 'table', schema='OMOP_QA') }}

SELECT 'CARE_SITE_CLARITY_ALL' AS OMOP_CLARITY_TABLE, COUNT(*) AS TABLE_COUNT_SNOWFLAKE FROM OMOP_CLARITY.CARE_SITE_CLARITY_ALL 
UNION ALL
SELECT 'CONDITION_OCCURRENCE_CLARITYAMB_ICD', COUNT(*) FROM OMOP_CLARITY.CONDITION_OCCURRENCE_CLARITYAMB_ICD
UNION ALL
SELECT 'CONDITION_OCCURRENCE_CLARITYHOSP_ICD', COUNT(*) FROM OMOP_CLARITY.CONDITION_OCCURRENCE_CLARITYHOSP_ICD
UNION ALL
SELECT 'DEATH_CLARITY_ALL', COUNT(*) FROM OMOP_CLARITY.DEATH_CLARITY_ALL
UNION ALL
SELECT 'DEVICE_EXPOSURE_CLARITYANES_LDA', COUNT(*) FROM OMOP_CLARITY.DEVICE_EXPOSURE_CLARITYANES_LDA
UNION ALL
SELECT 'DEVICE_EXPOSURE_CLARITYHOSP_BLOOD', COUNT(*) FROM OMOP_CLARITY.DEVICE_EXPOSURE_CLARITYHOSP_BLOOD
UNION ALL
SELECT 'DEVICE_EXPOSURE_CLARITYHOSP_LDA', COUNT(*) FROM OMOP_CLARITY.DEVICE_EXPOSURE_CLARITYHOSP_LDA
UNION ALL
SELECT 'DRUG_EXPOSURE_CLARITYAMB_RXNORM', COUNT(*) FROM OMOP_CLARITY.DRUG_EXPOSURE_CLARITYAMB_RXNORM
UNION ALL
SELECT 'DRUG_EXPOSURE_CLARITYANES_RXNORM', COUNT(*) FROM OMOP_CLARITY.DRUG_EXPOSURE_CLARITYANES_RXNORM
UNION ALL
SELECT 'DRUG_EXPOSURE_CLARITYHOSP_RXNORM', COUNT(*) FROM OMOP_CLARITY.DRUG_EXPOSURE_CLARITYHOSP_RXNORM
UNION ALL
SELECT 'LOCATION_CLARITY_ALL', COUNT(*) FROM OMOP_CLARITY.LOCATION_CLARITY_ALL
UNION ALL
SELECT 'MEASUREMENT_CLARITYAMB_FLOWSHEET', COUNT(*) FROM OMOP_CLARITY.MEASUREMENT_CLARITYAMB_FLOWSHEET
UNION ALL
SELECT 'MEASUREMENT_CLARITYAMB_LOINC', COUNT(*) FROM OMOP_CLARITY.MEASUREMENT_CLARITYAMB_LOINC
UNION ALL
SELECT 'MEASUREMENT_CLARITYANES_FLOWSHEET', COUNT(*) FROM OMOP_CLARITY.MEASUREMENT_CLARITYANES_FLOWSHEET
UNION ALL
SELECT 'MEASUREMENT_CLARITYHOSP_FLOWSHEET', COUNT(*) FROM OMOP_CLARITY.MEASUREMENT_CLARITYHOSP_FLOWSHEET
UNION ALL
SELECT 'MEASUREMENT_CLARITYHOSP_LOINC', COUNT(*) FROM OMOP_CLARITY.MEASUREMENT_CLARITYHOSP_LOINC
UNION ALL
SELECT 'NOTE_CLARITYAMB_ALL', COUNT(*) FROM OMOP_CLARITY.NOTE_CLARITYAMB_ALL
UNION ALL
SELECT 'NOTE_CLARITYANES_ALL', COUNT(*) FROM OMOP_CLARITY.NOTE_CLARITYANES_ALL
UNION ALL
SELECT 'NOTE_CLARITYHOSP_ALL', COUNT(*) FROM OMOP_CLARITY.NOTE_CLARITYHOSP_ALL
UNION ALL
SELECT 'OBSERVATION_CLARITYALL_ALLERGY', COUNT(*) FROM OMOP_CLARITY.OBSERVATION_CLARITYALL_ALLERGY
UNION ALL
SELECT 'OBSERVATION_CLARITYAMB_ICD', COUNT(*) FROM OMOP_CLARITY.OBSERVATION_CLARITYAMB_ICD
UNION ALL
SELECT 'OBSERVATION_CLARITYHOSP_ICD', COUNT(*) FROM OMOP_CLARITY.OBSERVATION_CLARITYHOSP_ICD
UNION ALL
SELECT 'PERSON_CLARITY_ALL', COUNT(*) FROM OMOP_CLARITY.PERSON_CLARITY_ALL
UNION ALL
SELECT 'PROCEDURE_OCCURRENCE_CLARITYAMB_CPT', COUNT(*) FROM OMOP_CLARITY.PROCEDURE_OCCURRENCE_CLARITYAMB_CPT
UNION ALL
--SELECT 'PROCEDURE_OCCURRENCE_CLARITYANES_SNOMED_ALLSYSTEM', COUNT(*) FROM OMOP_CLARITY.PROCEDURE_OCCURRENCE_CLARITYANES_SNOMED_ALLSYSTEM
--UNION ALL
SELECT 'PROCEDURE_OCCURRENCE_CLARITYHSP_CPT', COUNT(*) FROM OMOP_CLARITY.PROCEDURE_OCCURRENCE_CLARITYHSP_CPT
UNION ALL
SELECT 'PROCEDURE_OCCURRENCE_CLARITYSURG_CPT', COUNT(*) FROM OMOP_CLARITY.PROCEDURE_OCCURRENCE_CLARITYSURG_CPT
UNION ALL
SELECT 'PROVIDER_CLARITY_ALL', COUNT(*) FROM OMOP_CLARITY.PROVIDER_CLARITY_ALL
UNION ALL
SELECT 'SPECIMEN_CLARITY_ALL', COUNT(*) FROM OMOP_CLARITY.SPECIMEN_CLARITY_ALL
UNION ALL
SELECT 'VISIT_DETAIL_CLARITYHOSP_ALL', COUNT(*) FROM OMOP_CLARITY.VISIT_DETAIL_CLARITYHOSP_ALL
UNION ALL
SELECT 'VISIT_OCCURRENCE_CLARITYAMB_ALL', COUNT(*) FROM OMOP_CLARITY.VISIT_OCCURRENCE_CLARITYAMB_ALL
UNION ALL
SELECT 'VISIT_OCCURRENCE_CLARITYHOSP_ALL', COUNT(*) FROM OMOP_CLARITY.VISIT_OCCURRENCE_CLARITYHOSP_ALL