-- SQRY_SNOWFLAKE_DBT_COUNTS 

{{ config(materialized = 'table', schema='OMOP_QA') }}

SELECT 'CARE_SITE_CLARITY_ALL' AS OMOP_CLARITY_TABLE, COUNT(*) AS TABLE_COUNT_DBT FROM {{ref('CARE_SITE_CLARITY_ALL')}} AS CARE_SITE_CLARITY_ALL 
UNION ALL
SELECT 'CONDITION_OCCURRENCE_CLARITYAMB_ICD', COUNT(*) FROM {{ref('CONDITION_OCCURRENCE_CLARITYAMB_ICD')}} AS CONDITION_OCCURRENCE_CLARITYAMB_ICD
UNION ALL
SELECT 'CONDITION_OCCURRENCE_CLARITYHOSP_ICD', COUNT(*) FROM {{ref('CONDITION_OCCURRENCE_CLARITYHOSP_ICD')}} AS CONDITION_OCCURRENCE_CLARITYHOSP_ICD
UNION ALL
SELECT 'DEATH_CLARITY_ALL', COUNT(*) FROM {{ref('DEATH_CLARITY_ALL')}} AS DEATH_CLARITY_ALL
UNION ALL
SELECT 'DEVICE_EXPOSURE_CLARITYANES_LDA', COUNT(*) FROM {{ref('DEVICE_EXPOSURE_CLARITYANES_LDA')}} AS DEVICE_EXPOSURE_CLARITYANES_LDA
UNION ALL
SELECT 'DEVICE_EXPOSURE_CLARITYHOSP_BLOOD', COUNT(*) FROM {{ref('DEVICE_EXPOSURE_CLARITYHOSP_BLOOD')}} AS DEVICE_EXPOSURE_CLARITYHOSP_BLOOD
UNION ALL
SELECT 'DEVICE_EXPOSURE_CLARITYHOSP_LDA', COUNT(*) FROM {{ref('DEVICE_EXPOSURE_CLARITYHOSP_LDA')}} AS DEVICE_EXPOSURE_CLARITYHOSP_LDA
UNION ALL
SELECT 'DRUG_EXPOSURE_CLARITYAMB_RXNORM', COUNT(*) FROM {{ref('DRUG_EXPOSURE_CLARITYAMB_RXNORM')}} AS DRUG_EXPOSURE_CLARITYAMB_RXNORM
UNION ALL
SELECT 'DRUG_EXPOSURE_CLARITYANES_RXNORM', COUNT(*) FROM {{ref('DRUG_EXPOSURE_CLARITYANES_RXNORM')}} AS DRUG_EXPOSURE_CLARITYANES_RXNORM
UNION ALL
SELECT 'DRUG_EXPOSURE_CLARITYHOSP_RXNORM', COUNT(*) FROM {{ref('DRUG_EXPOSURE_CLARITYHOSP_RXNORM')}} AS DRUG_EXPOSURE_CLARITYHOSP_RXNORM
UNION ALL
SELECT 'LOCATION_CLARITY_ALL', COUNT(*) FROM {{ref('LOCATION_CLARITY_ALL')}} AS LOCATION_CLARITY_ALL
UNION ALL
SELECT 'MEASUREMENT_CLARITYAMB_FLOWSHEET', COUNT(*) FROM {{ref('MEASUREMENT_CLARITYAMB_FLOWSHEET')}} AS MEASUREMENT_CLARITYAMB_FLOWSHEET
UNION ALL
SELECT 'MEASUREMENT_CLARITYAMB_LOINC', COUNT(*) FROM {{ref('MEASUREMENT_CLARITYAMB_LOINC')}} AS MEASUREMENT_CLARITYAMB_LOINC
UNION ALL
SELECT 'MEASUREMENT_CLARITYANES_FLOWSHEET', COUNT(*) FROM {{ref('MEASUREMENT_CLARITYANES_FLOWSHEET')}} AS MEASUREMENT_CLARITYANES_FLOWSHEET
UNION ALL
SELECT 'MEASUREMENT_CLARITYHOSP_FLOWSHEET', COUNT(*) FROM {{ref('MEASUREMENT_CLARITYHOSP_FLOWSHEET')}} AS MEASUREMENT_CLARITYHOSP_FLOWSHEET
UNION ALL
SELECT 'MEASUREMENT_CLARITYHOSP_LOINC', COUNT(*) FROM {{ref('MEASUREMENT_CLARITYHOSP_LOINC')}} AS MEASUREMENT_CLARITYHOSP_LOINC
UNION ALL
SELECT 'NOTE_CLARITYAMB_ALL', COUNT(*) FROM {{ref('NOTE_CLARITYAMB_ALL')}} AS NOTE_CLARITYAMB_ALL
UNION ALL
SELECT 'NOTE_CLARITYANES_ALL', COUNT(*) FROM {{ref('NOTE_CLARITYANES_ALL')}} AS NOTE_CLARITYANES_ALL
UNION ALL
SELECT 'NOTE_CLARITYHOSP_ALL', COUNT(*) FROM {{ref('NOTE_CLARITYHOSP_ALL')}} AS NOTE_CLARITYHOSP_ALL
UNION ALL
SELECT 'OBSERVATION_CLARITYALL_ALLERGY', COUNT(*) FROM {{ref('OBSERVATION_CLARITYALL_ALLERGY')}} AS OBSERVATION_CLARITYALL_ALLERGY
UNION ALL
SELECT 'OBSERVATION_CLARITYAMB_ICD', COUNT(*) FROM {{ref('OBSERVATION_CLARITYAMB_ICD')}} AS OBSERVATION_CLARITYAMB_ICD
UNION ALL
SELECT 'OBSERVATION_CLARITYHOSP_ICD', COUNT(*) FROM {{ref('OBSERVATION_CLARITYHOSP_ICD')}} AS OBSERVATION_CLARITYHOSP_ICD
UNION ALL
SELECT 'PERSON_CLARITY_ALL', COUNT(*) FROM {{ref('PERSON_CLARITY_ALL')}} AS PERSON_CLARITY_ALL
UNION ALL
SELECT 'PROCEDURE_OCCURRENCE_CLARITYAMB_CPT', COUNT(*) FROM {{ref('PROCEDURE_OCCURRENCE_CLARITYAMB_CPT')}} AS PROCEDURE_OCCURRENCE_CLARITYAMB_CPT
UNION ALL
SELECT 'PROCEDURE_OCCURRENCE_CLARITYHSP_CPT', COUNT(*) FROM {{ref('PROCEDURE_OCCURRENCE_CLARITYHSP_CPT')}} AS PROCEDURE_OCCURRENCE_CLARITYHSP_CPT
UNION ALL
SELECT 'PROCEDURE_OCCURRENCE_CLARITYSURG_CPT', COUNT(*) FROM {{ref('PROCEDURE_OCCURRENCE_CLARITYSURG_CPT')}} AS PROCEDURE_OCCURRENCE_CLARITYSURG_CPT
UNION ALL
SELECT 'PROVIDER_CLARITY_ALL', COUNT(*) FROM {{ref('PROVIDER_CLARITY_ALL')}} AS PROVIDER_CLARITY_ALL
UNION ALL
SELECT 'SPECIMEN_CLARITY_ALL', COUNT(*) FROM {{ref('SPECIMEN_CLARITY_ALL')}} AS SPECIMEN_CLARITY_ALL
UNION ALL
SELECT 'VISIT_DETAIL_CLARITYHOSP_ALL', COUNT(*) FROM {{ref('VISIT_DETAIL_CLARITYHOSP_ALL')}} AS VISIT_DETAIL_CLARITYHOSP_ALL
UNION ALL
SELECT 'VISIT_OCCURRENCE_CLARITYAMB_ALL', COUNT(*) FROM {{ref('VISIT_OCCURRENCE_CLARITYAMB_ALL')}} AS VISIT_OCCURRENCE_CLARITYAMB_ALL
UNION ALL
SELECT 'VISIT_OCCURRENCE_CLARITYHOSP_ALL', COUNT(*) FROM {{ref('VISIT_OCCURRENCE_CLARITYHOSP_ALL')}} AS VISIT_OCCURRENCE_CLARITYHOSP_ALL