
--QA_DEATH_DUPLICATES_COUNT
---------------------------------------------------------------------

{{ config(materialized = 'view') }}

WITH TMP_DUPES AS (
SELECT DEATH_DATE
	,DEATH_DATETIME
	,DEATH_TYPE_CONCEPT_ID
	,CAUSE_CONCEPT_ID
	,CAUSE_SOURCE_VALUE
	,CAUSE_SOURCE_CONCEPT_ID
	,COUNT(*) AS CNT
FROM {{ref('DEATH')}} AS T1
GROUP BY DEATH_DATE
	,DEATH_DATETIME
	,DEATH_TYPE_CONCEPT_ID
	,CAUSE_CONCEPT_ID
	,CAUSE_SOURCE_VALUE
	,CAUSE_SOURCE_CONCEPT_ID
HAVING COUNT(*) > 1
)

SELECT CAST(GETDATE() AS DATE) AS RUN_DATE
	,'DEATH' AS STANDARD_DATA_TABLE
	, 'DUPLICATE' AS QA_METRIC
	, 'RECORDS'  AS METRIC_FIELD
	, COALESCE(SUM(CNT),0) AS QA_ERRORS
	, CASE WHEN SUM(CNT) IS NOT NULL THEN 'FATAL' ELSE NULL END   AS ERROR_TYPE
	, (SELECT COUNT(*) AS NUM_ROWS FROM {{ref('DEATH')}}) AS TOTAL_RECORDS
FROM TMP_DUPES

