--OBSERVATION 

{{ config(materialized = 'table') }} 

SELECT DISTINCT
     SEQ_OBSERVATION.NEXTVAL::NUMBER(28,0)        AS OBSERVATION_ID
    , PERSON_ID::NUMBER(28,0)                     AS PERSON_ID  
    , OBSERVATION_CONCEPT_ID::NUMBER(28,0)        AS OBSERVATION_CONCEPT_ID  
    , OBSERVATION_DATE::DATE                      AS OBSERVATION_DATE
    , OBSERVATION_DATETIME::DATETIME              AS OBSERVATION_DATETIME
    , OBSERVATION_TYPE_CONCEPT_ID::NUMBER(28,0)   AS OBSERVATION_TYPE_CONCEPT_ID  
    , VALUE_AS_NUMBER::FLOAT                      AS VALUE_AS_NUMBER
    , VALUE_AS_STRING::VARCHAR(60)                AS VALUE_AS_STRING
    , VALUE_AS_CONCEPT_ID::NUMBER(28,0)           AS VALUE_AS_CONCEPT_ID  
    , UNIT_CONCEPT_ID::NUMBER(28,0)               AS UNIT_CONCEPT_ID 
    , QUALIFIER_CONCEPT_ID::NUMBER(28,0)          AS QUALIFIER_CONCEPT_ID  
    , PROVIDER_ID::NUMBER(28,0)                   AS PROVIDER_ID 
    , VISIT_OCCURRENCE_ID::NUMBER(28,0)           AS VISIT_OCCURRENCE_ID  
    , VISIT_DETAIL_ID::NUMBER(28,0)               AS VISIT_DETAIL_ID 
    , OBSERVATION_SOURCE_VALUE::VARCHAR(50)       AS OBSERVATION_SOURCE_VALUE
    , OBSERVATION_SOURCE_CONCEPT_ID::NUMBER(28,0) AS OBSERVATION_SOURCE_CONCEPT_ID  
    , UNIT_SOURCE_VALUE::VARCHAR(50)              AS UNIT_SOURCE_VALUE
    , QUALIFIER_SOURCE_VALUE::VARCHAR(50)         AS QUALIFIER_SOURCE_VALUE
    , ETL_MODULE::VARCHAR(100)                    AS ETL_MODULE
    , VISIT_SOURCE_VALUE::VARCHAR(50)             AS VISIT_SOURCE_VALUE
FROM
(SELECT *
FROM
     {{ref('V_OBSERVATION_ICD_AMB')}}  AS V_OBSERVATION_ICD_AMB    
UNION ALL
SELECT *
FROM 
     {{ref('V_OBSERVATION_ICD_HSP')}} AS V_OBSERVATION_ICD_HSP 
UNION ALL
SELECT *
FROM 
     {{ref('V_OBSERVATION_ALLERGY_ALL')}} AS V_OBSERVATION_ALLERGY_ALL ) A