--OBSERVATION 

{{ config(materialized = 'table') }} 

SELECT
    DISTINCT SEQ_OBSERVATION.NEXTVAL AS OBSERVATION_ID
    , A.*
FROM
(SELECT *
FROM
     {{ref('V_OBSERVATION_ICD_AMB')}}  AS V_OBSERVATION_ICD_AMB    
UNION ALL
SELECT *
FROM 
     {{ref('V_OBSERVATION_ICD_HSP')}} AS V_OBSERVATION_ICD_HSP 
UNION ALL
SELECT *
FROM 
     {{ref('V_OBSERVATION_ALLERGY_ALL')}} AS V_OBSERVATION_ALLERGY_ALL ) A