--USE ROLE SF_SH_OMOP_DEVELOPER;
----USE SCHEMA SH_OMOP_DB_PROD.CDM;
--USE WAREHOUSE SH_OMOP_DATA_SCIENCE_WH;
--
--DELETE  FROM CDM.PROVIDER;

INSERT INTO CDM.PROVIDER (
  PROVIDER_ID
  ,PROVIDER_NAME
  ,NPI
  ,DEA
  ,SPECIALTY_CONCEPT_ID
  ,CARE_SITE_ID
  ,YEAR_OF_BIRTH
  ,GENDER_CONCEPT_ID
  ,PROVIDER_SOURCE_VALUE
  ,SPECIALTY_SOURCE_VALUE
  ,SPECIALTY_SOURCE_CONCEPT_ID
  ,GENDER_SOURCE_VALUE
  ,GENDER_SOURCE_CONCEPT_ID
  )

SELECT DISTINCT PROV_ID AS PROVIDER_ID
    ,PROV_NAME AS PROVIDER_NAME
    ,NPI
    ,DEA
--,SPECIALTY_CONCEPT_ID
    ,COALESCE(SOURCE_TO_CONCEPT_MAP_SPECIALTY.TARGET_CONCEPT_ID, 0) AS SPECIALTY_CONCEPT_ID
--,CARE_SITE_ID
    ,COALESCE(MAX(CARE_SITE.CARE_SITE_ID),1) AS CARE_SITE_ID
    ,YEAR(BIRTH_DATE) AS YEAR_OF_BIRTH 
--,GENDER_CONCEPT_ID
    ,COALESCE(SOURCE_TO_CONCEPT_MAP_GENDER.TARGET_CONCEPT_ID, 0) AS GENDER_CONCEPT_ID
    ,PROV_ID AS PROVIDER_SOURCE_VALUE
    ,PROV_TYPE AS SPECIALTY_SOURCE_VALUE
    ,0 AS SPECIALTY_SOURCE_CONCEPT_ID
    ,CAST (SEX_C AS VARCHAR(1)) || ':' || ZC_SEX_NAME  AS GENDER_SOURCE_VALUE
    ,0 AS GENDER_SOURCE_CONCEPT_ID

FROM OMOP_CLARITY.PROVIDER_CLARITY_ALL
    LEFT OUTER JOIN OMOP.SOURCE_TO_CONCEPT_MAP AS SOURCE_TO_CONCEPT_MAP_SPECIALTY
        ON SPECIALTY_C = SOURCE_TO_CONCEPT_MAP_SPECIALTY.SOURCE_CODE
            AND UPPER(SOURCE_TO_CONCEPT_MAP_SPECIALTY.SOURCE_VOCABULARY_ID) = 'SH_SPECIALTY'

    LEFT JOIN OMOP.CARE_SITE
        ON REV_LOC_ID = CARE_SITE.CARE_SITE_ID

    LEFT JOIN OMOP.SOURCE_TO_CONCEPT_MAP AS SOURCE_TO_CONCEPT_MAP_GENDER
        ON SEX_C = SOURCE_TO_CONCEPT_MAP_GENDER.SOURCE_CODE
            AND UPPER(SOURCE_TO_CONCEPT_MAP_GENDER.SOURCE_VOCABULARY_ID) = 'SH_GENDER'

GROUP BY
    PROV_ID
    ,PROV_NAME 
    ,NPI 
    ,DEA
    ,COALESCE(SOURCE_TO_CONCEPT_MAP_SPECIALTY.TARGET_CONCEPT_ID, 0) 
    ,YEAR(BIRTH_DATE) 
    ,COALESCE(SOURCE_TO_CONCEPT_MAP_GENDER.TARGET_CONCEPT_ID, 0)
    ,PROV_ID
    ,LEFT(ZC_SPECIALTY_NAME, 50)
    ,CAST( SEX_C AS VARCHAR(1)) || ':' || ZC_SEX_NAME 
    ,PROV_TYPE