/*******************************************************************************
# Copyright 2020 Spectrum Health 
# http://www.spectrumhealth.org
#
# Unless required by applicable law or agreed to in writing, this software
# is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, 
# either express or implied.
#
********************************************************************************/

/*******************************************************************************
Name: app_condition_occurrence_ICD_AMB_2.sql

Author: Roger Carlson
		Spectrum Health
		roger.carlson@spectrumhealth.org

Last Revised: 14-June-2020
		
Description: This script is the 2nd it a two-part process.  It is used in conjunction with 
	(and following) pull_condition_occurrence_ICD_AMB_2.sql. 

	Its purpose is to join the data in OMOP_Clarity.CONDITION_OCCURRENCE_ClarityAMB_ICD to the OMOP concept table
	to return standard concept ids, and append this data to CDM.condition_occurrence.

Structure: (if your structure is different, you will have to modify the code to match)
	Database:EpicCare
	Schemas: EpicCare.OMOP, EpicCare.OMOP_Clarity

Note: I don't use aliases unless necessary for joining. I find them more confusing than helpful.

********************************************************************************/

--USE ROLE SF_SH_OMOP_DEVELOPER;
--
----USE SCHEMA SH_CLINICAL_DB_PROD.EPIC_CLARITY_LZ;
----USE SCHEMA SH_OMOP_DB_PROD.OMOP_CLARITY;
----USE SCHEMA SH_OMOP_DB_PROD.CDM;
--
--USE WAREHOUSE SH_OMOP_DATA_SCIENCE_WH;
--
----CREATE OR REPLACE SEQUENCE CDM.SEQ_CONDITION_OCCURRENCE START = 1 INCREMENT = 1;
--
--DELETE FROM SH_OMOP_DB_PROD.CDM.CONDITION_OCCURRENCE
--WHERE ETL_MODULE =  'CONDITION_OCCURRENCE--CLARITYAMB--ICD';

INSERT INTO SH_OMOP_DB_PROD.CDM.CONDITION_OCCURRENCE ( 
--CONDITION_OCCURRENCE_ID
    PERSON_ID
	,CONDITION_CONCEPT_ID
	,CONDITION_START_DATE
	,CONDITION_START_DATETIME
	,CONDITION_END_DATE
	,CONDITION_END_DATETIME
	,CONDITION_TYPE_CONCEPT_ID
	,STOP_REASON
	,PROVIDER_ID
    ,VISIT_OCCURRENCE_ID
    ,VISIT_DETAIL_ID
	,CONDITION_SOURCE_VALUE
	,CONDITION_SOURCE_CONCEPT_ID
	,CONDITION_STATUS_SOURCE_VALUE
	,CONDITION_STATUS_CONCEPT_ID
	,ETL_MODULE
	,VISIT_SOURCE_VALUE
	)

WITH 
T_ICD_SOURCE
AS (
	SELECT CONCEPT_ID
		,CONCEPT_CODE
		,REPLACE(CONCEPT_NAME, '"', '') AS CONCEPT_NAME
	
	FROM SH_OMOP_DB_PROD.CDM.CONCEPT AS C
	
	WHERE C.VOCABULARY_ID IN ('ICD9CM','ICD10CM')
		AND (
			C.INVALID_REASON IS NULL
			OR C.INVALID_REASON = ''
			)
		AND C.DOMAIN_ID = 'Condition'
	)
,T_CONCEPT
AS (
	SELECT C2.CONCEPT_ID AS CONCEPT_ID
		,C1.CONCEPT_ID AS SOURCE_CONCEPT_ID
	
		FROM SH_OMOP_DB_PROD.CDM.CONCEPT C1
		
		INNER JOIN SH_OMOP_DB_PROD.CDM.CONCEPT_RELATIONSHIP CR
			ON C1.CONCEPT_ID = CR.CONCEPT_ID_1
				AND CR.RELATIONSHIP_ID = 'Maps to'
		
		INNER JOIN SH_OMOP_DB_PROD.CDM.CONCEPT C2
			ON C2.CONCEPT_ID = CR.CONCEPT_ID_2
	
	WHERE C2.STANDARD_CONCEPT = 'S'
		AND (
			C2.INVALID_REASON IS NULL
			OR C2.INVALID_REASON = ''
			)
		AND C2.DOMAIN_ID = 'Condition'
	)

SELECT DISTINCT 
	--CDM.SEQ_CONDITION_OCCURRENCE.NEXTVAL AS CONDITION_OCCURRENCE_ID
	CONDITION_OCCURRENCE_CLARITYAMB_ICD.PERSON_ID
	--,T_ICD10_CONCEPT.CONCEPT_ID AS CONDITION_CONCEPT_ID

	,CASE 
		WHEN CONDITION_OCCURRENCE_CLARITYAMB_ICD.CONTACT_DATE >= '2015-10-01'
			THEN T_ICD10_CONCEPT.CONCEPT_ID
		ELSE T_ICD9_CONCEPT.CONCEPT_ID
		END AS CONDITION_CONCEPT_ID

	,CAST( CONDITION_OCCURRENCE_CLARITYAMB_ICD.CONTACT_DATE AS DATE) AS CONDITION_START_DATE
	,CONDITION_OCCURRENCE_CLARITYAMB_ICD.CONTACT_DATE AS CONDITION_START_DATETIME
	,CAST( CONDITION_OCCURRENCE_CLARITYAMB_ICD.CONTACT_DATE AS DATE) AS CONDITION_END_DATE
	,CONDITION_OCCURRENCE_CLARITYAMB_ICD.CONTACT_DATE AS CONDITION_END_DATETIME
	,32817 AS CONDITION_TYPE_CONCEPT_ID
	,NULL AS STOP_REASON

	--MODIFIED 3/3/2021 FOR NULL PROVIDERS
	--,PROVIDER.PROVIDER_ID AS PROVIDER_ID	
	,COALESCE(VST.PROVIDER_ID, PCP.PROVIDER_ID) AS PROVIDER_ID

    ,VISIT_OCCURRENCE.VISIT_OCCURRENCE_ID AS VISIT_OCCURRENCE_ID
    
--    ,VISIT_DETAIL.VISIT_DETAIL_ID AS VISIT_DETAIL_ID
    ,0 AS VISIT_DETAIL_ID
    
	-- RETURNS ICD10 CODES AFTER SWITCH DATE-----
	,CASE 
		WHEN CONDITION_OCCURRENCE_CLARITYAMB_ICD.CONTACT_DATE >= '2015-10-01'
			THEN LEFT(T_ICD10_SOURCE.CONCEPT_CODE || ':' || T_ICD10_SOURCE.CONCEPT_NAME, 50)
		ELSE LEFT(T_ICD9_SOURCE.CONCEPT_CODE || ':' || T_ICD9_SOURCE.CONCEPT_NAME, 50)
		END AS CONDITION_SOURCE_VALUE
	,CASE 
		WHEN CONDITION_OCCURRENCE_CLARITYAMB_ICD.CONTACT_DATE >= '2015-10-01'
			THEN T_ICD10_SOURCE.CONCEPT_ID
		ELSE T_ICD9_SOURCE.CONCEPT_ID
		END AS CONDITION_SOURCE_CONCEPT_ID
	--------------------------------------------
	,'FINAL DIAGNOSIS' AS CONDITION_STATUS_SOURCE_VALUE
	,4230359 AS CONDITION_STATUS_CONCEPT_ID
	,'CONDITION_OCCURRENCE--CLARITYAMB--ICD' AS ETL_MODULE
	,VISIT_SOURCE_VALUE

FROM SH_OMOP_DB_PROD.OMOP_CLARITY.CONDITION_OCCURRENCE_ClarityAMB_ICD

	INNER JOIN SH_OMOP_DB_PROD.CDM.VISIT_OCCURRENCE
		ON CONDITION_OCCURRENCE_CLARITYAMB_ICD.PAT_ENC_CSN_ID = VISIT_OCCURRENCE.VISIT_SOURCE_VALUE

	--MODIFIED 3/3/2021 FOR NULL PROVIDERS
	--LEFT JOIN CDM.PROVIDER
	--	ON CONDITION_OCCURRENCE_CLARITYAMB_ICD.VISIT_PROV_ID = PROVIDER.PROVIDER_SOURCE_VALUE
    LEFT JOIN
                SH_OMOP_DB_PROD.CDM.PROVIDER AS VST
                ON  CONDITION_OCCURRENCE_CLARITYAMB_ICD.VISIT_PROV_ID = VST.PROVIDER_SOURCE_VALUE         
    LEFT JOIN
                SH_OMOP_DB_PROD.CDM.PROVIDER AS PCP
                ON  CONDITION_OCCURRENCE_CLARITYAMB_ICD.PCP_PROV_ID = PCP.PROVIDER_SOURCE_VALUE 
	--------CONCEPT MAPPING--------------------

	LEFT JOIN T_ICD_SOURCE AS T_ICD9_SOURCE
		ON CONDITION_OCCURRENCE_CLARITYAMB_ICD.ICD9_CODE = T_ICD9_SOURCE.CONCEPT_CODE

	LEFT JOIN T_ICD_SOURCE AS T_ICD10_SOURCE
		ON CONDITION_OCCURRENCE_CLARITYAMB_ICD.ICD10_CODE = T_ICD10_SOURCE.CONCEPT_CODE

	LEFT JOIN T_CONCEPT AS T_ICD9_CONCEPT
		ON T_ICD9_CONCEPT.SOURCE_CONCEPT_ID = T_ICD9_SOURCE.CONCEPT_ID

	LEFT JOIN T_CONCEPT AS T_ICD10_CONCEPT
		ON T_ICD10_CONCEPT.SOURCE_CONCEPT_ID = T_ICD10_SOURCE.CONCEPT_ID

WHERE 	
	(CONDITION_OCCURRENCE_CLARITYAMB_ICD.CONTACT_DATE >= '2015-10-01' AND T_ICD10_CONCEPT.CONCEPT_ID IS NOT NULL)   
	OR 
	(CONDITION_OCCURRENCE_CLARITYAMB_ICD.CONTACT_DATE < '2015-10-01' AND T_ICD9_CONCEPT.CONCEPT_ID IS NOT NULL   );

