/*******************************************************************************
# Copyright 2020 Spectrum Health 
# http://www.spectrumhealth.org
#
# Unless required by applicable law or agreed to in writing, this software
# is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, 
# either express or implied.
#
********************************************************************************/

/*******************************************************************************
Name: app_observation_ICD_HSP_2.sql

Author: Roger Carlson
		Spectrum Health
		roger.carlson@spectrumhealth.org

Last Revised: 14-June-2020
		
Description: This script is the 2nd it a two-part process.  It is used in conjunction with 
	(and following) pull_observation_ICD_HSP_2.sql. 

	Its purpose is to join the data in OMOP_Clarity.OBSERVATION_ClarityHosp_ICD to the OMOP concept table
	to return standard concept ids, and append this data to CDM.observation.

Structure: (if your structure is different, you will have to modify the code to match)
	Database:EpicCare
	Schemas: EpicCare.OMOP, EpicCare.OMOP_Clarity

Note: I don't use aliases unless necessary for joining. I find them more confusing than helpful.

********************************************************************************/

--USE DATABASE SH_OMOP_DB_PROD;
----USE SCHEMA OMOP_CLARITY;
--USE ROLE SF_SH_OMOP_DEVELOPER;
--USE WAREHOUSE SH_OMOP_DATA_SCIENCE_WH;

--CREATE OR REPLACE SEQUENCE CDM.SEQ_OBSERVATION START = 1 INCREMENT = 1;

--DELETE FROM CDM.OBSERVATION
--WHERE ETL_Module = 'OBSERVATION--ClarityHosp--ICD';


INSERT INTO CDM.OBSERVATION
(	--OBSERVATION_ID, ----IDENTITY
	   PERSON_ID
      ,OBSERVATION_CONCEPT_ID
      ,OBSERVATION_DATE
      ,OBSERVATION_DATETIME
      ,OBSERVATION_TYPE_CONCEPT_ID
      ,VALUE_AS_NUMBER
      ,VALUE_AS_STRING
      ,VALUE_AS_CONCEPT_ID
	  ,QUALIFIER_CONCEPT_ID
      ,UNIT_CONCEPT_ID
      ,PROVIDER_ID
      ,VISIT_OCCURRENCE_ID
      ,VISIT_DETAIL_ID 
      ,OBSERVATION_SOURCE_VALUE
      ,OBSERVATION_SOURCE_CONCEPT_ID
      ,UNIT_SOURCE_VALUE
      ,QUALIFIER_SOURCE_VALUE
	  ,ETL_MODULE
	  ,VISIT_SOURCE_VALUE
)

WITH T_ICD_SOURCE
AS (
	SELECT CONCEPT_ID
		,CONCEPT_CODE
		,CONCEPT_NAME
	
	FROM CDM.CONCEPT AS C
	
	WHERE UPPER(C.VOCABULARY_ID) IN ('ICD9CM','ICD10CM')
		AND (C.INVALID_REASON IS NULL OR C.INVALID_REASON = '')
		AND UPPER(C.DOMAIN_ID) = 'OBSERVATION'
	)
	,T_CONCEPT
AS (
	SELECT C2.CONCEPT_ID AS CONCEPT_ID
		,C1.CONCEPT_ID AS SOURCE_CONCEPT_ID
	
	FROM CDM.CONCEPT C1
	
		INNER JOIN CDM.CONCEPT_RELATIONSHIP CR
			ON C1.CONCEPT_ID = CR.CONCEPT_ID_1
				AND UPPER(CR.RELATIONSHIP_ID) = 'MAPS TO VALUE'
		
		INNER JOIN CDM.CONCEPT C2
			ON C2.CONCEPT_ID = CR.CONCEPT_ID_2
	
	WHERE C2.STANDARD_CONCEPT = 'S'
		AND (C2.INVALID_REASON IS NULL	OR C2.INVALID_REASON = '')
		AND UPPER(C2.DOMAIN_ID) = 'OBSERVATION'
	)

SELECT DISTINCT
	
--	CDM.SEQ_OBSERVATION.NEXTVAL AS OBSERVATION_ID
	OBSERVATION_CLARITYHOSP_ICD.PERSON_ID
	--,T_ICD10_CONCEPT.CONCEPT_ID AS OBSERVATION_CONCEPT_ID

	,CASE 
		WHEN OBSERVATION_CLARITYHOSP_ICD.CONTACT_DATE >= '2015-10-01'
			THEN T_ICD10_CONCEPT.CONCEPT_ID
		ELSE T_ICD9_CONCEPT.CONCEPT_ID
		END AS OBSERVATION_CONCEPT_ID

	,CAST( OBSERVATION_CLARITYHOSP_ICD.CONTACT_DATE AS DATE) AS OBSERVATION_DATE
	,OBSERVATION_CLARITYHOSP_ICD.CONTACT_DATE AS OBSERVATION_DATETIME
	,32817 AS OBSERVATION_TYPE_CONCEPT_ID --EHR
	,NULL AS VALUE_AS_NUMBER
	-- RETURNS ICD10 CODES AFTER SWITCH DATE-----
	,CASE 
		WHEN OBSERVATION_CLARITYHOSP_ICD.CONTACT_DATE >= '2015-10-01'
			THEN T_ICD10_SOURCE.CONCEPT_CODE
		ELSE T_ICD9_SOURCE.CONCEPT_CODE
		END AS VALUE_AS_STRING
	,CASE 
		WHEN OBSERVATION_CLARITYHOSP_ICD.CONTACT_DATE >= '2015-10-01'
			THEN T_ICD10_CONCEPT.CONCEPT_ID
		ELSE T_ICD9_CONCEPT.CONCEPT_ID
		END AS VALUE_AS_CONCEPT_ID
	--------------------------------------------
	,0 AS UNIT_CONCEPT_ID
	,0 AS QUALIFIER_CONCEPT_ID
	,PROVIDER.PROVIDER_ID AS PROVIDER_ID
	,VISIT_OCCURRENCE.VISIT_OCCURRENCE_ID AS VISIT_OCCURRENCE_ID
	    
--    ,VISIT_DETAIL.VISIT_DETAIL_ID AS VISIT_DETAIL_ID
    ,0 AS VISIT_DETAIL_ID

	-- RETURNS ICD10 CODES AFTER SWITCH DATE-----
	,CASE 
		WHEN OBSERVATION_CLARITYHOSP_ICD.CONTACT_DATE >= '2015-10-01'
			THEN LEFT(T_ICD10_SOURCE.CONCEPT_CODE || ':' || T_ICD10_SOURCE.CONCEPT_NAME, 50)
		ELSE LEFT(T_ICD9_SOURCE.CONCEPT_CODE || ':' || T_ICD9_SOURCE.CONCEPT_NAME, 50)
		END AS OBSERVATION_SOURCE_VALUE
	,CASE 
		WHEN OBSERVATION_CLARITYHOSP_ICD.CONTACT_DATE >= '2015-10-01'
			THEN T_ICD10_SOURCE.CONCEPT_ID
		ELSE T_ICD9_SOURCE.CONCEPT_ID
		END AS OBSERVATION_SOURCE_CONCEPT_ID
	--------------------------------------------
	,NULL AS UNIT_SOURCE_VALUE
	,NULL AS QUALIFIER_SOURCE_VALUE
	,'OBSERVATION--CLARITYHOSP--ICD' AS ETL_MODULE
    ,VISIT_SOURCE_VALUE

FROM OMOP_CLARITY.OBSERVATION_CLARITYHOSP_ICD

	INNER JOIN CDM.VISIT_OCCURRENCE
		ON OBSERVATION_CLARITYHOSP_ICD.PAT_ENC_CSN_ID = VISIT_OCCURRENCE.VISIT_SOURCE_VALUE

	--------CONCEPT MAPPING--------------------

	LEFT JOIN T_ICD_SOURCE AS T_ICD9_SOURCE
		ON OBSERVATION_CLARITYHOSP_ICD.ICD9_CODE = T_ICD9_SOURCE.CONCEPT_CODE

	LEFT JOIN T_ICD_SOURCE AS T_ICD10_SOURCE
		ON OBSERVATION_CLARITYHOSP_ICD.ICD10_CODE = T_ICD10_SOURCE.CONCEPT_CODE


	LEFT JOIN T_CONCEPT AS T_ICD9_CONCEPT
		ON T_ICD9_CONCEPT.SOURCE_CONCEPT_ID = T_ICD9_SOURCE.CONCEPT_ID

	LEFT JOIN T_CONCEPT AS T_ICD10_CONCEPT
		ON T_ICD10_CONCEPT.SOURCE_CONCEPT_ID = T_ICD10_SOURCE.CONCEPT_ID

	--------CONCEPT MAPPING END --------------------
	LEFT JOIN CDM.PROVIDER
		ON OBSERVATION_CLARITYHOSP_ICD.BILL_ATTEND_PROV_ID = PROVIDER.PROVIDER_SOURCE_VALUE


-------------------------------------------
WHERE 	
	(OBSERVATION_CLARITYHOSP_ICD.CONTACT_DATE >= '2015-10-01' AND T_ICD10_CONCEPT.CONCEPT_ID IS NOT NULL)   
	OR 
	(OBSERVATION_CLARITYHOSP_ICD.CONTACT_DATE < '2015-10-01' AND T_ICD9_CONCEPT.CONCEPT_ID IS NOT NULL   )