/*******************************************************************************
# Copyright 2020 Spectrum Health 
# http://www.spectrumhealth.org
#
# Unless required by applicable law or agreed to in writing, this software
# is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, 
# either express or implied.
#
********************************************************************************/


/*******************************************************************************
Name: app_observation_Allergy_ALL_2.sql

Author: Roger Carlson
		Spectrum Health
		roger.carlson@spectrumhealth.org

Last Revised: 15-January-2021
		
Description: This script is the 2nd it a two-part process.  It is used in conjunction with 
	(and following) pull_observation_Allergy_ALL_2.sql. 

	Its purpose is to join the data in SH_OMOP_DB_PROD.OMOP_CLARITY.OBSERVATION_ClarityALL_Allergy to the OMOP concept table
	to return standard concept ids, and append this data to CDM.observation.

Structure: (if your structure is different, you will have to modify the code to match)
	Database:EpicCare
	Schemas: EpicCare.OMOP, EpicCare.OMOP_Clarity

Note: I don't use aliases unless necessary for joining. I find them more confusing than helpful.

********************************************************************************/

--USE DATABASE SH_OMOP_DB_PROD;
----USE SCHEMA OMOP_CLARITY;
--USE ROLE SF_SH_OMOP_DEVELOPER;
--USE WAREHOUSE SH_OMOP_DATA_SCIENCE_WH;

--
--DELETE FROM CDM.OBSERVATION
--WHERE ETL_Module = 'OBSERVATION--ClarityALL--Allergy';

INSERT INTO CDM.OBSERVATION

(	  OBSERVATION_ID
	  ,PERSON_ID
      ,OBSERVATION_CONCEPT_ID
      ,OBSERVATION_DATE
      ,OBSERVATION_DATETIME
      ,OBSERVATION_TYPE_CONCEPT_ID
      ,VALUE_AS_NUMBER
      ,VALUE_AS_STRING
      ,VALUE_AS_CONCEPT_ID
	  ,QUALIFIER_CONCEPT_ID
      ,UNIT_CONCEPT_ID
      ,PROVIDER_ID
      ,VISIT_OCCURRENCE_ID
      ,VISIT_DETAIL_ID
      ,OBSERVATION_SOURCE_VALUE
      ,OBSERVATION_SOURCE_CONCEPT_ID
      ,UNIT_SOURCE_VALUE
      ,QUALIFIER_SOURCE_VALUE
	  ,ETL_MODULE
)

WITH T_SOURCE
AS (
	SELECT CONCEPT_ID
		,CONCEPT_CODE
		,CONCEPT_NAME
	FROM CDM.CONCEPT AS C
	WHERE UPPER(C.VOCABULARY_ID) IN ('SNOMED')
		AND (C.INVALID_REASON IS NULL
			OR C.INVALID_REASON = '')
		AND UPPER(C.DOMAIN_ID) = 'OBSERVATION'
		AND UPPER(CONCEPT_NAME) LIKE 'ALLERGY TO %'
)
,
	
T_CONCEPT
AS (
	SELECT C2.CONCEPT_ID AS CONCEPT_ID
		,C1.CONCEPT_ID AS SOURCE_CONCEPT_ID
	FROM CDM.CONCEPT C1
	INNER JOIN CDM.CONCEPT_RELATIONSHIP CR
		ON C1.CONCEPT_ID = CR.CONCEPT_ID_1
				AND UPPER(CR.RELATIONSHIP_ID) = 'MAPS TO'
	INNER JOIN CDM.CONCEPT C2
		ON C2.CONCEPT_ID = CR.CONCEPT_ID_2
	WHERE C2.STANDARD_CONCEPT = 'S'
		AND (C2.INVALID_REASON IS NULL
			OR C2.INVALID_REASON = '')
		AND UPPER(C2.DOMAIN_ID) = 'OBSERVATION'
)


SELECT DISTINCT CDM.SEQ_OBSERVATION.NEXTVAL AS OBSERVATION_ID
	,OBSERVATION_CLARITYALL_ALLERGY.PERSON_ID
	, CASE 
		WHEN UPPER(ALLERGEN_NAME) = 'PENICILLINS'
			THEN 4240903
		ELSE COALESCE(T_CONCEPT.CONCEPT_ID, 0)
	  END AS OBSERVATION_CONCEPT_ID
	, CAST( COALESCE(ALRGY_ENTERED_DTTM, DATE_NOTED, CONTACT_DATE) AS DATE) AS OBSERVATION_DATE
	, CAST( COALESCE(ALRGY_ENTERED_DTTM, DATE_NOTED, CONTACT_DATE) AS DATETIME) AS OBSERVATION_DATETIME
	--, 38000280 AS OBSERVATION_TYPE_CONCEPT_ID
	, 32817 AS OBSERVATION_TYPE_CONCEPT_ID -- NEW TYPE_ID
	, NULL AS VALUE_AS_NUMBER
	, LEFT(ALLERGEN_NAME,60) AS VALUE_AS_STRING
	, 0 AS VALUE_AS_CONCEPT_ID
	, 0 AS QUALIFIER_CONCEPT_ID
	, 0 AS UNIT_CONCEPT_ID
	, PROVIDER.PROVIDER_ID AS PROVIDER_ID
	, VISIT_OCCURRENCE.VISIT_OCCURRENCE_ID AS VISIT_OCCURRENCE_ID
	    
--    ,VISIT_DETAIL.VISIT_DETAIL_ID AS VISIT_DETAIL_ID
    ,0 AS VISIT_DETAIL_ID

	, LEFT('ALLERGY:' || ALLERGEN_NAME,50) AS OBSERVATION_SOURCE_VALUE
	, 0 AS OBSERVATION_SOURCE_CONCEPT_ID
	, NULL AS UNIT_SOURCE_VALUE
	, NULL AS QUALIFIER_SOURCE_VALUE
	,'OBSERVATION--CLARITYALL--ALLERGY' AS ETL_MODULE

FROM SH_OMOP_DB_PROD.OMOP_CLARITY.OBSERVATION_CLARITYALL_ALLERGY 
	LEFT JOIN T_SOURCE
		ON OBSERVATION_CLARITYALL_ALLERGY.CONCEPT_NAME = T_SOURCE.CONCEPT_NAME
	LEFT JOIN T_CONCEPT
		ON T_CONCEPT.SOURCE_CONCEPT_ID = T_SOURCE.CONCEPT_ID
	LEFT  JOIN CDM.VISIT_OCCURRENCE
		ON OBSERVATION_CLARITYALL_ALLERGY.PAT_ENC_CSN_ID = VISIT_OCCURRENCE.VISIT_SOURCE_VALUE
	LEFT JOIN CDM.PROVIDER
		ON OBSERVATION_CLARITYALL_ALLERGY.PROV_ID = PROVIDER.PROVIDER_SOURCE_VALUE

