--V_DRUG_EXPOSURE_RXNORM_HSP

{{ config(materialized = 'view') }}

SELECT DISTINCT 
--	CDM.SEQ_DRUG_EXPOSURE.NEXTVAL AS DRUG_EXPOSURE_ID
	DRUG_EXPOSURE_CLARITYHOSP_RXNORM.PERSON_ID
	,T_DRUG_CONCEPT.DRUG_CONCEPT_ID
	,CAST( TAKEN_TIME AS DATE) AS DRUG_EXPOSURE_START_DATE
	,TAKEN_TIME AS DRUG_EXPOSURE_START_DATETIME
	,CAST( COALESCE(ORDER_END_TIME, TAKEN_TIME)AS DATE) AS DRUG_EXPOSURE_END_DATE
	,CASE 
		WHEN (CAST( COALESCE(ORDER_END_TIME, TAKEN_TIME)AS DATE) = CAST( TAKEN_TIME AS DATE))
			AND (COALESCE(ORDER_END_TIME, TAKEN_TIME) < TAKEN_TIME)
			THEN TAKEN_TIME
			ELSE
			COALESCE(ORDER_END_TIME, TAKEN_TIME)
		END AS DRUG_EXPOSURE_END_DATETIME	
	,END_DATE AS VERBATIM_END_DATE
	,32817 AS DRUG_TYPE_CONCEPT_ID -- EHR
	,LEFT(ZC_RSN_FOR_DISCON_NAME, 20) AS STOP_REASON
      ,	CASE 
		--WHEN TRY_CONVERT(INT,REFILLS) IS NULL
		WHEN TRY_CAST(REFILLS AS NUMERIC) IS NULL
			THEN NULL
		ELSE  REFILLS
		END AS REFILLS	
	,CASE 
		WHEN TRY_TO_NUMERIC(LEFT(QUANTITY, CHARINDEX(' ', QUANTITY))) IS NULL
			OR UPPER(ZC_MED_UNIT_NAME) = 'APPLICATION'
			THEN 1
		ELSE CAST (LEFT(QUANTITY, CHARINDEX(' ', QUANTITY)) AS FLOAT)
		END AS QUANTITY
	,NULL AS DAYS_SUPPLY
	,SIG AS SIG
	,COALESCE(SOURCE_TO_CONCEPT_MAP_ROUTE.TARGET_CONCEPT_ID, 0) AS ROUTE_CONCEPT_ID
	,NULL AS LOT_NUMBER
	,PROVIDER.PROVIDER_ID AS PROVIDER_ID
	,VISIT_OCCURRENCE_ID AS VISIT_OCCURRENCE_ID
	    
--    ,VISIT_DETAIL.VISIT_DETAIL_ID AS VISIT_DETAIL_ID
    ,0 AS VISIT_DETAIL_ID

	,CAST( DRUG_EXPOSURE_CLARITYHOSP_RXNORM.MEDICATION_ID AS VARCHAR) 
	       || ':' || LEFT(CLARITY_MEDICATION_NAME, 49 
	       - LEN(DRUG_EXPOSURE_CLARITYHOSP_RXNORM.MEDICATION_ID)) AS DRUG_SOURCE_VALUE
	,T_DRUG_SOURCE.CONCEPT_ID AS DRUG_SOURCE_CONCEPT_ID
	,CAST( DRUG_EXPOSURE_CLARITYHOSP_RXNORM.MED_ROUTE_C AS VARCHAR) 
	       || ':' || LEFT(ZC_ADMIN_ROUTE_NAME, 49 
	       - LEN(DRUG_EXPOSURE_CLARITYHOSP_RXNORM.MED_ROUTE_C)) AS ROUTE_SOURCE_VALUE
	,ZC_MED_UNIT_NAME AS DOSE_UNIT_SOURCE_VALUE
	,'DRUG_EXPOSURE--CLARITYHOSP--RXNORM' AS ETL_MODULE
	,VISIT_SOURCE_VALUE

FROM {{ref('DRUG_EXPOSURE_CLARITYHOSP_RXNORM')}} AS DRUG_EXPOSURE_CLARITYHOSP_RXNORM

	INNER JOIN {{ref('VISIT_OCCURRENCE')}} AS VISIT_OCCURRENCE
		ON DRUG_EXPOSURE_CLARITYHOSP_RXNORM.PAT_ENC_CSN_ID = VISIT_OCCURRENCE.VISIT_SOURCE_VALUE

	LEFT JOIN {{ref('PROVIDER')}} AS PROVIDER
		ON DRUG_EXPOSURE_CLARITYHOSP_RXNORM.AUTHRZING_PROV_ID = PROVIDER.PROVIDER_SOURCE_VALUE

	INNER JOIN {{ref('TOP_RXNORM_HSP')}} AS TOP_RXNORM
		ON DRUG_EXPOSURE_CLARITYHOSP_RXNORM.MEDICATION_ID = TOP_RXNORM.MEDICATION_ID

	INNER JOIN {{ref('T_DRUG_SOURCE')}} AS T_DRUG_SOURCE
		ON TOP_RXNORM.CONCEPT_CODE = T_DRUG_SOURCE.CONCEPT_CODE

	INNER JOIN {{ref('T_DRUG_CONCEPT')}} AS T_DRUG_CONCEPT
		ON T_DRUG_SOURCE.CONCEPT_ID = T_DRUG_CONCEPT.DRUG_CONCEPT_SOURCE_CONCEPT_ID

	LEFT JOIN {{ source('CDM','SOURCE_TO_CONCEPT_MAP')}} AS SOURCE_TO_CONCEPT_MAP_ROUTE
		ON SOURCE_TO_CONCEPT_MAP_ROUTE.SOURCE_CODE = DRUG_EXPOSURE_CLARITYHOSP_RXNORM.MED_ROUTE_C
			AND (SOURCE_TO_CONCEPT_MAP_ROUTE.SOURCE_VOCABULARY_ID) = 'SH_route'

	INNER JOIN -- THIS REMOVES THE DUPLICATES 
		(
		SELECT MIN(RXNORM_CODES_LINE) AS FIRSTLINE
			,TOP_RXNORM.MEDICATION_ID
			,MIN(CONCEPT_CODE) AS CONCEPT_CODE
			,CONCEPT_CLASS_ID
			,THEORDER
	
		FROM {{ref('TOP_RXNORM_HSP')}} AS TOP_RXNORM
	
		GROUP BY MEDICATION_ID
			,CONCEPT_CLASS_ID
			,THEORDER
			
	    QUALIFY ROW_NUMBER() OVER (PARTITION BY TOP_RXNORM.MEDICATION_ID ORDER BY THEORDER, FIRSTLINE) = 1

		) X
		ON X.CONCEPT_CODE = TOP_RXNORM.CONCEPT_CODE
			AND X.MEDICATION_ID = TOP_RXNORM.MEDICATION_ID

WHERE DRUG_EXPOSURE_CLARITYHOSP_RXNORM.ORDER_START_TIME IS NOT NULL
