--SPECIMEN 
{{ config(materialized = 'table') }} 

SELECT DISTINCT SEQ_SPECIMEN.NEXTVAL AS SPECIMEN_ID
	, SUBSTRING(AOU_DRIVER.AOU_ID, 2, LEN(AOU_DRIVER.AOU_ID))::NUMBER(28,0)   AS PERSON_ID
    , COALESCE(SOURCE_TO_CONCEPT_MAP_SPECIMEN.TARGET_CONCEPT_ID, 0) AS SPECIMEN_CONCEPT_ID
	, 0 AS SPECIMEN_TYPE_CONCEPT_ID
	, COALESCE(SPEC_DTM_COLLECTED, SPEC_DTM_RECEIVED)::DATE AS SPECIMEN_DATE
	, COALESCE(SPEC_DTM_COLLECTED, SPEC_DTM_RECEIVED) AS SPECIMEN_DATETIME
	, SPECIMEN_SIZE AS QUANTITY -- MISSING FROM HSC_SPEC_INFO 
	, 0 AS UNIT_CONCEPT_ID -- MISSING FROM HSC_SPEC_INFO
	, COALESCE(SOURCE_TO_CONCEPT_MAP_ANATOMIC_SITE.TARGET_CONCEPT_ID, 0) AS ANATOMIC_SITE_CONCEPT_ID
	, 0 AS DISEASE_STATUS_CONCEPT_ID -- UNKNOWN
	, SPECIMEN_TYPE_C AS SPECIMEN_SOURCE_ID
	, ZC_SPECIMEN_TYPE_NAME AS SPECIMEN_SOURCE_VALUE
	, NULL AS UNIT_SOURCE_VALUE -- MISSING FROM HSC_SPEC_INFO
	, ZC_SPEC_SOURCE_NAME AS ANATOMIC_SITE_SOURCE_VALUE
	, NULL AS DISEASE_STATUS_SOURCE_VALUE -- UNKNOWN
	, 'SPECIMEN--CLARITYHOSP--ALL' AS ETL_MODULE

FROM  {{ref('SPECIMEN_CLARITY_ALL')}} AS SPECIMEN_CLARITY_ALL

	INNER JOIN  {{ref('AOU_DRIVER')}} AS AOU_DRIVER  
    	ON AOU_DRIVER.EPIC_PAT_ID = SPECIMEN_CLARITY_ALL.PAT_ID 

    ------- SOURCE TO CONCEPT MAPPINGS BEGIN---------
    LEFT JOIN   {{ source('CDM','SOURCE_TO_CONCEPT_MAP')}} AS   SOURCE_TO_CONCEPT_MAP_SPECIMEN
        ON SPECIMEN_TYPE_C::VARCHAR = SOURCE_TO_CONCEPT_MAP_SPECIMEN.SOURCE_CODE
            AND UPPER(SOURCE_TO_CONCEPT_MAP_SPECIMEN.SOURCE_VOCABULARY_ID) = 'SH_SPECIMEN'

    LEFT JOIN   {{ source('CDM','SOURCE_TO_CONCEPT_MAP')}} AS  SOURCE_TO_CONCEPT_MAP_ANATOMIC_SITE
        ON SPEC_SOURCE_C::VARCHAR = SOURCE_TO_CONCEPT_MAP_ANATOMIC_SITE.SOURCE_CODE
            AND UPPER(SOURCE_TO_CONCEPT_MAP_ANATOMIC_SITE.SOURCE_VOCABULARY_ID) = 'SH_ANATOMIC_SITE'
    ------- SOURCE TO CONCEPT MAPPINGS END ---------