--DEVICE_EXPOSURE

{{ config(materialized = 'table') }} 

SELECT
    DISTINCT SEQ_DEVICE_EXPOSURE.NEXTVAL AS DEVICE_EXPOSURE_ID
    , A.*
FROM
(SELECT *
FROM
     {{ref('V_DEVICE_EXPOSURE_HSP_BLOOD')}} AS V_DEVICE_EXPOSURE_HSP_BLOOD    
UNION ALL
SELECT *
FROM 
     {{ref('V_DEVICE_EXPOSURE_HSP_LDA')}} AS V_DEVICE_EXPOSURE_HSP_LDA 
UNION ALL
SELECT *
FROM 
     {{ref('V_DEVICE_EXPOSURE_ANES_LDA')}} AS V_DEVICE_EXPOSURE_ANES_LDA ) A