--DEVICE_EXPOSURE

{{ config(materialized = 'table') }} 

SELECT DISTINCT
     SEQ_DEVICE_EXPOSURE.NEXTVAL::NUMBER(28,0)    AS DEVICE_EXPOSURE_ID
    , PERSON_ID::NUMBER(28,0)                     AS PERSON_ID 
    , DEVICE_CONCEPT_ID::NUMBER(28,0)             AS DEVICE_CONCEPT_ID 
    , DEVICE_EXPOSURE_START_DATE::DATE            AS DEVICE_EXPOSURE_START_DATE
    , DEVICE_EXPOSURE_START_DATETIME::DATETIME    AS DEVICE_EXPOSURE_START_DATETIME
    , DEVICE_EXPOSURE_END_DATE::DATE              AS DEVICE_EXPOSURE_END_DATE
    , DEVICE_EXPOSURE_END_DATETIME::DATETIME      AS DEVICE_EXPOSURE_END_DATETIME
    , DEVICE_TYPE_CONCEPT_ID::NUMBER(28,0)        AS DEVICE_TYPE_CONCEPT_ID 
    , UNIQUE_DEVICE_ID::VARCHAR(50)               AS UNIQUE_DEVICE_ID 
    , QUANTITY::NUMBER(28,0)                      AS QUANTITY 
    , PROVIDER_ID::NUMBER(28,0)                   AS PROVIDER_ID 
    , VISIT_OCCURRENCE_ID::NUMBER(28,0)           AS VISIT_OCCURRENCE_ID 
    , VISIT_DETAIL_ID::NUMBER(28,0)               AS VISIT_DETAIL_ID 
    , DEVICE_SOURCE_VALUE::VARCHAR(50)            AS DEVICE_SOURCE_VALUE
    , DEVICE_SOURCE_CONCEPT_ID::NUMBER(28,0)      AS DEVICE_SOURCE_CONCEPT_ID 
    , ETL_MODULE::VARCHAR(100)                    AS ETL_MODULE
    , VISIT_SOURCE_VALUE::VARCHAR(50)             AS VISIT_SOURCE_VALUE
FROM
(SELECT *
FROM
     {{ref('V_DEVICE_EXPOSURE_HSP_BLOOD')}} AS V_DEVICE_EXPOSURE_HSP_BLOOD    
UNION ALL
SELECT *
FROM 
     {{ref('V_DEVICE_EXPOSURE_HSP_LDA')}} AS V_DEVICE_EXPOSURE_HSP_LDA 
UNION ALL
SELECT *
FROM 
     {{ref('V_DEVICE_EXPOSURE_ANES_LDA')}} AS V_DEVICE_EXPOSURE_ANES_LDA ) A