--V_CARE_SITE_ALL

{{ config(materialized='view') }}

SELECT DISTINCT POS_ID AS CARE_SITE_ID
    , POS_NAME AS CARE_SITE_NAME
    , COALESCE(SOURCE_TO_CONCEPT_MAP_POS.TARGET_CONCEPT_ID, 0) AS PLACE_OF_SERVICE_CONCEPT_ID
    , LOCATION_ID AS LOCATION_ID
    , LEFT(CAST(POS_ID AS VARCHAR) || ':' || POS_NAME, 50) AS CARE_SITE_SOURCE_VALUE
    , LEFT(POS_TYPE,50) AS PLACE_OF_SERVICE_SOURCE_VALUE
    
FROM {{ ref('CARE_SITE_CLARITY_ALL')}} AS CARE_SITE_CLARITY_ALL   
	LEFT JOIN {{ ref('LOCATION')}}	 as LOCATION --SH_OMOP_DB_PROD.CDM.location 
		ON LOCATION.LOCATION_SOURCE_VALUE = LEFT(COALESCE(CARE_SITE_CLARITY_ALL.ADDRESS_LINE_1, '') 
    										|| COALESCE(CARE_SITE_CLARITY_ALL.ADDRESS_LINE_2, '') 
   									        || COALESCE(CARE_SITE_CLARITY_ALL.CITY, '') 
    										|| COALESCE(LEFT(CARE_SITE_CLARITY_ALL.STATE_ABBR, 2), '') 
    										|| COALESCE(CARE_SITE_CLARITY_ALL.ZIP, '') 
    										|| COALESCE(CARE_SITE_CLARITY_ALL.COUNTY_C, ''), 50)
  LEFT JOIN {{ source('CDM','SOURCE_TO_CONCEPT_MAP')}}	AS SOURCE_TO_CONCEPT_MAP_POS
      ON SOURCE_TO_CONCEPT_MAP_POS.SOURCE_CODE = CARE_SITE_CLARITY_ALL.POS_TYPE
          AND SOURCE_TO_CONCEPT_MAP_POS.SOURCE_VOCABULARY_ID IN ('sh_pos')



