 --SPECIMEN

{{ config(materialized='table') }}

SELECT DISTINCT 
      SEQ_SPECIMEN.NEXTVAL::NUMBER(28,0)        AS SPECIMEN_ID
    , PERSON_ID::NUMBER(28,0)                   AS PERSON_ID 
    , SPECIMEN_CONCEPT_ID::NUMBER(28,0)         AS SPECIMEN_CONCEPT_ID 
    , SPECIMEN_TYPE_CONCEPT_ID::NUMBER(28,0)    AS SPECIMEN_TYPE_CONCEPT_ID 
    , SPECIMEN_DATE::DATE                       AS SPECIMEN_DATE
    , SPECIMEN_DATETIME::DATETIME               AS SPECIMEN_DATETIME
    , QUANTITY::FLOAT                           AS QUANTITY
    , UNIT_CONCEPT_ID::NUMBER(28,0)             AS UNIT_CONCEPT_ID 
    , ANATOMIC_SITE_CONCEPT_ID::NUMBER(28,0)    AS ANATOMIC_SITE_CONCEPT_ID 
    , DISEASE_STATUS_CONCEPT_ID::NUMBER(28,0)   AS DISEASE_STATUS_CONCEPT_ID 
    , SPECIMEN_SOURCE_ID::NUMBER(28,0)          AS SPECIMEN_SOURCE_ID 
    , SPECIMEN_SOURCE_VALUE::VARCHAR(50)        AS SPECIMEN_SOURCE_VALUE
    , UNIT_SOURCE_VALUE::VARCHAR(50)            AS UNIT_SOURCE_VALUE
    , ANATOMIC_SITE_SOURCE_VALUE::VARCHAR(50)   AS ANATOMIC_SITE_SOURCE_VALUE
    , DISEASE_STATUS_SOURCE_VALUE::VARCHAR(50)  AS DISEASE_STATUS_SOURCE_VALUE
    , ETL_MODULE::VARCHAR(100)                  AS ETL_MODULE
FROM 	
 {{ref('V_SPECIMEN_ALL')}} 