--MEASUREMENT_CLARITYHOSP_LOINC

SELECT DISTINCT
	 PAT_ENC_HSP.PERSON_ID
	,PAT_ENC_HSP.AOU_ID
	,ORDER_PROC_2.SPECIMN_TAKEN_TIME
	,ORDER_PROC.ORDER_TIME
	,ORD_VALUE
	,ORDER_RESULTS.REFERENCE_LOW
	,ORDER_RESULTS.REFERENCE_HIGH
	,LNC_DB_MAIN.LNC_CODE
	,LNC_DB_MAIN.LNC_COMPON
	,LNC_DB_MAIN.RECORD_ID
	,ORDER_RESULTS.REFERENCE_UNIT
	,ORDER_PROC.AUTHRZING_PROV_ID
	,AUTH_PROVIDER.PROV_NAME AS AUTH_PROVIDER_NAME
	,AUTH_PROVIDER.PROV_TYPE AS AUTH_PROVIDER_TYPE

	,PAT_ENC_HSP.BILL_ATTEND_PROV_ID
	,ATTEND_PROVIDER.PROV_NAME AS ATTEND_PROVIDER_NAME
	,ATTEND_PROVIDER.PROV_TYPE AS ATTEND_PROVIDER_TYPE

	,PAT_ENC_HSP.PAT_ID
	,PAT_ENC_HSP.PAT_ENC_CSN_ID
	,ORDER_PROC.ORDER_PROC_ID
	,ORDER_RESULTS.COMPON_LNC_ID
	,ORDER_RESULTS.RESULT_FLAG_C
	,ZC_RESULT_FLAG.NAME AS ZC_RESULT_FLAG_NAME
	,ORDER_RESULTS.RESULT_STATUS_C
	,ZC_RESULT_STATUS.NAME AS ZC_RESULT_STATUS_NAME
	,ORDER_PROC.ORDER_STATUS_C
	,ZC_ORDER_STATUS.NAME AS ZC_ORDER_STATUS_NAME
	,'PULL_MEASUREMENT--CLARITYHOSP--LOINC' AS ETL_MODULE

FROM {{ref('VISIT_OCCURRENCE_CLARITYHOSP_ALL')}} AS PAT_ENC_HSP

{# INNER JOIN SH_OMOP_DB_PROD.CDM.AOU_DRIVER
	ON PAT_ENC_HSP.PAT_ID = AOU_DRIVER.EPIC_PAT_ID #}

INNER JOIN {{ source('CLARITY','ORDER_PROC')}} AS ORDER_PROC
	ON ORDER_PROC.PAT_ENC_CSN_ID = PAT_ENC_HSP.PAT_ENC_CSN_ID

{# INNER JOIN SH_OMOP_DB_PROD.CDM.VISIT_OCCURRENCE
	ON ORDER_PROC.PAT_ENC_CSN_ID = VISIT_OCCURRENCE.VISIT_SOURCE_VALUE #}

INNER JOIN {{ source('CLARITY','ORDER_PROC_2')}} AS ORDER_PROC_2
	ON ORDER_PROC.ORDER_PROC_ID = ORDER_PROC_2.ORDER_PROC_ID

INNER JOIN {{ source('CLARITY','ORDER_RESULTS')}} AS ORDER_RESULTS
	ON ORDER_PROC.ORDER_PROC_ID = ORDER_RESULTS.ORDER_PROC_ID

	LEFT JOIN {{ source('CLARITY','CLARITY_SER')}} AS AUTH_PROVIDER
		ON ORDER_PROC.AUTHRZING_PROV_ID = AUTH_PROVIDER.PROV_ID

	LEFT JOIN {{ source('CLARITY','CLARITY_SER')}} AS ATTEND_PROVIDER
		ON PAT_ENC_HSP.BILL_ATTEND_PROV_ID = ATTEND_PROVIDER.PROV_ID

INNER JOIN {{ source('CLARITY','LNC_DB_MAIN')}} AS LNC_DB_MAIN
	ON ORDER_RESULTS.COMPON_LNC_ID = LNC_DB_MAIN.RECORD_ID

LEFT JOIN {{ source('CLARITY','ZC_RESULT_FLAG')}} AS ZC_RESULT_FLAG
	ON ORDER_RESULTS.RESULT_FLAG_C = ZC_RESULT_FLAG.RESULT_FLAG_C

LEFT JOIN {{ source('CLARITY','ZC_RESULT_STATUS')}} AS ZC_RESULT_STATUS
	ON ORDER_RESULTS.RESULT_STATUS_C = ZC_RESULT_STATUS.RESULT_STATUS_C

LEFT JOIN {{ source('CLARITY','ZC_ORDER_STATUS')}} AS ZC_ORDER_STATUS
	ON ORDER_PROC.ORDER_STATUS_C = ZC_ORDER_STATUS.ORDER_STATUS_C

WHERE (ORDER_PROC.ORDER_STATUS_C <> 4) 