
version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
  
  - name: location_clarity_all 
    description: "1a_pull_location_531"
    columns:
      - name: ADDRESS_1
      - name: ADDRESS_2
      - name: CITY
      - name: COUNTY
      - name: LOCATION_SOURCE_VALUE
      - name: STATE
      - name: ZIP
