--DEATH
{{ config(materialized = 'table') }}

SELECT  PERSON_ID
      ,DEATH_DATE
      ,DEATH_DATETIME
      ,32817 AS DEATH_TYPE_CONCEPT_ID -- FROM EHR
      ,0 AS CAUSE_CONCEPT_ID
      ,NULL AS CAUSE_SOURCE_VALUE
      ,0 AS CAUSE_SOURCE_CONCEPT_ID
  FROM  {{ref('DEATH_CLARITY_ALL')}} AS DEATH_CLARITY_ALL