select 'HNO_INFO' as Clarity_Table, count(*) as P02  from  EpicClarity.dbo.HNO_INFO
UNION select 'ALLERGY' , count(*) from  EpicClarity.dbo.ALLERGY
UNION select 'AN_HSB_LINK_INFO', count(*) from  EpicClarity.dbo.AN_HSB_LINK_INFO
UNION select 'AP_SPECIMEN_DESC', count(*) from  EpicClarity.dbo.AP_SPECIMEN_DESC
UNION select 'BLOOD_ADMIN_INFO', count(*) from  EpicClarity.dbo.BLOOD_ADMIN_INFO
UNION select 'CL_ELG', count(*) from  EpicClarity.dbo.CL_ELG
UNION select 'CLARITY_DEP', count(*) from  EpicClarity.dbo.CLARITY_DEP
UNION select 'CLARITY_EAP', count(*) from  EpicClarity.dbo.CLARITY_EAP
UNION select 'CLARITY_EDG', count(*) from  EpicClarity.dbo.CLARITY_EDG
UNION select 'CLARITY_LOC', count(*) from  EpicClarity.dbo.CLARITY_LOC
UNION select 'CLARITY_MEDICATION', count(*) from  EpicClarity.dbo.CLARITY_MEDICATION
UNION select 'CLARITY_MOD', count(*) from  EpicClarity.dbo.CLARITY_MOD
UNION select 'CLARITY_POS', count(*) from  EpicClarity.dbo.CLARITY_POS
UNION select 'CLARITY_PRC', count(*) from  EpicClarity.dbo.CLARITY_PRC
UNION select 'CLARITY_SER', count(*) from  EpicClarity.dbo.CLARITY_SER
UNION select 'CLARITY_SER_2', count(*) from  EpicClarity.dbo.CLARITY_SER_2 
UNION select 'CONCEPT_MAPPED', count(*) from  EpicClarity.dbo.CONCEPT_MAPPED
UNION select 'D_PROV_PRIMARY_HIERARCHY', count(*) from  EpicClarity.dbo.D_PROV_PRIMARY_HIERARCHY
UNION select 'EDG_CURRENT_ICD10', count(*) from  EpicClarity.dbo.EDG_CURRENT_ICD10
UNION select 'EDG_CURRENT_ICD9', count(*) from  EpicClarity.dbo.EDG_CURRENT_ICD9
UNION select 'EXTERNAL_CNCPT_MAP', count(*) from  EpicClarity.dbo.EXTERNAL_CNCPT_MAP
UNION select 'F_AN_RECORD_SUMMARY', count(*) from  EpicClarity.dbo.F_AN_RECORD_SUMMARY

UNION select 'HNO_NOTE_TEXT', count(*) from  EpicClarity.dbo.HNO_NOTE_TEXT
UNION select 'HSC_SPEC_INFO', count(*) from  EpicClarity.dbo.HSC_SPEC_INFO
UNION select 'HSP_ATND_PROV', count(*) from  EpicClarity.dbo.HSP_ATND_PROV
UNION select 'IDENTITY_ID', count(*) from  EpicClarity.dbo.IDENTITY_ID
UNION select 'IP_DATA_STORE', count(*) from  EpicClarity.dbo.IP_DATA_STORE
UNION select 'IP_FLO_GP_DATA', count(*) from  EpicClarity.dbo.IP_FLO_GP_DATA
UNION select 'IP_FLWSHT_MEAS', count_big(*) from  EpicClarity.dbo.IP_FLWSHT_MEAS
UNION select 'IP_FLWSHT_REC', count(*) from  EpicClarity.dbo.IP_FLWSHT_REC
UNION select 'IP_LDA_NOADDSINGLE', count(*) from  EpicClarity.dbo.IP_LDA_NOADDSINGLE
UNION select 'LINKED_CHARGEABLES', count(*) from  EpicClarity.dbo.LINKED_CHARGEABLES
UNION select 'LINKED_PERFORMABLE', count(*) from  EpicClarity.dbo.LINKED_PERFORMABLE
UNION select 'LNC_DB_MAIN', count(*) from  EpicClarity.dbo.LNC_DB_MAIN
UNION select 'MAR_ADMIN_INFO', count(*) from  EpicClarity.dbo.MAR_ADMIN_INFO
UNION select 'NOTE_ENC_INFO', count(*) from  EpicClarity.dbo.NOTE_ENC_INFO
UNION select 'OR_IMP', count(*) from  EpicClarity.dbo.OR_IMP
UNION select 'OR_IMP_IMPLANT', count(*) from  EpicClarity.dbo.OR_IMP_IMPLANT
UNION select 'OR_LOG', count(*) from  EpicClarity.dbo.OR_LOG
UNION select 'OR_LOG_ALL_PROC', count(*) from  EpicClarity.dbo.OR_LOG_ALL_PROC
UNION select 'OR_LOG_ALL_SURG', count(*) from  EpicClarity.dbo.OR_LOG_ALL_SURG
UNION select 'OR_LOG_VIRTUAL', count(*) from  EpicClarity.dbo.OR_LOG_VIRTUAL
UNION select 'OR_SER_SURG_SRVC', count(*) from  EpicClarity.dbo.OR_SER_SURG_SRVC
UNION select 'OR_SPLY_EXT_IDS', count(*) from  EpicClarity.dbo.OR_SPLY_EXT_IDS
UNION select 'ORD_BLOOD_ADMIN', count(*) from  EpicClarity.dbo.ORD_BLOOD_ADMIN
UNION select 'ORDER_DX_PROC', count(*) from  EpicClarity.dbo.ORDER_DX_PROC
UNION select 'ORDER_INSTANTIATED', count(*) from  EpicClarity.dbo.ORDER_INSTANTIATED
UNION select 'ORDER_MED', count(*) from  EpicClarity.dbo.ORDER_MED
UNION select 'ORDER_PROC', count(*) from  EpicClarity.dbo.ORDER_PROC
UNION select 'ORDER_PROC_2', count(*) from  EpicClarity.dbo.ORDER_PROC_2
UNION select 'ORDER_RESULTS', count(*) from  EpicClarity.dbo.ORDER_RESULTS
UNION select 'PAT_ALLERGIES', count(*) from  EpicClarity.dbo.PAT_ALLERGIES
UNION select 'PAT_ENC', count(*) from  EpicClarity.dbo.PAT_ENC
UNION select 'PAT_ENC_2', count(*) from  EpicClarity.dbo.PAT_ENC_2
UNION select 'PAT_ENC_DX', count(*) from  EpicClarity.dbo.PAT_ENC_DX
UNION select 'PAT_ENC_HSP', count(*) from  EpicClarity.dbo.PAT_ENC_HSP
UNION select 'PAT_OR_ADM_LINK', count(*) from  EpicClarity.dbo.PAT_OR_ADM_LINK
UNION select 'PATIENT', count(*) from  EpicClarity.dbo.PATIENT
UNION select 'PATIENT_RACE', count(*) from  EpicClarity.dbo.PATIENT_RACE
UNION select 'RXNORM_CODES', count(*) from  EpicClarity.dbo.RXNORM_CODES
UNION select 'SNOMED_CONCEPT', count(*) from  EpicClarity.dbo.SNOMED_CONCEPT
UNION select 'SNOMED_HIERARCHY', count(*) from  EpicClarity.dbo.SNOMED_HIERARCHY
UNION select 'SOCIAL_HX', count(*) from  EpicClarity.dbo.SOCIAL_HX
UNION select 'SPEC_DB_MAIN', count(*) from  EpicClarity.dbo.SPEC_DB_MAIN
UNION select 'ZC_ADM_SOURCE', count(*) from  EpicClarity.dbo.ZC_ADM_SOURCE
UNION select 'ZC_ADMIN_ROUTE', count(*) from  EpicClarity.dbo.ZC_ADMIN_ROUTE
UNION select 'ZC_APPT_STATUS', count(*) from  EpicClarity.dbo.ZC_APPT_STATUS
UNION select 'ZC_CALCULATED_ENC_STAT', count(*) from  EpicClarity.dbo.ZC_CALCULATED_ENC_STAT
UNION select 'ZC_COUNTY', count(*) from  EpicClarity.dbo.ZC_COUNTY
UNION select 'ZC_DISCH_DISP', count(*) from  EpicClarity.dbo.ZC_DISCH_DISP
UNION select 'ZC_DISP_ENC_TYPE', count(*) from  EpicClarity.dbo.ZC_DISP_ENC_TYPE
UNION select 'ZC_ETHNIC_GROUP', count(*) from  EpicClarity.dbo.ZC_ETHNIC_GROUP
UNION select 'ZC_LAB_STATUS', count(*) from  EpicClarity.dbo.ZC_LAB_STATUS
UNION select 'ZC_MAR_RSLT', count(*) from  EpicClarity.dbo.ZC_MAR_RSLT
UNION select 'ZC_MAR_RSN', count(*) from  EpicClarity.dbo.ZC_MAR_RSN
UNION select 'ZC_MED_UNIT', count(*) from  EpicClarity.dbo.ZC_MED_UNIT
UNION select 'ZC_NOTE_TYPE_IP', count(*) from  EpicClarity.dbo.ZC_NOTE_TYPE_IP
UNION select 'ZC_OR_IMP_STATUS', count(*) from  EpicClarity.dbo.ZC_OR_IMP_STATUS
UNION select 'ZC_OR_MANUFACTURER', count(*) from  EpicClarity.dbo.ZC_OR_MANUFACTURER
UNION select 'ZC_OR_SERVICE', count(*) from  EpicClarity.dbo.ZC_OR_SERVICE
UNION select 'ZC_OR_STATUS', count(*) from  EpicClarity.dbo.ZC_OR_STATUS
UNION select 'ZC_ORDER_CLASS', count(*) from  EpicClarity.dbo.ZC_ORDER_CLASS
UNION select 'ZC_ORDER_STATUS', count(*) from  EpicClarity.dbo.ZC_ORDER_STATUS
UNION select 'ZC_ORDER_TYPE', count(*) from  EpicClarity.dbo.ZC_ORDER_TYPE
UNION select 'ZC_PAT_CLASS', count(*) from  EpicClarity.dbo.ZC_PAT_CLASS
UNION select 'ZC_PAT_STATUS', count(*) from  EpicClarity.dbo.ZC_PAT_STATUS
UNION select 'ZC_PATIENT_RACE', count(*) from  EpicClarity.dbo.ZC_PATIENT_RACE
UNION select 'ZC_RESULT_FLAG', count(*) from  EpicClarity.dbo.ZC_RESULT_FLAG
UNION select 'ZC_RESULT_STATUS', count(*) from  EpicClarity.dbo.ZC_RESULT_STATUS
UNION select 'ZC_RSN_FOR_DISCON', count(*) from  EpicClarity.dbo.ZC_RSN_FOR_DISCON
UNION select 'ZC_RXNORM_TERM_TYPE', count(*) from  EpicClarity.dbo.ZC_RXNORM_TERM_TYPE
UNION select 'ZC_SEX', count(*) from  EpicClarity.dbo.ZC_SEX
UNION select 'ZC_SMOKING_TOB_USE', count(*) from  EpicClarity.dbo.ZC_SMOKING_TOB_USE
UNION select 'ZC_SPEC_SOURCE', count(*) from  EpicClarity.dbo.ZC_SPEC_SOURCE
UNION select 'ZC_SPECIMEN_TYPE', count(*) from  EpicClarity.dbo.ZC_SPECIMEN_TYPE
UNION select 'ZC_SPECIMEN_UNIT', count(*) from  EpicClarity.dbo.ZC_SPECIMEN_UNIT
UNION select 'ZC_STATE', count(*) from  EpicClarity.dbo.ZC_STATE
UNION select 'ZC_VAL_TYPE', count(*) from  EpicClarity.dbo.ZC_VAL_TYPE
UNION select 'ZC_SPECIALTY', count(*) from  EpicClarity.dbo.ZC_SPECIALTY
UNION select 'ZC_ED_DISPOSITION', count(*) from  EpicClarity.dbo.ZC_ED_DISPOSITION
order by Clarity_Table
