select 'HNO_INFO', count(*) from SH_CLINICAL_DB_PROD.EPIC_CLARITY_LZ.HNO_INFO
union all
select 'ZC_NOTE_TYPE_IP', count(*) from SH_CLINICAL_DB_PROD.EPIC_CLARITY_LZ.ZC_NOTE_TYPE_IP
union all
select 'NOTE_ENC_INFO', count(*) from SH_CLINICAL_DB_PROD.EPIC_CLARITY_LZ.NOTE_ENC_INFO
union all
select 'HNO_NOTE_TEXT', count(*) from SH_CLINICAL_DB_PROD.EPIC_CLARITY_LZ.HNO_NOTE_TEXT


SELECT ETL_MODULE, count(*)
FROM SH_OMOP_DB_PROD.CDM.note 
GROUP BY ETL_MODULE
order by ETL_Module;