--select 'ORDER_PROC', count(*) from SH_CLINICAL_DB_PROD.EPIC_CLARITY_LZ.ORDER_PROC
--union all
--select 'ORDER_INSTANTIATED', count(*) from SH_CLINICAL_DB_PROD.EPIC_CLARITY_LZ.ORDER_INSTANTIATED
--union all
--select 'ORDER_DX_PROC', count(*) from SH_CLINICAL_DB_PROD.EPIC_CLARITY_LZ.ORDER_DX_PROC
--union all
--select 'CLARITY_EAP', count(*) from SH_CLINICAL_DB_PROD.EPIC_CLARITY_LZ.CLARITY_EAP
--union all
--select 'LINKED_PERFORMABLE', count(*) from SH_CLINICAL_DB_PROD.EPIC_CLARITY_LZ.LINKED_PERFORMABLE
--union all
--select 'LINKED_CHARGEABLES', count(*) from SH_CLINICAL_DB_PROD.EPIC_CLARITY_LZ.LINKED_CHARGEABLES
--union all
--select 'CLARITY_MOD', count(*) from SH_CLINICAL_DB_PROD.EPIC_CLARITY_LZ.CLARITY_MOD
--union all
--select 'ZC_ORDER_STATUS', count(*) from SH_CLINICAL_DB_PROD.EPIC_CLARITY_LZ.ZC_ORDER_STATUS
--union all
--select 'ZC_LAB_STATUS', count(*) from SH_CLINICAL_DB_PROD.EPIC_CLARITY_LZ.ZC_LAB_STATUS
--union all
--select 'ZC_ORDER_CLASS', count(*) from SH_CLINICAL_DB_PROD.EPIC_CLARITY_LZ.ZC_ORDER_CLASS
--union all
--select 'ZC_ORDER_TYPE', count(*) from SH_CLINICAL_DB_PROD.EPIC_CLARITY_LZ.ZC_ORDER_TYPE
--union all
--select 'VISIT_OCCURRENCE_CLARITYAMB_ALL', count(*) from SH_OMOP_DB_PROD.OMOP_CLARITY.VISIT_OCCURRENCE_CLARITYAMB_ALL


select 'PROCEDURE_OCCURRENCE_ClarityAMB_CPT', count(*) from SH_OMOP_DB_PROD.OMOP_Clarity.PROCEDURE_OCCURRENCE_ClarityAMB_CPT
union all
select 'PROCEDURE_OCCURRENCE_ClarityANES_SNOMED', count(*) from SH_OMOP_DB_PROD.OMOP_Clarity.PROCEDURE_OCCURRENCE_ClarityANES_SNOMED  
union all
select 'PROCEDURE_OCCURRENCE_ClarityHSP_CPT', count(*) from SH_OMOP_DB_PROD.OMOP_Clarity.PROCEDURE_OCCURRENCE_ClarityHSP_CPT 
union all
select 'PROCEDURE_OCCURRENCE_ClaritySURG_CPT', count(*) from SH_OMOP_DB_PROD.OMOP_Clarity.PROCEDURE_OCCURRENCE_ClaritySURG_CPT

--SELECT ETL_MODULE, count(*)
--FROM cdm.measurement
--GROUP BY ETL_MODULE
--order by ETL_Module;
