--PROCEDURE_OCCURRENCE_CLARITYSURG_CPT

{{ config(materialized = 'view') }}

SELECT DISTINCT 
    SUBSTRING(AOU_DRIVER.AOU_ID, 2, LEN(AOU_DRIVER.AOU_ID)) AS PERSON_ID
    ,AOU_ID
    ,PAT_ENC_HSP.PAT_ENC_CSN_ID
    ,PAT_ENC_HSP.PAT_ID
    ,PAT_ENC_HSP.HSP_ACCOUNT_ID
    ,OR_LOG.INPATIENT_DATA_ID
    ,OR_LOG.SURGERY_DATE
    ,OR_LOG.SCHED_START_TIME
    ,OR_LOG.TOTAL_TIME_NEEDED
    ,OR_LOG_VIRTUAL.ACT_START_OTS_DTTM
    ,OR_LOG_VIRTUAL.ACT_END_OTS_DTTM
    ,COALESCE(OR_LOG_VIRTUAL.ACT_START_OTS_DTTM, OR_LOG.SCHED_START_TIME) AS CALC_START_TIME
    ,COALESCE(OR_LOG_VIRTUAL.ACT_END_OTS_DTTM, DATEADD(MINUTE, OR_LOG.TOTAL_TIME_NEEDED::INTEGER, OR_LOG.SCHED_START_TIME)) AS CALC_END_DTTM
    ,OR_LOG.PRIMARY_PHYS_ID
    ,OR_LOG_ALL_SURG.SURG_ID
    ,COALESCE(OR_LOG_ALL_SURG.SURG_ID, OR_LOG.PRIMARY_PHYS_ID) AS CALC_PERFORM_PHYS
    ,OR_LOG_ALL_PROC.OR_PROC_ID
    ,OR_LOG_ALL_PROC.ALL_PROC_CODE_ID
    ,OR_LOG_ALL_PROC.LINE
    ,OR_LOG_VIRTUAL.PRIMARY_PROC_ID
    ,T_CPT_CODES.PROC_CODE
    ,T_CPT_CODES.PROC_NAME
    ,OR_LOG.STATUS_C
    ,ZC_OR_STATUS.NAME AS ZC_ORDER_STATUS_NAME
    ,'PROCEDURE_OCCURRENCE--CLARITYSURG--CPT' AS ETL_MODULE


FROM {{ref('AOU_DRIVER')}} AS AOU_DRIVER

    INNER JOIN {{ source('CLARITY','PAT_ENC_HSP')}} AS PAT_ENC_HSP
        ON AOU_DRIVER.EPIC_PAT_ID = PAT_ENC_HSP.PAT_ID

    INNER JOIN {{ source('CLARITY','PAT_OR_ADM_LINK')}} AS PAT_OR_ADM_LINK
        ON PAT_ENC_HSP.PAT_ENC_CSN_ID = PAT_OR_ADM_LINK.OR_LINK_CSN

    INNER JOIN {{ source('CLARITY','OR_LOG')}} AS OR_LOG
        ON PAT_OR_ADM_LINK.LOG_ID = OR_LOG.LOG_ID

    INNER JOIN {{ source('CLARITY','OR_LOG_VIRTUAL')}} AS OR_LOG_VIRTUAL
        ON OR_LOG.LOG_ID = OR_LOG_VIRTUAL.LOG_ID

    INNER JOIN {{ source('CLARITY','OR_LOG_ALL_PROC')}} AS OR_LOG_ALL_PROC
        ON OR_LOG.LOG_ID = OR_LOG_ALL_PROC.LOG_ID

    LEFT JOIN {{ source('CLARITY','OR_LOG_ALL_SURG')}} AS OR_LOG_ALL_SURG
        ON OR_LOG.LOG_ID = OR_LOG_ALL_SURG.LOG_ID
            AND OR_LOG_ALL_PROC.LINE = OR_LOG_ALL_SURG.LINE

    LEFT JOIN {{ref('T_CPT_CODES')}} AS T_CPT_CODES
        ON OR_LOG_ALL_PROC.ALL_PROC_CODE_ID = T_CPT_CODES.PROC_ID

    LEFT JOIN {{ source('CLARITY','ZC_OR_STATUS')}} AS ZC_OR_STATUS
        ON OR_LOG.STATUS_C = ZC_OR_STATUS.STATUS_C

WHERE (OR_LOG.STATUS_C = 2)
    AND ALL_PROC_CODE_ID IS NOT NULL

ORDER BY PAT_ENC_HSP.PAT_ENC_CSN_ID
    ,OR_LOG_ALL_PROC.LINE

