--PROCEDURE_OCCURRENCE_CLARITYAMB_CPT 

{{ config(materialized = 'view') }}

SELECT  --NULL AS  PROCEDURE_OCCURRENCE_ID,
	SUBSTRING(PAT_ENC_AMB.AOU_ID, 2, LEN(PAT_ENC_AMB.AOU_ID)) AS PERSON_ID
	,PAT_ENC_AMB.AOU_ID
	,PAT_ENC_AMB.PAT_ID
	,PAT_ENC_AMB.PAT_ENC_CSN_ID
	,PAT_ENC_AMB.HSP_ACCOUNT_ID
	,PAT_ENC_AMB.IP_DOC_CONTACT_CSN
	,PAT_ENC_AMB.ENC_TYPE_C
	,PAT_ENC_AMB.ZC_DISP_ENC_TYPE_NAME
	,PAT_OR_ADM_LINK_CSN AS PAT_OR_ADM_LINK_PAT_ENC_CSN_ID
	,ORDER_PROC.INSTANTIATED_TIME AS OP_INSTANTIATED_TIME
	,ORDER_PROC.ORDER_TIME AS OP_ORDER_TIME
	,ORDER_PROC.PROC_START_TIME AS OP_PROC_START_TIME
	,ORDER_PROC.PROC_BGN_TIME AS OP_PROC_BGN_TIME
	,ORDER_PROC.PROC_END_TIME AS OP_PROC_END_TIME
	,ORDER_PROC_CHILD.ORDER_TIME AS OP_CHILD_ORDER_TIME
	,ORDER_PROC_CHILD.PROC_START_TIME AS OP_CHILD_START_TIME
	,ORDER_PROC_CHILD.INSTANTIATED_TIME AS OP_CHILD_INSTANTIATED_TIME
	,ORDER_PROC_CHILD.PROC_BGN_TIME AS OP_CHILD_PROC_BGN_TIME
	,ORDER_PROC_CHILD.PROC_END_TIME AS OP_CHILD_PROC_END_TIME
	,ORDER_PROC.MODIFIER1_ID
	,MODIFIER_NAME
	,ORDER_PROC.QUANTITY
	,ORDER_PROC.AUTHRZING_PROV_ID
	,ORDER_PROC.FUTURE_OR_STAND
	, ORDER_PROC.PROC_ID
	,ORDER_DX_PROC.LINE AS ORDER_DX_LINE
	,ORDER_DX_PROC.DX_ID AS ORDER_DX_ID
	,T_CPT_CODES.PROC_CODE
	,T_CPT_CODES.PROC_NAME
	,ORDER_PROC.ORDER_STATUS_C
	,ZC_ORDER_STATUS.NAME AS ZC_ORDER_STATUS_NAME
	, ORDER_PROC.ORDER_PROC_ID
	, ORDER_PROC.ORDER_TYPE_C
	, ZC_ORDER_TYPE.NAME AS ZC_ORDER_TYPE_NAME
	,ORDER_PROC.ORDER_CLASS_C
	,ZC_ORDER_CLASS.NAME AS ZC_ORDER_CLASS_NAME
	,ORDER_PROC.LAB_STATUS_C
	,ZC_LAB_STATUS.NAME AS ZC_LAB_STATUS_NAME

FROM SH_OMOP_DB_PROD.OMOP_CLARITY.VISIT_OCCURRENCE_CLARITYAMB_ALL AS PAT_ENC_AMB

	LEFT JOIN {{ source('CLARITY','ORDER_PROC')}} AS ORDER_PROC
		ON PAT_ENC_AMB.PAT_ENC_CSN_ID = ORDER_PROC.PAT_ENC_CSN_ID

	LEFT JOIN {{ source('CLARITY','ORDER_PROC')}} AS OP_CHILD
		ON PAT_ENC_AMB.PAT_ENC_CSN_ID = OP_CHILD.PAT_ENC_CSN_ID

	LEFT JOIN {{ source('CLARITY','ORDER_INSTANTIATED')}} AS ORDER_INSTANTIATED
		ON ORDER_PROC.ORDER_PROC_ID = ORDER_INSTANTIATED.ORDER_ID

	LEFT JOIN {{ source('CLARITY','ORDER_PROC')}}  AS ORDER_PROC_CHILD
		ON ORDER_INSTANTIATED.INSTNTD_ORDER_ID = ORDER_PROC_CHILD.ORDER_PROC_ID

	LEFT JOIN {{ source('CLARITY','ORDER_DX_PROC')}} AS ORDER_DX_PROC 
	   ON ORDER_PROC.ORDER_PROC_ID = ORDER_DX_PROC.ORDER_PROC_ID

	LEFT JOIN {{ref('T_CPT_CODES')}} AS T_CPT_CODES
		ON ORDER_PROC.PROC_ID = T_CPT_CODES.PROC_ID

	LEFT JOIN {{ source('CLARITY','CLARITY_MOD')}} AS CLARITY_MOD
		ON ORDER_PROC.MODIFIER1_ID = CLARITY_MOD.MODIFIER_ID

	LEFT JOIN {{ source('CLARITY','ZC_ORDER_STATUS')}} AS ZC_ORDER_STATUS 
	   ON ORDER_PROC.ORDER_STATUS_C = ZC_ORDER_STATUS.ORDER_STATUS_C
	   
	LEFT JOIN {{ source('CLARITY','ZC_LAB_STATUS')}} AS ZC_LAB_STATUS 
	   ON ORDER_PROC.LAB_STATUS_C = ZC_LAB_STATUS.LAB_STATUS_C
	   
	LEFT JOIN {{ source('CLARITY','ZC_ORDER_CLASS')}} AS 	ZC_ORDER_CLASS 
	   ON ORDER_PROC.ORDER_CLASS_C = ZC_ORDER_CLASS.ORDER_CLASS_C
	   
	LEFT JOIN {{ source('CLARITY','ZC_ORDER_TYPE')}} AS 	ZC_ORDER_TYPE	 
	   ON ORDER_PROC.ORDER_TYPE_C = ZC_ORDER_TYPE.ORDER_TYPE_C

WHERE  (
		PAT_ENC_AMB.CALCULATED_ENC_STAT_C = 2
		OR PAT_ENC_AMB.CALCULATED_ENC_STAT_C IS NULL
		)
	AND (
		PAT_ENC_AMB.APPT_STATUS_C = 2
		OR PAT_ENC_AMB.APPT_STATUS_C IS NULL
		)
	AND 
		ORDER_PROC.ORDER_STATUS_C = 5 -- COMPLETE

--ADDED 11/6/2020 TO REMOVE FUTURE OR STANDING ORDERS
	AND
		ORDER_PROC.LAB_STATUS_C = 3 -- FINAL		
