--PROCEDURE_OCCURRENCE_CLARITYHSP_CPT

{{ config(materialized = 'view') }}

SELECT  --NULL AS  PROCEDURE_OCCURRENCE_ID,
	SUBSTRING(AOU_DRIVER.AOU_ID, 2, LEN(AOU_DRIVER.AOU_ID)) AS PERSON_ID
	,AOU_ID
	,PAT_ENC_HSP.PAT_ENC_CSN_ID
	,PAT_ENC_HSP.HSP_ACCOUNT_ID
	,PAT_ENC_HSP.PAT_ID
	,ORDER_PROC.INSTANTIATED_TIME AS OP_INSTANTIATED_TIME
	,ORDER_PROC.ORDER_TIME AS OP_ORDER_TIME
	,ORDER_PROC.PROC_START_TIME AS OP_PROC_START_TIME
	,ORDER_PROC.PROC_BGN_TIME AS OP_PROC_BGN_TIME
	,ORDER_PROC.PROC_END_TIME AS OP_PROC_END_TIME
	,ORDER_PROC.MODIFIER1_ID
	,MODIFIER_NAME
	,ORDER_PROC.QUANTITY
	,ORDER_PROC.AUTHRZING_PROV_ID
	,ORDER_PROC.FUTURE_OR_STAND
	,ORDER_PROC.PROC_ID
	,ORDER_DX_PROC.LINE AS ORDER_DX_LINE
	,ORDER_DX_PROC.DX_ID AS ORDER_DX_ID
	,T_CPT_CODES.PROC_CODE
	,T_CPT_CODES.PROC_NAME
	,ORDER_PROC.ORDER_STATUS_C
	,ZC_ORDER_STATUS.NAME AS ZC_ORDER_STATUS_NAME
	, ORDER_PROC.ORDER_PROC_ID
	, ORDER_PROC.ORDER_TYPE_C
	, ZC_ORDER_TYPE.NAME AS ZC_ORDER_TYPE_NAME
	,ORDER_PROC.ORDER_CLASS_C
	,ZC_ORDER_CLASS.NAME AS ZC_ORDER_CLASS_NAME
	,ORDER_PROC.LAB_STATUS_C
	,ZC_LAB_STATUS.NAME AS ZC_LAB_STATUS_NAME
	,'PROCEDURE_OCCURRENCE--CLARITYHOSP--CPT' AS ETL_MODULE

FROM {{ref('AOU_DRIVER')}} AS AOU_DRIVER 

INNER JOIN {{ source('CLARITY','PAT_ENC_HSP')}} AS PAT_ENC_HSP
	ON AOU_DRIVER.EPIC_PAT_ID = PAT_ENC_HSP.PAT_ID

INNER JOIN {{ source('CLARITY','ORDER_PROC')}} AS ORDER_PROC
	ON PAT_ENC_HSP.PAT_ENC_CSN_ID = ORDER_PROC.PAT_ENC_CSN_ID

LEFT JOIN {{ source('CLARITY','ORDER_DX_PROC')}} AS ORDER_DX_PROC 
    ON ORDER_PROC.ORDER_PROC_ID = ORDER_DX_PROC.ORDER_PROC_ID

INNER JOIN {{ref('T_CPT_CODES')}} AS T_CPT_CODES
	ON ORDER_PROC.PROC_ID = T_CPT_CODES.PROC_ID

LEFT JOIN {{ source('CLARITY','ZC_ORDER_STATUS')}} AS ZC_ORDER_STATUS 
    ON ORDER_PROC.ORDER_STATUS_C = ZC_ORDER_STATUS.ORDER_STATUS_C
    
LEFT JOIN {{ source('CLARITY','ZC_LAB_STATUS')}} AS ZC_LAB_STATUS 
    ON ORDER_PROC.LAB_STATUS_C = ZC_LAB_STATUS.LAB_STATUS_C
    
LEFT JOIN {{ source('CLARITY','ZC_ORDER_CLASS')}} AS 	ZC_ORDER_CLASS 
    ON ORDER_PROC.ORDER_CLASS_C = ZC_ORDER_CLASS.ORDER_CLASS_C
    
LEFT JOIN {{ source('CLARITY','ZC_ORDER_TYPE')}} AS 	ZC_ORDER_TYPE	 
    ON ORDER_PROC.ORDER_TYPE_C = ZC_ORDER_TYPE.ORDER_TYPE_C

LEFT JOIN {{ source('CLARITY','CLARITY_MOD')}} AS CLARITY_MOD
	ON ORDER_PROC.MODIFIER1_ID = CLARITY_MOD.MODIFIER_ID


WHERE (	ORDER_PROC.ORDER_STATUS_C = 5) --COMPLETED

	-- ADDED 11/6/2020 TO REMOVE FUTURE OR STANDING ORDERS 
	AND ORDER_PROC.LAB_STATUS_C = 3 --FINAL
