DELETE FROM SH_OMOP_DB_PROD.CDM.AOU_PII;


INSERT INTO  SH_OMOP_DB_PROD.CDM.AOU_PII
	(CPI
      ,EPIC_PAT_ID
      ,AOU_ID
	  ,PID
      ,FIRSTNAME
      ,EPIC_FIRST_NAME
      ,AOU_FIRST_NAME
      ,LASTNAME
      ,EPIC_LAST_NAME
      ,AOU_LAST_NAME
      ,DOB
      ,EPIC_BIRTH_DATE
      ,AOU_BIRTH_DATE
      ,SEX
      ,EPIC_SEX
      ,AOU_SEX
      ,ADDRESS
      ,EPIC_ADDRESS
      ,AOU_ADDRESS
      ,"PHONE NUMBER"
      ,EPIC_PHONE
      ,AOU_PHONE
      ,EMAIL
      ,EPIC_EMAIL
      ,AOU_EMAIL
      ,"MANUAL VALIDATION")

SELECT distinct CPI
      ,AOU_DRIVER_PROD.EPIC_PAT_ID
      ,AOU_ID

	,SUBSTRING(AOU_DRIVER_PROD.AOU_ID, 2, LEN(AOU_DRIVER_PROD.AOU_ID)) AS PID
	,CASE 
		WHEN REPLACE(PAT_FIRST_NAME, ' ', '') LIKE REPLACE(FIRST_NAME, ' ', '') || '%'
			OR REPLACE(FIRST_NAME, ' ', '') LIKE REPLACE(PAT_FIRST_NAME, ' ', '') || '%'
			THEN 1
		ELSE 0
		END AS FIRSTNAME
	,PAT_FIRST_NAME AS EPIC_FIRST_NAME
	,FIRST_NAME AS AOU_FIRST_NAME
	,CASE 
		WHEN REPLACE(REPLACE(REPLACE(PAT_LAST_NAME, ' ', ''), '-', ''), '''', '') 
			LIKE REPLACE(REPLACE(REPLACE(AOU_DRIVER_PROD.LAST_NAME, ' ', ''), '-', ''), '''', '') || '%'
			OR REPLACE(REPLACE(REPLACE(AOU_DRIVER_PROD.LAST_NAME, ' ', ''), '-', ''), '''', '') 
			LIKE REPLACE(REPLACE(REPLACE(PAT_LAST_NAME, ' ', ''), '-', ''), '''', '') || '%'
			THEN 1
		ELSE 0
		END AS LASTNAME
	,PATIENT.PAT_LAST_NAME AS EPIC_LAST_NAME
	,AOU_DRIVER_PROD.LAST_NAME AS AOU_LAST_NAME
	,CASE 
--        WHEN CAST( BIRTH_DATE AS DATE) = CAST(DATE_OF_BIRTH AS DATE)       
        WHEN BIRTH_DATE::DATE = DATE_OF_BIRTH::DATE
			THEN 1
		ELSE 0
		END AS DOB
	,BIRTH_DATE AS EPIC_BIRTH_DATE
	,DATE_OF_BIRTH AS AOU_BIRTH_DATE
	,CASE 
		WHEN ZC_SEX.NAME = AOU_DRIVER_PROD.SEX
			THEN 1
		ELSE 0
		END AS SEX
	,ZC_SEX.NAME AS EPIC_SEX
	,AOU_DRIVER_PROD.SEX AS AOU_SEX
	,CASE 
		WHEN REPLACE(REPLACE(REPLACE(ADD_LINE_1, ' ', ''), '.', ''), ',', '') 
			LIKE REPLACE(REPLACE(REPLACE(STREET_ADDRESS, ' ', ''), '.', ''), ',', '') || '%'
			OR REPLACE(REPLACE(REPLACE(STREET_ADDRESS, ' ', ''), '.', ''), ',', '') 
			LIKE REPLACE(REPLACE(REPLACE(ADD_LINE_1, ' ', ''), '.', ''), ',', '') || '%'
			THEN 1
		ELSE 0
		END AS ADDRESS
	,ADD_LINE_1 AS EPIC_ADDRESS
	,STREET_ADDRESS AS AOU_ADDRESS
	,CASE 
		WHEN REPLACE(HOME_PHONE, '-', '') = REPLACE(REPLACE(REPLACE(REPLACE(AOU_DRIVER_PROD.PHONE, '-', ''), ')', ''), '(', ''), ' ', '')
			THEN 1
		ELSE 0
		END AS "PHONE NUMBER"
	,HOME_PHONE AS EPIC_PHONE
	,PHONE AS AOU_PHONE
	,CASE 
		WHEN REPLACE(EMAIL_ADDRESS, ',', '') = REPLACE(AOU_DRIVER_PROD.EMAIL, ',', '')
			THEN 1
		ELSE 0
		END AS EMAIL
	,EMAIL_ADDRESS AS EPIC_EMAIL
	,REPLACE(EMAIL, ',', '') AS AOU_EMAIL
	,EHR_EXPORT_PT_MATCH_PASS AS "MANUAL VALIDATION"

--INTO OMOP.AOU_PII

FROM SH_CLINICAL_DB_PROD.EPIC_CLARITY_LZ.PATIENT

	INNER JOIN SH_OMOP_DB_PROD.CDM.AOU_DRIVER_PROD
		ON PATIENT.PAT_ID = AOU_DRIVER_PROD.EPIC_PAT_ID

	--INNER JOIN SH_OMOP_DB_PROD.CDM.PERSON
	--	ON SUBSTRING(AOU_DRIVER_PROD.AOU_ID, 2, LEN(AOU_DRIVER_PROD.AOU_ID)) = PERSON.PERSON_ID

	INNER JOIN SH_CLINICAL_DB_PROD.EPIC_CLARITY_LZ.ZC_SEX
		ON PATIENT.SEX_C = ZC_SEX.RCPT_MEM_SEX_C;


-----------------------------------

DELETE FROM SH_OMOP_DB_PROD.CDM.AOU_PII_VALIDATION WHERE MANUAL_VALIDATION = 'NO';

----------------------------------

INSERT INTO SH_OMOP_DB_PROD.CDM.AOU_PII_VALIDATION (
	 PERSON_ID
	,FIRST_NAME
	,LAST_NAME
	,DOB
	,SEX
	,ADDRESS
	,PHONE_NUMBER
	,EMAIL
	,MANUAL_VALIDATION
	,ALGORITHM_VALIDATION
	)

SELECT PID
	,CASE 
		WHEN FIRSTNAME = 1
			THEN 'MATCH'
		ELSE 'NOMATCH'
		END AS FIRSTNAME
	,CASE 
		WHEN LASTNAME = 1
			THEN 'MATCH'
		ELSE 'NOMATCH'
		END AS LASTNAME
	,CASE 
		WHEN DOB = 1
			THEN 'MATCH'
		ELSE 'NOMATCH'
		END AS DOB
	,CASE 
		WHEN SEX = 1
			THEN 'MATCH'
		ELSE 'NOMATCH'
		END AS SEX
	,CASE 
		WHEN ADDRESS = 1
			THEN 'MATCH'
		ELSE 'NOMATCH'
		END AS ADDRESS
	,CASE 
		WHEN "PHONE NUMBER" = 1
			THEN 'MATCH'
		ELSE 'NOMATCH'
		END AS "PHONE NUMBER"
	,CASE 
		WHEN EMAIL = 1
			THEN 'MATCH'
		ELSE 'NOMATCH'
		END AS EMAIL
	,CASE 
		WHEN "MANUAL VALIDATION" = 1
			THEN 'YES'
		ELSE 'NO'
		END AS "MANUAL VALIDATION"
	,CASE 
		WHEN (LASTNAME + FIRSTNAME + DOB) = 3
			THEN 'YES'
		WHEN (LASTNAME + FIRSTNAME + DOB) < 3
			AND (SEX + ADDRESS + "PHONE NUMBER" + EMAIL) >= 2
			THEN  'YES'
		ELSE  'NO'
		END AS ALGORITHM_VALIDATION

FROM SH_OMOP_DB_PROD.CDM.AOU_PII;
 -- where 
	--case 
	--	when lastname + FirstName + dob = 3
	--		then 1 
	--	when lastname + FirstName + dob < 3  and sex + address + phone number + email >= 2
	--			then 1
	--	else 0
	--end = 1

