{%- macro load_omop_vocabulary_files() -%}
-- THIS MACRO DOES NOT WORK
-- RUN THE QUERIES MANUALLY
-- The vocabulary files should be copied from
-- file://X:/All of Us/OMOP_Working/OMOP files/OMOP_vocabulary_load_current/
-- to the local drive for efficiency
-- file://C:/SVN/SSIS/OMOP/aou_omop/SQL/OMOP_files/OMOP_vocabulary_load_current/

  {%- set query -%}
    -- allows multiple statements
    alter session set multi_statement_count = 0
  {%- endset -%}
  {%- do run_query(query) -%}

  {%- set query -%}
    -- removes ALL the files from the @OMOP_VOCABULARIES stage
    -- and then loads the new files from network drive to @OMOP_VOCABULARIES stage

    REMOVE @OMOP_VOCABULARIES;
    --put 'file://X:/All of Us/OMOP_Working/OMOP files/OMOP_vocabulary_load_current/*.csv' @OMOP_VOCABULARIES;  -- too slow to run from network drive over VPN
	put 'file://C:/SVN/SSIS/OMOP/aou_omop/SQL/OMOP_files/OMOP_vocabulary_load_current/*.csv' @OMOP_VOCABULARIES;

--  {%- endset -%}
--  {%- do run_query(query) -%}
--  {%- set query -%}

    -- truncate and load tables from the @OMOP_VOCABULARIES stage
 
	TRUNCATE TABLE CDM.DRUG_STRENGTH ;
	COPY INTO CDM.DRUG_STRENGTH FROM '@SH_OMOP_DB_PROD.OMOP.OMOP_VOCABULARIES/DRUG_STRENGTH.csv.gz' FILE_FORMAT = 'SH_OMOP_DB_PROD.OMOP.OMOP_VOCAB_FORMAT' ON_ERROR = 'ABORT_STATEMENT' PURGE = FALSE;

	TRUNCATE TABLE CDM.CONCEPT_RELATIONSHIP ;
	COPY INTO CDM.CONCEPT_RELATIONSHIP FROM '@SH_OMOP_DB_PROD.OMOP.OMOP_VOCABULARIES/CONCEPT_RELATIONSHIP.csv.gz' FILE_FORMAT = 'SH_OMOP_DB_PROD.OMOP.OMOP_VOCAB_FORMAT' ON_ERROR = 'ABORT_STATEMENT' PURGE = FALSE;
	 
	TRUNCATE TABLE CDM.CONCEPT_ANCESTOR ;
	COPY INTO CDM.CONCEPT_ANCESTOR FROM '@SH_OMOP_DB_PROD.OMOP.OMOP_VOCABULARIES/CONCEPT_ANCESTOR.csv.gz' FILE_FORMAT = 'SH_OMOP_DB_PROD.OMOP.OMOP_VOCAB_FORMAT' ON_ERROR = 'ABORT_STATEMENT' PURGE = FALSE;
	 
	TRUNCATE TABLE CDM.CONCEPT_SYNONYM ;
	COPY INTO CDM.CONCEPT_SYNONYM FROM '@SH_OMOP_DB_PROD.OMOP.OMOP_VOCABULARIES/CONCEPT_SYNONYM.csv.gz' FILE_FORMAT = 'SH_OMOP_DB_PROD.OMOP.OMOP_VOCAB_FORMAT' ON_ERROR = 'CONTINUE' PURGE = FALSE;
	 
	TRUNCATE TABLE CDM.VOCABULARY ;
	COPY INTO CDM.VOCABULARY FROM '@SH_OMOP_DB_PROD.OMOP.OMOP_VOCABULARIES/VOCABULARY.csv.gz' FILE_FORMAT = 'SH_OMOP_DB_PROD.OMOP.OMOP_VOCAB_FORMAT' ON_ERROR = 'ABORT_STATEMENT' PURGE = FALSE;
	 
	TRUNCATE TABLE CDM.RELATIONSHIP ;
	COPY INTO CDM.RELATIONSHIP FROM '@SH_OMOP_DB_PROD.OMOP.OMOP_VOCABULARIES/RELATIONSHIP.csv.gz' FILE_FORMAT = 'SH_OMOP_DB_PROD.OMOP.OMOP_VOCAB_FORMAT' ON_ERROR = 'ABORT_STATEMENT' PURGE = FALSE;
	 
	TRUNCATE TABLE CDM.CONCEPT ;
	COPY INTO CDM.CONCEPT FROM '@SH_OMOP_DB_PROD.OMOP.OMOP_VOCABULARIES/CONCEPT.csv.gz' FILE_FORMAT = 'SH_OMOP_DB_PROD.OMOP.OMOP_VOCAB_FORMAT' ON_ERROR = 'ABORT_STATEMENT' PURGE = FALSE;
	 
	TRUNCATE TABLE CDM.CONCEPT_CLASS ;
	COPY INTO CDM.CONCEPT_CLASS FROM '@SH_OMOP_DB_PROD.OMOP.OMOP_VOCABULARIES/CONCEPT_CLASS.csv.gz' FILE_FORMAT = 'SH_OMOP_DB_PROD.OMOP.OMOP_VOCAB_FORMAT' ON_ERROR = 'ABORT_STATEMENT' PURGE = FALSE;
	 
	TRUNCATE TABLE CDM.DOMAIN ;
    COPY INTO CDM.DOMAIN FROM '@SH_OMOP_DB_PROD.OMOP.OMOP_VOCABULARIES/DOMAIN.csv.gz' FILE_FORMAT = 'SH_OMOP_DB_PROD.OMOP.OMOP_VOCAB_FORMAT' ON_ERROR = 'ABORT_STATEMENT' PURGE = FALSE;
    -- end load
  {%- endset -%}
  {%- do run_query(query) -%}

{%- endmacro -%}