--CARE_SITE

{{ config(materialized='table') }}

SELECT DISTINCT
      CARE_SITE_ID::NUMBER(28,0)                    AS CARE_SITE_ID  
    , CARE_SITE_NAME::VARCHAR(255)                  AS CARE_SITE_NAME
    , PLACE_OF_SERVICE_CONCEPT_ID::NUMBER(28,0)     AS PLACE_OF_SERVICE_CONCEPT_ID  
    , LOCATION_ID::NUMBER(28,0)                     AS LOCATION_ID  
    , CARE_SITE_SOURCE_VALUE::VARCHAR(50)           AS CARE_SITE_SOURCE_VALUE
    , PLACE_OF_SERVICE_SOURCE_VALUE::VARCHAR(100)    AS PLACE_OF_SERVICE_SOURCE_VALUE
FROM 	
 {{ref('V_CARE_SITE_ALL')}} 