WITH 
T_SOURCE AS 
(
	SELECT CONCEPT_ID
		,CONCEPT_CODE
		,REPLACE(CONCEPT_NAME, '"', '') AS CONCEPT_NAME
	FROM SH_OMOP_DB_PROD.CDM.CONCEPT AS C
	WHERE C.VOCABULARY_ID IN ('ICD9CM','ICD10CM')
		AND (
			C.INVALID_REASON IS NULL
			OR C.INVALID_REASON = ''
			)
		AND C.DOMAIN_ID = 'Condition'
),

T_CONCEPT AS 
(
	SELECT C2.CONCEPT_ID AS CONCEPT_ID
		,C1.CONCEPT_ID AS SOURCE_CONCEPT_ID
	FROM SH_OMOP_DB_PROD.CDM.CONCEPT C1
		INNER JOIN SH_OMOP_DB_PROD.CDM.CONCEPT_RELATIONSHIP CR
			ON C1.CONCEPT_ID = CR.CONCEPT_ID_1
				AND CR.RELATIONSHIP_ID = 'Maps to'
		INNER JOIN SH_OMOP_DB_PROD.CDM.CONCEPT C2
			ON C2.CONCEPT_ID = CR.CONCEPT_ID_2
	WHERE C2.STANDARD_CONCEPT = 'S'
		AND (
			C2.INVALID_REASON IS NULL
			OR C2.INVALID_REASON = ''
			)
		AND C2.DOMAIN_ID = 'Condition'
)
	
	
SELECT DISTINCT T_SOURCE.*,T_CONCEPT.*
FROM SH_OMOP_DB_PROD.OMOP_CLARITY.CONDITION_OCCURRENCE_ClarityAMB_ICD
INNER JOIN T_SOURCE 
    ON CONDITION_OCCURRENCE_ClarityAMB_ICD.icd10_code = T_SOURCE.CONCEPT_CODE
INNER JOIN T_CONCEPT 
    ON T_CONCEPT.SOURCE_CONCEPT_ID = T_SOURCE.CONCEPT_ID;


