WITH	
T_SOURCE AS 
(
	SELECT CONCEPT_ID
		,CONCEPT_CODE
		,DOMAIN_ID
		,VOCABULARY_ID
	FROM CDM.CONCEPT AS C
	WHERE UPPER(C.VOCABULARY_ID) IN ('CPT4')
		AND UPPER(C.DOMAIN_ID) = 'PROCEDURE'
)
,
	
T_CONCEPT AS 
(
	SELECT C2.CONCEPT_ID AS CONCEPT_ID
		,C1.CONCEPT_ID AS SOURCE_CONCEPT_ID
	FROM CDM.CONCEPT C1
	INNER JOIN CDM.CONCEPT_RELATIONSHIP CR
		ON C1.CONCEPT_ID = CR.CONCEPT_ID_1
			AND UPPER(CR.RELATIONSHIP_ID) = 'MAPS TO'
	INNER JOIN CDM.CONCEPT C2
		ON C2.CONCEPT_ID = CR.CONCEPT_ID_2
	WHERE C2.STANDARD_CONCEPT = 'S'
		AND UPPER(C2.DOMAIN_ID) = 'PROCEDURE'		
)


SELECT DISTINCT T_SOURCE.*,T_CONCEPT.*
FROM SH_OMOP_DB_PROD.OMOP_CLARITY.PROCEDURE_OCCURRENCE_CLARITYAMB_CPT
INNER JOIN T_SOURCE 
ON PROCEDURE_OCCURRENCE_CLARITYAMB_CPT.PROC_CODE = T_SOURCE.CONCEPT_CODE
INNER JOIN T_CONCEPT 
ON T_CONCEPT.SOURCE_CONCEPT_ID = T_SOURCE.CONCEPT_ID;

