--DEATH
{{ config(materialized = 'table') }}

SELECT  PERSON_ID::NUMBER(28,0) AS PERSON_ID 
      ,DEATH_DATE::DATE AS DEATH_DATE
      ,DEATH_DATETIME::DATETIME AS DEATH_DATETIME
      ,32817::NUMBER(28,0) AS DEATH_TYPE_CONCEPT_ID -- FROM EHR
      ,0::NUMBER(28,0) AS CAUSE_CONCEPT_ID
      ,NULL::VARCHAR(50) AS CAUSE_SOURCE_VALUE
      ,0::NUMBER(28,0) AS CAUSE_SOURCE_CONCEPT_ID
  FROM  {{ref('DEATH_CLARITY_ALL')}} AS DEATH_CLARITY_ALL