--USE ROLE SF_SH_OMOP_DEVELOPER;
--
--USE SCHEMA SH_CLINICAL_DB_PROD.EPIC_CLARITY_LZ;
--USE SCHEMA SH_OMOP_DB_PROD.OMOP_CLARITY;
--USE SCHEMA SH_OMOP_DB_PROD.CDM;
--
--USE WAREHOUSE SH_OMOP_DATA_SCIENCE_WH;

INSERT  OVERWRITE INTO  CDM.AOU_DRIVER_PROD
    (CPI
    , EPIC_PAT_ID
    , AOU_ID
    , FLAG
    , FIRST_NAME
    , LAST_NAME
    , DATE_OF_BIRTH
    , SEX
    , PHONE
    , STREET_ADDRESS
    , CITY
    , STATE
    , ZIP
    , EMAIL
    , EHR_EXPORT_PT_MATCH_PASS)

SELECT UPPER(CPI) AS CPI
    , UPPER(IDENTITY_ID.PAT_ID) AS EPIC_PAT_ID
    , UPPER(PMI_ID) AS PMI_ID
    , 1 AS FLAG
    , UPPER(FIRST_NAME) AS FIRST_NAME
    , UPPER(LAST_NAME) AS LAST_NAME
    , DATE_OF_BIRTH
    , UPPER(SEX) AS SEX
    , UPPER(PHONE) AS PHONE
    , UPPER(STREET_ADDRESS) AS STREET_ADDRESS
    , UPPER(CITY) AS CITY
    , UPPER(STATE) AS STATE
    , UPPER(ZIP) AS ZIP
    , UPPER(EMAIL) AS EMAIL
    , UPPER(EHR_EXPORT_PT_MATCH_PASS) AS EHR_EXPORT_PT_MATCH_PASS

FROM CDM.ALLOFUSPARTICIPANTS A

INNER JOIN SH_CLINICAL_DB_PROD.EPIC_CLARITY_LZ.IDENTITY_ID
    ON A.CPI = EPIC_CLARITY_LZ.IDENTITY_ID.IDENTITY_ID
        AND (EPIC_CLARITY_LZ.IDENTITY_ID.IDENTITY_TYPE_ID = 49);