

INSERT OVERWRITE INTO SH_OMOP_DB_PROD.CDM.AOU_PII_VALIDATION (
	 PERSON_ID
	,FIRST_NAME
	,LAST_NAME
	,DOB
	,SEX
	,ADDRESS
	,PHONE_NUMBER
	,EMAIL
	,MANUAL_VALIDATION
	,ALGORITHM_VALIDATION
	)

SELECT PID
	,CASE 
		WHEN FIRSTNAME = 1
			THEN 'MATCH'
		ELSE 'NOMATCH'
		END AS FIRSTNAME
	,CASE 
		WHEN LASTNAME = 1
			THEN 'MATCH'
		ELSE 'NOMATCH'
		END AS LASTNAME
	,CASE 
		WHEN DOB = 1
			THEN 'MATCH'
		ELSE 'NOMATCH'
		END AS DOB
	,CASE 
		WHEN SEX = 1
			THEN 'MATCH'
		ELSE 'NOMATCH'
		END AS SEX
	,CASE 
		WHEN ADDRESS = 1
			THEN 'MATCH'
		ELSE 'NOMATCH'
		END AS ADDRESS
	,CASE 
		WHEN "PHONE NUMBER" = 1
			THEN 'MATCH'
		ELSE 'NOMATCH'
		END AS "PHONE NUMBER"
	,CASE 
		WHEN EMAIL = 1
			THEN 'MATCH'
		ELSE 'NOMATCH'
		END AS EMAIL
	,CASE 
		WHEN "MANUAL VALIDATION" = 1
			THEN 'YES'
		ELSE 'NO'
		END AS "MANUAL VALIDATION"
	,CASE 
		WHEN (LASTNAME + FIRSTNAME + DOB) = 3
			THEN 'YES'
		WHEN (LASTNAME + FIRSTNAME + DOB) < 3
			AND (SEX + ADDRESS + "PHONE NUMBER" + EMAIL) >= 2
			THEN  'YES'
		ELSE  'NO'
		END AS ALGORITHM_VALIDATION

FROM SH_OMOP_DB_PROD.CDM.AOU_PII;
 -- where 
	--case 
	--	when lastname + FirstName + dob = 3
	--		then 1 
	--	when lastname + FirstName + dob < 3  and sex + address + phone number + email >= 2
	--			then 1
	--	else 0
	--end = 1

