CREATE OR REPLACE TABLE SH_OMOP_DB_PROD.CDM.AOU_DRIVER
AS 
SELECT        
CPI, EPIC_PAT_ID, AOU_ID, FLAG, DATE_1, DATE_2, AOU_DRIVER_PROD.FIRST_NAME, AOU_DRIVER_PROD.LAST_NAME, DATE_OF_BIRTH, 
AOU_DRIVER_PROD.SEX, PHONE, STREET_ADDRESS, CITY, STATE, ZIP, AOU_DRIVER_PROD.EMAIL, MANUAL_VALIDATION, ALGORITHM_VALIDATION
FROM            SH_OMOP_DB_PROD.CDM.AOU_DRIVER_PROD INNER JOIN CDM.AOU_PII_VALIDATION ON UPPER(AOU_ID) = 'P'|| PERSON_ID::VARCHAR 
WHERE EPIC_PAT_ID IS NOT NULL AND ((UPPER(ALGORITHM_VALIDATION) = 'YES' OR UPPER(MANUAL_VALIDATION) = 'YES'));