--USE ROLE SF_SH_OMOP_DEVELOPER;
----USE SCHEMA SH_CLINICAL_DB_PROD.EPIC_CLARITY_LZ;
----USE SCHEMA SH_OMOP_DB_PROD.OMOP_CLARITY;
--USE SCHEMA SH_OMOP_DB_PROD.CDM;
--USE WAREHOUSE SH_OMOP_DATA_SCIENCE_WH;

 BEGIN 
     DELETE FROM SPECIMEN;
     DELETE FROM NOTE;
     DELETE FROM OBSERVATION;
     DELETE FROM DEVICE_EXPOSURE;
     DELETE FROM PROCEDURE_OCCURRENCE;
     DELETE FROM DRUG_EXPOSURE;
     DELETE FROM MEASUREMENT;
     DELETE FROM CONDITION_OCCURRENCE;
     DELETE FROM VISIT_OCCURRENCE;
     DELETE FROM VISIT_DETAIL;
     DELETE FROM PERSON;
     DELETE FROM PROVIDER;
     DELETE FROM CARE_SITE;
     DELETE FROM LOCATION;
     DELETE FROM DEATH;
 END  ;
