--OMOP_CS.COUNT_DEVICE

SELECT DEVICE_EXPOSURE.VISIT_OCCURRENCE_ID
    , COUNT(DEVICE_EXPOSURE.PERSON_ID) AS COUNTOFDEVICE
    , DEVICE_EXPOSURE.PERSON_ID

FROM {{ref('DEVICE_EXPOSURE')}} AS DEVICE_EXPOSURE

GROUP BY DEVICE_EXPOSURE.VISIT_OCCURRENCE_ID
    , DEVICE_EXPOSURE.PERSON_ID