--QRY_NOTE 

SELECT NOTE.NOTE_ID
    , NOTE.PERSON_ID
    , NOTE.NOTE_DATETIME
    , NOTE_TYPE_CONCEPT_ID || '::' || CONCEPT.CONCEPT_NAME AS NOTE_TYPE
    , NOTE_CLASS_CONCEPT_ID || '::' || CONCEPT_1.CONCEPT_NAME AS NOTE_CLASS
    , NOTE.NOTE_TITLE
    , NOTE.NOTE_TEXT
    , ENCODING_CONCEPT_ID || '::' || CONCEPT_2.CONCEPT_NAME AS ENCODING
    , LANGUAGE_CONCEPT_ID || '::' || CONCEPT_3.CONCEPT_NAME AS LANGUAGE
    , PROVIDER.PROVIDER_NAME
    , NOTE.VISIT_OCCURRENCE_ID
    , NOTE.NOTE_SOURCE_VALUE
    , 'NOTE' AS SDT_TAB
    , VISIT_OCCURRENCE.PERSON_ID || NOTE_SOURCE_VALUE || NOTE_DATETIME AS NK
    , NOTE.ETL_MODULE
    , VISIT_OCCURRENCE.VISIT_SOURCE_VALUE

FROM (
    (
        (
            (
                (
                    {{ref('NOTE')}} AS NOTE INNER JOIN {{ source('CDM','CONCEPT')}}
                        ON NOTE.NOTE_TYPE_CONCEPT_ID = CONCEPT.CONCEPT_ID
                    ) INNER JOIN {{ source('CDM','CONCEPT')}} AS CONCEPT_1
                    ON NOTE.NOTE_CLASS_CONCEPT_ID = CONCEPT_1.CONCEPT_ID
                ) LEFT JOIN {{ref('PROVIDER')}} AS PROVIDER
                ON NOTE.PROVIDER_ID = PROVIDER.PROVIDER_ID
            ) INNER JOIN {{ source('CDM','CONCEPT')}} AS CONCEPT_2
            ON NOTE.ENCODING_CONCEPT_ID = CONCEPT_2.CONCEPT_ID
        ) INNER JOIN {{ source('CDM','CONCEPT')}} AS CONCEPT_3
        ON NOTE.LANGUAGE_CONCEPT_ID = CONCEPT_3.CONCEPT_ID
    )

INNER JOIN {{ref('VISIT_OCCURRENCE')}} AS VISIT_OCCURRENCE
    ON NOTE.VISIT_OCCURRENCE_ID = VISIT_OCCURRENCE.VISIT_OCCURRENCE_ID
