
--QRY_OBSERVATION 

SELECT OBSERVATION.OBSERVATION_ID
    , OBSERVATION.PERSON_ID
    , LEFT(OBSERVATION_CONCEPT_ID || '::' || CONCEPT.CONCEPT_NAME, 100) AS OBSERVATION
    , OBSERVATION.OBSERVATION_DATETIME
    , OBSERVATION_TYPE_CONCEPT_ID || '::' || CONCEPT_1.CONCEPT_NAME AS OBSERVATION_TYPE
    , OBSERVATION.VALUE_AS_NUMBER
    , OBSERVATION.VALUE_AS_STRING
    , VALUE_AS_CONCEPT_ID || '::' || CONCEPT_2.CONCEPT_NAME AS VALUE_AS_CONCEPT
    , QUALIFIER_CONCEPT_ID || '::' || CONCEPT_3.CONCEPT_NAME AS QUALIFIER
    , UNIT_CONCEPT_ID || '::' || CONCEPT_4.CONCEPT_NAME AS UNIT
    , PROVIDER.PROVIDER_NAME
    , OBSERVATION.VISIT_OCCURRENCE_ID
    , OBSERVATION.OBSERVATION_SOURCE_VALUE
    , OBSERVATION_SOURCE_CONCEPT_ID || '::' || CONCEPT_5.CONCEPT_NAME AS OBSERVATION_SOURCE_CONCEPT
    , OBSERVATION.UNIT_SOURCE_VALUE
    , OBSERVATION.QUALIFIER_SOURCE_VALUE
    , 'OBSERVATION' AS SDT_TAB
    , VISIT_OCCURRENCE.PERSON_ID || OBSERVATION_SOURCE_VALUE || OBSERVATION_DATETIME AS NK
    , OBSERVATION.ETL_MODULE
    , VISIT_OCCURRENCE.VISIT_SOURCE_VALUE

FROM (
    (
        (
            (
                (
                    (
                        (
                            {{ref('OBSERVATION')}} AS OBSERVATION INNER JOIN {{ source('CDM','CONCEPT')}}
                                ON OBSERVATION.OBSERVATION_CONCEPT_ID = CONCEPT.CONCEPT_ID
                            ) INNER JOIN {{ source('CDM','CONCEPT')}} AS CONCEPT_1
                            ON OBSERVATION.OBSERVATION_TYPE_CONCEPT_ID = CONCEPT_1.CONCEPT_ID
                        ) INNER JOIN {{ source('CDM','CONCEPT')}} AS CONCEPT_3
                        ON OBSERVATION.QUALIFIER_CONCEPT_ID = CONCEPT_3.CONCEPT_ID
                    ) INNER JOIN {{ source('CDM','CONCEPT')}} AS CONCEPT_4
                    ON OBSERVATION.UNIT_CONCEPT_ID = CONCEPT_4.CONCEPT_ID
                ) INNER JOIN {{ source('CDM','CONCEPT')}} AS CONCEPT_2
                ON OBSERVATION.VALUE_AS_CONCEPT_ID = CONCEPT_2.CONCEPT_ID
            ) LEFT JOIN {{ref('PROVIDER')}} AS PROVIDER
            ON OBSERVATION.PROVIDER_ID =  PROVIDER.PROVIDER_ID
        ) INNER JOIN {{ source('CDM','CONCEPT')}} AS CONCEPT_5
        ON OBSERVATION.OBSERVATION_SOURCE_CONCEPT_ID = CONCEPT_5.CONCEPT_ID
    )

INNER JOIN {{ref('VISIT_OCCURRENCE')}} AS VISIT_OCCURRENCE
    ON OBSERVATION.VISIT_OCCURRENCE_ID = VISIT_OCCURRENCE.VISIT_OCCURRENCE_ID