--QRY_CONDITION_OCCURRENCE

SELECT CONDITION_OCCURRENCE.CONDITION_OCCURRENCE_ID
    , CONDITION_OCCURRENCE.PERSON_ID
    , LEFT(CONDITION_CONCEPT_ID || '::' || CONCEPT_2.CONCEPT_NAME, 100) AS CONDITION
    , CONDITION_OCCURRENCE.CONDITION_START_DATETIME    , CONDITION_OCCURRENCE.CONDITION_END_DATETIME
    , CONDITION_TYPE_CONCEPT_ID || '::' || CONCEPT.CONCEPT_NAME AS CONDITION_TYPE
    , CONDITION_OCCURRENCE.STOP_REASON
    , PROVIDER.PROVIDER_NAME
    , CONDITION_OCCURRENCE.VISIT_OCCURRENCE_ID
    , CONDITION_OCCURRENCE.CONDITION_SOURCE_VALUE
    , CONDITION_OCCURRENCE.CONDITION_SOURCE_CONCEPT_ID
    , CONDITION_STATUS_CONCEPT_ID || '::' || CONCEPT_1.CONCEPT_NAME AS CONDITION_STATUS
    , 'CONDITION' AS SDT_TAB
    , CONDITION_OCCURRENCE.PERSON_ID || CONDITION_SOURCE_VALUE || CONDITION_START_DATETIME AS NK
    , CONDITION_OCCURRENCE.ETL_MODULE
    , VISIT_OCCURRENCE.VISIT_SOURCE_VALUE

FROM (
    (
        {{ source('CDM','CONCEPT')}}  AS CONCEPT_1 INNER JOIN (
            (
                {{ref('CONDITION_OCCURRENCE')}} AS CONDITION_OCCURRENCE LEFT JOIN {{ref('PROVIDER')}} AS PROVIDER
                    ON CONDITION_OCCURRENCE.PROVIDER_ID = PROVIDER.PROVIDER_ID
                ) LEFT JOIN {{ source('CDM','CONCEPT')}} 
                ON CONDITION_OCCURRENCE.CONDITION_TYPE_CONCEPT_ID = CONCEPT.CONCEPT_ID
            )
            ON CONCEPT_1.CONCEPT_ID = CONDITION_OCCURRENCE.CONDITION_STATUS_CONCEPT_ID
        ) INNER JOIN {{ source('CDM','CONCEPT')}}  AS CONCEPT_2
        ON CONDITION_OCCURRENCE.CONDITION_CONCEPT_ID = CONCEPT_2.CONCEPT_ID
    )

INNER JOIN {{ref('VISIT_OCCURRENCE')}} AS VISIT_OCCURRENCE
    ON CONDITION_OCCURRENCE.VISIT_OCCURRENCE_ID = VISIT_OCCURRENCE.VISIT_OCCURRENCE_ID