--QRY_DRUG_EXPOSURE 

SELECT DRUG_EXPOSURE.DRUG_EXPOSURE_ID
    , DRUG_EXPOSURE.PERSON_ID
    , LEFT(DRUG_CONCEPT_ID || '::' || CONCEPT.CONCEPT_NAME, 100) AS DRUG_CONCEPT
    , DRUG_EXPOSURE.DRUG_EXPOSURE_START_DATETIME
    , DRUG_EXPOSURE.DRUG_EXPOSURE_END_DATETIME
    , DRUG_EXPOSURE.VERBATIM_END_DATE
    , DRUG_TYPE_CONCEPT_ID || '::' || CONCEPT_1.CONCEPT_NAME AS DRUG_TYPE
    , DRUG_EXPOSURE.STOP_REASON
    , DRUG_EXPOSURE.REFILLS
    , DRUG_EXPOSURE.QUANTITY
    , DRUG_EXPOSURE.DAYS_SUPPLY
    , DRUG_EXPOSURE.SIG
    , ROUTE_CONCEPT_ID || '::' || CONCEPT_2.CONCEPT_NAME AS ROUTE
    , DRUG_EXPOSURE.LOT_NUMBER
    , PROVIDER.PROVIDER_NAME
    , DRUG_EXPOSURE.VISIT_OCCURRENCE_ID
    , DRUG_EXPOSURE.DRUG_SOURCE_VALUE
    , DRUG_SOURCE_CONCEPT_ID || '::' || CONCEPT_3.CONCEPT_NAME AS DRUG_SOURCE_CONCEPT
    , DRUG_EXPOSURE.ROUTE_SOURCE_VALUE
    , DRUG_EXPOSURE.DOSE_UNIT_SOURCE_VALUE
    , 'DRUG' AS SDT_TAB
    , VISIT_OCCURRENCE.PERSON_ID || DRUG_SOURCE_VALUE || DRUG_EXPOSURE_START_DATETIME AS NK
    , DRUG_EXPOSURE.ETL_MODULE
    , VISIT_OCCURRENCE.VISIT_SOURCE_VALUE

FROM (
    (
        (
            {{ source('CDM','CONCEPT')}} AS CONCEPT_1 INNER JOIN (
                (
                    {{ref('DRUG_EXPOSURE')}} AS DRUG_EXPOSURE LEFT JOIN {{ref('PROVIDER')}} AS PROVIDER
                        ON DRUG_EXPOSURE.PROVIDER_ID = PROVIDER.PROVIDER_ID
                    ) INNER JOIN {{ source('CDM','CONCEPT')}}
                    ON DRUG_EXPOSURE.DRUG_CONCEPT_ID = CONCEPT.CONCEPT_ID
                )
                ON CONCEPT_1.CONCEPT_ID = DRUG_EXPOSURE.DRUG_TYPE_CONCEPT_ID
            ) INNER JOIN {{ source('CDM','CONCEPT')}} AS CONCEPT_2
            ON DRUG_EXPOSURE.ROUTE_CONCEPT_ID = CONCEPT_2.CONCEPT_ID
        ) INNER JOIN {{ source('CDM','CONCEPT')}} AS CONCEPT_3
        ON DRUG_EXPOSURE.DRUG_SOURCE_CONCEPT_ID = CONCEPT_3.CONCEPT_ID
    )

INNER JOIN {{ref('VISIT_OCCURRENCE')}} AS VISIT_OCCURRENCE
    ON DRUG_EXPOSURE.VISIT_OCCURRENCE_ID = VISIT_OCCURRENCE.VISIT_OCCURRENCE_ID