--QRY_MEASUREMENT 

SELECT MEASUREMENT.MEASUREMENT_ID
    , MEASUREMENT.PERSON_ID
    , LEFT(MEASUREMENT_CONCEPT_ID || '::' || CONCEPT.CONCEPT_NAME, 100) AS MEASUREMENT
    , MEASUREMENT.MEASUREMENT_DATETIME
    , MEASUREMENT_TYPE_CONCEPT_ID || '::' || CONCEPT_2.CONCEPT_NAME AS MEASUREMENT_TYPE
    , OPERATOR_CONCEPT_ID || '::' || CONCEPT_1.CONCEPT_NAME AS OPERATOR
    , MEASUREMENT.VALUE_AS_NUMBER
    , VALUE_AS_CONCEPT_ID || '::' || CONCEPT_3.CONCEPT_NAME AS VALUE_AS_CONCEPT
    , UNIT_CONCEPT_ID || '::' || CONCEPT_4.CONCEPT_NAME AS UNIT
    , MEASUREMENT.RANGE_LOW
    , MEASUREMENT.RANGE_HIGH
    , PROVIDER.PROVIDER_NAME
    , MEASUREMENT.VISIT_OCCURRENCE_ID
    , MEASUREMENT.MEASUREMENT_SOURCE_VALUE
    , MEASUREMENT_SOURCE_CONCEPT_ID || '::' || CONCEPT_5.CONCEPT_NAME AS MEASUREMENT_SOURCE
    , MEASUREMENT.UNIT_SOURCE_VALUE
    , MEASUREMENT.VALUE_SOURCE_VALUE
    , 'MEASUREMENT' AS SDT_TAB
    , VISIT_OCCURRENCE.PERSON_ID || MEASUREMENT_SOURCE_VALUE || MEASUREMENT_DATETIME AS NK
    , MEASUREMENT.ETL_MODULE
    , VISIT_OCCURRENCE.VISIT_SOURCE_VALUE

FROM (
    (
        {{ source('CDM','CONCEPT')}} AS CONCEPT_4 INNER JOIN (
            {{ source('CDM','CONCEPT')}} AS CONCEPT_3 INNER JOIN (
                {{ source('CDM','CONCEPT')}} AS CONCEPT_2 INNER JOIN (
                    {{ source('CDM','CONCEPT')}} AS CONCEPT_1 INNER JOIN (
                        {{ source('CDM','CONCEPT')}} INNER JOIN (
                            {{ref('MEASUREMENT')}} AS MEASUREMENT LEFT JOIN {{ref('PROVIDER')}} AS PROVIDER
                                ON MEASUREMENT.PROVIDER_ID = PROVIDER.PROVIDER_ID
                            )
                            ON CONCEPT.CONCEPT_ID = MEASUREMENT.MEASUREMENT_CONCEPT_ID
                        )
                        ON CONCEPT_1.CONCEPT_ID = MEASUREMENT.OPERATOR_CONCEPT_ID
                    )
                    ON CONCEPT_2.CONCEPT_ID = MEASUREMENT.MEASUREMENT_TYPE_CONCEPT_ID
                )
                ON CONCEPT_3.CONCEPT_ID = MEASUREMENT.VALUE_AS_CONCEPT_ID
            )
            ON CONCEPT_4.CONCEPT_ID = MEASUREMENT.UNIT_CONCEPT_ID
        ) INNER JOIN {{ source('CDM','CONCEPT')}} AS CONCEPT_5
        ON MEASUREMENT.MEASUREMENT_SOURCE_CONCEPT_ID = CONCEPT_5.CONCEPT_ID
    )

INNER JOIN {{ref('VISIT_OCCURRENCE')}} AS VISIT_OCCURRENCE
    ON MEASUREMENT.VISIT_OCCURRENCE_ID = VISIT_OCCURRENCE.VISIT_OCCURRENCE_ID