--QRY_PROCEDURE_OCCURRENCE 

SELECT PROCEDURE_OCCURRENCE.PROCEDURE_OCCURRENCE_ID
    , PROCEDURE_OCCURRENCE.PERSON_ID
    , LEFT(PROCEDURE_CONCEPT_ID || '::' || CONCEPT.CONCEPT_NAME, 100) AS PROCEDURE
    , PROCEDURE_OCCURRENCE.PROCEDURE_DATETIME
    , PROCEDURE_TYPE_CONCEPT_ID || '::' || CONCEPT_1.CONCEPT_NAME AS "PROCEDURE TYPE"
    , MODIFIER_CONCEPT_ID || '::' || CONCEPT_2.CONCEPT_NAME AS MODIFIER
    , PROCEDURE_OCCURRENCE.QUANTITY
    , PROVIDER.PROVIDER_NAME
    , PROCEDURE_OCCURRENCE.VISIT_OCCURRENCE_ID
    , PROCEDURE_OCCURRENCE.PROCEDURE_SOURCE_VALUE
    , PROCEDURE_SOURCE_CONCEPT_ID || '::' || CONCEPT_3.CONCEPT_NAME AS PROCEDURE_SOURCE
    , PROCEDURE_OCCURRENCE.MODIFIER_SOURCE_VALUE AS QUALIFIER_SOURCE_VALUE
    , 'PROCEDURE' AS SDT_TAB
    , PROCEDURE_OCCURRENCE.PERSON_ID || PROCEDURE_SOURCE_VALUE || PROCEDURE_DATETIME AS NK
    , PROCEDURE_OCCURRENCE.ETL_MODULE
    , VISIT_OCCURRENCE.VISIT_SOURCE_VALUE

FROM (
    (
        (
            (
                {{ source('CDM','CONCEPT')}} AS CONCEPT_1 INNER JOIN (
                    {{ref('PROCEDURE_OCCURRENCE')}} AS PROCEDURE_OCCURRENCE INNER JOIN {{ source('CDM','CONCEPT')}} AS CONCEPT
                        ON PROCEDURE_OCCURRENCE.PROCEDURE_CONCEPT_ID = CONCEPT.CONCEPT_ID
                    )
                    ON CONCEPT_1.CONCEPT_ID = PROCEDURE_OCCURRENCE.PROCEDURE_TYPE_CONCEPT_ID
                ) INNER JOIN {{ source('CDM','CONCEPT')}}  AS CONCEPT_2
                ON PROCEDURE_OCCURRENCE.MODIFIER_CONCEPT_ID = CONCEPT_2.CONCEPT_ID
            ) LEFT JOIN {{ref('PROVIDER')}} AS PROVIDER
            ON PROCEDURE_OCCURRENCE.PROVIDER_ID = PROVIDER.PROVIDER_ID
        ) INNER JOIN {{ source('CDM','CONCEPT')}} AS CONCEPT_3
        ON PROCEDURE_OCCURRENCE.PROCEDURE_SOURCE_CONCEPT_ID = CONCEPT_3.CONCEPT_ID
    )

INNER JOIN OMOP.VISIT_OCCURRENCE
    ON PROCEDURE_OCCURRENCE.VISIT_OCCURRENCE_ID = VISIT_OCCURRENCE.VISIT_OCCURRENCE_ID