-- OMOP_CS.QRY_VISIT_OCCURRENCE


SELECT VISIT_OCCURRENCE.VISIT_OCCURRENCE_ID
    , VISIT_OCCURRENCE.PERSON_ID
    , VISIT_TYPE_CONCEPT_ID || '::' || CONCEPT_1.CONCEPT_NAME AS VISIT_TYPE
    , VISIT_OCCURRENCE.VISIT_START_DATETIME
    , VISIT_OCCURRENCE.VISIT_END_DATETIME
    , PROVIDER.PROVIDER_ID || '::' || PROVIDER_NAME AS PROVIDER
    , CARE_SITE.CARE_SITE_ID || '::' || CARE_SITE_NAME AS CARE_SITE
    , VISIT_OCCURRENCE.VISIT_SOURCE_VALUE
    , VISIT_CONCEPT_ID || '::' || CONCEPT.CONCEPT_NAME AS VISIT
    , VISIT_OCCURRENCE.VISIT_SOURCE_CONCEPT_ID
    , ADMITTING_SOURCE_CONCEPT_ID || '::' || CONCEPT_2.CONCEPT_NAME AS ADMITTING_SOURCE
    , DISCHARGE_TO_CONCEPT_ID || '::' || CONCEPT_3.CONCEPT_NAME AS DISCHARGE
    , VISIT_OCCURRENCE.ADMITTING_SOURCE_VALUE
    , VISIT_OCCURRENCE.ADMITTING_SOURCE_CONCEPT_ID
    , VISIT_OCCURRENCE.DISCHARGE_TO_SOURCE_VALUE
    , VISIT_OCCURRENCE.DISCHARGE_TO_CONCEPT_ID
    , VISIT_OCCURRENCE.PRECEDING_VISIT_OCCURRENCE_ID
    , 'VISIT_OCCURRENCE' AS SDT_TAB
    , VISIT_OCCURRENCE.VISIT_SOURCE_VALUE AS NK
    , VISIT_OCCURRENCE.ETL_MODULE


FROM (
    {{ source('CDM','CONCEPT')}} AS CONCEPT_2 INNER JOIN (
        (
            (
                (
                    {{ref('VISIT_OCCURRENCE')}} AS VISIT_OCCURRENCE LEFT JOIN {{ref('PROVIDER')}} AS PROVIDER
                        ON VISIT_OCCURRENCE.PROVIDER_ID = PROVIDER.PROVIDER_ID
                    ) INNER JOIN {{ref('CARE_SITE')}} AS CARE_SITE
                    ON VISIT_OCCURRENCE.CARE_SITE_ID = CARE_SITE.CARE_SITE_ID
                ) INNER JOIN {{ source('CDM','CONCEPT')}}
                ON VISIT_OCCURRENCE.VISIT_CONCEPT_ID = CONCEPT.CONCEPT_ID
            ) INNER JOIN {{ source('CDM','CONCEPT')}}   AS CONCEPT_1
            ON VISIT_OCCURRENCE.VISIT_TYPE_CONCEPT_ID = CONCEPT_1.CONCEPT_ID
        )
        ON CONCEPT_2.CONCEPT_ID = VISIT_OCCURRENCE.ADMITTING_SOURCE_CONCEPT_ID
    )

INNER JOIN {{ source('CDM','CONCEPT')}}  AS CONCEPT_3
    ON VISIT_OCCURRENCE.DISCHARGE_TO_CONCEPT_ID = CONCEPT_3.CONCEPT_ID