--VISIT_OCCURRENCE 

{{ config(materialized = 'table') }} 

SELECT
    DISTINCT SEQ_VISIT_OCCURRENCE.NEXTVAL AS VISIT_OCCURRENCE_ID
    , A.*
FROM
(SELECT *
FROM
     {{ref('V_VISIT_OCCURRENCE_AMB_F2F')}} AS VISIT_OCCURRENCE_AMB_F2F    
UNION
SELECT *
FROM 
     {{ref('V_VISIT_OCCURRENCE_HSP')}} AS VISIT_OCCURRENCE_HSP ) A