
--VISIT_OCCURRENCE_CLARITYAMB_ALL

SELECT DISTINCT SUBSTRING(AOU_DRIVER.AOU_ID, 2, LEN(AOU_DRIVER.AOU_ID)) AS PERSON_ID
    ,AOU_ID
    ,PAT_ENC.PAT_ID
    ,PAT_ENC.PAT_ENC_CSN_ID
 
    ,PAT_ENC.ENC_TYPE_C
    ,ZC_DISP_ENC_TYPE.NAME AS ZC_DISP_ENC_TYPE_NAME

    ,PAT_ENC.CHECKIN_TIME
    ,PAT_ENC.APPT_TIME
    ,PAT_ENC.ENC_INSTANT
    ,PAT_ENC.CONTACT_DATE

    ,PAT_ENC.CHECKOUT_TIME
    ,PAT_ENC.ENC_CLOSE_TIME

    ,PAT_ENC.ACCOUNT_ID
    ,PAT_ENC.HSP_ACCOUNT_ID
    ,PAT_ENC.INPATIENT_DATA_ID
    ,PAT_ENC_2.IP_DOC_CONTACT_CSN
    ,PAT_OR_ADM_LINK.PAT_ENC_CSN_ID AS PAT_OR_ADM_LINK_CSN

    ,PAT_ENC.VISIT_PROV_ID
    ,VISIT_PROVIDER.PROV_NAME AS VISIT_PROVIDER_NAME
    ,VISIT_PROVIDER.PROV_TYPE AS VISIT_PROVIDER_TYPE

    ,PAT_ENC.PCP_PROV_ID
    ,PCP_PROVIDER.PROV_NAME AS PCP_PROVIDER_NAME
    ,PCP_PROVIDER.PROV_TYPE AS PCP_PROVIDER_TYPE

    ,PAT_ENC.PRIMARY_LOC_ID
    ,CLARITY_LOC.LOC_NAME

    ,PAT_ENC.CALCULATED_ENC_STAT_C
    ,ZC_CALCULATED_ENC_STAT.NAME AS CALCULATED_ENC_STAT_NAME
    ,PAT_ENC.APPT_STATUS_C
    ,ZC_APPT_STATUS.NAME AS APPT_STATUS_NAME


FROM  {{ source('CLARITY','PAT_ENC_HSP')}} AS PAT_ENC_HSP --HOSP

        RIGHT JOIN  {{ source('CLARITY','PAT_ENC_2')}} AS PAT_ENC_2 --HOD_2
                        ON PAT_ENC_HSP.PAT_ENC_CSN_ID = PAT_ENC_2.IP_DOC_CONTACT_CSN

        INNER JOIN  {{ source('CLARITY','PAT_ENC')}} AS PAT_ENC --HOD
                        ON PAT_ENC_2.PAT_ENC_CSN_ID = PAT_ENC.PAT_ENC_CSN_ID

        LEFT JOIN  {{ source('CLARITY','PAT_OR_ADM_LINK')}} AS PAT_OR_ADM_LINK
        ON PAT_ENC.PAT_ENC_CSN_ID = PAT_OR_ADM_LINK.PAT_ENC_CSN_ID

    INNER JOIN   {{ref('AOU_DRIVER')}} AS AOU_DRIVER
        ON  PAT_ENC.PAT_ID = AOU_DRIVER.EPIC_PAT_ID

    LEFT JOIN  {{ source('CLARITY','CLARITY_LOC')}} AS CLARITY_LOC
        ON PAT_ENC.PRIMARY_LOC_ID = CLARITY_LOC.LOC_ID

    LEFT JOIN  {{ source('CLARITY','CLARITY_SER')}} AS VISIT_PROVIDER
        ON PAT_ENC.VISIT_PROV_ID = VISIT_PROVIDER.PROV_ID

    LEFT JOIN  {{ source('CLARITY','CLARITY_SER')}} AS PCP_PROVIDER
        ON PAT_ENC.PCP_PROV_ID = PCP_PROVIDER.PROV_ID

    LEFT JOIN  {{ source('CLARITY','ZC_DISP_ENC_TYPE')}} AS ZC_DISP_ENC_TYPE
        ON PAT_ENC.ENC_TYPE_C = ZC_DISP_ENC_TYPE.DISP_ENC_TYPE_C

    LEFT JOIN  {{ source('CLARITY','ZC_CALCULATED_ENC_STAT')}} AS ZC_CALCULATED_ENC_STAT
        ON PAT_ENC.CALCULATED_ENC_STAT_C = ZC_CALCULATED_ENC_STAT.CALCULATED_ENC_STAT_C

    LEFT JOIN  {{ source('CLARITY','ZC_APPT_STATUS')}} AS ZC_APPT_STATUS
        ON PAT_ENC.APPT_STATUS_C = ZC_APPT_STATUS.APPT_STATUS_C

WHERE ENC_TYPE_C <> 3