--VISIT_OCCURRENCE_CLARITYHOSP_ALL
{{ config(materialized='table') }}

SELECT DISTINCT SUBSTRING(AOU_DRIVER.AOU_ID, 2, LEN(AOU_DRIVER.AOU_ID))::NUMBER(28,0) AS PERSON_ID
	,AOU_DRIVER.AOU_ID
	,PAT_ENC_HSP.PAT_ID
	,PAT_ENC_HSP.PAT_ENC_CSN_ID

	,PAT_ENC_HSP.ADT_PAT_CLASS_C
	, ZC_PAT_CLASS.NAME AS ADT_PAT_CLASS_NAME

	,PAT_ENC_HSP.HOSP_ADMSN_TIME
	,PAT_ENC_HSP.INP_ADM_DATE
	,PAT_ENC_HSP.EXP_ADMISSION_TIME
	,PAT_ENC_HSP.OP_ADM_DATE
	,PAT_ENC_HSP.EMER_ADM_DATE
	,PAT_ENC_HSP.INSTANT_OF_ENTRY_TM

	,PAT_ENC_HSP.HOSP_DISCH_TIME
	,PAT_ENC_HSP.ED_DISP_TIME

	,PAT_ENC_HSP.HOSPITAL_AREA_ID
	,PAT_ENC_HSP.HSP_ACCOUNT_ID
	,PAT_ENC_HSP.INPATIENT_DATA_ID

	,PAT_ENC_HSP.IP_EPISODE_ID
	,PAT_ENC_HSP.ED_EPISODE_ID

	,PAT_ENC_HSP.ED_DISPOSITION_C
	, ZC_ED_DISPOSITION.NAME AS ED_DISPOSITION_NAME

	,PAT_ENC_HSP.ADMIT_SOURCE_C
	,ZC_ADM_SOURCE.NAME AS ADMIT_SOURCE_NAME

	,PAT_ENC_HSP.DISCH_DISP_C
	,ZC_DISCH_DISP.NAME AS DISCH_DISP_NAME

	,PAT_ENC_HSP.BILL_ATTEND_PROV_ID

	,PAT_ENC_HSP.ADT_PATIENT_STAT_C
	,ZC_PAT_STATUS.NAME AS ADT_PATIENT_STAT_NAME

	, HSP_ACCOUNT.ATTENDING_PROV_ID
	, HSP_ACCOUNT.REFERRING_PROV_ID
	, HSP_ACCOUNT.ADM_DATE_TIME
	, HSP_ACCOUNT.DISCH_DATE_TIME



FROM  {{ source('CLARITY','PAT_ENC_HSP')}} AS PAT_ENC_HSP

	INNER JOIN {{ref('AOU_DRIVER')}} AS AOU_DRIVER 
		ON PAT_ENC_HSP.PAT_ID = AOU_DRIVER.EPIC_PAT_ID

	LEFT JOIN  {{ source('CLARITY','ZC_PAT_CLASS')}} AS ZC_PAT_CLASS
		ON PAT_ENC_HSP.ADT_PAT_CLASS_C = ZC_PAT_CLASS.ADT_PAT_CLASS_C

	LEFT JOIN  {{ source('CLARITY','ZC_PAT_STATUS')}} AS ZC_PAT_STATUS
		ON PAT_ENC_HSP.ADT_PATIENT_STAT_C = ZC_PAT_STATUS.ADT_PATIENT_STAT_C

	LEFT JOIN  {{ source('CLARITY','ZC_ADM_SOURCE')}} AS ZC_ADM_SOURCE
		ON PAT_ENC_HSP.ADMIT_SOURCE_C = ZC_ADM_SOURCE.ADMIT_SOURCE_C

	LEFT JOIN  {{ source('CLARITY','ZC_DISCH_DISP')}} AS ZC_DISCH_DISP
		ON PAT_ENC_HSP.DISCH_DISP_C = ZC_DISCH_DISP.DISCH_DISP_C

	LEFT JOIN 	 {{ source('CLARITY','ZC_ED_DISPOSITION')}} AS ZC_ED_DISPOSITION
		ON PAT_ENC_HSP.ED_DISPOSITION_C	= ZC_ED_DISPOSITION.ED_DISPOSITION_C
		
	LEFT JOIN  {{ source('CLARITY','HSP_ACCOUNT')}} AS HSP_ACCOUNT
		ON PAT_ENC_HSP.HSP_ACCOUNT_ID = HSP_ACCOUNT.HSP_ACCOUNT_ID

WHERE HOSP_DISCH_TIME IS NOT NULL