--DEVICE_EXPOSURE_CLARITYHOSP_BLOOD

SELECT SUBSTRING(AOU_DRIVER.AOU_ID, 2, LEN(AOU_DRIVER.AOU_ID)) AS PERSON_ID
	,AOU_DRIVER.AOU_ID
	,PROC_START_TIME
	,PROC_ENDING_TIME
	,T_CODES.BLOOD_ADMIN_UNIT
	,ORDER_PROC.QUANTITY
	,ORDER_PROC.PROC_ID
	,ORDER_PROC.PROC_CODE
	,CLARITY_EAP.PROC_NAME
	,PAT_ENC_HSP.PAT_ENC_CSN_ID
	,ORDER_PROC.FUTURE_OR_STAND
	,ORDER_PROC.INSTANTIATED_TIME
	,AUTHRZING_PROV_ID
	,'PULL_DEVICE_EXPOSURE--CLARITYHOSP--BLOOD' AS ETL_MODULE

--INTO SH_OMOP_DB_PROD.OMOP_CLARITY.DEVICE_EXPOSURE_CLARITYHOSP_BLOOD

FROM {{ref('AOU_DRIVER')}} AS AOU_DRIVER

INNER JOIN {{ source('CLARITY','PAT_ENC_HSP')}} AS PAT_ENC_HSP
	ON AOU_DRIVER.EPIC_PAT_ID = PAT_ENC_HSP.PAT_ID

INNER JOIN {{ source('CLARITY','ORDER_PROC')}} AS ORDER_PROC
	ON PAT_ENC_HSP.PAT_ENC_CSN_ID = ORDER_PROC.PAT_ENC_CSN_ID
		AND ORDER_PROC.FUTURE_OR_STAND IS NULL
		AND ORDER_PROC.INSTANTIATED_TIME IS NOT NULL

LEFT JOIN {{ source('CLARITY','CLARITY_EAP')}} AS CLARITY_EAP
	ON ORDER_PROC.PROC_ID = CLARITY_EAP.PROC_ID

INNER JOIN {{ref('T_CODES_DEVICE_EXPOSURE')}} AS  T_CODES
	ON ORDER_PROC.ORDER_PROC_ID = T_CODES.ORDER_ID
