--DEVICE_EXPOSURE_CLARITYANES_LDA

SELECT DISTINCT SUBSTRING(AOU_DRIVER.AOU_ID, 2, LEN(AOU_DRIVER.AOU_ID)) AS PERSON_ID
	--,AOU_DRIVER.CPI
	,IP_LDA_NOADDSINGLE.PAT_ID
	,IP_LDA_NOADDSINGLE.IP_LDA_ID
	,IP_LDA_NOADDSINGLE.PAT_ENC_CSN_ID AS LDS_ENC
	,F_AN_RECORD_SUMMARY.AN_52_ENC_CSN_ID ANES_ENC
	,PAT_ENC_HSP.PAT_ENC_CSN_ID
	,IP_LDA_NOADDSINGLE.FLO_MEAS_ID
	,IP_FLO_GP_DATA.FLO_MEAS_NAME
	,IP_FLO_GP_DATA.DISP_NAME AS FLO_MEAS_DISP_NAME
	,IP_LDA_NOADDSINGLE.PLACEMENT_INSTANT
	,IP_LDA_NOADDSINGLE.REMOVAL_INSTANT
	,IP_LDA_NOADDSINGLE.DESCRIPTION
	,IP_LDA_NOADDSINGLE.PROPERTIES_DISPLAY
	,IP_LDA_NOADDSINGLE.SITE
	,PAT_ENC_HSP.BILL_ATTEND_PROV_ID
	,'PULL_DEVICE_EXPOSURE--CLARITYANES--LDA' AS ETL_MODULE
	--,PAT_ENC.*

--INTO OMOP_CLARITY.DEVICE_EXPOSURE_CLARITYANES_LDA

FROM {{ref('AOU_DRIVER')}} AS AOU_DRIVER  

INNER JOIN {{ source('CLARITY','PAT_ENC')}} AS PAT_ENC  
	ON AOU_DRIVER.EPIC_PAT_ID = PAT_ENC.PAT_ID

-- ASSOCIATES ANETHESIA EVENT TO HOSPITAL ENCOUNTER
  INNER JOIN {{ source('CLARITY','F_AN_RECORD_SUMMARY')}} AS F_AN_RECORD_SUMMARY 
	ON PAT_ENC.PAT_ENC_CSN_ID = F_AN_RECORD_SUMMARY.AN_52_ENC_CSN_ID

  INNER JOIN {{ source('CLARITY','AN_HSB_LINK_INFO')}} AS AN_HSB_LINK_INFO 
	ON F_AN_RECORD_SUMMARY.AN_EPISODE_ID=AN_HSB_LINK_INFO.SUMMARY_BLOCK_ID

  INNER JOIN {{ source('CLARITY','PAT_ENC_HSP')}} AS PAT_ENC_HSP 
	ON AN_HSB_LINK_INFO.AN_BILLING_CSN_ID=PAT_ENC_HSP.PAT_ENC_CSN_ID
 
 -- LDA data 
INNER JOIN {{ source('CLARITY','IP_LDA_NOADDSINGLE')}} AS IP_LDA_NOADDSINGLE  
	ON pat_enc.PAT_ENC_CSN_ID = IP_LDA_NOADDSINGLE.PAT_ENC_CSN_ID

INNER JOIN {{ source('CLARITY','IP_FLO_GP_DATA')}} AS IP_FLO_GP_DATA  
	ON IP_LDA_NOADDSINGLE.FLO_MEAS_ID = IP_FLO_GP_DATA.FLO_MEAS_ID
