SELECT DISTINCT 
	--OMOP.SEQ_CONDITION_OCCURRENCE.NEXTVAL AS CONDITION_OCCURRENCE_ID
	CONDITION_OCCURRENCE_CLARITYAMB_ICD.PERSON_ID

	,CASE 
		WHEN CONDITION_OCCURRENCE_CLARITYAMB_ICD.CONTACT_DATE >= '2015-10-01'
			THEN T_ICD10_CONCEPT.CONCEPT_ID
		ELSE T_ICD9_CONCEPT.CONCEPT_ID
		END AS CONDITION_CONCEPT_ID

	,CAST( CONDITION_OCCURRENCE_CLARITYAMB_ICD.CONTACT_DATE AS DATE) AS CONDITION_START_DATE
	,CONDITION_OCCURRENCE_CLARITYAMB_ICD.CONTACT_DATE AS CONDITION_START_DATETIME
	,CAST( CONDITION_OCCURRENCE_CLARITYAMB_ICD.CONTACT_DATE AS DATE) AS CONDITION_END_DATE
	,CONDITION_OCCURRENCE_CLARITYAMB_ICD.CONTACT_DATE AS CONDITION_END_DATETIME
	,32817 AS CONDITION_TYPE_CONCEPT_ID
	,NULL AS STOP_REASON

	,COALESCE(VST.PROVIDER_ID, PCP.PROVIDER_ID) AS PROVIDER_ID

    ,VISIT_OCCURRENCE.VISIT_OCCURRENCE_ID AS VISIT_OCCURRENCE_ID
    
    ,0 AS VISIT_DETAIL_ID
    
	-- RETURNS ICD10 CODES AFTER SWITCH DATE-----
	,CASE 
		WHEN CONDITION_OCCURRENCE_CLARITYAMB_ICD.CONTACT_DATE >= '2015-10-01'
			THEN LEFT(T_ICD10_SOURCE.CONCEPT_CODE || ':' || T_ICD10_SOURCE.CONCEPT_NAME, 50)
		ELSE LEFT(T_ICD9_SOURCE.CONCEPT_CODE || ':' || T_ICD9_SOURCE.CONCEPT_NAME, 50)
		END AS CONDITION_SOURCE_VALUE
	,CASE 
		WHEN CONDITION_OCCURRENCE_CLARITYAMB_ICD.CONTACT_DATE >= '2015-10-01'
			THEN T_ICD10_SOURCE.CONCEPT_ID
		ELSE T_ICD9_SOURCE.CONCEPT_ID
		END AS CONDITION_SOURCE_CONCEPT_ID
	--------------------------------------------
	,'FINAL DIAGNOSIS' AS CONDITION_STATUS_SOURCE_VALUE
	,4230359 AS CONDITION_STATUS_CONCEPT_ID
	,'CONDITION_OCCURRENCE--CLARITYAMB--ICD' AS ETL_MODULE
	,VISIT_SOURCE_VALUE

FROM {{ref('CONDITION_OCCURRENCE_CLARITYAMB_ICD')}} AS CONDITION_OCCURRENCE_CLARITYAMB_ICD

	INNER JOIN {{ref('VISIT_OCCURRENCE')}} AS VISIT_OCCURRENCE
		ON CONDITION_OCCURRENCE_CLARITYAMB_ICD.PAT_ENC_CSN_ID = VISIT_OCCURRENCE.VISIT_SOURCE_VALUE

    LEFT JOIN
                {{ref('PROVIDER')}} AS VST
                ON  CONDITION_OCCURRENCE_CLARITYAMB_ICD.VISIT_PROV_ID = VST.PROVIDER_SOURCE_VALUE         
    LEFT JOIN
                {{ref('PROVIDER')}} AS PCP
                ON  CONDITION_OCCURRENCE_CLARITYAMB_ICD.PCP_PROV_ID = PCP.PROVIDER_SOURCE_VALUE 
	--------CONCEPT MAPPING--------------------

	LEFT JOIN {{ref('T_ICD_SOURCE')}} AS T_ICD9_SOURCE
		ON CONDITION_OCCURRENCE_CLARITYAMB_ICD.ICD9_CODE = T_ICD9_SOURCE.CONCEPT_CODE

	LEFT JOIN {{ref('T_ICD_SOURCE')}} AS T_ICD10_SOURCE
		ON CONDITION_OCCURRENCE_CLARITYAMB_ICD.ICD10_CODE = T_ICD10_SOURCE.CONCEPT_CODE

	LEFT JOIN {{ref('T_CONDITION_CONCEPT')}} AS  T_ICD9_CONCEPT
		ON T_ICD9_CONCEPT.SOURCE_CONCEPT_ID = T_ICD9_SOURCE.CONCEPT_ID

	LEFT JOIN {{ref('T_CONDITION_CONCEPT')}} AS  T_ICD10_CONCEPT
		ON T_ICD10_CONCEPT.SOURCE_CONCEPT_ID = T_ICD10_SOURCE.CONCEPT_ID

WHERE 	
	(CONDITION_OCCURRENCE_CLARITYAMB_ICD.CONTACT_DATE >= '2015-10-01' AND T_ICD10_CONCEPT.CONCEPT_ID IS NOT NULL)   
	OR 
	(CONDITION_OCCURRENCE_CLARITYAMB_ICD.CONTACT_DATE < '2015-10-01' AND T_ICD9_CONCEPT.CONCEPT_ID IS NOT NULL   )

