
USE DATABASE SH_OMOP_DB_PROD;
--USE SCHEMA OMOP_CLARITY;
USE ROLE SF_SH_OMOP_DEVELOPER;
USE WAREHOUSE SH_OMOP_DATA_SCIENCE_WH;

CREATE OR REPLACE VIEW OMOP_QA.V_AOU_DRIVER_PROD_DUPLICATES_DETAIL AS (

SELECT CAST(GETDATE() AS DATE) AS RUN_DATE
    , 'AOU_DRIVER_PROD' AS STANDARD_DATA_TABLE
    , 'DUPLICATE ' AS QA_METRIC 
    , 'RECORDS'  AS METRIC_FIELD
    , 'FATAL' AS ERROR_TYPE
    , SUBSTRING(AOU_DRIVER_PROD.AOU_ID, 2, LEN(AOU_DRIVER_PROD.AOU_ID)) AS CDT_ID

    
FROM CDM.AOU_DRIVER_PROD

WHERE (
        (
            (AOU_DRIVER_PROD.EPIC_PAT_ID) IN (
                SELECT EPIC_PAT_ID
                
                FROM CDM.AOU_DRIVER_PROD AS Tmp
                
                GROUP BY EPIC_PAT_ID
                
                HAVING Count(*) > 1
                )
            )
        )

ORDER BY CDM.AOU_DRIVER_PROD.EPIC_PAT_ID
 );