USE DATABASE SH_OMOP_DB_PROD;
USE SCHEMA CDM;
USE ROLE SF_SH_OMOP_DEVELOPER;
USE WAREHOUSE SH_OMOP_DATA_SCIENCE_WH;

CREATE OR REPLACE VIEW OMOP_QA.V_care_site_duplicates_detail AS (
---------------------------------------------------------------------
--care_site_duplicates_detail
---------------------------------------------------------------------
WITH TMP_DUPES AS (
SELECT  PLACE_OF_SERVICE_CONCEPT_ID, LOCATION_ID, PLACE_OF_SERVICE_SOURCE_VALUE,
        CARE_SITE_NAME, CARE_SITE_SOURCE_VALUE,
        COUNT(*) AS CNT
--INTO #TMP_DUPES
FROM CDM.CARE_SITE AS T1
GROUP BY  PLACE_OF_SERVICE_CONCEPT_ID, LOCATION_ID, PLACE_OF_SERVICE_SOURCE_VALUE,
        CARE_SITE_NAME, CARE_SITE_SOURCE_VALUE
HAVING COUNT(*) > 1
)

--INSERT INTO OMOP_QA.QA_ERR(
--	RUN_DATE
--	,STANDARD_DATA_TABLE
--	,QA_METRIC
--	,METRIC_FIELD
--	,ERROR_TYPE
--	,CDT_ID	)
SELECT CAST(GETDATE() AS DATE) AS RUN_DATE
	, 'CARE_SITE' AS STANDARD_DATA_TABLE
	, 'DUPLICATE ' AS QA_METRIC	
	, 'RECORDS'  AS METRIC_FIELD
	, 'FATAL' AS ERROR_TYPE
	, CS.CARE_SITE_ID
FROM TMP_DUPES AS D
INNER JOIN CDM.CARE_SITE AS CS ON 
	 COALESCE(D.CARE_SITE_NAME, '0') = COALESCE(CS.CARE_SITE_NAME, '0')
	AND COALESCE(D.PLACE_OF_SERVICE_CONCEPT_ID, 0) = COALESCE(CS.PLACE_OF_SERVICE_CONCEPT_ID, 0)
	AND COALESCE(D.LOCATION_ID, 0) = COALESCE(CS.LOCATION_ID, 0)
	AND COALESCE(D.CARE_SITE_SOURCE_VALUE, '0') = COALESCE(CS.CARE_SITE_SOURCE_VALUE, '0')
	AND COALESCE(D.PLACE_OF_SERVICE_SOURCE_VALUE, '0') = COALESCE(CS.PLACE_OF_SERVICE_SOURCE_VALUE, '0')
 );
 