USE DATABASE SH_OMOP_DB_PROD;
USE SCHEMA CDM;
USE ROLE SF_SH_OMOP_DEVELOPER;
USE WAREHOUSE SH_OMOP_DATA_SCIENCE_WH;


CREATE OR REPLACE VIEW OMOP_QA.V_care_site_duplicates_count AS (
---------------------------------------------------------------------
--care_site duplicates_count
---------------------------------------------------------------------
WITH TMP_DUPES AS (
SELECT  PLACE_OF_SERVICE_CONCEPT_ID, LOCATION_ID, PLACE_OF_SERVICE_SOURCE_VALUE,
        CARE_SITE_NAME, CARE_SITE_SOURCE_VALUE,
        COUNT(*) AS CNT
--INTO #TMP_DUPES
FROM CDM.CARE_SITE AS T1
GROUP BY  PLACE_OF_SERVICE_CONCEPT_ID, LOCATION_ID, PLACE_OF_SERVICE_SOURCE_VALUE,
        CARE_SITE_NAME, CARE_SITE_SOURCE_VALUE
HAVING COUNT(*) > 1
)

--INSERT INTO OMOP_QA.QA_LOG   (    
--		RUN_DATE
--      ,STANDARD_DATA_TABLE
--      ,QA_METRIC
--	  , METRIC_FIELD
--      ,QA_ERRORS
--      ,ERROR_TYPE
--	  ,TOTAL_RECORDS)
SELECT CAST(GETDATE() AS DATE) AS RUN_DATE
	, 'CARE_SITE' AS STANDARD_DATA_TABLE
	, 'DUPLICATE' AS QA_METRIC
	, 'RECORDS'  AS METRIC_FIELD
	, COALESCE(SUM(CNT),0) AS QA_ERRORS
	, CASE WHEN SUM(CNT) IS NOT NULL THEN 'FATAL' ELSE NULL END   AS ERROR_TYPE
	, (SELECT COUNT(*) AS NUM_ROWS FROM CDM.CARE_SITE) AS TOTAL_RECORDS
FROM TMP_DUPES
);
