USE DATABASE SH_OMOP_DB_PROD;
USE SCHEMA CDM;
USE ROLE SF_SH_OMOP_DEVELOPER;
USE WAREHOUSE SH_OMOP_DATA_SCIENCE_WH;


CREATE OR REPLACE VIEW OMOP_QA.V_CARE_SITE_NULLFK_DETAIL AS (
---------------------------------------------------------------------
--CARE_SITE_NULLFK_DETAIL
---------------------------------------------------------------------
WITH CTE_ERROR_DETAIL AS (
	SELECT 'CARE_SITE' AS STANDARD_DATA_TABLE
		,'LOCATION_ID' AS METRIC_FIELD
		,'NULL FK' AS QA_METRIC
		,'WARNING' AS ERROR_TYPE
		, CARE_SITE_ID AS CDT_ID
	FROM CDM.CARE_SITE 
	WHERE (LOCATION_ID IS NULL)
)
--INSERT INTO OMOP_QA.QA_ERR(    
--	RUN_DATE
--    ,STANDARD_DATA_TABLE
--    ,QA_METRIC
--	,METRIC_FIELD
--    ,ERROR_TYPE
--	,CDT_ID)
SELECT CAST(GETDATE() AS DATE) AS RUN_DATE
	, STANDARD_DATA_TABLE
	, QA_METRIC AS QA_METRIC
	, METRIC_FIELD  AS METRIC_FIELD
	, ERROR_TYPE
	, CDT_ID
FROM CTE_ERROR_DETAIL		
  WHERE ERROR_TYPE <>'EXPECTED'	
);
