USE DATABASE SH_OMOP_DB_PROD;
USE SCHEMA CDM;
USE ROLE SF_SH_OMOP_DEVELOPER;
USE WAREHOUSE SH_OMOP_DATA_SCIENCE_WH;

--DROP VIEW CDM.V_DEATH_NULL_CONCEPT_DETAIL;
CREATE OR REPLACE VIEW OMOP_QA.V_DEATH_NULL_CONCEPT_DETAIL AS (
---------------------------------------------------------------------
------ DEATH_NULL_CONCEPT_DETAIL -------------------------------------------
---------------------------------------------------------------------
WITH NULLCONCEPT_DETAIL AS (
	SELECT 'DEATH_TYPE_CONCEPT_ID' AS METRIC_FIELD,'NULL CONCEPT' AS QA_METRIC,'FATAL' AS ERROR_TYPE
		,PERSON_ID AS CDT_ID
	FROM CDM.DEATH AS T1
	WHERE (DEATH_TYPE_CONCEPT_ID IS NULL)
UNION ALL
	SELECT 'CAUSE_SOURCE_CONCEPT_ID' AS METRIC_FIELD,'NULL CONCEPT' AS QA_METRIC,'FATAL' AS ERROR_TYPE
		,PERSON_ID AS CDT_ID
	FROM CDM.DEATH AS T1
	WHERE (CAUSE_SOURCE_CONCEPT_ID IS NULL)
)
--INSERT INTO OMOP_QA.QA_ERR(    
--	RUN_DATE
--    ,STANDARD_DATA_TABLE
--    ,QA_METRIC
--	,METRIC_FIELD
--    ,ERROR_TYPE
--	,CDT_ID)
SELECT CAST( GETDATE() AS DATE) AS RUN_DATE
	,'DEATH' AS STANDARD_DATA_TABLE
	, QA_METRIC AS QA_METRIC
	, METRIC_FIELD  AS METRIC_FIELD
	, ERROR_TYPE
	, CDT_ID
FROM NULLCONCEPT_DETAIL			
  WHERE ERROR_TYPE <>'EXPECTED'	

 );
 