USE DATABASE SH_OMOP_DB_PROD;
USE SCHEMA CDM;
USE ROLE SF_SH_OMOP_DEVELOPER;
USE WAREHOUSE SH_OMOP_DATA_SCIENCE_WH;

CREATE OR REPLACE VIEW OMOP_QA.V_DEVICE_CONCEPT_DUPLICATES_DETAIL AS (
---------------------------------------------------------------------
--DEVICE_CONCEPT_DUPLICATES_DETAIL
---------------------------------------------------------------------
WITH TMP_DUPES AS (
SELECT PERSON_ID
	,DEVICE_CONCEPT_ID
	,DEVICE_EXPOSURE_START_DATE
	,DEVICE_EXPOSURE_START_DATETIME
	,DEVICE_EXPOSURE_END_DATE
	,DEVICE_EXPOSURE_END_DATETIME
	,DEVICE_TYPE_CONCEPT_ID
	,UNIQUE_DEVICE_ID
	,QUANTITY
	,PROVIDER_ID
	,VISIT_OCCURRENCE_ID
	,DEVICE_SOURCE_VALUE
	,DEVICE_SOURCE_CONCEPT_ID
	,COUNT(*) AS CNT


FROM CDM.DEVICE_EXPOSURE AS T1

WHERE T1.DEVICE_CONCEPT_ID != 0
	AND T1.DEVICE_CONCEPT_ID IS NOT NULL
	AND T1.PERSON_ID != 0
	AND T1.PERSON_ID IS NOT NULL

GROUP BY PERSON_ID
	,DEVICE_CONCEPT_ID
	,DEVICE_EXPOSURE_START_DATE
	,DEVICE_EXPOSURE_START_DATETIME
	,DEVICE_EXPOSURE_END_DATE
	,DEVICE_EXPOSURE_END_DATETIME
	,DEVICE_TYPE_CONCEPT_ID
	,UNIQUE_DEVICE_ID
	,QUANTITY
	,PROVIDER_ID
	,VISIT_OCCURRENCE_ID
	,DEVICE_SOURCE_VALUE
	,DEVICE_SOURCE_CONCEPT_ID
HAVING COUNT(*) > 1
)

--INSERT INTO OMOP_QA.QA_ERR(
--	RUN_DATE
--	,STANDARD_DATA_TABLE
--	,QA_METRIC
--	,METRIC_FIELD
--	,ERROR_TYPE
--	,CDT_ID	)
SELECT CAST(GETDATE() AS DATE) AS RUN_DATE
	,'DEVICE_EXPOSURE' AS STANDARD_DATA_TABLE
	, 'DUPLICATE' AS QA_METRIC
	, 'RECORDS'  AS METRIC_FIELD
	, 'FATAL' AS ERROR_TYPE
	,DE.DEVICE_EXPOSURE_ID

FROM TMP_DUPES AS D
INNER JOIN CDM.DEVICE_EXPOSURE AS DE ON D.PERSON_ID = DE.PERSON_ID
	AND D.DEVICE_CONCEPT_ID = DE.DEVICE_CONCEPT_ID
	AND D.DEVICE_EXPOSURE_START_DATE = DE.DEVICE_EXPOSURE_START_DATE
	AND D.DEVICE_EXPOSURE_START_DATETIME = DE.DEVICE_EXPOSURE_START_DATETIME
	AND COALESCE(D.DEVICE_EXPOSURE_END_DATE,'1900-01-01') = COALESCE(DE.DEVICE_EXPOSURE_END_DATE,'1900-01-01')
	AND COALESCE(D.DEVICE_EXPOSURE_END_DATETIME,'1900-01-01') = COALESCE(DE.DEVICE_EXPOSURE_END_DATETIME,'1900-01-01')
	AND COALESCE(D.DEVICE_TYPE_CONCEPT_ID, 0) = COALESCE(DE.DEVICE_TYPE_CONCEPT_ID, 0)
	AND COALESCE(D.UNIQUE_DEVICE_ID, '0') = COALESCE(DE.UNIQUE_DEVICE_ID, '0')
	AND COALESCE(D.QUANTITY, 0) = COALESCE(DE.QUANTITY, 0)
	AND COALESCE(D.PROVIDER_ID, 0) = COALESCE(DE.PROVIDER_ID, 0)
	AND COALESCE(D.VISIT_OCCURRENCE_ID, 0) = COALESCE(DE.VISIT_OCCURRENCE_ID, 0)
	AND COALESCE(D.DEVICE_SOURCE_VALUE, '0') = COALESCE(DE.DEVICE_SOURCE_VALUE, '0')
	AND COALESCE(D.DEVICE_SOURCE_CONCEPT_ID, 0) = COALESCE(DE.DEVICE_SOURCE_CONCEPT_ID, 0)
 );
 