USE DATABASE SH_OMOP_DB_PROD;
USE SCHEMA CDM;
USE ROLE SF_SH_OMOP_DEVELOPER;
USE WAREHOUSE SH_OMOP_DATA_SCIENCE_WH;


CREATE OR REPLACE VIEW OMOP_QA.V_DEVICE_CONCEPT_DUPLICATES_COUNT AS (
---------------------------------------------------------------------
--DEVICE_CONCEPT_DUPLICATES_COUNT
---------------------------------------------------------------------
WITH TMP_DUPES AS (
SELECT PERSON_ID
	,DEVICE_CONCEPT_ID
	,DEVICE_EXPOSURE_START_DATE
	,DEVICE_EXPOSURE_START_DATETIME
	,DEVICE_EXPOSURE_END_DATE
	,DEVICE_EXPOSURE_END_DATETIME
	,DEVICE_TYPE_CONCEPT_ID
	,UNIQUE_DEVICE_ID
	,QUANTITY
	,PROVIDER_ID
	,VISIT_OCCURRENCE_ID
	,DEVICE_SOURCE_VALUE
	,DEVICE_SOURCE_CONCEPT_ID
	,COUNT(*) AS CNT

FROM CDM.DEVICE_EXPOSURE AS T1

WHERE T1.DEVICE_CONCEPT_ID != 0
	AND T1.DEVICE_CONCEPT_ID IS NOT NULL
	AND T1.PERSON_ID != 0
	AND T1.PERSON_ID IS NOT NULL

GROUP BY PERSON_ID
	,DEVICE_CONCEPT_ID
	,DEVICE_EXPOSURE_START_DATE
	,DEVICE_EXPOSURE_START_DATETIME
	,DEVICE_EXPOSURE_END_DATE
	,DEVICE_EXPOSURE_END_DATETIME
	,DEVICE_TYPE_CONCEPT_ID
	,UNIQUE_DEVICE_ID
	,QUANTITY
	,PROVIDER_ID
	,VISIT_OCCURRENCE_ID
	,DEVICE_SOURCE_VALUE
	,DEVICE_SOURCE_CONCEPT_ID
HAVING COUNT(*) > 1
)

--
--INSERT INTO OMOP_QA.QA_LOG   (    
--		RUN_DATE
--      ,STANDARD_DATA_TABLE
--      ,QA_METRIC
--	  , METRIC_FIELD
--      ,QA_ERRORS
--      ,ERROR_TYPE
--	  ,TOTAL_RECORDS)
SELECT CAST(GETDATE() AS DATE) AS RUN_DATE
	, 'DEVICE_EXPOSURE' AS STANDARD_DATA_TABLE
	, 'DUPLICATE' AS QA_METRIC
	, 'RECORDS'  AS METRIC_FIELD
	, COALESCE(SUM(CNT),0) AS QA_ERRORS
	, CASE WHEN SUM(CNT) IS NOT NULL THEN 'FATAL' ELSE NULL END   AS ERROR_TYPE
	, (SELECT COUNT(*) AS NUM_ROWS FROM CDM.DEVICE_EXPOSURE) AS TOTAL_RECORDS
FROM TMP_DUPES
);
