USE DATABASE SH_OMOP_DB_PROD;
USE SCHEMA CDM;
USE ROLE SF_SH_OMOP_DEVELOPER;
USE WAREHOUSE SH_OMOP_DATA_SCIENCE_WH;


CREATE OR REPLACE VIEW OMOP_QA.V_DEVICE_EXPOSURE_NOMATCH_DETAIL AS (
---------------------------------------------------------------------
--DEVICE_EXPOSURE_NOMATCH_DETAIL
---------------------------------------------------------------------
WITH CTE_NO_MATCH_DETAIL AS (
	SELECT 'DEVICE_EXPOSURE' AS STANDARD_DATA_TABLE
		,'DEVICE_CONCEPT_ID' AS METRIC_FIELD
		,'NO-MATCH' AS QA_METRIC
		,'FATAL' AS ERROR_TYPE
		,DEVICE_EXPOSURE_ID AS CDT_ID
	FROM CDM.DEVICE_EXPOSURE AS P
	LEFT JOIN CDM.CONCEPT AS C ON P.DEVICE_CONCEPT_ID = C.CONCEPT_ID
	WHERE DEVICE_CONCEPT_ID <> 0
		AND CONCEPT_ID IS NULL

	UNION ALL

	SELECT 'DEVICE_EXPOSURE' AS STANDARD_DATA_TABLE
		,'DEVICE_TYPE_CONCEPT_ID' AS METRIC_FIELD
		,'NO-MATCH' AS QA_METRIC
		,'FATAL' AS ERROR_TYPE
		,DEVICE_EXPOSURE_ID AS CDT_ID
	FROM CDM.DEVICE_EXPOSURE AS P
	LEFT JOIN CDM.CONCEPT AS C ON P.DEVICE_TYPE_CONCEPT_ID = C.CONCEPT_ID
	WHERE DEVICE_TYPE_CONCEPT_ID <> 0
		AND CONCEPT_ID IS NULL

	UNION ALL

	SELECT 'DEVICE_EXPOSURE' AS STANDARD_DATA_TABLE
		,'DEVICE_SOURCE_CONCEPT_ID' AS METRIC_FIELD
		,'NO-MATCH' AS QA_METRIC
		,'FATAL' AS ERROR_TYPE
		,DEVICE_EXPOSURE_ID AS CDT_ID
	FROM CDM.DEVICE_EXPOSURE AS P
	LEFT JOIN CDM.CONCEPT AS C ON P.DEVICE_SOURCE_CONCEPT_ID = C.CONCEPT_ID
	WHERE DEVICE_SOURCE_CONCEPT_ID <> 0
		AND CONCEPT_ID IS NULL
)
--INSERT INTO OMOP_QA.QA_ERR  (    
--	RUN_DATE
--	,STANDARD_DATA_TABLE
--	,QA_METRIC
--	,METRIC_FIELD
--	,ERROR_TYPE
--	,CDT_ID)
SELECT CAST(GETDATE() AS DATE) AS RUN_DATE
	, STANDARD_DATA_TABLE
	, QA_METRIC AS QA_METRIC
	, METRIC_FIELD  AS METRIC_FIELD
	, ERROR_TYPE
	, CDT_ID
FROM CTE_NO_MATCH_DETAIL	
  WHERE ERROR_TYPE <>'EXPECTED'	
);
