USE DATABASE SH_OMOP_DB_PROD;
USE SCHEMA CDM;
USE ROLE SF_SH_OMOP_DEVELOPER;
USE WAREHOUSE SH_OMOP_DATA_SCIENCE_WH;


CREATE OR REPLACE VIEW OMOP_QA.V_DEATH_DUPLICATES_COUNT AS (
---------------------------------------------------------------------
--DEATH_DUPLICATES_COUNT
---------------------------------------------------------------------
WITH TMP_DUPES AS (
SELECT DEATH_DATE
	,DEATH_DATETIME
	,DEATH_TYPE_CONCEPT_ID
	,CAUSE_CONCEPT_ID
	,CAUSE_SOURCE_VALUE
	,CAUSE_SOURCE_CONCEPT_ID
	,COUNT(*) AS CNT
FROM CDM.DEATH AS T1
GROUP BY DEATH_DATE
	,DEATH_DATETIME
	,DEATH_TYPE_CONCEPT_ID
	,CAUSE_CONCEPT_ID
	,CAUSE_SOURCE_VALUE
	,CAUSE_SOURCE_CONCEPT_ID
HAVING COUNT(*) > 1
)
--
--INSERT INTO OMOP_QA.QA_LOG   (    
--		RUN_DATE
--      ,STANDARD_DATA_TABLE
--      ,QA_METRIC
--	  , METRIC_FIELD
--      ,QA_ERRORS
--      ,ERROR_TYPE
--	  ,TOTAL_RECORDS)

SELECT CAST(GETDATE() AS DATE) AS RUN_DATE
	,'DEATH' AS STANDARD_DATA_TABLE
	, 'DUPLICATE' AS QA_METRIC
	, 'RECORDS'  AS METRIC_FIELD
	, COALESCE(SUM(CNT),0) AS QA_ERRORS
	, CASE WHEN SUM(CNT) IS NOT NULL THEN 'FATAL' ELSE NULL END   AS ERROR_TYPE
	, (SELECT COUNT(*) AS NUM_ROWS FROM CDM.DEATH) AS TOTAL_RECORDS
FROM TMP_DUPES
);
