USE DATABASE SH_OMOP_DB_PROD;
USE SCHEMA CDM;
USE ROLE SF_SH_OMOP_DEVELOPER;
USE WAREHOUSE SH_OMOP_DATA_SCIENCE_WH;

--DROP VIEW CDM.V_DRUG_EXPOSURE_NONSTANDARD_COUNT;
CREATE OR REPLACE VIEW OMOP_QA.V_DRUG_EXPOSURE_NONSTANDARD_COUNT AS (
-------------------------------------------------------------------
---- DRUG_EXPOSURE NON STANDARD INVALID DATA-----------------------
-------------------------------------------------------------------
----DRUG_EXPOSURE_NONSTANDARD_COUNT
-------------------------------------------------------------------
WITH NONSTANDARD_COUNT
AS (
	SELECT 'DRUG_CONCEPT_ID' AS METRIC_FIELD, 'NON-STANDARD' AS QA_METRIC, 'INVALID DATA' AS ERROR_TYPE, COUNT(*) AS CNT
	FROM CDM.DRUG_EXPOSURE AS DE
	LEFT JOIN CDM.CONCEPT AS C
		ON DE.DRUG_CONCEPT_ID = C.CONCEPT_ID AND upper(C.DOMAIN_ID) = 'DRUG' AND upper(C.VOCABULARY_ID) =  'RXNORM'
	WHERE DRUG_CONCEPT_ID <> 0 AND DRUG_CONCEPT_ID IS NOT NULL AND (STANDARD_CONCEPT <> 'S' OR STANDARD_CONCEPT IS NULL)
	
	UNION ALL
	
	SELECT 'DRUG_TYPE_CONCEPT_ID' AS METRIC_FIELD, 'NON-STANDARD' AS QA_METRIC, 'INVALID DATA' AS ERROR_TYPE, COUNT(*) AS CNT
	FROM CDM.DRUG_EXPOSURE AS DE
	LEFT JOIN CDM.CONCEPT AS C
		ON DE.DRUG_TYPE_CONCEPT_ID = C.CONCEPT_ID AND upper(C.DOMAIN_ID) = 'TYPE CONCEPT' AND upper(C.VOCABULARY_ID) =  'TYPE CONCEPT'
	WHERE DRUG_TYPE_CONCEPT_ID <> 0 AND DRUG_TYPE_CONCEPT_ID IS NOT NULL AND (STANDARD_CONCEPT <> 'S' OR STANDARD_CONCEPT IS NULL)
	
	UNION ALL
	
	SELECT 'ROUTE_CONCEPT_ID' AS METRIC_FIELD, 'NON-STANDARD' AS QA_METRIC, 'INVALID DATA' AS ERROR_TYPE, COUNT(*) AS CNT
	FROM CDM.DRUG_EXPOSURE AS DE
	LEFT JOIN CDM.CONCEPT AS C
		ON DE.ROUTE_CONCEPT_ID = C.CONCEPT_ID AND upper(C.DOMAIN_ID) = 'ROUTE' AND upper(C.VOCABULARY_ID) =  'SNOMED'
	WHERE ROUTE_CONCEPT_ID <> 0 AND ROUTE_CONCEPT_ID IS NOT NULL AND (STANDARD_CONCEPT <> 'S' OR STANDARD_CONCEPT IS NULL)
	
	UNION ALL
	
	SELECT 'DRUG_SOURCE_CONCEPT_ID' AS METRIC_FIELD, 'NON-STANDARD' AS QA_METRIC, 'INVALID DATA' AS ERROR_TYPE, --C.CONCEPT_ID, STANDARD_CONCEPT,
		COUNT(*) AS CNT
	FROM CDM.DRUG_EXPOSURE AS DE
	LEFT JOIN CDM.CONCEPT AS C
		ON DE.DRUG_SOURCE_CONCEPT_ID = C.CONCEPT_ID AND upper(C.DOMAIN_ID) = 'DRUG' AND upper(C.VOCABULARY_ID) =  'RXNORM'
	WHERE DRUG_TYPE_CONCEPT_ID <> 0 AND C.CONCEPT_ID IS NULL
)

--INSERT INTO OMOP_QA.QA_LOG   (    
--		RUN_DATE
--      ,STANDARD_DATA_TABLE
--      ,QA_METRIC
--	  , METRIC_FIELD
--      ,QA_ERRORS
--      ,ERROR_TYPE
--	  ,TOTAL_RECORDS)

SELECT CAST(GETDATE() AS DATE) AS RUN_DATE
	,'DRUG_EXPOSURE' AS STANDARD_DATA_TABLE
	, QA_METRIC AS QA_METRIC	
	, METRIC_FIELD  AS METRIC_FIELD
	, COALESCE (SUM(CNT),0) AS QA_ERRORS
	, CASE WHEN SUM(CNT) <> 0 THEN ERROR_TYPE ELSE NULL END   AS ERROR_TYPE
	, (SELECT COUNT(*) AS NUM_ROWS FROM CDM.DRUG_EXPOSURE) AS TOTAL_RECORDS
FROM NONSTANDARD_COUNT	
GROUP BY   METRIC_FIELD, QA_METRIC, ERROR_TYPE
);
