USE DATABASE SH_OMOP_DB_PROD;
USE SCHEMA CDM;
USE ROLE SF_SH_OMOP_DEVELOPER;
USE WAREHOUSE SH_OMOP_DATA_SCIENCE_WH;


CREATE OR REPLACE VIEW OMOP_QA.V_DRUG_EXPOSURE_NOVISIT_DETAIL AS (
---------------------------------------------------------------------
--DRUG_EXPOSURE_NOVISIT_DETAIL
---------------------------------------------------------------------
WITH NOVISIT_DETAIL AS (
SELECT 'VISIT_OCCURRENCE_ID' AS METRIC_FIELD, 'NO VISIT' AS QA_METRIC, 'WARNING' AS ERROR_TYPE, DRUG_EXPOSURE_ID AS CDT_ID
		
FROM CDM.DRUG_EXPOSURE
LEFT JOIN CDM.VISIT_OCCURRENCE
	ON DRUG_EXPOSURE.VISIT_OCCURRENCE_ID = VISIT_OCCURRENCE.VISIT_OCCURRENCE_ID
WHERE (VISIT_OCCURRENCE.VISIT_OCCURRENCE_ID IS NULL)
)
--
--INSERT INTO OMOP_QA.QA_ERR(    
--	 RUN_DATE
--    ,STANDARD_DATA_TABLE
--    ,QA_METRIC
--	,METRIC_FIELD
--    ,ERROR_TYPE
--	,CDT_ID)
SELECT CAST(GETDATE() AS DATE) AS RUN_DATE
	,'DRUG_EXPOSURE' AS STANDARD_DATA_TABLE
	, QA_METRIC AS QA_METRIC
	, METRIC_FIELD  AS METRIC_FIELD
	, ERROR_TYPE
	, CDT_ID
FROM NOVISIT_DETAIL		
  WHERE ERROR_TYPE <>'EXPECTED'						
);
