USE DATABASE SH_OMOP_DB_PROD;
USE SCHEMA CDM;
USE ROLE SF_SH_OMOP_DEVELOPER;
USE WAREHOUSE SH_OMOP_DATA_SCIENCE_WH;


CREATE OR REPLACE VIEW OMOP_QA.V_DRUG_EXPOSURE_NOMATCH_DETAIL AS (
---------------------------------------------------------------------
--DRUG_EXPOSURE_NOMATCH_DETAIL
---------------------------------------------------------------------
WITH NOMATCH_DETAIL
AS (
	SELECT 'DRUG_CONCEPT_ID' AS METRIC_FIELD, 'NO-MATCH' AS QA_METRIC, 'FATAL' AS ERROR_TYPE
		, DRUG_EXPOSURE_ID AS CDT_ID
	FROM CDM.DRUG_EXPOSURE AS DE
	LEFT JOIN CDM.CONCEPT AS C
		ON DE.DRUG_CONCEPT_ID = C.CONCEPT_ID
	WHERE DRUG_CONCEPT_ID <> 0 AND CONCEPT_ID IS NULL
	
	UNION ALL
	
	SELECT 'DRUG_TYPE_CONCEPT_ID' AS METRIC_FIELD, 'NO-MATCH' AS QA_METRIC, 'FATAL' AS ERROR_TYPE
		, DRUG_EXPOSURE_ID AS CDT_ID
	FROM CDM.DRUG_EXPOSURE AS DE
	LEFT JOIN CDM.CONCEPT AS C
		ON DE.DRUG_TYPE_CONCEPT_ID = C.CONCEPT_ID
	WHERE DRUG_TYPE_CONCEPT_ID <> 0 AND CONCEPT_ID IS NULL
	
	UNION ALL
	
	SELECT 'ROUTE_CONCEPT_ID' AS METRIC_FIELD, 'NO-MATCH' AS QA_METRIC, 'FATAL' AS ERROR_TYPE
		, DRUG_EXPOSURE_ID AS CDT_ID
	FROM CDM.DRUG_EXPOSURE AS DE
	LEFT JOIN CDM.CONCEPT AS C
		ON DE.ROUTE_CONCEPT_ID = C.CONCEPT_ID
	WHERE ROUTE_CONCEPT_ID <> 0 AND CONCEPT_ID IS NULL
	
	UNION ALL
	
	SELECT 'DRUG_SOURCE_CONCEPT_ID' AS METRIC_FIELD, 'NO-MATCH' AS QA_METRIC, 'FATAL' AS ERROR_TYPE
		, DRUG_EXPOSURE_ID AS CDT_ID
	FROM CDM.DRUG_EXPOSURE AS DE
	LEFT JOIN CDM.CONCEPT AS C
		ON DE.DRUG_SOURCE_CONCEPT_ID = C.CONCEPT_ID
	WHERE DRUG_SOURCE_CONCEPT_ID <> 0 AND CONCEPT_ID IS NULL
)

--INSERT INTO OMOP_QA.QA_ERR(    
--	 RUN_DATE
--    ,STANDARD_DATA_TABLE
--    ,QA_METRIC
--	,METRIC_FIELD
--    ,ERROR_TYPE
--	,CDT_ID)
SELECT CAST(GETDATE() AS DATE) AS RUN_DATE
	,'DRUG_EXPOSURE' AS STANDARD_DATA_TABLE
	, QA_METRIC AS QA_METRIC
	, METRIC_FIELD  AS METRIC_FIELD
	, ERROR_TYPE
	, CDT_ID
FROM NOMATCH_DETAIL		
  WHERE ERROR_TYPE <>'EXPECTED'	
);
