USE DATABASE SH_OMOP_DB_PROD;
USE SCHEMA OMOP;
USE ROLE SF_SH_OMOP_DEVELOPER;
USE WAREHOUSE SH_OMOP_DATA_SCIENCE_WH;

CREATE OR REPLACE VIEW OMOP_QA.V_ERR_LOG AS (

SELECT  *
FROM SH_OMOP_DB_PROD.OMOP_QA.V_CARE_SITE_NON_STANDARD_COUNT
UNION SELECT  * FROM
SH_OMOP_DB_PROD.OMOP_QA.V_CARE_SITE_NULL_CONCEPT_COUNT
UNION SELECT  * FROM
SH_OMOP_DB_PROD.OMOP_QA.V_CARE_SITE_ZERO_CONCEPT_COUNT
UNION SELECT  * FROM
SH_OMOP_DB_PROD.OMOP_QA.V_CONDITION_30AFTERDEATH_COUNT
UNION SELECT  * FROM
SH_OMOP_DB_PROD.OMOP_QA.V_CONDITION_OCCURRENCE_NONSTANDARD_COUNT
UNION SELECT  * FROM
SH_OMOP_DB_PROD.OMOP_QA.V_CONDITION_OCCURRENCE_NULLCONCEPT_COUNT
UNION SELECT  * FROM
SH_OMOP_DB_PROD.OMOP_QA.V_CONDITION_OCCURRENCE_ZEROCONCEPT_COUNT
UNION SELECT  * FROM
SH_OMOP_DB_PROD.OMOP_QA.V_DEATH_NULL_CONCEPT_COUNT
UNION SELECT  * FROM
SH_OMOP_DB_PROD.OMOP_QA.V_DEATH_ZERO_CONCEPT_COUNT
UNION SELECT  * FROM
SH_OMOP_DB_PROD.OMOP_QA.V_DEVICE_EXPOSURE_NONSTANDARD_COUNT
UNION SELECT  * FROM
SH_OMOP_DB_PROD.OMOP_QA.V_DEVICE_EXPOSURE_NULL_CONCEPT_COUNT
UNION SELECT  * FROM
SH_OMOP_DB_PROD.OMOP_QA.V_DEVICE_EXPOSURE_ZERO_CONCEPT_COUNT
UNION SELECT  * FROM
SH_OMOP_DB_PROD.OMOP_QA.V_DRUG_30AFTERDEATH_COUNT
UNION SELECT  * FROM
SH_OMOP_DB_PROD.OMOP_QA.V_DRUG_EXPOSURE_NONSTANDARD_COUNT
UNION SELECT  * FROM
SH_OMOP_DB_PROD.OMOP_QA.V_DRUG_EXPOSURE_NULLCONCEPT_COUNT
UNION SELECT  * FROM
SH_OMOP_DB_PROD.OMOP_QA.V_DRUG_EXPOSURE_ZEROCONCEPT_COUNT
UNION SELECT  * FROM
SH_OMOP_DB_PROD.OMOP_QA.V_MEASUREMENT30AFTERDEATH_COUNT
UNION SELECT  * FROM
SH_OMOP_DB_PROD.OMOP_QA.V_MEASUREMENT_NONSTANDARD_COUNT
UNION SELECT  * FROM
SH_OMOP_DB_PROD.OMOP_QA.V_MEASUREMENT_NULLCONCEPT_COUNT
UNION SELECT  * FROM
SH_OMOP_DB_PROD.OMOP_QA.V_MEASUREMENT_ZEROCONCEPT_COUNT
UNION SELECT  * FROM
SH_OMOP_DB_PROD.OMOP_QA.V_NOTE_NONSTANDARD_COUNT
UNION SELECT  * FROM
SH_OMOP_DB_PROD.OMOP_QA.V_NOTE_NULLCONCEPT_COUNT
UNION SELECT  * FROM
SH_OMOP_DB_PROD.OMOP_QA.V_NOTE_ZEROCONCEPT_COUNT
UNION SELECT  * FROM
SH_OMOP_DB_PROD.OMOP_QA.V_OBSERVATION_NONSTANDARD_COUNT
UNION SELECT  * FROM
SH_OMOP_DB_PROD.OMOP_QA.V_OBSERVATION_NULLCONCEPT_COUNT
UNION SELECT  * FROM
SH_OMOP_DB_PROD.OMOP_QA.V_OBSERVATION_ZEROCONCEPT_COUNT
UNION SELECT  * FROM
SH_OMOP_DB_PROD.OMOP_QA.V_PERSON_NONSTANDARD_COUNT
UNION SELECT  * FROM
SH_OMOP_DB_PROD.OMOP_QA.V_PERSON_NULLCONCEPT_COUNT
UNION SELECT  * FROM
SH_OMOP_DB_PROD.OMOP_QA.V_PERSON_ZEROCONCEPT_COUNT
UNION SELECT  * FROM
SH_OMOP_DB_PROD.OMOP_QA.V_PROCEDURE_30AFTERDEATH_COUNT
UNION SELECT  * FROM
SH_OMOP_DB_PROD.OMOP_QA.V_PROCEDURE_OCCURRENCE_NON_STANDARD_COUNT
UNION SELECT  * FROM
SH_OMOP_DB_PROD.OMOP_QA.V_PROCEDURE_OCCURRENCE_NULLCONCEPT_COUNT
UNION SELECT  * FROM
SH_OMOP_DB_PROD.OMOP_QA.V_PROCEDURE_OCCURRENCE_ZEROCONCEPT_COUNT
UNION SELECT  * FROM
SH_OMOP_DB_PROD.OMOP_QA.V_PROVIDER_NONSTANDARD_COUNT
UNION SELECT  * FROM
SH_OMOP_DB_PROD.OMOP_QA.V_PROVIDER_NULL_CONCEPT_COUNT
UNION SELECT  * FROM
SH_OMOP_DB_PROD.OMOP_QA.V_PROVIDER_ZEROCONCEPT_COUNT
UNION SELECT  * FROM
SH_OMOP_DB_PROD.OMOP_QA.V_SPECIMEN_NONSTANDARD_COUNT
UNION SELECT  * FROM
SH_OMOP_DB_PROD.OMOP_QA.V_SPECIMEN_NULLCONCEPT_COUNT
UNION SELECT  * FROM
SH_OMOP_DB_PROD.OMOP_QA.V_SPECIMEN_ZEROCONCEPT_COUNT
UNION SELECT  * FROM
SH_OMOP_DB_PROD.OMOP_QA.V_VISIT_30AFTERDEATH_COUNT
UNION SELECT  * FROM
SH_OMOP_DB_PROD.OMOP_QA.V_VISIT_OCCURRENCE_DUPLICATES_COUNT
UNION SELECT  * FROM
SH_OMOP_DB_PROD.OMOP_QA.V_VISIT_OCCURRENCE_NONSTANDARD_COUNT
UNION SELECT  * FROM
SH_OMOP_DB_PROD.OMOP_QA.V_VISIT_OCCURRENCE_NULLCONCEPT_COUNT
UNION SELECT  * FROM
SH_OMOP_DB_PROD.OMOP_QA.V_VISIT_OCCURRENCE_ZEROCONCEPT_COUNT

);


