USE DATABASE SH_OMOP_DB_PROD;
USE SCHEMA CDM;
USE ROLE SF_SH_OMOP_DEVELOPER;
USE WAREHOUSE SH_OMOP_DATA_SCIENCE_WH;


CREATE OR REPLACE VIEW OMOP_QA.V_MEASUREMENT_NOMATCH_DETAIL AS (
---------------------------------------------------------------------
--MEASUREMENT_NOMATCH_DETAIL
---------------------------------------------------------------------
WITH NOMATCH_DETAIL
AS (
	SELECT 'MEASUREMENT_CONCEPT_ID' AS METRIC_FIELD, 'NO-MATCH' AS QA_METRIC, 'FATAL' AS ERROR_TYPE
		, MEASUREMENT_ID AS CDT_ID
	--,MEASUREMENT_CONCEPT_ID, CONCEPT_ID
	FROM CDM.MEASUREMENT AS M
	LEFT JOIN CDM.CONCEPT AS C
		ON M.MEASUREMENT_CONCEPT_ID = C.CONCEPT_ID
	WHERE MEASUREMENT_CONCEPT_ID <> 0 AND CONCEPT_ID IS NULL
	
	UNION ALL
	
	SELECT 'MEASUREMENT_TYPE_CONCEPT_ID' AS METRIC_FIELD, 'NO-MATCH' AS QA_METRIC, 'FATAL' AS ERROR_TYPE
		, MEASUREMENT_ID AS CDT_ID
	FROM CDM.MEASUREMENT AS M
	LEFT JOIN CDM.CONCEPT AS C
		ON M.MEASUREMENT_TYPE_CONCEPT_ID = C.CONCEPT_ID
	WHERE MEASUREMENT_TYPE_CONCEPT_ID <> 0 AND CONCEPT_ID IS NULL
	
	UNION ALL
	
	SELECT 'OPERATOR_CONCEPT_ID' AS METRIC_FIELD, 'NO-MATCH' AS QA_METRIC, 'FATAL' AS ERROR_TYPE
		, MEASUREMENT_ID AS CDT_ID
	FROM CDM.MEASUREMENT AS M
	LEFT JOIN CDM.CONCEPT AS C
		ON M.OPERATOR_CONCEPT_ID = C.CONCEPT_ID
	WHERE OPERATOR_CONCEPT_ID <> 0 AND CONCEPT_ID IS NULL
	
	UNION ALL
	
	SELECT 'VALUE_AS_CONCEPT_ID' AS METRIC_FIELD, 'NO-MATCH' AS QA_METRIC, 'FATAL' AS ERROR_TYPE
		, MEASUREMENT_ID AS CDT_ID
	FROM CDM.MEASUREMENT AS M
	LEFT JOIN CDM.CONCEPT AS C
		ON M.VALUE_AS_CONCEPT_ID = C.CONCEPT_ID
	WHERE VALUE_AS_CONCEPT_ID <> 0 AND CONCEPT_ID IS NULL
	
	UNION ALL
	
	SELECT 'UNIT_CONCEPT_ID' AS METRIC_FIELD, 'NO-MATCH' AS QA_METRIC, 'FATAL' AS ERROR_TYPE
		, MEASUREMENT_ID AS CDT_ID
	FROM CDM.MEASUREMENT AS M
	LEFT JOIN CDM.CONCEPT AS C
		ON M.UNIT_CONCEPT_ID = C.CONCEPT_ID
	WHERE UNIT_CONCEPT_ID <> 0 AND CONCEPT_ID IS NULL
	
	UNION ALL
	
	SELECT 'MEASUREMENT_SOURCE_CONCEPT_ID' AS METRIC_FIELD, 'NO-MATCH' AS QA_METRIC, 'FATAL' AS ERROR_TYPE
		, MEASUREMENT_ID AS CDT_ID
	FROM CDM.MEASUREMENT AS M
	LEFT JOIN CDM.CONCEPT AS C
		ON M.MEASUREMENT_SOURCE_CONCEPT_ID = C.CONCEPT_ID
	WHERE MEASUREMENT_SOURCE_CONCEPT_ID <> 0 AND CONCEPT_ID IS NULL
)

--INSERT INTO OMOP_QA.QA_ERR(    
--	 RUN_DATE
--    ,STANDARD_DATA_TABLE
--    ,QA_METRIC
--	,METRIC_FIELD
--    ,ERROR_TYPE
--	,CDT_ID)
SELECT CAST(GETDATE() AS DATE) AS RUN_DATE
	,'MEASUREMENT' AS STANDARD_DATA_TABLE
	, QA_METRIC AS QA_METRIC
	, METRIC_FIELD  AS METRIC_FIELD
	, ERROR_TYPE
	, CDT_ID
FROM NOMATCH_DETAIL		
  WHERE ERROR_TYPE <>'EXPECTED'	
);
