USE DATABASE SH_OMOP_DB_PROD;
USE SCHEMA CDM;
USE ROLE SF_SH_OMOP_DEVELOPER;
USE WAREHOUSE SH_OMOP_DATA_SCIENCE_WH;

--DROP VIEW CDM.V_MEASUREMENT_NULLCONCEPT_DETAIL;
CREATE OR REPLACE VIEW OMOP_QA.V_MEASUREMENT_NULLCONCEPT_DETAIL AS (
---------------------------------------------------------------------
------ MEASUREMENT_NULLCONCEPT_DETAIL
--------------------------------------------------------------------- 
WITH NULLCONCEPT_DETAIL
AS (
	SELECT 'MEASUREMENT_CONCEPT_ID' AS METRIC_FIELD, 'NULL CONCEPT' AS QA_METRIC, 'FATAL' AS ERROR_TYPE
		, MEASUREMENT_ID AS CDT_ID
	FROM CDM.MEASUREMENT
	WHERE (MEASUREMENT_CONCEPT_ID IS NULL)
	
	UNION ALL
	
	SELECT 'OPERATOR_CONCEPT_ID' AS METRIC_FIELD, 'NULL CONCEPT' AS QA_METRIC, 'FATAL' AS ERROR_TYPE
		, MEASUREMENT_ID AS CDT_ID
	FROM CDM.MEASUREMENT
	WHERE (OPERATOR_CONCEPT_ID IS NULL)
	
	UNION ALL
	
	SELECT 'VALUE_AS_CONCEPT_ID' AS METRIC_FIELD, 'NULL CONCEPT' AS QA_METRIC, 'FATAL' AS ERROR_TYPE
		, MEASUREMENT_ID AS CDT_ID
	FROM CDM.MEASUREMENT
	WHERE (VALUE_AS_CONCEPT_ID IS NULL)
	
	UNION ALL
	
	SELECT 'UNIT_CONCEPT_ID' AS METRIC_FIELD, 'NULL CONCEPT' AS QA_METRIC, 'FATAL' AS ERROR_TYPE
		, MEASUREMENT_ID AS CDT_ID
	FROM CDM.MEASUREMENT
	WHERE (UNIT_CONCEPT_ID IS NULL)
	
	UNION ALL
	
	SELECT 'MEASUREMENT_SOURCE_CONCEPT_ID' AS METRIC_FIELD, 'NULL CONCEPT' AS QA_METRIC, 'FATAL' AS ERROR_TYPE
		, MEASUREMENT_ID AS CDT_ID
	FROM CDM.MEASUREMENT
	WHERE (MEASUREMENT_SOURCE_CONCEPT_ID IS NULL)
)

--INSERT INTO OMOP_QA.QA_ERR(    
--	 RUN_DATE
--    ,STANDARD_DATA_TABLE
--    ,QA_METRIC
--	,METRIC_FIELD
--    ,ERROR_TYPE
--	,CDT_ID)
SELECT CAST( GETDATE() AS DATE) AS RUN_DATE
	,'MEASUREMENT' AS STANDARD_DATA_TABLE
	, QA_METRIC AS QA_METRIC
	, METRIC_FIELD  AS METRIC_FIELD
	, ERROR_TYPE
	, CDT_ID
FROM NULLCONCEPT_DETAIL	
  WHERE ERROR_TYPE <>'EXPECTED'	
 );
 