USE DATABASE SH_OMOP_DB_PROD;
USE SCHEMA CDM;
USE ROLE SF_SH_OMOP_DEVELOPER;
USE WAREHOUSE SH_OMOP_DATA_SCIENCE_WH;


CREATE OR REPLACE VIEW OMOP_QA.V_MEASUREMENT_DUPLICATES_COUNT AS (
---------------------------------------------------------------------
--MEASUREMENT_DUPLICATES_COUNT
---------------------------------------------------------------------
WITH TMP_DUPES AS (
SELECT PERSON_ID
	,MEASUREMENT_CONCEPT_ID
	,MEASUREMENT_DATE
	,MEASUREMENT_DATETIME
	,MEASUREMENT_TYPE_CONCEPT_ID
	,OPERATOR_CONCEPT_ID
	,VALUE_AS_NUMBER
	,VALUE_AS_CONCEPT_ID
	,UNIT_CONCEPT_ID
	,RANGE_LOW
	,RANGE_HIGH
	,PROVIDER_ID
	,VISIT_OCCURRENCE_ID
	,MEASUREMENT_SOURCE_VALUE
	,MEASUREMENT_SOURCE_CONCEPT_ID
	,UNIT_SOURCE_VALUE
	,VALUE_SOURCE_VALUE
	,COUNT(*) AS CNT
FROM CDM.MEASUREMENT AS T1
WHERE T1.MEASUREMENT_CONCEPT_ID <> 0
	AND T1.MEASUREMENT_CONCEPT_ID IS NOT NULL
	AND T1.PERSON_ID <> 0
	AND T1.PERSON_ID IS NOT NULL
GROUP BY PERSON_ID
	,MEASUREMENT_CONCEPT_ID
	,MEASUREMENT_DATE
	,MEASUREMENT_DATETIME
	,MEASUREMENT_TYPE_CONCEPT_ID
	,OPERATOR_CONCEPT_ID
	,VALUE_AS_NUMBER
	,VALUE_AS_CONCEPT_ID
	,UNIT_CONCEPT_ID
	,RANGE_LOW
	,RANGE_HIGH
	,PROVIDER_ID
	,VISIT_OCCURRENCE_ID
	,MEASUREMENT_SOURCE_VALUE
	,MEASUREMENT_SOURCE_CONCEPT_ID
	,UNIT_SOURCE_VALUE
	,VALUE_SOURCE_VALUE
HAVING COUNT(*) > 1
)
--
--INSERT INTO OMOP_QA.QA_LOG   (    
--		RUN_DATE
--      ,STANDARD_DATA_TABLE
--      ,QA_METRIC
--	  , METRIC_FIELD
--      ,QA_ERRORS
--      ,ERROR_TYPE
--	  ,TOTAL_RECORDS)

	SELECT CAST(GETDATE() AS DATE) AS RUN_DATE
	, 'MEASUREMENT' AS STANDARD_DATA_TABLE
	, 'DUPLICATE' AS QA_METRIC
	, 'RECORDS'  AS METRIC_FIELD
	, COALESCE(SUM(CNT),0) AS QA_ERRORS
	, CASE WHEN SUM(CNT) IS NOT NULL THEN 'FATAL' ELSE NULL END   AS ERROR_TYPE
	, (SELECT COUNT(*) AS NUM_ROWS FROM CDM.MEASUREMENT) AS TOTAL_RECORDS	
	FROM TMP_DUPES
);
