USE DATABASE SH_OMOP_DB_PROD;
USE SCHEMA CDM;
USE ROLE SF_SH_OMOP_DEVELOPER;
USE WAREHOUSE SH_OMOP_DATA_SCIENCE_WH;

--DROP VIEW CDM.V_NOTE_NONSTANDARD_COUNT;
CREATE OR REPLACE VIEW OMOP_QA.V_NOTE_NONSTANDARD_COUNT AS (
-------------------------------------------------------------------
---- NOTE NON STANDARD --------------------------------------------
-------------------------------------------------------------------
---- NONSTANDARD_COUNT
-------------------------------------------------------------------

WITH NONSTANDARD_COUNT
AS (
	SELECT 'NOTE_TYPE_CONCEPT_ID' AS CONCEPT_ERR_ID, 'NON-STANDARD' AS QA_METRIC, 'INVALID DATA' AS ERROR_TYPE, COUNT(*) AS CNT
	FROM CDM.NOTE AS NT
	LEFT JOIN CDM.CONCEPT AS C
		ON NT.NOTE_TYPE_CONCEPT_ID = C.CONCEPT_ID AND upper(C.DOMAIN_ID) = 'TYPE CONCEPT' AND upper(C.VOCABULARY_ID) =  ('TYPE CONCEPT')
	WHERE NOTE_TYPE_CONCEPT_ID <> 0 AND NOTE_TYPE_CONCEPT_ID IS NOT NULL AND (STANDARD_CONCEPT <> 'S' OR STANDARD_CONCEPT IS NULL)
	
	UNION ALL
	
	SELECT 'NOTE_CLASS_CONCEPT_ID' AS CONCEPT_ERR_ID, 'NON-STANDARD' AS QA_METRIC, 'INVALID DATA' AS ERROR_TYPE, COUNT(*) AS CNT
	FROM CDM.NOTE AS NT
	LEFT JOIN CDM.CONCEPT AS C
		ON NT.NOTE_CLASS_CONCEPT_ID = C.CONCEPT_ID AND upper(C.DOMAIN_ID) = 'MEAS VALUE' AND upper(C.VOCABULARY_ID) =  ('LOINC') 
		  AND C.CONCEPT_CLASS_ID IN ('Doc Kind', 'Doc Subject Matter', 'Doc Setting', 'Doc Role', 'Doc Type of Service')
	WHERE NOTE_CLASS_CONCEPT_ID <> 0 AND NOTE_CLASS_CONCEPT_ID IS NOT NULL AND (STANDARD_CONCEPT <> 'S' OR STANDARD_CONCEPT IS NULL)
	
	UNION ALL
	
	SELECT 'ENCODING_CONCEPT_ID' AS CONCEPT_ERR_ID, 'NON-STANDARD' AS QA_METRIC, 'INVALID DATA' AS ERROR_TYPE, COUNT(*) AS CNT
	FROM CDM.NOTE AS NT
	LEFT JOIN CDM.CONCEPT AS C
		ON NT.ENCODING_CONCEPT_ID = C.CONCEPT_ID AND upper(C.DOMAIN_ID) = 'METADATA' AND upper(C.CONCEPT_CLASS_ID) =  'METADATA'
	WHERE ENCODING_CONCEPT_ID <> 0 AND ENCODING_CONCEPT_ID IS NOT NULL AND (STANDARD_CONCEPT <> 'S' OR STANDARD_CONCEPT IS NULL)
	
	UNION ALL
	
	SELECT 'LANGUAGE_CONCEPT_ID' AS CONCEPT_ERR_ID, 'NON-STANDARD' AS QA_METRIC, 'INVALID DATA' AS ERROR_TYPE, COUNT(*) AS CNT
	FROM CDM.NOTE AS NT
	LEFT JOIN CDM.CONCEPT AS C
		ON NT.LANGUAGE_CONCEPT_ID = C.CONCEPT_ID AND upper(C.DOMAIN_ID) = 'OBSERVATION' AND upper(C.VOCABULARY_ID) =  ('SNOMED') AND upper(C.CONCEPT_CLASS_ID) =  ('QUALIFIER VALUE')
	WHERE LANGUAGE_CONCEPT_ID <> 0 AND LANGUAGE_CONCEPT_ID IS NOT NULL AND (STANDARD_CONCEPT <> 'S' OR STANDARD_CONCEPT IS NULL)
	)

--INSERT INTO OMOP_QA.QA_LOG   (    
--	RUN_DATE
--    ,STANDARD_DATA_TABLE
--    ,QA_METRIC
--	, METRIC_FIELD
--    ,QA_ERRORS
--    ,ERROR_TYPE
--	,TOTAL_RECORDS)

SELECT CAST(GETDATE() AS DATE) AS RUN_DATE
	,'NOTE' AS STANDARD_DATA_TABLE
	, QA_METRIC AS QA_METRIC	
	, CONCEPT_ERR_ID  AS METRIC_FIELD
	, COALESCE (SUM(CNT),0) AS QA_ERRORS
	, CASE WHEN SUM(CNT) <> 0 THEN ERROR_TYPE ELSE NULL END   AS ERROR_TYPE
	, (SELECT COUNT(*) AS NUM_ROWS FROM CDM.NOTE) AS TOTAL_RECORDS
FROM NONSTANDARD_COUNT	
GROUP BY   CONCEPT_ERR_ID, QA_METRIC, ERROR_TYPE

);
