USE DATABASE SH_OMOP_DB_PROD;
USE SCHEMA CDM;
USE ROLE SF_SH_OMOP_DEVELOPER;
USE WAREHOUSE SH_OMOP_DATA_SCIENCE_WH;

--DROP VIEW CDM.V_NOTE_ZEROCONCEPT_DETAIL;
CREATE OR REPLACE VIEW OMOP_QA.V_NOTE_ZEROCONCEPT_DETAIL AS (
--------------------------------------------------------------------- 
------ NOTE_ZEROCONCEPT_DETAIL
--------------------------------------------------------------------- 
WITH ZEROCONCEPT_DETAIL
AS (
	SELECT 'NOTE_TYPE_CONCEPT_ID' AS METRIC_FIELD, 'ZERO CONCEPT' AS QA_METRIC, 'WARNING' AS ERROR_TYPE
		, NOTE_ID AS CDT_ID
	FROM CDM.NOTE
	WHERE (NOTE_TYPE_CONCEPT_ID = 0)
	
	UNION ALL
	
	SELECT 'NOTE_CLASS_CONCEPT_ID' AS METRIC_FIELD, 'ZERO CONCEPT' AS QA_METRIC, 'WARNING' AS ERROR_TYPE
		, NOTE_ID AS CDT_ID
	FROM CDM.NOTE
	WHERE (NOTE_CLASS_CONCEPT_ID = 0)
	
	UNION ALL
	
	SELECT 'ENCODING_CONCEPT_ID' AS METRIC_FIELD, 'ZERO CONCEPT' AS QA_METRIC, 'WARNING' AS ERROR_TYPE
		, NOTE_ID AS CDT_ID
	FROM CDM.NOTE
	WHERE (ENCODING_CONCEPT_ID = 0)
	
	UNION ALL
	
	SELECT 'LANGUAGE_CONCEPT_ID' AS METRIC_FIELD, 'ZERO CONCEPT' AS QA_METRIC, 'WARNING' AS ERROR_TYPE
		, NOTE_ID AS CDT_ID
	FROM CDM.NOTE
	WHERE (LANGUAGE_CONCEPT_ID = 0)
)

--INSERT INTO OMOP_QA.QA_ERR(    
--	 RUN_DATE
--    ,STANDARD_DATA_TABLE
--    ,QA_METRIC
--	,METRIC_FIELD
--    ,ERROR_TYPE
--	,CDT_ID)
SELECT CAST(GETDATE() AS DATE) AS RUN_DATE
	,'NOTE' AS STANDARD_DATA_TABLE
	, QA_METRIC AS QA_METRIC
	, METRIC_FIELD  AS METRIC_FIELD
	, ERROR_TYPE
	, CDT_ID
FROM ZEROCONCEPT_DETAIL		
  WHERE ERROR_TYPE <>'EXPECTED'		
 );
 