USE DATABASE SH_OMOP_DB_PROD;
USE SCHEMA CDM;
USE ROLE SF_SH_OMOP_DEVELOPER;
USE WAREHOUSE SH_OMOP_DATA_SCIENCE_WH;

--DROP VIEW CDM.V_OBSERVATION_30AFTERDEATH_DETAIL;
CREATE OR REPLACE VIEW OMOP_QA.V_OBSERVATION_30AFTERDEATH_DETAIL AS (
-------------------------------------------------------------------
----OBSERVATION_30AFTERDEATH_DETAIL
-------------------------------------------------------------------
WITH OBSERVATION30AFTERDEATH_DETAIL AS (
SELECT 'OBSERVATION_DATE' AS METRIC_FIELD, '30AFTERDEATH' AS QA_METRIC, 'INVALID DATA' AS ERROR_TYPE, 
	 OBSERVATION_ID AS CDT_ID
FROM CDM.OBSERVATION AS T1
INNER JOIN CDM.DEATH AS T2
	ON T1.PERSON_ID = T2.PERSON_ID
WHERE DATEDIFF(DAY, DEATH_DATE, OBSERVATION_DATE) > 30
)

--INSERT INTO OMOP_QA.QA_ERR(    
--	 RUN_DATE
--    ,STANDARD_DATA_TABLE
--    ,QA_METRIC
--	,METRIC_FIELD
--    ,ERROR_TYPE
--	,CDT_ID)
SELECT CAST(GETDATE() AS DATE) AS RUN_DATE
	,'OBSERVATION' AS STANDARD_DATA_TABLE
	, QA_METRIC AS QA_METRIC
	, METRIC_FIELD  AS METRIC_FIELD
	, ERROR_TYPE
	, CDT_ID
FROM OBSERVATION30AFTERDEATH_DETAIL	
 );
 