USE DATABASE SH_OMOP_DB_PROD;
USE SCHEMA CDM;
USE ROLE SF_SH_OMOP_DEVELOPER;
USE WAREHOUSE SH_OMOP_DATA_SCIENCE_WH;


CREATE OR REPLACE VIEW OMOP_QA.V_PERSON_AGE_ERR_DETAIL AS (
---------------------------------------------------------------------
--PERSON_AGE_ERR_DETAIL
---------------------------------------------------------------------
WITH AGE_ERR_DETAIL AS (
	SELECT
        'UNDER18' AS AGE,
		PERSON_ID AS CDT_ID
    FROM
       CDM.PERSON AS T1       
	WHERE  (DATEDIFF(YEAR,  BIRTH_DATETIME, GETDATE())<18)
UNION ALL
    SELECT
        'OVER120' AS AGE,
		PERSON_ID AS CDT_ID
    FROM
       CDM.PERSON AS T1
	WHERE  (DATEDIFF(YEAR,  BIRTH_DATETIME, GETDATE())>120)
)
--INSERT INTO OMOP_QA.QA_ERR(    
--	RUN_DATE
--    ,STANDARD_DATA_TABLE
--    ,QA_METRIC
--	,METRIC_FIELD
--    ,ERROR_TYPE
--	,CDT_ID)
SELECT CAST(GETDATE() AS DATE) AS RUN_DATE
	,'PERSON' AS STANDARD_DATA_TABLE
	, 'WRONG AGE:'|| AGE AS QA_METRIC
	, 'BIRTH_DATETIME'  AS METRIC_FIELD
	, 'WARNING' AS ERROR_TYPE
	, CDT_ID
FROM AGE_ERR_DETAIL
);
