USE DATABASE SH_OMOP_DB_PROD;
USE SCHEMA CDM;
USE ROLE SF_SH_OMOP_DEVELOPER;
USE WAREHOUSE SH_OMOP_DATA_SCIENCE_WH;


CREATE OR REPLACE VIEW OMOP_QA.V_PERSON_AGE_ERR_COUNT AS (
---------------------------------------------------------------------
--PERSON_AGE_ERR_COUNT
---------------------------------------------------------------------
WITH AGE_ERR_COUNT AS (
	SELECT
        'UNDER18' AS AGE,
        SUM(CASE WHEN (DATEDIFF(YEAR,  BIRTH_DATETIME, GETDATE())<18) THEN 1 ELSE 0 END) AS CNT
    FROM
       CDM.PERSON AS T1
UNION ALL
    SELECT
        'OVER120' AS AGE,
        SUM(CASE WHEN (DATEDIFF(YEAR,  BIRTH_DATETIME, GETDATE())>120) THEN 1 ELSE 0 END) AS CNT
    FROM
       CDM.PERSON AS T1
)

--INSERT INTO OMOP_QA.QA_LOG   (    
--		RUN_DATE
--      ,STANDARD_DATA_TABLE
--      ,QA_METRIC
--	  ,METRIC_FIELD
--      ,QA_ERRORS
--      ,ERROR_TYPE
--	  ,TOTAL_RECORDS)

SELECT CAST(GETDATE() AS DATE) AS RUN_DATE
	,'PERSON' AS STANDARD_DATA_TABLE
	, 'WRONG AGE:'|| AGE AS QA_METRIC
	, 'BIRTH_DATETIME'  AS METRIC_FIELD
	, COALESCE(SUM(CNT),0) AS QA_ERRORS
	, CASE WHEN SUM(CNT) <>0 THEN 'WARNING' ELSE NULL END   AS ERROR_TYPE
	, (SELECT COUNT(*) AS NUM_ROWS FROM CDM.PERSON) AS TOTAL_RECORDS	
FROM AGE_ERR_COUNT	
GROUP BY AGE
);
