USE DATABASE SH_OMOP_DB_PROD;
USE SCHEMA CDM;
USE ROLE SF_SH_OMOP_DEVELOPER;
USE WAREHOUSE SH_OMOP_DATA_SCIENCE_WH;

--DROP VIEW CDM.V_PERSON_NULLCONCEPT_DETAIL;
CREATE OR REPLACE VIEW OMOP_QA.V_PERSON_NULLCONCEPT_DETAIL AS (
---------------------------------------------------------------------
-- PERSON_NULLCONCEPT_DETAIL
---------------------------------------------------------------------
WITH NULLCONCEPT_DETAIL AS (
	SELECT 'GENDER_CONCEPT_ID' AS METRIC_FIELD,'NULL CONCEPT' AS QA_METRIC,'FATAL' AS ERROR_TYPE
		,PERSON_ID AS CDT_ID
	FROM CDM.PERSON AS T1
	WHERE (GENDER_CONCEPT_ID IS NULL)
UNION ALL
	SELECT 'RACE_CONCEPT_ID' AS METRIC_FIELD,'NULL CONCEPT' AS QA_METRIC,'FATAL' AS ERROR_TYPE
		,PERSON_ID AS CDT_ID
	FROM CDM.PERSON AS T1
	WHERE (RACE_CONCEPT_ID IS NULL)
UNION ALL
	SELECT 'ETHNICITY_CONCEPT_ID' AS METRIC_FIELD,'NULL CONCEPT' AS QA_METRIC,'FATAL' AS ERROR_TYPE
		,PERSON_ID AS CDT_ID
	FROM CDM.PERSON AS T1
	WHERE (ETHNICITY_CONCEPT_ID IS NULL)
UNION ALL
	SELECT 'GENDER_SOURCE_CONCEPT_ID' AS METRIC_FIELD,'NULL CONCEPT' AS QA_METRIC,'FATAL' AS ERROR_TYPE
		,PERSON_ID AS CDT_ID
	FROM CDM.PERSON AS T1
	WHERE (GENDER_SOURCE_CONCEPT_ID IS NULL)
UNION ALL
	SELECT 'RACE_SOURCE_CONCEPT_ID' AS METRIC_FIELD,'NULL CONCEPT' AS QA_METRIC,'FATAL' AS ERROR_TYPE
		,PERSON_ID AS CDT_ID
	FROM CDM.PERSON AS T1
	WHERE (RACE_SOURCE_CONCEPT_ID IS NULL)
UNION ALL
	SELECT 'ETHNICITY_SOURCE_CONCEPT_ID' AS METRIC_FIELD,'NULL CONCEPT' AS QA_METRIC,'FATAL' AS ERROR_TYPE
		,PERSON_ID AS CDT_ID
	FROM CDM.PERSON AS T1
	WHERE (ETHNICITY_SOURCE_CONCEPT_ID IS NULL)
)
	
--INSERT INTO OMOP_QA.QA_ERR(    
--	RUN_DATE
--    ,STANDARD_DATA_TABLE
--    ,QA_METRIC
--	,METRIC_FIELD
--    ,ERROR_TYPE
--	,CDT_ID)
SELECT CAST( GETDATE() AS DATE) AS RUN_DATE
	,'PERSON' AS STANDARD_DATA_TABLE
	, QA_METRIC AS QA_METRIC
	, METRIC_FIELD  AS METRIC_FIELD
	, ERROR_TYPE
	, CDT_ID
FROM NULLCONCEPT_DETAIL		
  WHERE ERROR_TYPE <>'EXPECTED'	
 );
 