USE DATABASE SH_OMOP_DB_PROD;
USE SCHEMA CDM;
USE ROLE SF_SH_OMOP_DEVELOPER;
USE WAREHOUSE SH_OMOP_DATA_SCIENCE_WH;

--DROP VIEW CDM.V_PROCEDURE_OCCURRENCE_ZEROCONCEPT_COUNT;
CREATE OR REPLACE VIEW OMOP_QA.V_PROCEDURE_OCCURRENCE_ZEROCONCEPT_COUNT AS (
--------------------------------------------------------------------- 
------ PROCEDURE_OCCURRENCE_ZEROCONCEPT_COUNT
---------------------------------------------------------------------
WITH ZEROCONCEPT_COUNT
AS (
	SELECT 'PROCEDURE_CONCEPT_ID' AS METRIC_FIELD, 'ZERO CONCEPT' AS QA_METRIC, 'WARNING' AS ERROR_TYPE, COUNT(*) AS CNT
	FROM CDM.PROCEDURE_OCCURRENCE
	WHERE (PROCEDURE_CONCEPT_ID = 0)
	
	UNION ALL
	
	SELECT 'PROCEDURE_TYPE_CONCEPT_ID' AS METRIC_FIELD, 'ZERO CONCEPT' AS QA_METRIC, 'WARNING' AS ERROR_TYPE, COUNT(*) AS CNT
	FROM CDM.PROCEDURE_OCCURRENCE
	WHERE (PROCEDURE_TYPE_CONCEPT_ID = 0)
	
	UNION ALL
	
	--MODIFIER_CONCEPT_ID
	--IF THERE IS A VALUE IN 'MODIFIER_SOURCE_VALUE' THERE SHOULD NOT BE A ZERO IN 'MODIFIER_CONCEPT_ID'
	SELECT 'MODIFIER_CONCEPT_ID' AS METRIC_FIELD, 'ZERO CONCEPT' AS QA_METRIC, 'WARNING' AS ERROR_TYPE, COUNT(*) AS CNT
	FROM CDM.PROCEDURE_OCCURRENCE
	WHERE (MODIFIER_CONCEPT_ID = 0 AND MODIFIER_SOURCE_VALUE IS NOT NULL)
	
	UNION ALL
	
	--MODIFIER_CONCEPT_ID
	--IF THERE IS NOT A VALUE IN 'MODIFIER_SOURCE_VALUE' THERE SHOULD BE A ZERO IN 'MODIFIER_CONCEPT_ID'
	SELECT 'MODIFIER_CONCEPT_ID' AS METRIC_FIELD, 'ZERO CONCEPT' AS QA_METRIC, 'EXPECTED' AS ERROR_TYPE, COUNT(*) AS CNT
	FROM CDM.PROCEDURE_OCCURRENCE
	WHERE (MODIFIER_CONCEPT_ID = 0 AND MODIFIER_SOURCE_VALUE IS NULL)
	
	UNION ALL
	
	SELECT 'PROCEDURE_SOURCE_CONCEPT_ID' AS METRIC_FIELD, 'ZERO CONCEPT' AS QA_METRIC, 'WARNING' AS ERROR_TYPE, COUNT(*) AS CNT
	FROM CDM.PROCEDURE_OCCURRENCE
	WHERE (PROCEDURE_SOURCE_CONCEPT_ID = 0)
	)
	
--INSERT INTO OMOP_QA.QA_LOG   (    
--	RUN_DATE
--    ,STANDARD_DATA_TABLE
--    ,QA_METRIC
--	,METRIC_FIELD
--    ,QA_ERRORS
--    ,ERROR_TYPE
--	,TOTAL_RECORDS)

SELECT CAST(GETDATE() AS DATE) AS RUN_DATE
	,'PROCEDURE_OCCURRENCE' AS STANDARD_DATA_TABLE
	, QA_METRIC AS QA_METRIC	
	, METRIC_FIELD  AS METRIC_FIELD
	, COALESCE(SUM(CNT),0) AS QA_ERRORS
	, CASE WHEN SUM(CNT) <> 0 THEN ERROR_TYPE ELSE NULL END AS ERROR_TYPE
	, (SELECT COUNT(*) AS NUM_ROWS FROM CDM.PROCEDURE_OCCURRENCE) AS TOTAL_RECORDS
FROM ZEROCONCEPT_COUNT
GROUP BY METRIC_FIELD, QA_METRIC, ERROR_TYPE
);
