USE DATABASE SH_OMOP_DB_PROD;
USE SCHEMA CDM;
USE ROLE SF_SH_OMOP_DEVELOPER;
USE WAREHOUSE SH_OMOP_DATA_SCIENCE_WH;


CREATE OR REPLACE VIEW OMOP_QA.V_PROVIDER_NOMATCH_COUNT AS (
---------------------------------------------------------------------
--PROVIDER_NOMATCH_COUNT
---------------------------------------------------------------------
WITH NO_MATCH_COUNT AS (
	SELECT 'SPECIALTY_CONCEPT_ID' AS METRIC_FIELD , 'NO-MATCH' AS QA_METRIC, 'FATAL' AS ERROR_TYPE,
        COUNT(*) AS CNT 
    FROM
       CDM.PROVIDER AS P
		LEFT JOIN 
			CDM.CONCEPT AS C
			ON P.SPECIALTY_CONCEPT_ID=C.CONCEPT_ID
	WHERE SPECIALTY_CONCEPT_ID <> 0 
		AND  CONCEPT_ID IS  NULL
UNION ALL
    SELECT 'GENDER_CONCEPT_ID' AS METRIC_FIELD , 'NO-MATCH' AS QA_METRIC, 'FATAL' AS ERROR_TYPE,
        COUNT(*) AS CNT
    FROM
       CDM.PROVIDER AS P
		LEFT JOIN
			CDM.CONCEPT AS C
			ON P.GENDER_CONCEPT_ID=C.CONCEPT_ID
	WHERE GENDER_CONCEPT_ID <> 0
	AND  CONCEPT_ID IS NULL
UNION ALL
    SELECT 'SPECIALTY_SOURCE_CONCEPT_ID' AS METRIC_FIELD , 'NO-MATCH' AS QA_METRIC, 'FATAL' AS ERROR_TYPE,
        COUNT(*) AS CNT
    FROM
       CDM.PROVIDER AS P
		LEFT JOIN
			CDM.CONCEPT AS C
			ON P.SPECIALTY_SOURCE_CONCEPT_ID=C.CONCEPT_ID
	WHERE SPECIALTY_SOURCE_CONCEPT_ID <> 0
		AND  CONCEPT_ID IS NULL
UNION ALL
    SELECT 'GENDER_SOURCE_CONCEPT_ID' AS METRIC_FIELD , 'NO-MATCH' AS QA_METRIC, 'FATAL' AS ERROR_TYPE,
        COUNT(*) AS CNT
    FROM
       CDM.PROVIDER AS P
		LEFT JOIN
			CDM.CONCEPT AS C
			ON P.GENDER_SOURCE_CONCEPT_ID=C.CONCEPT_ID
	WHERE (GENDER_SOURCE_CONCEPT_ID <> 0
		AND  CONCEPT_ID IS NULL)
)
--INSERT INTO OMOP_QA.QA_LOG   (    
--		RUN_DATE
--      ,STANDARD_DATA_TABLE
--      ,QA_METRIC
--	  , METRIC_FIELD
--      ,QA_ERRORS
--      ,ERROR_TYPE
--	  ,TOTAL_RECORDS)
SELECT CAST(GETDATE() AS DATE) AS RUN_DATE
	,'PROVIDER' AS STANDARD_DATA_TABLE
	, QA_METRIC AS QA_METRIC	
	, METRIC_FIELD  AS METRIC_FIELD
	, COALESCE(SUM(CNT),0) AS QA_ERRORS
	, CASE WHEN SUM(CNT) <> 0 THEN ERROR_TYPE ELSE NULL END   AS ERROR_TYPE
	, (SELECT COUNT(*) AS NUM_ROWS FROM CDM.PROVIDER) AS TOTAL_RECORDS	
FROM NO_MATCH_COUNT	
GROUP BY   METRIC_FIELD, QA_METRIC, ERROR_TYPE
);
