USE DATABASE SH_OMOP_DB_PROD;
USE SCHEMA CDM;
USE ROLE SF_SH_OMOP_DEVELOPER;
USE WAREHOUSE SH_OMOP_DATA_SCIENCE_WH;


CREATE OR REPLACE VIEW OMOP_QA.V_PROVIDER_NOMATCH_DETAIL AS (
---------------------------------------------------------------------
--PROVIDER_NOMATCH_DETAIL
---------------------------------------------------------------------
WITH NO_MATCH_DETAIL AS (
	SELECT 'SPECIALTY_CONCEPT_ID' AS METRIC_FIELD , 'NO-MATCH' AS QA_METRIC, 'FATAL' AS ERROR_TYPE,
		PROVIDER_ID AS CDT_ID
    FROM
       CDM.PROVIDER AS P
		LEFT JOIN 
			CDM.CONCEPT AS C
			ON P.SPECIALTY_CONCEPT_ID=C.CONCEPT_ID
	WHERE SPECIALTY_CONCEPT_ID <> 0 
		AND  CONCEPT_ID IS  NULL
UNION ALL
    SELECT 'GENDER_CONCEPT_ID' AS METRIC_FIELD , 'NO-MATCH' AS QA_METRIC, 'FATAL' AS ERROR_TYPE,
		PROVIDER_ID AS CDT_ID
    FROM
       CDM.PROVIDER AS P
		LEFT JOIN
			CDM.CONCEPT AS C
			ON P.GENDER_CONCEPT_ID=C.CONCEPT_ID
	WHERE GENDER_CONCEPT_ID <> 0
	AND  CONCEPT_ID IS NULL
UNION ALL
    SELECT 'SPECIALTY_SOURCE_CONCEPT_ID' AS METRIC_FIELD , 'NO-MATCH' AS QA_METRIC, 'FATAL' AS ERROR_TYPE,
		PROVIDER_ID AS CDT_ID
    FROM
       CDM.PROVIDER AS P
		LEFT JOIN
			CDM.CONCEPT AS C
			ON P.SPECIALTY_SOURCE_CONCEPT_ID=C.CONCEPT_ID
	WHERE SPECIALTY_SOURCE_CONCEPT_ID <> 0
		AND  CONCEPT_ID IS NULL
UNION ALL
    SELECT 'GENDER_SOURCE_CONCEPT_ID' AS METRIC_FIELD , 'NO-MATCH' AS QA_METRIC, 'FATAL' AS ERROR_TYPE,
		PROVIDER_ID AS CDT_ID
    FROM
       CDM.PROVIDER AS P
		LEFT JOIN
			CDM.CONCEPT AS C
			ON P.GENDER_SOURCE_CONCEPT_ID=C.CONCEPT_ID
	WHERE (GENDER_SOURCE_CONCEPT_ID <> 0
		AND  CONCEPT_ID IS NULL)
)
--INSERT INTO OMOP_QA.QA_ERR(    
--	RUN_DATE
--    ,STANDARD_DATA_TABLE
--    ,QA_METRIC
--	,METRIC_FIELD
--    ,ERROR_TYPE
--	,CDT_ID)
SELECT CAST(GETDATE() AS DATE) AS RUN_DATE
	,'PROVIDER' AS STANDARD_DATA_TABLE
	, QA_METRIC AS QA_METRIC
	, METRIC_FIELD  AS METRIC_FIELD
	, ERROR_TYPE
	, CDT_ID
FROM NO_MATCH_DETAIL		
  WHERE ERROR_TYPE <>'EXPECTED'	
);
