USE DATABASE SH_OMOP_DB_PROD;
USE SCHEMA CDM;
USE ROLE SF_SH_OMOP_DEVELOPER;
USE WAREHOUSE SH_OMOP_DATA_SCIENCE_WH;

-------------------------------------------------------------------
----PROCEDURE_OCCURRENCE NON STANDARD -----------------------------
-------------------------------------------------------------------
----NONSTANDARD_DETAIL
-------------------------------------------------------------------

--DROP VIEW CDM.V_PROCEDURE_OCCURRENCE_NON_STANDARD_DETAIL;
CREATE OR REPLACE VIEW OMOP_QA.V_PROCEDURE_OCCURRENCE_NON_STANDARD_DETAIL AS (

WITH NONSTANDARD_DETAIL
AS (
	SELECT 'PROCEDURE_CONCEPT_ID' AS METRIC_FIELD, 'NON-STANDARD' AS QA_METRIC, 'INVALID DATA' AS ERROR_TYPE
		, PROCEDURE_OCCURRENCE_ID AS CDT_ID
	FROM CDM.PROCEDURE_OCCURRENCE AS P
	LEFT JOIN CDM.CONCEPT AS C
		ON P.PROCEDURE_CONCEPT_ID = C.CONCEPT_ID AND upper(C.DOMAIN_ID) =  'PROCEDURE'
	WHERE PROCEDURE_CONCEPT_ID <> 0 AND PROCEDURE_CONCEPT_ID IS NOT NULL AND (STANDARD_CONCEPT <> 'S' OR STANDARD_CONCEPT IS NULL)
	
	UNION ALL
	
	SELECT 'PROCEDURE_TYPE_CONCEPT_ID' AS METRIC_FIELD, 'NON-STANDARD' AS QA_METRIC, 'INVALID DATA' AS ERROR_TYPE
		, PROCEDURE_OCCURRENCE_ID AS CDT_ID
	FROM CDM.PROCEDURE_OCCURRENCE AS P
	LEFT JOIN CDM.CONCEPT AS C
		ON P.PROCEDURE_TYPE_CONCEPT_ID = C.CONCEPT_ID AND upper(C.DOMAIN_ID) =  'TYPE CONCEPT' AND upper(C.VOCABULARY_ID) IN  ('TYPE CONCEPT')
	WHERE PROCEDURE_TYPE_CONCEPT_ID <> 0 AND PROCEDURE_TYPE_CONCEPT_ID IS NOT NULL AND (STANDARD_CONCEPT <> 'S' OR STANDARD_CONCEPT IS NULL)
	
	UNION ALL
	
	SELECT 'MODIFIER_CONCEPT_ID' AS METRIC_FIELD, 'NON-STANDARD' AS QA_METRIC, 'INVALID DATA' AS ERROR_TYPE
		, PROCEDURE_OCCURRENCE_ID AS CDT_ID
	FROM CDM.PROCEDURE_OCCURRENCE AS P
	LEFT JOIN CDM.CONCEPT AS C
		ON P.MODIFIER_CONCEPT_ID = C.CONCEPT_ID AND upper(C.CONCEPT_CLASS_ID) IN ('CPT4 MODIFIER', 'HCPCS MODIFIER')
	WHERE MODIFIER_CONCEPT_ID <> 0 AND MODIFIER_CONCEPT_ID IS NOT NULL AND (STANDARD_CONCEPT <> 'S' OR STANDARD_CONCEPT IS NULL)
	
	UNION ALL
	
	SELECT 'PROCEDURE_SOURCE_CONCEPT_ID' AS METRIC_FIELD, 'NON-STANDARD' AS QA_METRIC, 'INVALID DATA' AS ERROR_TYPE
		, PROCEDURE_OCCURRENCE_ID AS CDT_ID
	FROM CDM.PROCEDURE_OCCURRENCE AS P
	LEFT JOIN CDM.CONCEPT AS C
		ON P.PROCEDURE_SOURCE_CONCEPT_ID = C.CONCEPT_ID AND upper(C.DOMAIN_ID) =  'PROCEDURE'
	WHERE PROCEDURE_SOURCE_CONCEPT_ID <> 0 AND C.CONCEPT_ID IS NULL
)

--INSERT INTO OMOP_QA.QA_ERR(    
--	 RUN_DATE
--    ,STANDARD_DATA_TABLE
--    ,QA_METRIC
--	,METRIC_FIELD
--    ,ERROR_TYPE
--	,CDT_ID)
SELECT CAST(GETDATE() AS DATE) AS RUN_DATE
	,'PROCEDURE_OCCURRENCE' AS STANDARD_DATA_TABLE
	, QA_METRIC AS QA_METRIC
	, METRIC_FIELD  AS METRIC_FIELD
	, ERROR_TYPE
	, CDT_ID
FROM NONSTANDARD_DETAIL		
  WHERE ERROR_TYPE <>'EXPECTED'	
  );
  