USE DATABASE SH_OMOP_DB_PROD;
USE SCHEMA CDM;
USE ROLE SF_SH_OMOP_DEVELOPER;
USE WAREHOUSE SH_OMOP_DATA_SCIENCE_WH;

--DROP VIEW CDM.V_PROVIDER_NULL_CONCEPT_DETAIL;
CREATE OR REPLACE VIEW OMOP_QA.V_PROVIDER_NULL_CONCEPT_DETAIL AS (
---------------------------------------------------------------------
--PROVIDER_NULL_CONCEPT_DETAIL
---------------------------------------------------------------------
WITH CTE_NULLCONCEPT_DETAIL AS (
	SELECT 'PROVIDER' AS STANDARD_DATA_TABLE
		,'SPECIALTY_CONCEPT_ID' AS METRIC_FIELD
		,'NULL CONCEPT' AS QA_METRIC
		,'WARNING' AS ERROR_TYPE
		,PROVIDER_ID AS CDT_ID
	FROM CDM.PROVIDER AS T1
	WHERE (SPECIALTY_CONCEPT_ID IS NULL )
	UNION ALL
	SELECT 'PROVIDER' AS STANDARD_DATA_TABLE
		,'GENDER_CONCEPT_ID' AS METRIC_FIELD
		,'NULL CONCEPT' AS QA_METRIC
		,'WARNING' AS ERROR_TYPE
		,PROVIDER_ID AS CDT_ID
	FROM CDM.PROVIDER AS T1
	WHERE (GENDER_CONCEPT_ID IS NULL )
	UNION ALL
	SELECT 'PROVIDER' AS STANDARD_DATA_TABLE
		,'SPECIALTY_SOURCE_CONCEPT_ID' AS METRIC_FIELD
		,'NULL CONCEPT' AS QA_METRIC
		,'EXPECTED' AS ERROR_TYPE
		,PROVIDER_ID AS CDT_ID
	FROM CDM.PROVIDER AS T1
	WHERE (SPECIALTY_SOURCE_CONCEPT_ID IS NULL )
	UNION ALL
	SELECT 'PROVIDER' AS STANDARD_DATA_TABLE
		,'GENDER_SOURCE_CONCEPT_ID' AS METRIC_FIELD
		,'NULL CONCEPT' AS QA_METRIC
		,'EXPECTED' AS ERROR_TYPE
		,PROVIDER_ID AS CDT_ID
	FROM CDM.PROVIDER AS T1
	WHERE (GENDER_SOURCE_CONCEPT_ID IS NULL )
	)
--INSERT INTO OMOP_QA.QA_ERR(    
--	RUN_DATE
--    ,STANDARD_DATA_TABLE
--    ,QA_METRIC
--	,METRIC_FIELD
--    ,ERROR_TYPE
--	,CDT_ID)
SELECT CAST( GETDATE() AS DATE) AS RUN_DATE
	, STANDARD_DATA_TABLE
	, QA_METRIC AS QA_METRIC
	, METRIC_FIELD  AS METRIC_FIELD
	, ERROR_TYPE
	, CDT_ID
FROM CTE_NULLCONCEPT_DETAIL		
  WHERE ERROR_TYPE <>'EXPECTED'				
 );
 