USE DATABASE SH_OMOP_DB_PROD;
USE SCHEMA CDM;
USE ROLE SF_SH_OMOP_DEVELOPER;
USE WAREHOUSE SH_OMOP_DATA_SCIENCE_WH;


CREATE OR REPLACE VIEW OMOP_QA.V_PROCEDURE_OCCURRENCE_VISITDATEDISPARITY_DETAIL AS (
---------------------------------------------------------------------
--PROCEDURE_OCCURRENCE_VISITDATEDISPARITY_DETAIL
---------------------------------------------------------------------
WITH VISITDATEDISPARITY_DETAIL AS (
SELECT 'PROCEDURE_DATE' AS METRIC_FIELD, 'VISIT_DATE_DISPARITY' AS QA_METRIC, 'WARNING' AS ERROR_TYPE, PROCEDURE_OCCURRENCE_ID AS CDT_ID
FROM CDM.PROCEDURE_OCCURRENCE PO
LEFT JOIN CDM.VISIT_OCCURRENCE VO
	ON PO.VISIT_OCCURRENCE_ID = VO.VISIT_OCCURRENCE_ID
WHERE
	-- MUST HAVE POPULATED VISIT OCCURRENCE ID
	(PO.VISIT_OCCURRENCE_ID IS NOT NULL
		AND PO.VISIT_OCCURRENCE_ID <> 0
		AND VO.VISIT_OCCURRENCE_ID IS NOT NULL
		AND VO.VISIT_OCCURRENCE_ID <> 0)
	AND (
		-- PROBLEM WITH PROCEDURE DATE
		(PO.PROCEDURE_DATE< VO.VISIT_START_DATE
			OR PO.PROCEDURE_DATE> VO.VISIT_END_DATE)
		OR
		-- PROBLEM WITH DATETIME
		(CAST(PO.PROCEDURE_DATETIME AS DATE) < CAST(VO.VISIT_START_DATETIME AS DATE)
			OR CAST(PO.PROCEDURE_DATETIME AS DATE) > CAST(VO.VISIT_END_DATETIME AS DATE))
		OR
		-- PROBLEM WITH THE DATETIME (EXTRACTING DATE FOR COMPARISON)
		(PO.PROCEDURE_DATE< CAST(VO.VISIT_START_DATETIME AS DATE)
			OR PO.PROCEDURE_DATE> CAST(VO.VISIT_END_DATETIME AS DATE))
		OR
		--PROBLEM WITH THE DATETIME
		(CAST(PO.PROCEDURE_DATETIME AS DATE) < VO.VISIT_START_DATE
			OR CAST(PO.PROCEDURE_DATETIME AS DATE) > VO.VISIT_END_DATE)
		)
)

--INSERT INTO OMOP_QA.QA_ERR(    
--	 RUN_DATE
--    ,STANDARD_DATA_TABLE
--    ,QA_METRIC
--	,METRIC_FIELD
--    ,ERROR_TYPE
--	,CDT_ID)
SELECT CAST(GETDATE() AS DATE) AS RUN_DATE
	,'PROCEDURE_OCCURRENCE' AS STANDARD_DATA_TABLE
	, QA_METRIC AS QA_METRIC
	, METRIC_FIELD  AS METRIC_FIELD
	, ERROR_TYPE
	, CDT_ID
FROM VISITDATEDISPARITY_DETAIL					
);
