USE DATABASE SH_OMOP_DB_PROD;
USE SCHEMA CDM;
USE ROLE SF_SH_OMOP_DEVELOPER;
USE WAREHOUSE SH_OMOP_DATA_SCIENCE_WH;

--DROP VIEW CDM.V_PROVIDER_NONSTANDARD_DETAIL;
CREATE OR REPLACE VIEW OMOP_QA.V_PROVIDER_NONSTANDARD_DETAIL AS (
---------------------------------------------------------------------
------PROVIDER_NONSTANDARD_DETAIL -------------------------------------------
---------------------------------------------------------------------
WITH NON_STANDARD_DETAIL AS (
	SELECT 'SPECIALTY_CONCEPT_ID' AS METRIC_FIELD,'NON-STANDARD' AS QA_METRIC,'INVALID DATA' AS ERROR_TYPE
		,PROVIDER_ID AS CDT_ID
	FROM CDM.PROVIDER AS P
		LEFT JOIN CDM.CONCEPT AS C ON P.SPECIALTY_CONCEPT_ID = C.CONCEPT_ID
			AND upper(C.DOMAIN_ID) =  'PROVIDER'
			AND upper(C.CONCEPT_CLASS_ID) =  'PHYSICIAN SPECIALTY'
	WHERE SPECIALTY_CONCEPT_ID <> 0
		AND SPECIALTY_CONCEPT_ID IS NOT NULL
		AND (STANDARD_CONCEPT <> 'S' OR STANDARD_CONCEPT IS NULL)
UNION ALL
	SELECT 'GENDER_CONCEPT_ID' AS METRIC_FIELD,'NON-STANDARD' AS QA_METRIC,'INVALID DATA' AS ERROR_TYPE
		,PROVIDER_ID AS CDT_ID
	FROM CDM.PROVIDER AS P
		LEFT JOIN CDM.CONCEPT AS C ON P.GENDER_CONCEPT_ID = C.CONCEPT_ID
			AND upper(C.DOMAIN_ID) =  'GENDER'
	WHERE GENDER_CONCEPT_ID <> 0
		AND GENDER_CONCEPT_ID IS NOT NULL
		AND (STANDARD_CONCEPT <> 'S' OR STANDARD_CONCEPT IS NULL)
UNION ALL
	SELECT 'SPECIALTY_SOURCE_CONCEPT_ID' AS METRIC_FIELD,'NON-STANDARD' AS QA_METRIC,'INVALID DATA' AS ERROR_TYPE
		,PROVIDER_ID AS CDT_ID
	FROM CDM.PROVIDER AS P
		LEFT JOIN CDM.CONCEPT AS C ON P.SPECIALTY_SOURCE_CONCEPT_ID = C.CONCEPT_ID
			AND upper(C.DOMAIN_ID) =  'PROVIDER'
			AND upper(C.CONCEPT_CLASS_ID) =  'PHYSICIAN SPECIALTY'
	WHERE SPECIALTY_SOURCE_CONCEPT_ID <> 0
		AND SPECIALTY_SOURCE_CONCEPT_ID IS NOT NULL
		AND (STANDARD_CONCEPT <> 'S' OR STANDARD_CONCEPT IS NULL)
UNION ALL
	SELECT 'GENDER_SOURCE_CONCEPT_ID' AS METRIC_FIELD,'NON-STANDARD' AS QA_METRIC,'INVALID DATA' AS ERROR_TYPE
		,PROVIDER_ID AS CDT_ID
	FROM CDM.PROVIDER AS P
		LEFT JOIN CDM.CONCEPT AS C ON P.GENDER_SOURCE_CONCEPT_ID = C.CONCEPT_ID
			AND upper(C.DOMAIN_ID) =  'GENDER'
	WHERE GENDER_SOURCE_CONCEPT_ID <> 0
		AND GENDER_SOURCE_CONCEPT_ID IS NOT NULL
		AND (STANDARD_CONCEPT <> 'S' OR STANDARD_CONCEPT IS NULL)
)

--INSERT INTO OMOP_QA.QA_ERR(    
--	RUN_DATE
--    ,STANDARD_DATA_TABLE
--    ,QA_METRIC
--	,METRIC_FIELD
--    ,ERROR_TYPE
--	,CDT_ID)
	
SELECT CAST(GETDATE() AS DATE) AS RUN_DATE
	,'PROVIDER' AS STANDARD_DATA_TABLE
	, QA_METRIC AS QA_METRIC
	, METRIC_FIELD  AS METRIC_FIELD
	, ERROR_TYPE
	, CDT_ID
FROM NON_STANDARD_DETAIL		
  WHERE ERROR_TYPE <>'EXPECTED'	
 );
 