USE DATABASE SH_OMOP_DB_PROD;
USE SCHEMA CDM;
USE ROLE SF_SH_OMOP_DEVELOPER;
USE WAREHOUSE SH_OMOP_DATA_SCIENCE_WH;

--DROP VIEW CDM.V_SPECIMEN_NONSTANDARD_DETAIL;
CREATE OR REPLACE VIEW OMOP_QA.V_SPECIMEN_NONSTANDARD_DETAIL AS (

-------------------------------------------------------------------
----NONSTANDARD_DETAIL	
-------------------------------------------------------------------

WITH NONSTANDARD_DETAIL	
AS (
	SELECT 'SPECIMEN_CONCEPT_ID' AS METRIC_FIELD, 'NON-STANDARD' AS QA_METRIC, 'INVALID DATA' AS ERROR_TYPE
		, SPECIMEN_ID AS CDT_ID
	FROM CDM.SPECIMEN AS P
	LEFT JOIN CDM.CONCEPT AS C
		ON P.SPECIMEN_CONCEPT_ID = C.CONCEPT_ID AND upper(C.DOMAIN_ID) = 'SPECIMEN' AND upper(C.VOCABULARY_ID) =  ('SNOMED')
	WHERE SPECIMEN_CONCEPT_ID <> 0 AND SPECIMEN_CONCEPT_ID IS NOT NULL AND (STANDARD_CONCEPT <> 'S' OR STANDARD_CONCEPT IS NULL)
	
	UNION ALL
	
	SELECT 'SPECIMEN_TYPE_CONCEPT_ID' AS METRIC_FIELD, 'NON-STANDARD' AS QA_METRIC, 'INVALID DATA' AS ERROR_TYPE
		, SPECIMEN_ID AS CDT_ID
	FROM CDM.SPECIMEN AS P
	LEFT JOIN CDM.CONCEPT AS C
		ON P.SPECIMEN_TYPE_CONCEPT_ID = C.CONCEPT_ID AND upper(C.DOMAIN_ID) = 'TYPE CONCEPT' AND upper(C.VOCABULARY_ID) =  ('TYPE CONCEPT')
	WHERE SPECIMEN_TYPE_CONCEPT_ID <> 0 AND SPECIMEN_TYPE_CONCEPT_ID IS NOT NULL AND (STANDARD_CONCEPT <> 'S' OR STANDARD_CONCEPT IS NULL)
	
	UNION ALL
	
	SELECT 'UNIT_CONCEPT_ID' AS METRIC_FIELD, 'NON-STANDARD' AS QA_METRIC, 'INVALID DATA' AS ERROR_TYPE
		, SPECIMEN_ID AS CDT_ID
	FROM CDM.SPECIMEN AS P
	LEFT JOIN CDM.CONCEPT AS C
		ON P.UNIT_CONCEPT_ID = C.CONCEPT_ID AND upper(C.DOMAIN_ID) = 'UNIT'
	WHERE UNIT_CONCEPT_ID <> 0 AND UNIT_CONCEPT_ID IS NOT NULL AND (STANDARD_CONCEPT <> 'S' OR STANDARD_CONCEPT IS NULL)
	
	UNION ALL
	
	SELECT 'ANATOMIC_SITE_CONCEPT_ID' AS METRIC_FIELD, 'NON-STANDARD' AS QA_METRIC, 'INVALID DATA' AS ERROR_TYPE
		, SPECIMEN_ID AS CDT_ID
	FROM CDM.SPECIMEN AS P
	LEFT JOIN CDM.CONCEPT AS C
		ON P.ANATOMIC_SITE_CONCEPT_ID = C.CONCEPT_ID AND upper(C.DOMAIN_ID) = 'SPEC ANATOMIC SITE' AND upper(C.VOCABULARY_ID) =  ('SNOMED')
	WHERE ANATOMIC_SITE_CONCEPT_ID <> 0 AND ANATOMIC_SITE_CONCEPT_ID IS NOT NULL AND (STANDARD_CONCEPT <> 'S' OR STANDARD_CONCEPT IS NULL)
	
--	UNION ALL
--	
--	SELECT 'UNIT_CONCEPT_ID' AS METRIC_FIELD, 'NON-STANDARD' AS QA_METRIC, 'INVALID DATA' AS ERROR_TYPE
--		, SPECIMEN_ID AS CDT_ID
--	FROM CDM.SPECIMEN AS P
--	LEFT JOIN CDM.CONCEPT AS C
--		ON P.UNIT_CONCEPT_ID = C.CONCEPT_ID AND upper(C.DOMAIN_ID) = 'UNIT'
--	WHERE UNIT_CONCEPT_ID <> 0 AND UNIT_CONCEPT_ID IS NOT NULL AND (STANDARD_CONCEPT <> 'S' OR STANDARD_CONCEPT IS NULL)
	
	UNION ALL
	
	SELECT 'DISEASE_STATUS_CONCEPT_ID' AS METRIC_FIELD, 'NON-STANDARD' AS QA_METRIC, 'INVALID DATA' AS ERROR_TYPE
		, SPECIMEN_ID AS CDT_ID
	FROM CDM.SPECIMEN AS P
	LEFT JOIN CDM.CONCEPT AS C
		ON P.DISEASE_STATUS_CONCEPT_ID = C.CONCEPT_ID AND upper(C.DOMAIN_ID) = 'MEASUREMENT' AND upper(C.VOCABULARY_ID) IN  ('LOINC', 'SNOMED')
	WHERE DISEASE_STATUS_CONCEPT_ID <> 0 AND C.CONCEPT_ID IS NULL
)

--INSERT INTO OMOP_QA.QA_ERR(    
--	 RUN_DATE
--    ,STANDARD_DATA_TABLE
--    ,QA_METRIC
--	,METRIC_FIELD
--    ,ERROR_TYPE
--	,CDT_ID)
SELECT CAST(GETDATE() AS DATE) AS RUN_DATE
	,'SPECIMEN' AS STANDARD_DATA_TABLE
	, QA_METRIC AS QA_METRIC
	, METRIC_FIELD  AS METRIC_FIELD
	, ERROR_TYPE
	, CDT_ID
FROM NONSTANDARD_DETAIL		
  WHERE ERROR_TYPE <>'EXPECTED'	
);
