USE DATABASE SH_OMOP_DB_PROD;
USE SCHEMA CDM;
USE ROLE SF_SH_OMOP_DEVELOPER;
USE WAREHOUSE SH_OMOP_DATA_SCIENCE_WH;


CREATE OR REPLACE VIEW OMOP_QA.V_SPECIMEN_NOMATCH_DETAIL AS (
---------------------------------------------------------------------
--SPECIMEN_NOMATCH_DETAIL
---------------------------------------------------------------------
WITH NOMATCH_DETAIL
AS (
	SELECT 'SPECIMEN_CONCEPT_ID' AS METRIC_FIELD, 'NO-MATCH' AS QA_METRIC, 'FATAL' AS ERROR_TYPE
		, SPECIMEN_ID AS CDT_ID
	FROM CDM.SPECIMEN AS P
	LEFT JOIN CDM.CONCEPT AS C
		ON P.SPECIMEN_CONCEPT_ID = C.CONCEPT_ID
	WHERE SPECIMEN_CONCEPT_ID <> 0 AND CONCEPT_ID IS NULL
	
	UNION ALL
	
	SELECT 'SPECIMEN_TYPE_CONCEPT_ID' AS METRIC_FIELD, 'NO-MATCH' AS QA_METRIC, 'FATAL' AS ERROR_TYPE
		, SPECIMEN_ID AS CDT_ID
	FROM CDM.SPECIMEN AS P
	LEFT JOIN CDM.CONCEPT AS C
		ON P.SPECIMEN_TYPE_CONCEPT_ID = C.CONCEPT_ID
	WHERE SPECIMEN_TYPE_CONCEPT_ID <> 0 AND CONCEPT_ID IS NULL
	
	UNION ALL
	
	SELECT 'UNIT_CONCEPT_ID' AS METRIC_FIELD, 'NO-MATCH' AS QA_METRIC, 'FATAL' AS ERROR_TYPE
		, SPECIMEN_ID AS CDT_ID
	FROM CDM.SPECIMEN AS P
	LEFT JOIN CDM.CONCEPT AS C
		ON P.UNIT_CONCEPT_ID = C.CONCEPT_ID
	WHERE UNIT_CONCEPT_ID <> 0 AND CONCEPT_ID IS NULL
	
	UNION ALL
	
	SELECT 'ANATOMIC_SITE_CONCEPT_ID' AS METRIC_FIELD, 'NO-MATCH' AS QA_METRIC, 'FATAL' AS ERROR_TYPE
		, SPECIMEN_ID AS CDT_ID
	FROM CDM.SPECIMEN AS P
	LEFT JOIN CDM.CONCEPT AS C
		ON P.ANATOMIC_SITE_CONCEPT_ID = C.CONCEPT_ID
	WHERE ANATOMIC_SITE_CONCEPT_ID <> 0 AND CONCEPT_ID IS NULL
	
	UNION ALL
	
	SELECT 'UNIT_CONCEPT_ID' AS METRIC_FIELD, 'NO-MATCH' AS QA_METRIC, 'FATAL' AS ERROR_TYPE
		, SPECIMEN_ID AS CDT_ID
	FROM CDM.SPECIMEN AS P
	LEFT JOIN CDM.CONCEPT AS C
		ON P.UNIT_CONCEPT_ID = C.CONCEPT_ID
	WHERE UNIT_CONCEPT_ID <> 0 AND CONCEPT_ID IS NULL
	
	UNION ALL
	
	SELECT 'DISEASE_STATUS_CONCEPT_ID' AS METRIC_FIELD, 'NO-MATCH' AS QA_METRIC, 'FATAL' AS ERROR_TYPE
		, SPECIMEN_ID AS CDT_ID
	FROM CDM.SPECIMEN AS P
	LEFT JOIN CDM.CONCEPT AS C
		ON P.DISEASE_STATUS_CONCEPT_ID = C.CONCEPT_ID
	WHERE DISEASE_STATUS_CONCEPT_ID <> 0 AND CONCEPT_ID IS NULL
)

--INSERT INTO OMOP_QA.QA_ERR(    
--	 RUN_DATE
--    ,STANDARD_DATA_TABLE
--    ,QA_METRIC
--	,METRIC_FIELD
--    ,ERROR_TYPE
--	,CDT_ID)
SELECT CAST(GETDATE() AS DATE) AS RUN_DATE
	,'SPECIMEN' AS STANDARD_DATA_TABLE
	, QA_METRIC AS QA_METRIC
	, METRIC_FIELD  AS METRIC_FIELD
	, ERROR_TYPE
	, CDT_ID
FROM NOMATCH_DETAIL		
  WHERE ERROR_TYPE <>'EXPECTED'	
);
