USE DATABASE SH_OMOP_DB_PROD;
USE SCHEMA CDM;
USE ROLE SF_SH_OMOP_DEVELOPER;
USE WAREHOUSE SH_OMOP_DATA_SCIENCE_WH;


CREATE OR REPLACE VIEW OMOP_QA.V_SPECIMEN_NOMATCH_COUNT AS (
---------------------------------------------------------------------
--SPECIMEN_NOMATCH_COUNT
---------------------------------------------------------------------
WITH NOMATCH_COUNT
AS (
	SELECT 'SPECIMEN_CONCEPT_ID' AS METRIC_FIELD, 'NO-MATCH' AS QA_METRIC, 'FATAL' AS ERROR_TYPE, COUNT(*) AS CNT
	FROM CDM.SPECIMEN AS P
	LEFT JOIN CDM.CONCEPT AS C
		ON P.SPECIMEN_CONCEPT_ID = C.CONCEPT_ID
	WHERE SPECIMEN_CONCEPT_ID <> 0 AND CONCEPT_ID IS NULL
	
	UNION ALL
	
	SELECT 'SPECIMEN_TYPE_CONCEPT_ID' AS METRIC_FIELD, 'NO-MATCH' AS QA_METRIC, 'FATAL' AS ERROR_TYPE, COUNT(*) AS CNT
	FROM CDM.SPECIMEN AS P
	LEFT JOIN CDM.CONCEPT AS C
		ON P.SPECIMEN_TYPE_CONCEPT_ID = C.CONCEPT_ID
	WHERE SPECIMEN_TYPE_CONCEPT_ID <> 0 AND CONCEPT_ID IS NULL
	
	UNION ALL
	
	SELECT 'UNIT_CONCEPT_ID' AS METRIC_FIELD, 'NO-MATCH' AS QA_METRIC, 'FATAL' AS ERROR_TYPE, COUNT(*) AS CNT
	FROM CDM.SPECIMEN AS P
	LEFT JOIN CDM.CONCEPT AS C
		ON P.UNIT_CONCEPT_ID = C.CONCEPT_ID
	WHERE UNIT_CONCEPT_ID <> 0 AND CONCEPT_ID IS NULL
	
	UNION ALL
	
	SELECT 'ANATOMIC_SITE_CONCEPT_ID' AS METRIC_FIELD, 'NO-MATCH' AS QA_METRIC, 'FATAL' AS ERROR_TYPE, COUNT(*) AS CNT
	FROM CDM.SPECIMEN AS P
	LEFT JOIN CDM.CONCEPT AS C
		ON P.ANATOMIC_SITE_CONCEPT_ID = C.CONCEPT_ID
	WHERE ANATOMIC_SITE_CONCEPT_ID <> 0 AND CONCEPT_ID IS NULL
	
	UNION ALL
	
	SELECT 'UNIT_CONCEPT_ID' AS METRIC_FIELD, 'NO-MATCH' AS QA_METRIC, 'FATAL' AS ERROR_TYPE, COUNT(*) AS CNT
	FROM CDM.SPECIMEN AS P
	LEFT JOIN CDM.CONCEPT AS C
		ON P.UNIT_CONCEPT_ID = C.CONCEPT_ID
	WHERE UNIT_CONCEPT_ID <> 0 AND CONCEPT_ID IS NULL
	
	UNION ALL
	
	SELECT 'DISEASE_STATUS_CONCEPT_ID' AS METRIC_FIELD, 'NO-MATCH' AS QA_METRIC, 'FATAL' AS ERROR_TYPE, COUNT(*) AS CNT
	FROM CDM.SPECIMEN AS P
	LEFT JOIN CDM.CONCEPT AS C
		ON P.DISEASE_STATUS_CONCEPT_ID = C.CONCEPT_ID
	WHERE DISEASE_STATUS_CONCEPT_ID <> 0 AND CONCEPT_ID IS NULL
)
--
--INSERT INTO OMOP_QA.QA_LOG   (    
--	RUN_DATE
--    ,STANDARD_DATA_TABLE
--    ,QA_METRIC
--	, METRIC_FIELD
--    ,QA_ERRORS
--    ,ERROR_TYPE
--	,TOTAL_RECORDS)

SELECT CAST(GETDATE() AS DATE) AS RUN_DATE
	,'SPECIMEN' AS STANDARD_DATA_TABLE
	, QA_METRIC AS QA_METRIC	
	, METRIC_FIELD  AS METRIC_FIELD
	, COALESCE(SUM(CNT),0) AS QA_ERRORS
	, CASE WHEN SUM(CNT) <> 0 THEN ERROR_TYPE ELSE NULL END   AS ERROR_TYPE
	, (SELECT COUNT(*) AS NUM_ROWS FROM CDM.SPECIMEN) AS TOTAL_RECORDS
FROM NOMATCH_COUNT	
GROUP BY   METRIC_FIELD, QA_METRIC, ERROR_TYPE
);
