USE DATABASE SH_OMOP_DB_PROD;
USE SCHEMA CDM;
USE ROLE SF_SH_OMOP_DEVELOPER;
USE WAREHOUSE SH_OMOP_DATA_SCIENCE_WH;

--DROP VIEW CDM.V_SPECIMEN_ZEROCONCEPT_DETAIL;
CREATE OR REPLACE VIEW OMOP_QA.V_SPECIMEN_ZEROCONCEPT_DETAIL AS (
--------------------------------------------------------------------- 
------ SPECIMEN_ZEROCONCEPT_DETAIL
---------------------------------------------------------------------
WITH ZEROCONCEPT_DETAIL
AS (
	SELECT 'SPECIMEN_CONCEPT_ID' AS METRIC_FIELD, 'ZERO CONCEPT' AS QA_METRIC, 'WARNING' AS ERROR_TYPE
		, SPECIMEN_ID AS CDT_ID
	FROM CDM.SPECIMEN
	WHERE (SPECIMEN_CONCEPT_ID = 0)
	
	UNION ALL
	
	SELECT 'SPECIMEN_TYPE_CONCEPT_ID' AS METRIC_FIELD, 'ZERO CONCEPT' AS QA_METRIC, 'WARNING' AS ERROR_TYPE
		, SPECIMEN_ID AS CDT_ID
	FROM CDM.SPECIMEN
	WHERE (SPECIMEN_TYPE_CONCEPT_ID = 0)
	
	UNION ALL
	
	SELECT 'UNIT_CONCEPT_ID' AS METRIC_FIELD, 'ZERO CONCEPT' AS QA_METRIC, 'WARNING' AS ERROR_TYPE
		, SPECIMEN_ID AS CDT_ID
	FROM CDM.SPECIMEN
	WHERE (UNIT_CONCEPT_ID = 0)
	
	UNION ALL
	
	SELECT 'ANATOMIC_SITE_CONCEPT_ID' AS METRIC_FIELD, 'ZERO CONCEPT' AS QA_METRIC, 'WARNING' AS ERROR_TYPE
		, SPECIMEN_ID AS CDT_ID
	FROM CDM.SPECIMEN
	WHERE (ANATOMIC_SITE_CONCEPT_ID = 0)
	
	UNION ALL
	
	SELECT 'DISEASE_STATUS_CONCEPT_ID' AS METRIC_FIELD, 'ZERO CONCEPT' AS QA_METRIC, 'WARNING' AS ERROR_TYPE
		, SPECIMEN_ID AS CDT_ID
	FROM CDM.SPECIMEN
	WHERE (DISEASE_STATUS_CONCEPT_ID = 0)
	)
--	
--INSERT INTO OMOP_QA.QA_ERR(    
--	 RUN_DATE
--    ,STANDARD_DATA_TABLE
--    ,QA_METRIC
--	,METRIC_FIELD
--    ,ERROR_TYPE
--	,CDT_ID)
SELECT CAST(GETDATE() AS DATE) AS RUN_DATE
	,'SPECIMEN' AS STANDARD_DATA_TABLE
	, QA_METRIC AS QA_METRIC
	, METRIC_FIELD  AS METRIC_FIELD
	, ERROR_TYPE
	, CDT_ID
FROM ZEROCONCEPT_DETAIL		
  WHERE ERROR_TYPE <>'EXPECTED'	
 );
 