USE DATABASE SH_OMOP_DB_PROD;
USE SCHEMA CDM;
USE ROLE SF_SH_OMOP_DEVELOPER;
USE WAREHOUSE SH_OMOP_DATA_SCIENCE_WH;

--DROP VIEW CDM.V_SPECIMEN_NULLCONCEPT_DETAIL;
CREATE OR REPLACE VIEW OMOP_QA.V_SPECIMEN_NULLCONCEPT_DETAIL AS (
---------------------------------------------------------------------
------ SPECIMEN_NULLCONCEPT_DETAIL
---------------------------------------------------------------------
WITH NULLCONCEPT_DETAIL
AS (
	SELECT 'SPECIMEN_CONCEPT_ID' AS METRIC_FIELD, 'NULL CONCEPT' AS QA_METRIC, 'FATAL' AS ERROR_TYPE
		, SPECIMEN_ID AS CDT_ID
	FROM CDM.SPECIMEN
	WHERE (SPECIMEN_CONCEPT_ID IS NULL)
	
	UNION ALL
	
	SELECT 'SPECIMEN_TYPE_CONCEPT_ID' AS METRIC_FIELD, 'NULL CONCEPT' AS QA_METRIC, 'FATAL' AS ERROR_TYPE
		, SPECIMEN_ID AS CDT_ID
	FROM CDM.SPECIMEN
	WHERE (SPECIMEN_TYPE_CONCEPT_ID IS NULL)
	
	UNION ALL
	
	SELECT 'UNIT_CONCEPT_ID' AS METRIC_FIELD, 'NULL CONCEPT' AS QA_METRIC, 'FATAL' AS ERROR_TYPE
		, SPECIMEN_ID AS CDT_ID
	FROM CDM.SPECIMEN
	WHERE (UNIT_CONCEPT_ID IS NULL)
	
	UNION ALL
	
	SELECT 'ANATOMIC_SITE_CONCEPT_ID' AS METRIC_FIELD, 'NULL CONCEPT' AS QA_METRIC, 'FATAL' AS ERROR_TYPE
		, SPECIMEN_ID AS CDT_ID
	FROM CDM.SPECIMEN
	WHERE (ANATOMIC_SITE_CONCEPT_ID IS NULL)
	
	UNION ALL
	
	SELECT 'DISEASE_STATUS_CONCEPT_ID' AS METRIC_FIELD, 'NULL CONCEPT' AS QA_METRIC, 'FATAL' AS ERROR_TYPE
		, SPECIMEN_ID AS CDT_ID
	FROM CDM.SPECIMEN
	WHERE (DISEASE_STATUS_CONCEPT_ID IS NULL)
	)
	
--INSERT INTO OMOP_QA.QA_ERR(    
--	 RUN_DATE
--    ,STANDARD_DATA_TABLE
--    ,QA_METRIC
--	,METRIC_FIELD
--    ,ERROR_TYPE
--	,CDT_ID)
SELECT CAST(GETDATE() AS DATE) AS RUN_DATE
	,'SPECIMEN' AS STANDARD_DATA_TABLE
	, QA_METRIC AS QA_METRIC
	, METRIC_FIELD  AS METRIC_FIELD
	, ERROR_TYPE
	, CDT_ID
FROM NULLCONCEPT_DETAIL	
  WHERE ERROR_TYPE <>'EXPECTED'			
 );
 