USE DATABASE SH_OMOP_DB_PROD;
USE SCHEMA CDM;
USE ROLE SF_SH_OMOP_DEVELOPER;
USE WAREHOUSE SH_OMOP_DATA_SCIENCE_WH;


CREATE OR REPLACE VIEW OMOP_QA.V_VISIT_OCCURRENCE_NOMATCH_DETAIL AS (
---------------------------------------------------------------------
--VISIT_OCCURRENCE_NOMATCH_DETAIL
---------------------------------------------------------------------
WITH NOMATCH_DETAIL
AS (
	--VISIT_CONCEPT_ID-------------------------------------------
	SELECT 'VISIT_CONCEPT_ID' AS METRIC_FIELD, 'NO-MATCH' AS QA_METRIC, 'FATAL' AS ERROR_TYPE
		, VISIT_OCCURRENCE_ID AS CDT_ID
	FROM CDM.VISIT_OCCURRENCE AS VO
	LEFT JOIN CDM.CONCEPT AS C
		ON VO.VISIT_CONCEPT_ID = C.CONCEPT_ID 
	WHERE VISIT_CONCEPT_ID <> 0 AND STANDARD_CONCEPT IS NULL
	
	UNION ALL
	
	--VISIT_TYPE_CONCEPT_ID-------------------------------------------
	SELECT 'VISIT_TYPE_CONCEPT_ID', 'NO-MATCH' AS QA_METRIC, 'FATAL' AS ERROR_TYPE
		, VISIT_OCCURRENCE_ID AS CDT_ID
	FROM CDM.VISIT_OCCURRENCE AS VO
	LEFT JOIN CDM.CONCEPT AS C
		ON VO.VISIT_TYPE_CONCEPT_ID = C.CONCEPT_ID 
	WHERE VISIT_TYPE_CONCEPT_ID <> 0 AND STANDARD_CONCEPT IS NULL
	
	UNION ALL
	
	--VISIT_SOURCE_CONCEPT_ID-------------------------------------------
	SELECT 'VISIT_SOURCE_CONCEPT_ID', 'NO-MATCH' AS QA_METRIC, 'FATAL' AS ERROR_TYPE
		, VISIT_OCCURRENCE_ID AS CDT_ID
	FROM CDM.VISIT_OCCURRENCE AS VO
	LEFT JOIN CDM.CONCEPT AS C
		ON VO.VISIT_SOURCE_CONCEPT_ID = C.CONCEPT_ID 
	WHERE VISIT_SOURCE_CONCEPT_ID <> 0 AND STANDARD_CONCEPT IS NULL
	
	UNION ALL
	
	--ADMITTING_SOURCE_CONCEPT_ID-------------------------------------------			
	SELECT 'ADMITTING_SOURCE_CONCEPT_ID', 'NO-MATCH' AS QA_METRIC, 'FATAL' AS ERROR_TYPE
		, VISIT_OCCURRENCE_ID AS CDT_ID
	FROM CDM.VISIT_OCCURRENCE AS VO
	LEFT JOIN CDM.CONCEPT AS C
		ON VO.ADMITTING_SOURCE_CONCEPT_ID = C.CONCEPT_ID 
	WHERE ADMITTING_SOURCE_CONCEPT_ID <> 0 AND STANDARD_CONCEPT IS NULL
	
	UNION ALL
	
	--DISCHARGE_TO_CONCEPT_ID-------------------------------------------
	SELECT 'DISCHARGE_TO_CONCEPT_ID', 'NO-MATCH' AS QA_METRIC, 'FATAL' AS ERROR_TYPE
		, VISIT_OCCURRENCE_ID AS CDT_ID
	FROM CDM.VISIT_OCCURRENCE AS VO
	LEFT JOIN CDM.CONCEPT AS C
		ON VO.DISCHARGE_TO_CONCEPT_ID = C.CONCEPT_ID 
	WHERE DISCHARGE_TO_CONCEPT_ID <> 0 AND STANDARD_CONCEPT IS NULL
)

--INSERT INTO OMOP_QA.QA_ERR(    
--	 RUN_DATE
--    ,STANDARD_DATA_TABLE
--    ,QA_METRIC
--	,METRIC_FIELD
--    ,ERROR_TYPE
--	,CDT_ID)
SELECT CAST(GETDATE() AS DATE) AS RUN_DATE
	,'VISIT_OCCURRENCE' AS STANDARD_DATA_TABLE
	, QA_METRIC AS QA_METRIC
	, METRIC_FIELD  AS METRIC_FIELD
	, ERROR_TYPE
	, CDT_ID
FROM NOMATCH_DETAIL		
  WHERE ERROR_TYPE <>'EXPECTED'	
);
