USE DATABASE SH_OMOP_DB_PROD;
USE SCHEMA CDM;
USE ROLE SF_SH_OMOP_DEVELOPER;
USE WAREHOUSE SH_OMOP_DATA_SCIENCE_WH;


--DROP VIEW CDM.V_VISIT_OCCURRENCE_DUPLICATES_COUNT;
CREATE OR REPLACE VIEW OMOP_QA.V_VISIT_OCCURRENCE_DUPLICATES_COUNT AS (
---------------------------------------------------------------------
--VISIT_OCCURRENCE_DUPLICATES_COUNT
---------------------------------------------------------------------
WITH TMP_DUPES AS (
SELECT PERSON_ID
	,VISIT_CONCEPT_ID
	,VISIT_START_DATE
	,VISIT_START_DATETIME
	,VISIT_END_DATE
	,VISIT_END_DATETIME
	,VISIT_TYPE_CONCEPT_ID
	,PROVIDER_ID
	,CARE_SITE_ID
	,VISIT_SOURCE_VALUE
	,VISIT_SOURCE_CONCEPT_ID
	,ADMITTING_SOURCE_CONCEPT_ID
	,ADMITTING_SOURCE_VALUE
	,DISCHARGE_TO_CONCEPT_ID
	,DISCHARGE_TO_SOURCE_VALUE
	,PRECEDING_VISIT_OCCURRENCE_ID
	,COUNT(*) AS CNT
--INTO #TMP_DUPES	
FROM CDM.VISIT_OCCURRENCE AS T1
GROUP BY PERSON_ID
	,VISIT_CONCEPT_ID
	,VISIT_START_DATE
	,VISIT_START_DATETIME
	,VISIT_END_DATE
	,VISIT_END_DATETIME
	,VISIT_TYPE_CONCEPT_ID
	,PROVIDER_ID
	,CARE_SITE_ID
	,VISIT_SOURCE_VALUE
	,VISIT_SOURCE_CONCEPT_ID
	,ADMITTING_SOURCE_CONCEPT_ID
	,ADMITTING_SOURCE_VALUE
	,DISCHARGE_TO_CONCEPT_ID
	,DISCHARGE_TO_SOURCE_VALUE
	,PRECEDING_VISIT_OCCURRENCE_ID
HAVING COUNT(*) > 1
)

--INSERT INTO OMOP_QA.QA_LOG   (    
--		RUN_DATE
--      ,STANDARD_DATA_TABLE
--      ,QA_METRIC
--	  , METRIC_FIELD
--      ,QA_ERRORS
--      ,ERROR_TYPE
--	  ,TOTAL_RECORDS)
SELECT CAST(GETDATE() AS DATE) AS RUN_DATE
	, 'VISIT_OCCURRENCE' AS STANDARD_DATA_TABLE
	, 'DUPLICATE' AS QA_METRIC
	, 'RECORDS'  AS METRIC_FIELD
	, COALESCE(SUM(CNT),0) AS QA_ERRORS
	, CASE WHEN SUM(CNT) IS NOT NULL THEN 'FATAL' ELSE NULL END   AS ERROR_TYPE
	, (SELECT COUNT(*) AS NUM_ROWS FROM CDM.VISIT_OCCURRENCE) AS TOTAL_RECORDS
FROM TMP_DUPES
);
