--Query_AoU_Driver_Dup


SELECT QA_ERR_DBT.Run_date
    , QA_ERR_DBT.Standard_Data_Table
    , AOU_DRIVER.CPI
    , AOU_DRIVER.EPIC_PAT_ID
    , 'P' || QA_ERR_DBT.CDT_ID AS AOU_ID
    , AOU_DRIVER.FIRST_NAME
    , AOU_DRIVER.LAST_NAME
    , AOU_DRIVER.DATE_OF_BIRTH
    , AOU_DRIVER.SEX
    , AOU_DRIVER.PHONE
    , AOU_DRIVER.STREET_ADDRESS
    , AOU_DRIVER.CITY
    , AOU_DRIVER.STATE
    , AOU_DRIVER.ZIP
    , AOU_DRIVER.EMAIL

FROM {{ref('AOU_DRIVER')}} AS AOU_DRIVER 

INNER JOIN {{ref('QA_ERR_DBT')}} AS QA_ERR_DBT
    ON AOU_DRIVER.AOU_ID = 'P' || QA_ERR_DBT.CDT_ID

WHERE QA_ERR_DBT.Standard_Data_Table = 'AOU_DRIVER'