--Query__xref_Compare_OMOP_CLARITY_Counts

SELECT
    SQRY_SNOWFLAKE_DBT_COUNTS.OMOP_CLARITY_TABLE
    , SQRY_SNOWFLAKE_DBT_COUNTS.TABLE_COUNT_DBT
    , SQRY_SNOWFLAKE_COUNTS.TABLE_COUNT_SNOWFLAKE
FROM
    {{ref('SQRY_SNOWFLAKE_DBT_COUNTS')}} AS SQRY_SNOWFLAKE_DBT_COUNTS
LEFT JOIN {{ref('SQRY_SNOWFLAKE_COUNTS')}} AS SQRY_SNOWFLAKE_COUNTS 
ON
    SQRY_SNOWFLAKE_DBT_COUNTS.OMOP_CLARITY_TABLE = SQRY_SNOWFLAKE_COUNTS.OMOP_CLARITY_TABLE

