--Query_Procedure_Occurrence_Errors

SELECT
    QA_ERR.RUN_DATE
    , QA_ERR.STANDARD_DATA_TABLE
    , QA_ERR.QA_METRIC
    , QA_ERR.METRIC_FIELD
    , QA_ERR.ERROR_TYPE
    , PROCEDURE_OCCURRENCE.*
FROM
    {{ref('QA_ERR')}} AS QA_ERR
INNER JOIN {{ref('PROCEDURE_OCCURRENCE')}} AS PROCEDURE_OCCURRENCE ON
    QA_ERR.CDT_ID = PROCEDURE_OCCURRENCE.PROCEDURE_OCCURRENCE_ID
    AND QA_ERR.CDT_ID = PROCEDURE_OCCURRENCE.PROCEDURE_OCCURRENCE_ID
WHERE
    QA_ERR.STANDARD_DATA_TABLE = 'PROCEDURE_OCCURRENCE'
