--Query_Provider_Errors

SELECT
    QA_ERR.RUN_DATE
    , QA_ERR.STANDARD_DATA_TABLE
    , QA_ERR.QA_METRIC
    , QA_ERR.METRIC_FIELD
    , QA_ERR.ERROR_TYPE
    , PROVIDER.*
FROM
    {{ref('QA_ERR')}} AS QA_ERR
INNER JOIN {{ref('PROVIDER')}} AS PROVIDER ON
    QA_ERR.CDT_ID = PROVIDER.PROVIDER_ID
    AND QA_ERR.CDT_ID = PROVIDER.PROVIDER_ID
WHERE
    QA_ERR.STANDARD_DATA_TABLE = 'PROVIDER'
