--Query_Measurement_Errors

SELECT
    QA_ERR.RUN_DATE
    , QA_ERR.STANDARD_DATA_TABLE
    , QA_ERR.QA_METRIC
    , QA_ERR.METRIC_FIELD
    , QA_ERR.ERROR_TYPE
    , MEASUREMENT.*
FROM
    {{ref('QA_ERR')}} AS QA_ERR
INNER JOIN {{ref('MEASUREMENT')}} AS MEASUREMENT ON
    QA_ERR.CDT_ID = MEASUREMENT.MEASUREMENT_ID
    AND QA_ERR.CDT_ID = MEASUREMENT.MEASUREMENT_ID
WHERE
    QA_ERR.STANDARD_DATA_TABLE = 'MEASUREMENT'
