--Query_Drug_Exposure_Errors

SELECT
    QA_ERR.RUN_DATE
    , QA_ERR.STANDARD_DATA_TABLE
    , QA_ERR.QA_METRIC
    , QA_ERR.METRIC_FIELD
    , QA_ERR.ERROR_TYPE
    , DRUG_EXPOSURE.*
FROM
    {{ref('QA_ERR')}} AS QA_ERR
INNER JOIN {{ref('DRUG_EXPOSURE')}} AS DRUG_EXPOSURE ON
    QA_ERR.CDT_ID = DRUG_EXPOSURE.DRUG_EXPOSURE_ID
    AND QA_ERR.CDT_ID = DRUG_EXPOSURE.DRUG_EXPOSURE_ID
WHERE
    QA_ERR.STANDARD_DATA_TABLE = 'DRUG_EXPOSURE'
