--Query_Location_Errors

SELECT
    QA_ERR.RUN_DATE
    , QA_ERR.STANDARD_DATA_TABLE
    , QA_ERR.QA_METRIC
    , QA_ERR.METRIC_FIELD
    , QA_ERR.ERROR_TYPE
    , LOCATION.*
FROM
    {{ref('QA_ERR')}} AS QA_ERR
INNER JOIN {{ref('LOCATION')}} AS LOCATION ON
    QA_ERR.CDT_ID = LOCATION.CARE_SITE_ID
    AND QA_ERR.CDT_ID = LOCATION.CARE_SITE_ID
WHERE
    QA_ERR.STANDARD_DATA_TABLE = 'LOCATION'
