--Query_Observation_Errors

SELECT
    QA_ERR.RUN_DATE
    , QA_ERR.STANDARD_DATA_TABLE
    , QA_ERR.QA_METRIC
    , QA_ERR.METRIC_FIELD
    , QA_ERR.ERROR_TYPE
    , OBSERVATION.*
FROM
    {{ref('QA_ERR')}} AS QA_ERR
INNER JOIN {{ref('OBSERVATION')}} AS OBSERVATION ON
    QA_ERR.CDT_ID = OBSERVATION.OBSERVATION_ID
    AND QA_ERR.CDT_ID = OBSERVATION.OBSERVATION_ID
WHERE
    QA_ERR.STANDARD_DATA_TABLE = 'OBSERVATION'
