--Query_AoU_Driver_Dup

SELECT QA_ERR.Run_date
    , QA_ERR.Standard_Data_Table
    , AOU_DRIVER.CPI
    , AOU_DRIVER.EPIC_PAT_ID
    , 'P' || QA_ERR.CDT_ID AS AOU_ID
    , AOU_DRIVER.FIRST_NAME
    , AOU_DRIVER.LAST_NAME
    , AOU_DRIVER.DATE_OF_BIRTH
    , AOU_DRIVER.SEX
    , AOU_DRIVER.PHONE
    , AOU_DRIVER.STREET_ADDRESS
    , AOU_DRIVER.CITY
    , AOU_DRIVER.STATE
    , AOU_DRIVER.ZIP
    , AOU_DRIVER.EMAIL

FROM {{ref('AOU_DRIVER')}} AS AOU_DRIVER 

INNER JOIN QA_ERR
    ON AOU_DRIVER.AOU_ID = 'P' || QA_ERR.CDT_ID

WHERE QA_ERR.Standard_Data_Table = 'AOU_DRIVER'