--Query_Note_Errors

SELECT
    QA_ERR.RUN_DATE
    , QA_ERR.STANDARD_DATA_TABLE
    , QA_ERR.QA_METRIC
    , QA_ERR.METRIC_FIELD
    , QA_ERR.ERROR_TYPE
    , NOTE.*
FROM
    {{ref('QA_ERR')}} AS QA_ERR
INNER JOIN {{ref('NOTE')}} AS NOTE ON
    QA_ERR.CDT_ID = NOTE.NOTE_ID
    AND QA_ERR.CDT_ID = NOTE.NOTE_ID
WHERE
    QA_ERR.STANDARD_DATA_TABLE = 'NOTE'
