--Query_Specimen_Errors

SELECT
    QA_ERR.RUN_DATE
    , QA_ERR.STANDARD_DATA_TABLE
    , QA_ERR.QA_METRIC
    , QA_ERR.METRIC_FIELD
    , QA_ERR.ERROR_TYPE
    , SPECIMEN.*
FROM
    {{ref('QA_ERR')}} AS QA_ERR
INNER JOIN {{ref('SPECIMEN')}} AS SPECIMEN ON
    QA_ERR.CDT_ID = SPECIMEN.SPECIMEN_ID
    AND QA_ERR.CDT_ID = SPECIMEN.SPECIMEN_ID
WHERE
    QA_ERR.STANDARD_DATA_TABLE = 'SPECIMEN'