--Query_Care_Site_Errors

SELECT
    QA_ERR.RUN_DATE
    , QA_ERR.STANDARD_DATA_TABLE
    , QA_ERR.QA_METRIC
    , QA_ERR.METRIC_FIELD
    , QA_ERR.ERROR_TYPE
    , CARE_SITE.*
FROM
    {{ref('QA_ERR')}} AS QA_ERR
INNER JOIN {{ref('CARE_SITE')}} AS CARE_SITE ON
    QA_ERR.CDT_ID = CARE_SITE.CARE_SITE_ID
    AND QA_ERR.CDT_ID = CARE_SITE.CARE_SITE_ID
WHERE
    QA_ERR.STANDARD_DATA_TABLE = 'CARE_SITE'
