--Query_Death_Errors

{{ config(materialized = 'view') }}

SELECT
    QA_ERR.RUN_DATE
    , QA_ERR.STANDARD_DATA_TABLE
    , QA_ERR.QA_METRIC
    , QA_ERR.METRIC_FIELD
    , QA_ERR.ERROR_TYPE
    , DEATH.*
FROM
    {{ref('QA_ERR')}} AS QA_ERR
INNER JOIN {{ref('DEATH')}} AS DEATH ON
    QA_ERR.CDT_ID = DEATH.PERSON_ID
WHERE
    QA_ERR.STANDARD_DATA_TABLE = 'DEATH'


