--DRUG_EXPOSURE_CLARITYANES_RXNORM

{{ config(materialized='view') }}

SELECT DISTINCT SUBSTRING(AOU_DRIVER.AOU_ID, 2, LEN(AOU_DRIVER.AOU_ID)) AS PERSON_ID
	,AOU_ID
	-----HOSPITAL ENCOUNTER---------
	,PAT_ENC_HSP.PAT_ENC_CSN_ID
	--------------------------------
	,AN_PAT_ID
	,AN_53_ENC_CSN_ID
	,F_AN_RECORD_SUMMARY.AN_52_ENC_CSN_ID
	,AN_INPATIENT_DATA_ID
	,AN_LOG_ID
	,F_AN_RECORD_SUMMARY.AN_RESP_PROV_ID
	,ORDER_MED.AUTHRZING_PROV_ID
	,MAR_ADMIN_INFO.TAKEN_TIME
	,F_AN_RECORD_SUMMARY.AN_START_DATETIME
	,F_AN_RECORD_SUMMARY.AN_STOP_DATETIME
	,F_AN_RECORD_SUMMARY.AN_PROC_NAME
	,RXNORM_CODES.RXNORM_CODE
	,RXNORM_CODES.RXNORM_TERM_TYPE_C
	,ZC_RXNORM_TERM_TYPE.NAME AS ZC_RXNORM_TERM_TYPE_NAME
	,ORDER_MED.RSN_FOR_DISCON_C
	,ZC_RSN_FOR_DISCON.NAME AS ZC_RSN_FOR_DISCON_NAME
	,MAR_ADMIN_INFO.INFUSION_RATE
	,MAR_ADMIN_INFO.MAR_INF_RATE_UNIT_C
	,INF_RATE.NAME AS INFUSION_RATE_UNIT_NAME
	,MAR_ADMIN_INFO.DOSE_UNIT_C
	,DOSE_UNIT.NAME AS DOSE_UNIT_NAME
	,QUANTITY
	,MAR_ADMIN_INFO.SIG
	,MAR_ADMIN_INFO.LINE AS MAR_ADMIN_INFO_LINE
	,MAR_ADMIN_INFO.MAR_ACTION_C
	,MAR_RESULT.NAME AS MAR_ACTION_NAME
	,MAR_ADMIN_INFO.REASON_C
	,ZC_MAR_RSN.NAME AS MAR_REASON_NAME
	,MAR_ADMIN_INFO.MAR_ENC_CSN
	,RXNORM_CODES.LINE AS RXNORM_CODES_LINE
	,MAR_ADMIN_INFO.ORDER_MED_ID
	,CLARITY_MEDICATION.MEDICATION_ID
	,CLARITY_MEDICATION.NAME AS CLARITY_MEDICATION_NAME
	,MAR_ADMIN_INFO.ROUTE_C
	,ZC_ADMIN_ROUTE.NAME AS ZC_ADMIN_ROUTE_NAME
	,ORDER_STATUS_C
	,'PULL_DRUG_EXPOSURE--CLARITYANES--RXNORM' AS ETL_MODULE

FROM {{ source('CDM','AOU_DRIVER')}} AS AOU_DRIVER 	

INNER JOIN {{ source('CLARITY','PAT_ENC_HSP')}} AS PAT_ENC_HSP
	ON AOU_DRIVER.EPIC_PAT_ID = PAT_ENC_HSP.PAT_ID

-- ASSOCIATES ANETHESIA RECORD TO HOSPITAL ENCOUNTER
INNER JOIN {{ source('CLARITY','AN_HSB_LINK_INFO')}} AS AN_HSB_LINK_INFO
	ON AN_HSB_LINK_INFO.AN_BILLING_CSN_ID = PAT_ENC_HSP.PAT_ENC_CSN_ID

INNER JOIN {{ source('CLARITY','F_AN_RECORD_SUMMARY')}} AS F_AN_RECORD_SUMMARY
	ON F_AN_RECORD_SUMMARY.AN_EPISODE_ID = AN_HSB_LINK_INFO.SUMMARY_BLOCK_ID

INNER JOIN {{ source('CLARITY','MAR_ADMIN_INFO')}} AS MAR_ADMIN_INFO
	ON F_AN_RECORD_SUMMARY.AN_52_ENC_CSN_ID = MAR_ADMIN_INFO.MAR_ENC_CSN

INNER JOIN {{ source('CLARITY','ORDER_MED')}} AS ORDER_MED
	ON ORDER_MED.ORDER_MED_ID = MAR_ADMIN_INFO.ORDER_MED_ID

INNER JOIN {{ source('CLARITY','CLARITY_MEDICATION')}} AS CLARITY_MEDICATION
	ON ORDER_MED.MEDICATION_ID = CLARITY_MEDICATION.MEDICATION_ID

LEFT JOIN {{ source('CLARITY','ZC_RSN_FOR_DISCON')}} AS ZC_RSN_FOR_DISCON
	ON ORDER_MED.RSN_FOR_DISCON_C = ZC_RSN_FOR_DISCON.RSN_FOR_DISCON_C

LEFT JOIN {{ source('CLARITY','ZC_ADMIN_ROUTE')}} AS ZC_ADMIN_ROUTE
	ON MAR_ADMIN_INFO.ROUTE_C = ZC_ADMIN_ROUTE.MED_ROUTE_C

LEFT JOIN {{ source('CLARITY','ZC_MED_UNIT')}} AS INF_RATE
	ON MAR_ADMIN_INFO.MAR_INF_RATE_UNIT_C = INF_RATE.DISP_QTYUNIT_C

LEFT JOIN {{ source('CLARITY','ZC_MED_UNIT')}} AS DOSE_UNIT
	ON MAR_ADMIN_INFO.DOSE_UNIT_C = DOSE_UNIT.DISP_QTYUNIT_C

LEFT JOIN {{ source('CLARITY','ZC_MAR_RSLT')}} AS MAR_RESULT
	ON MAR_ADMIN_INFO.MAR_ACTION_C = MAR_RESULT.RESULT_C

LEFT JOIN {{ source('CLARITY','ZC_MAR_RSN')}} AS ZC_MAR_RSN
	ON MAR_ADMIN_INFO.REASON_C = ZC_MAR_RSN.REASON_C

INNER JOIN {{ source('CLARITY','RXNORM_CODES')}} AS RXNORM_CODES
	ON ORDER_MED.MEDICATION_ID = RXNORM_CODES.MEDICATION_ID

INNER JOIN {{ source('CLARITY','ZC_RXNORM_TERM_TYPE')}} AS ZC_RXNORM_TERM_TYPE
	ON RXNORM_CODES.RXNORM_TERM_TYPE_C = ZC_RXNORM_TERM_TYPE.RXNORM_TERM_TYPE_C

WHERE MAR_ACTION_C = 1


