--DRUG_EXPOSURE_CLARITYAMB_RXNORM

{{ config(materialized = 'view') }}

SELECT DISTINCT  PAT_ENC_AMB.PERSON_ID
    ,PAT_ENC_AMB.AOU_ID
    ,PAT_ENC_AMB.PAT_ID
    ,PAT_ENC_AMB.PAT_ENC_CSN_ID
    ,PAT_ENC_AMB.HSP_ACCOUNT_ID
    ,PAT_ENC_AMB.IP_DOC_CONTACT_CSN
    ,PAT_ENC_AMB.ENC_TYPE_C
    ,PAT_ENC_AMB.ZC_DISP_ENC_TYPE_NAME
    ,PAT_ENC_AMB.PAT_OR_ADM_LINK_CSN AS PAT_OR_ADM_LINK_PAT_ENC_CSN_ID
    ,ORDER_MED.ORDER_END_TIME
    ,ORDER_MED.ORDER_START_TIME
    ,RXNORM_CODES.RXNORM_CODE
    ,RXNORM_CODES.RXNORM_TERM_TYPE_C
    ,ZC_RXNORM_TERM_TYPE.NAME AS ZC_RXNORM_TERM_TYPE_NAME
    ,ORDER_MED.END_DATE
    ,ORDER_MED.RSN_FOR_DISCON_C
    ,ZC_RSN_FOR_DISCON.NAME AS ZC_RSN_FOR_DISCON_NAME
    ,ORDER_MED.REFILLS
    ,ORDER_MED.QUANTITY
    ,ZC_MED_UNIT.NAME AS ZC_MED_UNIT_NAME
    ,REPLACE(ORDER_MED.SIG,'\\',' ') AS SIG
    ,RXNORM_CODES.LINE AS RXNORM_CODES_LINE
    ,CLARITY_MEDICATION.MEDICATION_ID
    ,ORDER_MED.AUTHRZING_PROV_ID
    ,CLARITY_MEDICATION.NAME AS CLARITY_MEDICATION_NAME
    ,ORDER_MED.MED_ROUTE_C
    ,ZC_ADMIN_ROUTE.NAME AS ZC_ADMIN_ROUTE_NAME
    ,ORDER_MED.ORDER_STATUS_C
    ,'PULL_DRUG_EXPOSURE--CLARITYAMB--RXNORM' AS ETL_MODULE

FROM {{ref('VISIT_OCCURRENCE_CLARITYAMB_ALL')}} AS PAT_ENC_AMB

INNER JOIN {{ source('CLARITY','ORDER_MED')}} AS ORDER_MED
    ON ORDER_MED.PAT_ENC_CSN_ID = PAT_ENC_AMB.PAT_ENC_CSN_ID

INNER JOIN {{ source('CLARITY','CLARITY_MEDICATION')}} AS CLARITY_MEDICATION
    ON ORDER_MED.MEDICATION_ID = CLARITY_MEDICATION.MEDICATION_ID

INNER JOIN {{ source('CLARITY','ZC_MED_UNIT')}} AS ZC_MED_UNIT
    ON ORDER_MED.HV_DOSE_UNIT_C = ZC_MED_UNIT.DISP_QTYUNIT_C

LEFT JOIN {{ source('CLARITY','ZC_RSN_FOR_DISCON')}} AS ZC_RSN_FOR_DISCON
    ON ORDER_MED.RSN_FOR_DISCON_C = ZC_RSN_FOR_DISCON.RSN_FOR_DISCON_C

LEFT JOIN {{ source('CLARITY','ZC_ADMIN_ROUTE')}} AS ZC_ADMIN_ROUTE
    ON ORDER_MED.MED_ROUTE_C = ZC_ADMIN_ROUTE.MED_ROUTE_C

INNER JOIN {{ source('CLARITY','RXNORM_CODES')}} AS RXNORM_CODES
    ON ORDER_MED.MEDICATION_ID = RXNORM_CODES.MEDICATION_ID

INNER JOIN {{ source('CLARITY','ZC_RXNORM_TERM_TYPE')}} AS ZC_RXNORM_TERM_TYPE
    ON RXNORM_CODES.RXNORM_TERM_TYPE_C = ZC_RXNORM_TERM_TYPE.RXNORM_TERM_TYPE_C

WHERE START_DATE IS NOT NULL    
    AND PAT_ENC_AMB.ENC_TYPE_C <> 3

    AND ORDER_STATUS_C NOT IN (
        4 --4 - CANCELED
        ,6 --6 - HOLDING
        ,7 --7 - DENIED
        ,8 --8 - SUSPEND
        ,9 --9 - DISCONTINUED
        )