USE ROLE SF_SH_OMOP_DEVELOPER;

--USE SCHEMA SH_CLINICAL_DB_PROD.EPIC_CLARITY_LZ;
--USE SCHEMA SH_OMOP_DB_PROD.OMOP_CLARITY;
USE SCHEMA SH_OMOP_DB_PROD.OMOP;

USE WAREHOUSE SH_OMOP_DATA_SCIENCE_WH;


CREATE OR REPLACE PROCEDURE TRUNCATE_STANDARD_CLINICAL_TABLES()
RETURNS VARCHAR
LANGUAGE SQL
AS
 $$
     DECLARE
        V1 VARCHAR DEFAULT 'DELETE FROM SPECIMEN';
        V2 VARCHAR DEFAULT 'DELETE FROM NOTE';
        V3 VARCHAR DEFAULT 'DELETE FROM OBSERVATION';
        V4 VARCHAR DEFAULT 'DELETE FROM DEVICE_EXPOSURE';
        V5 VARCHAR DEFAULT 'DELETE FROM PROCEDURE_OCCURRENCE';
        V6 VARCHAR DEFAULT 'DELETE FROM DRUG_EXPOSURE';
        V7 VARCHAR DEFAULT 'DELETE FROM MEASUREMENT';
        V8 VARCHAR DEFAULT 'DELETE FROM CONDITION_OCCURRENCE';
        V9 VARCHAR DEFAULT 'DELETE FROM VISIT_OCCURRENCE';
       V10 VARCHAR DEFAULT 'DELETE FROM VISIT_DETAIL';
       V11 VARCHAR DEFAULT 'DELETE FROM PERSON';
       V12 VARCHAR DEFAULT 'DELETE FROM PROVIDER';
       V13 VARCHAR DEFAULT 'DELETE FROM CARE_SITE';
       V14 VARCHAR DEFAULT 'DELETE FROM LOCATION';
         I INTEGER DEFAULT 0;
     BEGIN
--         FOR I IN 1 TO 14
--            EXECUTE IMMEDIATE 'V' || I::VARCHAR;
--        END FOR;
         EXECUTE IMMEDIATE V1;
         EXECUTE IMMEDIATE V2;
         EXECUTE IMMEDIATE V3;
         EXECUTE IMMEDIATE V4;
         EXECUTE IMMEDIATE V5;
         EXECUTE IMMEDIATE V6;
         EXECUTE IMMEDIATE V7;
         EXECUTE IMMEDIATE V8;
         EXECUTE IMMEDIATE V9;
--         EXECUTE IMMEDIATE V10;
         EXECUTE IMMEDIATE V11;
         EXECUTE IMMEDIATE V12;
         EXECUTE IMMEDIATE V13;
         EXECUTE IMMEDIATE V14;
        RETURN 'DONE';
     END;
$$;
/*
CALL TRUNCATE_STANDARD_CLINICAL_TABLES();
*/