--Structure: (if your structure is different, you will have to modify the code to match)
--    Databases:SH_OMOP_DB_PROD, SH_CLINICAL_DB_PROD
--    Schemas: SH_OMOP_DB_PROD.OMOP_CLARITY, SH_OMOP_DB_PROD.CDM, SH_CLINICAL_DB_PROD.EPIC_CLARITY_LZ


--USE ROLE SF_SH_OMOP_DEVELOPER;
--USE SCHEMA SH_CLINICAL_DB_PROD.EPIC_CLARITY_LZ;
--USE WAREHOUSE SH_OMOP_DATA_SCIENCE_WH;

CREATE OR REPLACE TABLE SH_OMOP_DB_PROD.OMOP_CLARITY.SPECIMEN_CLARITY_ALL 
AS   

SELECT DISTINCT 
    SUBSTRING(AOU_DRIVER.AOU_ID, 2, LEN(AOU_DRIVER.AOU_ID))::NUMERIC   AS PERSON_ID
    , SPEC_DB_MAIN.SPEC_DTM_COLLECTED
    , SPEC_DB_MAIN.SPEC_DTM_RECEIVED
    , HSC_SPEC_INFO.SPECIMEN_SIZE                                       -- MISSING FROM HSC_SPEC_INFO
    , HSC_SPEC_INFO.SPECIMEN_TYPE_C    
    , SPEC_DB_MAIN.SPEC_SOURCE_C
    , ZC_SPECIMEN_TYPE.NAME                                             AS ZC_SPECIMEN_TYPE_NAME                                                                   
    , ZC_SPEC_SOURCE.NAME                                               AS  ZC_SPEC_SOURCE_NAME                                                              
--INTO SH_OMOP_DB_PROD.OMOP_CLARITY.SPECIMEN_CLARITY_ALL
FROM SH_OMOP_DB_PROD.CDM.PERSON

	INNER JOIN SH_OMOP_DB_PROD.CDM.AOU_DRIVER
		ON PERSON.PERSON_ID = SUBSTRING(AOU_DRIVER.AOU_ID, 2, LEN(AOU_DRIVER.AOU_ID))::NUMERIC
		
	INNER JOIN SH_CLINICAL_DB_PROD.EPIC_CLARITY_LZ.SPEC_DB_MAIN
		ON SPEC_DB_MAIN.SPEC_EPT_PAT_ID = SH_OMOP_DB_PROD.CDM.AOU_DRIVER.EPIC_PAT_ID
		
	INNER JOIN SH_CLINICAL_DB_PROD.EPIC_CLARITY_LZ.ZC_SPEC_SOURCE
		ON SPEC_DB_MAIN.SPEC_SOURCE_C = ZC_SPEC_SOURCE.SPEC_SOURCE_C

	INNER JOIN SH_CLINICAL_DB_PROD.EPIC_CLARITY_LZ.HSC_SPEC_INFO
		ON SPEC_DB_MAIN.SPECIMEN_COL_ID = HSC_SPEC_INFO.RECORD_ID
		
	LEFT JOIN SH_CLINICAL_DB_PROD.EPIC_CLARITY_LZ.ZC_SPECIMEN_TYPE
		ON HSC_SPEC_INFO.SPECIMEN_TYPE_C = ZC_SPECIMEN_TYPE.SPECIMEN_TYPE_C
		
	LEFT JOIN SH_CLINICAL_DB_PROD.EPIC_CLARITY_LZ.ZC_SPECIMEN_UNIT
		ON HSC_SPEC_INFO.SPECIMEN_UNIT_C = ZC_SPECIMEN_UNIT.SPECIMEN_UNIT_C

WHERE COALESCE(SPEC_DB_MAIN.SPEC_DTM_COLLECTED, SPEC_DB_MAIN.SPEC_DTM_RECEIVED) IS NOT NULL